### ISSUE TITLE
Can't run apollo graphql federation sample

### ISSUE THREAD

**Issue by bartoszmajkut** [nestjs/nest#10129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I've cloned nest repo and tried to run sample 31-graphql-federation-code-first/users-application on two versions of nodejs - lts/fermium and lts/gallium with:

`npm install`
`npm run start`

and I get:
```[Nest] 8071  - 08/17/2022, 6:12:19 PM     LOG [NestFactory] Starting Nest application...
[Nest] 8071  - 08/17/2022, 6:12:19 PM     LOG [InstanceLoader] UsersModule dependencies initialized +22ms
[Nest] 8071  - 08/17/2022, 6:12:19 PM     LOG [InstanceLoader] AppModule dependencies initialized +0ms
[Nest] 8071  - 08/17/2022, 6:12:19 PM     LOG [InstanceLoader] GraphQLSchemaBuilderModule dependencies initialized +1ms
[Nest] 8071  - 08/17/2022, 6:12:19 PM     LOG [InstanceLoader] GraphQLModule dependencies initialized +1ms
[Nest] 8071  - 08/17/2022, 6:12:19 PM     LOG [RoutesResolver] AppController {/}: +3ms
[Nest] 8071  - 08/17/2022, 6:12:19 PM     LOG [RouterExplorer] Mapped {/, GET} route +1ms

/nest/sample/31-graphql-federation-code-first/users-application/node_modules/@apollo/federation-internals/src/validate.ts:155
      this.errors.push(new GraphQLError(`Type ${type.name} must define one or more fields.`, type.sourceAST));
                       ^
GraphQLError: Type User must define one or more fields.
    at Validator.validateObjectOrInterfaceType (/nest/sample/31-graphql-federation-code-first/users-application/node_modules/@apollo/federation-internals/src/validate.ts:155:24)
    at Validator.validate (/nest/sample/31-graphql-federation-code-first/users-application/node_modules/@apollo/federation-internals/src/validate.ts:85:16)
    at validateSchema (/nest/sample/31-graphql-federation-code-first/users-application/node_modules/@apollo/federation-internals/src/validate.ts:28:32)
    at Schema.validate (/nest/sample/31-graphql-federation-code-first/users-application/node_modules/@apollo/federation-internals/src/definitions.ts:1468:42)
    at Subgraph.validate (/nest/sample/31-graphql-federation-code-first/users-application/node_modules/@apollo/federation-internals/src/federation.ts:1382:19)
    at buildSubgraph (/nest/sample/31-graphql-federation-code-first/users-application/node_modules/@apollo/federation-internals/src/federation.ts:979:19)
    at printSubgraphSchema (/nest/sample/31-graphql-federation-code-first/users-application/node_modules/@apollo/subgraph/src/printSubgraphSchema.ts:16:33)
    at GraphQLFederationFactory.generateSchema (/nest/sample/31-graphql-federation-code-first/users-application/node_modules/@nestjs/graphql/dist/federation/graphql-federation.factory.js:62:46)
    at GraphQLFederationFactory.mergeWithSchema (/nest/sample/31-graphql-federation-code-first/users-application/node_modules/@nestjs/graphql/dist/federation/graphql-federation.factory.js:28:22)
    at ApolloFederationDriver.start (/nest/sample/31-graphql-federation-code-first/users-application/node_modules/@nestjs/apollo/dist/drivers/apollo-federation.driver.js:19:32)```

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/sample/31-graphql-federation-code-first/users-application

### Steps to reproduce

`npm install`
`npm run start`

### Expected behavior

Nest app should run without any problems.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

_No response_

### NestJS version

_No response_

### Packages versions

```json
{
  "name": "users-application",
  "version": "1.0.0",
  "description": "",
  "author": "Flusinerd",
  "license": "MIT",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "echo 'No e2e tests implemented yet.'"
  },
  "dependencies": {
    "@apollo/federation": "0.36.1",
    "@apollo/gateway": "2.0.5",
    "@apollo/subgraph": "2.0.5",
    "@nestjs/apollo": "10.0.17",
    "@nestjs/common": "9.0.1",
    "@nestjs/core": "9.0.1",
    "@nestjs/graphql": "10.0.18",
    "@nestjs/platform-express": "9.0.1",
    "apollo-server-express": "3.9.0",
    "graphql": "16.5.0",
    "graphql-tools": "8.3.0",
    "reflect-metadata": "0.1.13",
    "rimraf": "3.0.2",
    "rxjs": "7.5.5",
    "ts-morph": "15.1.0"
  },
  "devDependencies": {
    "@nestjs/cli": "9.0.0",
    "@nestjs/schematics": "9.0.1",
    "@nestjs/testing": "9.0.1",
    "@types/express": "4.17.13",
    "@types/jest": "28.1.4",
    "@types/node": "18.0.3",
    "@types/supertest": "2.0.12",
    "@typescript-eslint/eslint-plugin": "5.30.5",
    "@typescript-eslint/parser": "5.30.5",
    "eslint": "8.19.0",
    "eslint-config-prettier": "8.5.0",
    "eslint-plugin-prettier": "4.2.1",
    "jest": "28.1.2",
    "prettier": "2.7.1",
    "supertest": "6.2.4",
    "ts-jest": "28.0.5",
    "ts-loader": "9.3.1",
    "ts-node": "10.8.2",
    "tsconfig-paths": "4.0.0",
    "typescript": "4.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

lts/gallium lts/fermium

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by killjoy2013** [comment]
Having the same issue. Looking forward to hear a solution :-)
thanks
