### ISSUE TITLE
e2e tests fail when using cache-manager-mongoose

### ISSUE THREAD

**Issue by sclausen** [nestjs/nest#10251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I've got an issue regarding e2e tests and using `cache-manager-mongoose` and am not quite sure, if this is a bug in nestjs or not. I couldn't find any suspicious lines in `cache-manager-mongoose` nor `cache-manager`.
If I run e2e tests, after the first test case, every case fails with a mongooose error 
```
OverwriteModelError: Cannot overwrite `MongooseCache` model once compiled.
```

That's the output I get in the MWE

```
docker-compose run web npm run test:e2e

> foo@0.0.1 test:e2e
> jest --forceExit --config ./test/jest-e2e.json

 FAIL  test/app.e2e-spec.ts
  AppController (e2e)
    ✓ / (GET) (176 ms)
    ✕ /foo (GET) (4 ms)

  ● AppController (e2e) › /foo (GET)

    OverwriteModelError: Cannot overwrite `MongooseCache` model once compiled.

      at Mongoose.Object.<anonymous>.Mongoose.model (../node_modules/mongoose/lib/index.js:553:13)
      at MongooseStore.makeModel (../node_modules/cache-manager-mongoose/src/index.js:58:35)
      at new MongooseStore (../node_modules/cache-manager-mongoose/src/index.js:28:31)
      at Object.create (../node_modules/cache-manager-mongoose/src/index.js:163:16)
      at Object.caching (../node_modules/cache-manager/lib/caching.js:26:37)
      at InstanceWrapper.useFactory [as metatype] (../node_modules/@nestjs/common/cache/cache.providers.js:20:32)
      at TestingInjector.instantiateClass (../node_modules/@nestjs/core/injector/injector.js:343:55)
      at callback (../node_modules/@nestjs/core/injector/injector.js:53:45)
      at TestingInjector.resolveConstructorParams (../node_modules/@nestjs/core/injector/injector.js:132:24)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        2.49 s
Ran all test suites.
Force exiting Jest: Have you considered using `--detectOpenHandles` to detect async operations that kept running after all tests finished?
```

### Minimum reproduction code

https://github.com/sclausen/nestjs-mongoose-cache-bug

### Steps to reproduce

1. `docker-compose build --no-cache`
2. `docker-compose up`
3. in another terminal `docker-compose run web npm run test:e2e`

### Expected behavior

e2e tests do not fail when using cache-manager-mongoose

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

mongoose, cache-manager-mongoose, cache-manager

### NestJS version

9.0.11

### Packages versions

```
[System Information]
OS Version     : Linux 5.10
NodeJS Version : v16.15.1
NPM Version    : 8.11.0 

[Nest CLI]
Nest CLI Version : 9.1.2 

[Nest Platform Information]
platform-express version : 9.0.11
schematics version       : 9.0.3
testing version          : 9.0.11
common version           : 9.0.11
core version             : 9.0.11
cli version              : 9.1.2
```

### Node.js version

16.15.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

the docker image used is `node:16.15.1-alpine3.16`

**Comment by sclausen** [comment]
Fo anyone encountering the same issue: That's not a nestjs bug but an issue with mongoose model cache. I found out that mongoose seems to cache the compiled models once per nodejs process.
So in parallel to the `beforeEach` containing the `createNestApplication` part has to be a cleanup script
```ts
afterEach(() => {
  mongoose.modelNames().map(mongoose.deleteModel);
});
````
to clean the models which would be compiled again when `createNestApplication` is executed a second time.
