### ISSUE TITLE
@nestjs/cli build breaks 9.0 -> 9.1

### ISSUE THREAD

**Issue by horrendo** [nestjs/nest#10250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Something seems to have changed (for the worst for us) with `nest build` going from 9.0 to 9.1.

With 9.0 everything is ok:

```
[~/git/unsullied] yarn list --pattern nestjs
yarn list v1.22.19
├─ @nestjs-plus/discovery@2.0.2
├─ @nestjs/cli@9.0.0
├─ @nestjs/common@9.0.11
├─ @nestjs/core@9.0.11
├─ @nestjs/platform-express@9.0.11
├─ @nestjs/schematics@9.0.3
└─ @nestjs/testing@9.0.11
✨  Done in 0.78s.
[~/git/unsullied] yarn nest build
yarn run v1.22.19
$ /Users/stbaldwin/git/unsullied/node_modules/.bin/nest build
✨  Done in 25.66s.
[~/git/unsullied] node -r tsconfig-paths/register dist/main.js
[Nest] 24328  - 07/09/2022, 12:41:28 am     LOG [main] Running unsullied app on Node.js v16.17.0.
[Nest] 24328  - 07/09/2022, 12:41:28 am     LOG [MasterHost] sqlite database found
[Nest] 24328  - 07/09/2022, 12:41:28 am     LOG [MasterHost] Opening database ./master-host.db
[Nest] 24328  - 07/09/2022, 12:41:28 am     LOG [NestFactory] Starting Nest application... +47ms
[Nest] 24328  - 07/09/2022, 12:41:29 am     LOG [InstanceLoader] TemplateModule dependencies initialized +186ms
:
```

Upgrading to 9.1+ breaks for us:

```
[~/git/unsullied] yarn upgrade @nestjs/cli@9.1.0
yarn upgrade v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning Workspaces can only be enabled in private projects.
[5/5] 🔨  Rebuilding all packages...
success Saved lockfile.
warning Workspaces can only be enabled in private projects.
success Saved 5 new dependencies.
info Direct dependencies
└─ @nestjs/cli@9.1.0
info All dependencies
├─ @angular-devkit/schematics-cli@14.2.0
├─ @nestjs/cli@9.1.0
├─ ansi-colors@4.1.3
├─ node-abort-controller@3.0.1
└─ tsconfig-paths-webpack-plugin@4.0.0
✨  Done in 12.81s.
[~/git/unsullied] yarn list --pattern nestjs
yarn list v1.22.19
├─ @nestjs-plus/discovery@2.0.2
├─ @nestjs/cli@9.1.0
├─ @nestjs/common@9.0.11
├─ @nestjs/core@9.0.11
├─ @nestjs/platform-express@9.0.11
├─ @nestjs/schematics@9.0.3
└─ @nestjs/testing@9.0.11
✨  Done in 0.77s.
[~/git/unsullied] yarn nest build
yarn run v1.22.19
$ /Users/stbaldwin/git/unsullied/node_modules/.bin/nest build
✨  Done in 25.85s.
[~/git/unsullied] node -r tsconfig-paths/register dist/main.js
[Nest] 25790  - 07/09/2022, 12:43:54 am     LOG [main] Running unsullied app on Node.js v16.17.0.
[Nest] 25790  - 07/09/2022, 12:43:54 am     LOG [MasterHost] sqlite database found
[Nest] 25790  - 07/09/2022, 12:43:54 am     LOG [MasterHost] Opening database ./master-host.db
[Nest] 25790  - 07/09/2022, 12:43:54 am     LOG [NestFactory] Starting Nest application... +43ms
[Nest] 25790  - 07/09/2022, 12:43:54 am     LOG [InjectorLogger] Nest encountered an undefined dependency. This may be due to a circular import or a missing dependency declaration.
[Nest] 25790  - 07/09/2022, 12:43:54 am   ERROR [ExceptionHandler] Nest can't resolve dependencies of the RepositoryCacheManager (?, NotificationListener, AppEventEmitter). Please make sure that the argument dependency at index [0] is available in the CacheModule context.

Potential solutions:
- If dependency is a provider, is it part of the current CacheModule?
- If dependency is exported from a separate @Module, is that module imported within CacheModule?
  @Module({
    imports: [ /* the Module containing dependency */ ]
  })

Error: Nest can't resolve dependencies of the RepositoryCacheManager (?, NotificationListener, AppEventEmitter). Please make sure that the argument dependency at index [0] is available in the CacheModule context.

Potential solutions:
- If dependency is a provider, is it part of the current CacheModule?
- If dependency is exported from a separate @Module, is that module imported within CacheModule?
  @Module({
    imports: [ /* the Module containing dependency */ ]
  })

    at Injector.resolveSingleParam (/Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/injector.js:178:19)
    at resolveParam (/Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/injector.js:116:49)
    at Array.map (<anonymous>)
    at Injector.resolveConstructorParams (/Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/injector.js:131:58)
    at Injector.loadInstance (/Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/injector.js:57:24)
    at Injector.loadProvider (/Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/injector.js:84:20)
    at /Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/instance-loader.js:47:62
    at Array.map (<anonymous>)
    at InstanceLoader.createInstancesOfProviders (/Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/instance-loader.js:47:36)
    at /Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/instance-loader.js:32:24
```

We can fix our max version of `@nestjs/cli` for now, but it would be good to know if this is a bug, or something we need to fix.

The dependency it is complaining about it provided in a `@Global()` module.

### Minimum reproduction code

See above

### Expected behavior

I would expect the build to generate runnable code as it did pre-9.1.0

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/cli

### NestJS version

9.0.11

### Packages versions

See above

### Node.js version

16.17.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
We'd need a [minimum reproduction](https://minimum-reproduction.wtf) to begin to track down what's happening here. The only change we made was to [how the `tsconfig-paths` code was being called programmatically](https://github.com/nestjs/nest-cli/compare/9.0.0...9.1.1)
