### ISSUE TITLE
Can't implement data model with @nestjs/mongoose : "Error: Cannot determine a type for the \"SectionTemplate.section\" field"

### ISSUE THREAD

**Issue by liitfr** [nestjs/nest#10400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

issue manifests when runing simplified reproduction code : 

```
/home/mat/code/test-mongoose/node_modules/reflect-metadata/Reflect.js:553
                var decorated = decorator(target, propertyKey, descriptor);
                                ^
Error: Cannot determine a type for the "SectionTemplate.section" field (union/intersection/ambiguous type was used). Make sure your property is decorated with a "@Prop({ type: TYPE_HERE })" decorator.
    at /home/mat/code/test-mongoose/node_modules/@nestjs/mongoose/dist/decorators/prop.decorator.js:22:23
    at DecorateProperty (/home/mat/code/test-mongoose/node_modules/reflect-metadata/Reflect.js:553:33)
    at Reflect.decorate (/home/mat/code/test-mongoose/node_modules/reflect-metadata/Reflect.js:123:24)
    at __decorate (/home/mat/code/test-mongoose/dist/schemas/section-template.schema.js:4:92)
    at Object.<anonymous> (/home/mat/code/test-mongoose/src/schemas/section-template.schema.ts:11:3)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
```

This error isn't so much relevant since `SectionTemplate.section` is actually decorated with a `@Prop({ type: SectionSchema, required: true })` decorator

### Minimum reproduction code

https://github.com/soolidtech/test-mongoose

### Steps to reproduce

1. `npm install`
2. start a local mongodb : `sudo mongod --port 27018 --dbpath ~/data/tbd`
3. `npm run start:dev` 

### Expected behavior

I've tried to simplify this use-case as much as possible.

I'm working on a CMS feature for a customer. I've picked 3 of the entities that create the problem : 
- a `document template` has predefined `sections`. This sections are not expressed as relations, but as a **nested array**.
- a `section template` is a predefined `section`.  As for `document template`, this `section` composes `template`, meaning that it's not a relation, but a **nested object**
- a `section` can contain `sub sections` (recursivity) as **nested objects**, and can have a **relation** to a `section template`

I can't implement this model with @nestjs/mongoose since it gives me an error as reported above. I can't ideentify what breaks app, but i guess it's related to some kind of circular dependency ? I tried to mess with `forwardRef` without any sucess

Is such a requirement is possible with nest and its mongoose decorators ? 

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/mongoose

### NestJS version

9.1.4

### Packages versions

[System Information]
OS Version     : Linux 5.15
NodeJS Version : v16.17.0
NPM Version    : 8.15.0 

[Nest CLI]
Nest CLI Version : 9.1.4 

[Nest Platform Information]
platform-express version : 9.1.4
schematics version       : 9.0.3
mongoose version         : 9.2.0
testing version          : 9.1.4
common version           : 9.1.4
core version             : 9.1.4
cli version              : 9.1.4

### Node.js version

v16.17.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [x] Linux

### Other

As you can see  I had to to thunk sub section prop type : 
```
  @Prop({ type: () => [SectionSchema], required: false })
  subSections?: Section[];
```

but i'm not sure it's the good way to do. I've seen it's used here : https://github.com/nestjs/mongoose/blob/master/tests/e2e/schema-definitions.factory.spec.ts but not documented.

**Comment by liitfr** [comment]
Hello !
I was able to make it work.
I gathered all schemas in a single file, and fixed circular references by using TS interfaces.
Then, for recursive reference of sub sections, i directly used mongoose instead of `@Prop` decorator.

Sorry for this illegitimate issue, i'll close it. 

It gives following code. If you have any advice about my code, feel free to share, it'll be greatly appreciated.
Bye

```
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import {
  Document as MongooseDocument,
  Schema as MongooseSchema,
} from 'mongoose';

interface SectionI {
  template?: SectionTemplateI;
  text: string;
  date: Date;
  subSections?: SectionI[];
}

interface SectionTemplateI {
  section: SectionI;
}

interface DocumentTemplateI {
  sections: SectionI[];
}

export type SectionDocument = Section & Document;

@Schema()
export class Section implements SectionI {
  // a section can come from a template. It's a reference, not a nested object.
  @Prop({
    type: MongooseSchema.Types.ObjectId,
    ref: 'SectionTemplate',
    autopoulate: true,
    required: false,
  })
  template?: SectionTemplateI;

  @Prop({ type: String, required: true })
  text: string;

  @Prop({ type: Date, required: true })
  date: Date;

  // a section has a list of sub-sections. They are nested, not related.
  //   @Prop({ type: () => [SectionSchema], required: false })
  subSections?: SectionI[];
}

export const SectionSchema = SchemaFactory.createForClass(Section);

SectionSchema.add({
  subSections: {
    type: [SectionSchema],
    required: false,
  },
});

export type DocumentTemplateDocument = DocumentTemplate & MongooseDocument;

@Schema()
export class DocumentTemplate implements DocumentTemplateI {
  // a document template has predefined sections. It's not a relation, it's a nested array.
  @Prop({ type: [SectionSchema], required: true })
  sections: SectionI[];
}

export const DocumentTemplateSchema =
  SchemaFactory.createForClass(DocumentTemplate);

export type SectionTemplateDocument = SectionTemplate & Document;

@Schema()
export class SectionTemplate implements SectionTemplateI {
  // a section template has it's own content. It's not a relation, it's a nested object.
  @Prop({ type: SectionSchema, required: true })
  section: SectionI;
}

export const SectionTemplateSchema =
  SchemaFactory.createForClass(SectionTemplate);

```
