### ISSUE TITLE
Fastify plugin register seems not working

### ISSUE THREAD

**Issue by andreafspeziale** [nestjs/nest#10426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Using a registered plugin will result in an error at runtime.

### Minimum reproduction code

https://github.com/andreafspeziale/nestjs-fastify-plugin-issue-sample

### Steps to reproduce

https://github.com/andreafspeziale/nestjs-fastify-plugin-issue-sample/blob/main/README.md

### Expected behavior

No runtime error and info logged as expected

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

@fastify/url-data

### NestJS version

9.0.1

### Packages versions

https://github.com/andreafspeziale/nestjs-fastify-plugin-issue-sample/blob/main/package.json

### Node.js version

18.5.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
Please share the error message as well

**Comment by andreafspeziale** [comment]
Sure, maybe it's just something trivial. Thanks in advance

```
[Nest] 99175  - 20/10/2022, 14:18:30     LOG [NestFactory] Starting Nest application...
[Nest] 99175  - 20/10/2022, 14:18:30     LOG [InstanceLoader] AppModule dependencies initialized +39ms
[Nest] 99175  - 20/10/2022, 14:18:30     LOG [InstanceLoader] CatsModule dependencies initialized +0ms
[Nest] 99175  - 20/10/2022, 14:18:30     LOG [RoutesResolver] CatsController {/cats}: +4ms
[Nest] 99175  - 20/10/2022, 14:18:30     LOG [RouterExplorer] Mapped {/cats, GET} route +1ms
[Nest] 99175  - 20/10/2022, 14:18:30     LOG [NestApplication] Nest application successfully started +1ms
[Nest] 99175  - 20/10/2022, 14:18:46   ERROR [ExceptionsHandler] req.urlData is not a function
TypeError: req.urlData is not a function
    at LoggerMiddleware.use (/Users/andrea.speziale/Repositories/10-fastify/src/common/middleware/logger.middleware.ts:8:45)
    at /Users/andrea.speziale/Repositories/10-fastify/node_modules/@nestjs/core/router/router-proxy.js:9:23
    at Holder.done (/Users/andrea.speziale/Repositories/10-fastify/node_modules/@fastify/middie/engine.js:107:13)
    at Object.run (/Users/andrea.speziale/Repositories/10-fastify/node_modules/@fastify/middie/engine.js:59:12)
    at Object.runMiddie (/Users/andrea.speziale/Repositories/10-fastify/node_modules/@fastify/middie/index.js:42:21)
    at hookIterator (/Users/andrea.speziale/Repositories/10-fastify/node_modules/fastify/lib/hooks.js:246:10)
    at next (/Users/andrea.speziale/Repositories/10-fastify/node_modules/fastify/lib/hooks.js:174:16)
    at hookRunner (/Users/andrea.speziale/Repositories/10-fastify/node_modules/fastify/lib/hooks.js:196:3)
    at Object.routeHandler [as handler] (/Users/andrea.speziale/Repositories/10-fastify/node_modules/fastify/lib/route.js:426:7)
    at Router.lookup (/Users/andrea.speziale/Repositories/10-fastify/node_modules/find-my-way/index.js:359:14)
```

**Comment by kaioduarte** [comment]
The plugin is only available in the controllers, I couldn't trace the whole flow to understand the difference between the request object in the middleware vs the controller.

So, this works:
```ts
@Get()
async findAll(@Request() req: Request): Promise<Cat[]> {
  console.log("CONTROLLER", req.urlData());
  return this.catsService.findAll();
}
```

**Comment by jmcdo29** [comment]
In fastify, middleware fire before plugins. This is documented in their docs and not something we can control.
