### ISSUE TITLE
Heap out of memory when dynamic modules have circular dependencies

### ISSUE THREAD

**Issue by azaiko-akveo** [nestjs/nest#10548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

We are trying to implement hexagonal architecture and we use dynamic modules in our project

There are two problems when we start the project:

### FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x1013221f5 node::Abort() (.cold.1) [/Users/artemzaiko/.nvm/versions/node/v14.19.1/bin/node]
 2: 0x1000b6399 node::Abort() [/Users/artemzaiko/.nvm/versions/node/v14.19.1/bin/node]
 3: 0x1000b650f node::OnFatalError(char const*, char const*) [/Users/artemzaiko/.nvm/versions/node/v14.19.1/bin/node]
 4: 0x100201497 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/artemzaiko/.nvm/versions/node/v14.19.1/bin/node]
 5: 0x100201433 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/artemzaiko/.nvm/versions/node/v14.19.1/bin/node]
 6: 0x1003af545 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/artemzaiko/.nvm/versions/node/v14.19.1/bin/node]
 7: 0x1003b0fea v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/Users/artemzaiko/.nvm/versions/node/v14.19.1/bin/node]
 8: 0x1003ac715 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/artemzaiko/.nvm/versions/node/v14.19.1/bin/node]
 9: 0x1003aa040 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/artemzaiko/.nvm/versions/node/v14.19.1/bin/node]
10: 0x1003b876a v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/artemzaiko/.nvm/versions/node/v14.19.1/bin/node]
11: 0x1003b87f1 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/artemzaiko/.nvm/versions/node/v14.19.1/bin/node]
12: 0x10037fd27 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/Users/artemzaiko/.nvm/versions/node/v14.19.1/bin/node]
13: 0x100274b54 v8::internal::Builtin_Impl_ArrayConcat(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/Users/artemzaiko/.nvm/versions/node/v14.19.1/bin/node]
14: 0x100a8e8b9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/Users/artemzaiko/.nvm/versions/node/v14.19.1/bin/node]
```

The issue is reproduced when modules `ProjectModule` and `UserModule` have circular dependencies to each other and they are imported with dynamic module as shown below

```TypeScript
@Module({})
export class ProjectModule {
  static forRoot(): DynamicModule {
    return {
      module: ProjectModule,
      imports: [forwardRef(() => UserModule.forRoot())],
      providers: [ProjectService],
      exports: [ProjectService],
    };
  }
}

@Module({})
export class UserModule {
  static forRoot(): DynamicModule {
    return {
      module: UserModule,
      imports: [forwardRef(() => ProjectModule.forRoot())],
      providers: [UserService],
      exports: [UserService],
    };
  }
}
```

But we don't have a problem if we add the same imports in @Module() decorator
```TypeScript
@Module({
  imports: [forwardRef(() => UserModule.forRoot())],
})
export class ProjectModule {
  static forRoot(): DynamicModule {
    return {
      module: ProjectModule,
      // imports: [forwardRef(() => UserModule.forRoot())],
      providers: [ProjectService],
      exports: [ProjectService],
    };
  }
}

@Module({
  imports: [forwardRef(() => ProjectModule.forRoot())],
})
export class UserModule {
  static forRoot(): DynamicModule {
    return {
      module: UserModule,
      // imports: [forwardRef(() => ProjectModule.forRoot())],
      providers: [UserService],
      exports: [UserService],
    };
  }
}
```

Problem investigating (Nest source): `nest/packages/core/scanner.ts`

There is a place where Nest checks that the module is already registered (inside the `scanForModules` method).

```TypeScript
if (ctxRegistry.includes(innerModule)) {
  continue;
}
```

If the module is imported via `forwardRef` the `innerModule` variable contains an object and the `ctxRegistry.includes(innerModule)` condition is always `false`. In such cases the code recursively pushes the same modules until the error

<img width="541" alt="image" src="https://user-images.githubusercontent.com/102226752/200812982-569a7555-743b-4d15-935e-53f449a1e7ee.png">

We patch the code of Nest to temporary solve the problem:
```TypeScript
if (this.isForwardReference(innerModule)) {
    const extractedInnerModuleRef = innerModule.forwardRef();
    const extractedInnerModuleInst =
        this.isDynamicModule(extractedInnerModuleRef) ?
        extractedInnerModuleRef.module :
        extractedInnerModuleRef;

    const moduleAlreadyRegistered = ctxRegistry.some((registeredModule) => {
        const registeredModuleRef =
            this.isForwardReference(registeredModule) ?
            registeredModule.forwardRef() :
            registeredModule;
        
        const registeredModuleInst =
            this.isDynamicModule(registeredModuleRef) ?
            registeredModuleRef.module :
            registeredModuleRef;

        return extractedInnerModuleInst == registeredModuleInst;
    })

    if (moduleAlreadyRegistered) {
        continue;
    }
}

if (ctxRegistry.includes(innerModule)) {
    continue;
}
```

But we run into with another problem when we start the project:

### ERROR [ExceptionHandler] metatype is not a constructor
```
[Nest] 6003  - 09/11/2022, 14:19:13   ERROR [ExceptionHandler] metatype is not a constructor
TypeError: metatype is not a constructor
    at Injector.instantiateClass (/Users/artemzaiko/Documents/projects/github-azaiko-akveo/nest-issue/node_modules/@nestjs/core/injector/injector.js:340:19)
    at callback (/Users/artemzaiko/Documents/projects/github-azaiko-akveo/nest-issue/node_modules/@nestjs/core/injector/injector.js:53:45)
    at Injector.resolveConstructorParams (/Users/artemzaiko/Documents/projects/github-azaiko-akveo/nest-issue/node_modules/@nestjs/core/injector/injector.js:132:24)
    at Injector.loadInstance (/Users/artemzaiko/Documents/projects/github-azaiko-akveo/nest-issue/node_modules/@nestjs/core/injector/injector.js:57:13)
    at Injector.loadProvider (/Users/artemzaiko/Documents/projects/github-azaiko-akveo/nest-issue/node_modules/@nestjs/core/injector/injector.js:84:9)
    at async Promise.all (index 0)
    at InstanceLoader.createInstancesOfProviders (/Users/artemzaiko/Documents/projects/github-azaiko-akveo/nest-issue/node_modules/@nestjs/core/injector/instance-loader.js:47:9)
    at /Users/artemzaiko/Documents/projects/github-azaiko-akveo/nest-issue/node_modules/@nestjs/core/injector/instance-loader.js:32:13
    at async Promise.all (index 6)
    at InstanceLoader.createInstances (/Users/artemzaiko/Documents/projects/github-azaiko-akveo/nest-issue/node_modules/@nestjs/core/injector/instance-loader.js:31:9)
```

The issue is the same as #10347, but we mention it here to have the same project to reproduce both problems

Problem investigating (Nest source): `nest/packages/core/injector/module.ts`

In the `addModuleAsProvider` method the `metatype` property is added as `ForwardReference` object but not as the module class
<img width="858" alt="image" src="https://user-images.githubusercontent.com/102226752/200820556-4af4d8a0-9e03-4974-b44b-8a340ce34501.png">

### Minimum reproduction code

https://github.com/azaiko-akveo/nest-issue

### Steps to reproduce

1. `npm ci`
2. `npm run start:dev`
3. See the error

### Expected behavior

Project is started successfully

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json
"@nestjs/common": "^9.0.0",
"@nestjs/core": "^9.0.0",
"@nestjs/platform-express": "^9.0.0",
"reflect-metadata": "^0.1.13",
```

### Node.js version

14.19.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
