### ISSUE TITLE
new graphql module breaks e2e tests

### ISSUE THREAD

**Issue by agborkowski** [nestjs/nest#1055]
## I'm submitting a...
[ ] Regression
[x ] Bug report
[ ] Feature request
[ ] Documentation issue or request

## Current behavior
Adding graphql module to app.module.ts break a e2e tests 

```
const moduleFixture = await Test.createTestingModule({
			imports: [
				AppModule,
			],
		}).compile();
```

each `it` test throw

````
TypeError: this.httpServer.getInstance is not a function

      at GraphQLModule.<anonymous> (../node_modules/@nestjs/graphql/dist/graphql.module.js:89:41)
      at ../node_modules/@nestjs/graphql/dist/graphql.module.js:19:71
      at Object.<anonymous>.__awaiter (../node_modules/@nestjs/graphql/dist/graphql.module.js:15:12)
      at GraphQLModule.onModuleInit (../node_modules/@nestjs/graphql/dist/graphql.module.js:87:16)
      at NestApplication.callModuleInitHook (../node_modules/@nestjs/core/nest-application-context.js:66:39)
````

## Expected behavior
dont throw type error

## Minimal reproduction of the problem with instructions
add to app.module.ts imports array:

```
GraphQLModule.forRoot({
			typePaths: ['./**/*.graphql'],
		}),
```

npm run test:e2e

**Comment by kamilmysliwiec** [comment]
Let's track this issue here: https://github.com/nestjs/graphql/issues/58
