### ISSUE TITLE
ConfigService from '@nestjs/config'; stops bringing env variables when "resolveJsonModule": true is used in the tsconfig.ts

### ISSUE THREAD

**Issue by bethsugar** [nestjs/nest#10563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

-------------------------------------------------------
                          HERE IT WORKS
-------------------------------------------------------

My configuration.service.ts

```
@Injectable()
export class ConfigurationService {
  @Inject(ConfigService)
  public config: ConfigService;

  get getBanner(): string {
    let file = fs.readFileSync(banner).toString();

    file = file
      .toString()
      .replace(/_port_/, this.config.get('SERVER_PORT').toString());
    file = file
      .toString()
      .replace(/_databaseHost_/, this.config.get('DB_HOST').toString());
    file = file
      .toString()
      .replace(/_databasePort_/, this.config.get('DB_PORT').toString());
    file = file
      .toString()
      .replace(/_schema_/, this.config.get('DB_SCHEMA').toString());
    file = file
      .toString()
      .replace(/_mode_/, this.config.get('NODE_ENV').toString());

    return file.toLocaleString();
  }
```

My main.ts
```
import { NestFactory } from '@nestjs/core';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { AppModule } from './app.module';
import { ConfigurationService } from './configuration/configuration.service';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  const config: ConfigurationService = app.get(ConfigurationService);

  console.log(config.getBanner);
```
My tsconfig.json
```
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  }
}
```
My console.log

```

[Nest] 31592  - 11/14/2022, 3:00:52 PM     LOG [NestFactory] Starting Nest application...
[Nest] 31592  - 11/14/2022, 3:00:52 PM     LOG [InstanceLoader] SwaggerModule dependencies initialized +27ms
[Nest] 31592  - 11/14/2022, 3:00:52 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +1ms
[Nest] 31592  - 11/14/2022, 3:00:52 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 31592  - 11/14/2022, 3:00:52 PM     LOG [InstanceLoader] AppModule dependencies initialized +1ms

  █████╗ ██████╗ ██╗    ██╗    ██████╗ ███████╗██╗     ███████╗ █████╗ ███████╗███████╗███████╗  Http server port:  3000
 ██╔══██╗██╔══██╗██║    ██║    ██╔══██╗██╔════╝██║     ██╔════╝██╔══██╗██╔════╝██╔════╝██╔════╝  Database host: database-blah-blah
 ███████║██████╔╝██║    ██║    ██████╔╝█████╗  ██║     █████╗  ███████║███████╗█████╗  ███████╗  Database port: 543
 ██╔══██║██╔═══╝ ██║    ██║    ██╔══██╗██╔══╝  ██║     ██╔══╝  ██╔══██║╚════██║██╔══╝  ╚════██║  Database Schema: public
 ██║  ██║██║     ██║    ██║    ██║  ██║███████╗███████╗███████╗██║  ██║███████║███████╗███████║  Started in [ yanina-dev ] mode!
 ╚═╝  ╚═╝╚═╝     ╚═╝    ╚═╝    ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝  
  Powered by ......
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

[Nest] 31592  - 11/14/2022, 3:00:52 PM     LOG [RoutesResolver] AppController {/}: +17ms
[Nest] 31592  - 11/14/2022, 3:00:52 PM     LOG [NestApplication] Nest application successfully started +3ms
```

-------------------------------------------------------
                     HERE STOPS WORKING
-------------------------------------------------------
I need to log the version of the API from the package.json to make it easier. So I need to add `"resolveJsonModule": true` in my tsconfig.json like this:

tsconfig.json
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,  
   /* HERE */
    "resolveJsonModule": true,    /* HERE */
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false,
  }
}

```

my main.ts:
```
import { NestFactory } from '@nestjs/core';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { AppModule } from './app.module';
import { ConfigurationService } from './configuration/configuration.service';
import { version } from 'package.json';  //HERE

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  const config: ConfigurationService = app.get(ConfigurationService);

  console.log(config.getBanner);
  console.log(version);   // This works
```

The error log:

```
[3:09:39 PM] Found 0 errors. Watching for file changes.

[Nest] 26556  - 11/14/2022, 3:09:39 PM     LOG [NestFactory] Starting Nest application...
[Nest] 26556  - 11/14/2022, 3:09:39 PM     LOG [InstanceLoader] SwaggerModule dependencies initialized +28ms
[Nest] 26556  - 11/14/2022, 3:09:39 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 26556  - 11/14/2022, 3:09:39 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 26556  - 11/14/2022, 3:09:39 PM     LOG [InstanceLoader] AppModule dependencies initialized +1ms
(node:26556) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at ConfigurationService.get getBanner [as getBanner] (C:\Users\yanis\Documents\back-api-integracion-release\src\configuration\configuration.service.ts:17:56)
    at bootstrap (C:\Users\yanis\Documents\back-api-integracion-release\src\main.ts:11:22)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:26556) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
  And when I remove again the ``` "resolveJsonModule": true ```  from the tsconfig.ts it works again.

The problem is with the ``` this.config.get('SERVER_PORT').toString() ``` it brings undefined

### Minimum reproduction code

none

### Steps to reproduce

1. Add "resolveJsonModule": true in the tsconfig.ts
2. npm run build
3. npm run start

### Expected behavior

`ConfigService  from '@nestjs/config' ` must work when `"resolveJsonModule": true` is used in the` tsconfig.ts`

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/config

### NestJS version

9.1.5

### Packages versions

```json
{
  "name": "back-api-integracion-release",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:dev:yani": "SET NODE_ENV=yanina-dev & nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/swagger": "^6.1.3",
    "@nestjs/typeorm": "^9.0.1",
    "async": "^3.2.4",
    "firebase": "^9.13.0",
    "firebase-admin": "^11.2.0",
    "mysql2": "^2.3.3",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "typeorm": "^0.3.10"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "28.1.8",
    "@types/node": "^16.18.3",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.1.3",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.8",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.1.0",
    "typescript": "^4.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

14.17.6

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
I've been using that `resolveJsonModule` flag along with `app.get(ConfigService)` in `bootstrap` since nestjs v8 just fine.

If you think this could be an issue in the framework side, please share us a minimum reproduction repository. Or you can discuss this in our [Discord](https://discord.gg/nestjs)

![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)

### [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)
