### ISSUE TITLE
[RabbitMQ Microservice]  "No matching message handler defined in the remote service." Every 2 requests

### ISSUE THREAD

**Issue by kanottonp** [nestjs/nest#10576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello guys,

Now I'm implementing 2 monorepo microservices, communicated each other with RabbitMQ and handle requests with Graphql.

In every 2 requests from reproduction step below cause the error like this

```
{
	"errors": [
		{
			"message": "Unexpected error value: \"There is no matching message handler defined in the remote service.\"",
			"locations": [
				{
					"line": 2,
					"column": 2
				}
			],
			"path": [
				"itemInventory1List"
			],
			"extensions": {
				"code": "INTERNAL_SERVER_ERROR",
				"exception": {
					"name": "NonErrorThrown",
					"thrownValue": "There is no matching message handler defined in the remote service.",
					"stacktrace": [
						"NonErrorThrown: Unexpected error value: \"There is no matching message handler defined in the remote service.\"",
						"    at toError (/usr/src/app/node_modules/graphql/jsutils/toError.js:16:7)",
						"    at locatedError (/usr/src/app/node_modules/graphql/error/locatedError.js:20:46)",
						"    at /usr/src/app/node_modules/graphql/execution/execute.js:503:54",
						"    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
						"    at async Promise.all (index 0)",
						"    at execute (/usr/src/app/node_modules/apollo-server-core/src/requestPipeline.ts:501:14)",
						"    at processGraphQLRequest (/usr/src/app/node_modules/apollo-server-core/src/requestPipeline.ts:407:22)",
						"    at processHTTPRequest (/usr/src/app/node_modules/apollo-server-core/src/runHttpQuery.ts:436:24)"
					]
				}
			}
		}
	],
	"data": {
		"itemInventory1List": null
	}
}
```

Is there anything I'm wrong or is this a new bug?

Thank you.

### Minimum reproduction code

https://github.com/kanottonp/nestjs-rabbitmq-bug-reproducer

### Steps to reproduce

1. npm install
2. npm run start:dev inventory-1
3. npm run start:dev inventory-2
4. send Graphql query to 'localhost:3001/graphql'  repeatedly as 
```
query {
	itemInventory1List {
		id
		name
		description
	}
}
```
5. the error will be showed in every 2 requests.

### Expected behavior

can request repeatedly without an error.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

^8.0.0

### Packages versions

```
{
  "name": "app-name",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"apps/**/*.ts\" \"libs/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./apps/npru-backend/test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/apollo": "^10.1.6",
    "@nestjs/common": "^8.0.0",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/graphql": "^10.1.6",
    "@nestjs/microservices": "^9.2.0",
    "@nestjs/platform-express": "^8.0.0",
    "@prisma/client": "^4.6.1",
    "amqp-connection-manager": "^4.1.9",
    "amqplib": "^0.10.3",
    "apollo-server-core": "^3.11.1",
    "apollo-server-express": "^3.11.1",
    "graphql": "^16.6.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "27.4.1",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "^27.2.5",
    "prettier": "^2.3.2",
    "prisma": "^4.6.1",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": ".",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "./coverage",
    "testEnvironment": "node",
    "roots": [
      "<rootDir>/apps/"
    ]
  }
}


```

### Node.js version

16.14.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
