### ISSUE TITLE
How to use socketIO middlewares

### ISSUE THREAD

**Issue by jackple** [nestjs/nest#1059]
How can I achieve like:

```
...
import socketioWildcard from 'socketio-wildcard'
....

@SubscribeMessage('*')
onEvent(): Observable<WsResponse<number>> {
    return from([1, 2, 3]).pipe(
          map(item => ({ event: 'events_from_server', data: item })),
     )
}
```

**Comment by jackple** [comment]
@kamilmysliwiec It does not work!
```

/Users/jackple/Documents/node/showcase/node_modules/socket.io/lib/namespace.js:124
    fns[i](socket, function(err){
          ^
TypeError: fns[i] is not a function
    at run (/Users/jackple/Documents/node/showcase/node_modules/socket.io/lib/namespace.js:124:11)
    at Namespace.run (/Users/jackple/Documents/node/showcase/node_modules/socket.io/lib/namespace.js:136:3)
    at Namespace.add (/Users/jackple/Documents/node/showcase/node_modules/socket.io/lib/namespace.js:164:8)
    at Client.doConnect (/Users/jackple/Documents/node/showcase/node_modules/socket.io/lib/client.js:97:20)
    at Client.connect (/Users/jackple/Documents/node/showcase/node_modules/socket.io/lib/client.js:66:17)
    at Server.onconnection (/Users/jackple/Documents/node/showcase/node_modules/socket.io/lib/index.js:434:10)
    at emitOne (events.js:116:13)
    at Server.emit (events.js:211:7)
    at Server.handshake (/Users/jackple/Documents/node/showcase/node_modules/engine.io/lib/server.js:338:8)
    at /Users/jackple/Documents/node/showcase/node_modules/engine.io/lib/server.js:232:12
    at Server.checkRequest (/Users/jackple/Documents/node/showcase/node_modules/socket.io/lib/index.js:76:51)
    at Server.verify (/Users/jackple/Documents/node/showcase/node_modules/engine.io/lib/server.js:168:17)
    at Server.handleRequest (/Users/jackple/Documents/node/showcase/node_modules/engine.io/lib/server.js:222:8)
    at Server.<anonymous> (/Users/jackple/Documents/node/showcase/node_modules/engine.io/lib/server.js:467:14)
    at Server.<anonymous> (/Users/jackple/Documents/node/showcase/node_modules/socket.io/lib/index.js:343:16)
    at emitTwo (events.js:126:13)
```

**Comment by jackple** [comment]
Base on the error, I resolve this problem by:
```
import { IoAdapter } from '@nestjs/websockets'
import { EventEmitter } from 'events'
import * as socketioWildcard from 'socketio-wildcard'
import { Server } from 'socket.io'

export default class WildcardsIoAdapter extends IoAdapter {
    createIOServer(port: number, options?: any): any {
        const server: Server = super.createIOServer(port, options)
        server.use(socketioWildcard(EventEmitter))
        return server
    }
}
```

I do not know if it is a right way. But it work!
