### ISSUE TITLE
Fastify Http Proxy not working with Nestjs

### ISSUE THREAD

**Issue by all2pie** [nestjs/nest#10731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Getting this error on app start: 

```

C:\Work\Bugs\nest-fastify-http-proxy-bug\node_modules\.pnpm\fastify@4.10.2\node_modules\fastify\lib\contentTypeParser.js:51
    throw new FST_ERR_CTP_ALREADY_PRESENT(contentType)
          ^
FastifyError: Content type parser 'application/json' already present.
    at ContentTypeParser.add (C:\Work\Bugs\nest-fastify-http-proxy-bug\node_modules\.pnpm\fastify@4.10.2\node_modules\fastify\lib\contentTypeParser.js:51:11)
    at Object.addContentTypeParser (C:\Work\Bugs\nest-fastify-http-proxy-bug\node_modules\.pnpm\fastify@4.10.2\node_modules\fastify\lib\contentTypeParser.js:329:30)
    at fastifyHttpProxy (C:\Work\Bugs\nest-fastify-http-proxy-bug\node_modules\.pnpm\@fastify+http-proxy@8.4.0\node_modules\@fastify\http-proxy\index.js:209:13)
    at Plugin.exec (C:\Work\Bugs\nest-fastify-http-proxy-bug\node_modules\.pnpm\avvio@8.2.0\node_modules\avvio\plugin.js:130:19)
    at Boot.loadPlugin (C:\Work\Bugs\nest-fastify-http-proxy-bug\node_modules\.pnpm\avvio@8.2.0\node_modules\avvio\plugin.js:272:10)        
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

### Minimum reproduction code

https://github.com/all2pie/nest-fastify-http-proxy-bug

### Steps to reproduce

You will get error on `npm start`

Comment the `app.register()` method in the main.ts file to start app properly.

### Expected behavior

It should work correctly as specified in this [Example](https://github.com/fastify/fastify-http-proxy#example)

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.1.4

### Packages versions

```json
  {
    "@fastify/http-proxy": "^8.4.0",
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/platform-fastify": "^9.2.1",
    "fastify": "^4.10.2",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  }
```

### Node.js version

16.17.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
You can have Nest not add the body parser by default with the option: `{ bodyParser: false }` in the third parameter of the `NestFactory.create()`. Then this works as expected. 

For further support, please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
