### ISSUE TITLE
Kafka consumer and a validation pipe can't work together - infinite retry loop

### ISSUE THREAD

**Issue by skilef** [nestjs/nest#10972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When the **ValidationPipe** throws `BadRequestException` on an invalid input, Kafka's retry mechanism is triggered.
This causes an infinite retry loop - after max retries exceeded the consumer crashes, then restarts and then we get the same exceptions again and again.

I read this [https://docs.nestjs.com/microservices/kafka#retriable-exceptions](https://docs.nestjs.com/microservices/kafka#retriable-exceptions). It says clearly that all unhandled exceptions of event handlers are considered retriable. I tried then to use the **MessagePattern** instead of the **EventPattern** but this acts the same - every exception is retriable.

Of course I can just not use exceptions at all but then I can't enjoy of features like **ValidationPipe**s and etc.

I think this stackoverflow question talks about the same issue: [https://stackoverflow.com/questions/74403746/infinite-retries-when-using-rpcfilter-in-nestjs-microservice-setup-with-kafka](https://stackoverflow.com/questions/74403746/infinite-retries-when-using-rpcfilter-in-nestjs-microservice-setup-with-kafka).

### Minimum reproduction code

https://github.com/skilef/kafka-validation-pipe-bug-reproduction

### Steps to reproduce

1. npm install
2. docker compose up -d zookeeper
3. docker compose up -d kafka
4. docker compose up -d kafka-ui # not required
5. npx nest start
6. curl http://localhost:3001/bug

### Expected behavior

I would expect that not every exception will start the Kafka's retry mechanism because then I can't use exceptions for normal non-retriable scenarios like input validation.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json
{
  "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/microservices": "^9.2.1",
    "@nestjs/platform-express": "^9.0.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "kafkajs": "^2.2.3",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.5.5"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "^28.1.4",
    "@types/node": "^18.0.3",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.30.5",
    "@typescript-eslint/parser": "^5.30.5",
    "eslint": "^8.19.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^28.1.2",
    "prettier": "^2.7.1",
    "source-map-support": "^0.5.21",
    "supertest": "^6.2.4",
    "ts-jest": "^28.0.5",
    "ts-loader": "^9.3.1",
    "ts-node": "^10.8.2",
    "tsconfig-paths": "^4.0.0",
    "typescript": "^4.7.4"
  }
}

```

### Node.js version

18.12.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

# A partial log
```bash
[Nest] 91122  - 27/01/2023, 14:56:01   ERROR [RpcExceptionsHandler] Bad Request Exception
BadRequestException: Bad Request Exception
    at ValidationPipe.exceptionFactory (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/common/pipes/validation.pipe.js:90:20)
    at ValidationPipe.transform (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/common/pipes/validation.pipe.js:66:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at resolveParamValue (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:106:31)
    at async Promise.all (index 0)
    at pipesFn (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:108:13)
    at /home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:43:17
    at /home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-proxy.js:11:32
    at ServerKafka.handleEvent (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/server/server-kafka.js:189:32)
    at Runner.processEachMessage (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/kafkajs/src/consumer/runner.js:231:9)
[Nest] 91122  - 27/01/2023, 14:56:01   ERROR [ServerKafka] ERROR [Runner] Error when calling eachMessage {"timestamp":"2023-01-27T12:56:01.642Z","logger":"kafkajs","topic":"hero.weapon.set","partition":0,"offset":"12","error":{"status":"error","message":"Internal server error"}}
[Nest] 91122  - 27/01/2023, 14:56:01   ERROR [RpcExceptionsHandler] Bad Request Exception
BadRequestException: Bad Request Exception
    at ValidationPipe.exceptionFactory (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/common/pipes/validation.pipe.js:90:20)
    at ValidationPipe.transform (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/common/pipes/validation.pipe.js:66:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at resolveParamValue (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:106:31)
    at async Promise.all (index 0)
    at pipesFn (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:108:13)
    at /home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:43:17
    at /home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-proxy.js:11:32
    at ServerKafka.handleEvent (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/server/server-kafka.js:189:32)
    at Runner.processEachMessage (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/kafkajs/src/consumer/runner.js:231:9)
[Nest] 91122  - 27/01/2023, 14:56:01   ERROR [ServerKafka] ERROR [Runner] Error when calling eachMessage {"timestamp":"2023-01-27T12:56:01.985Z","logger":"kafkajs","topic":"hero.weapon.set","partition":0,"offset":"12","error":{"status":"error","message":"Internal server error"}}
[Nest] 91122  - 27/01/2023, 14:56:02   ERROR [RpcExceptionsHandler] Bad Request Exception
BadRequestException: Bad Request Exception
    at ValidationPipe.exceptionFactory (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/common/pipes/validation.pipe.js:90:20)
    at ValidationPipe.transform (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/common/pipes/validation.pipe.js:66:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at resolveParamValue (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:106:31)
    at async Promise.all (index 0)
    at pipesFn (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:108:13)
    at /home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:43:17
    at /home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-proxy.js:11:32
    at ServerKafka.handleEvent (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/server/server-kafka.js:189:32)
    at Runner.processEachMessage (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/kafkajs/src/consumer/runner.js:231:9)
[Nest] 91122  - 27/01/2023, 14:56:02   ERROR [ServerKafka] ERROR [Runner] Error when calling eachMessage {"timestamp":"2023-01-27T12:56:02.530Z","logger":"kafkajs","topic":"hero.weapon.set","partition":0,"offset":"12","error":{"status":"error","message":"Internal server error"}}
[Nest] 91122  - 27/01/2023, 14:56:03   ERROR [RpcExceptionsHandler] Bad Request Exception
BadRequestException: Bad Request Exception
    at ValidationPipe.exceptionFactory (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/common/pipes/validation.pipe.js:90:20)
    at ValidationPipe.transform (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/common/pipes/validation.pipe.js:66:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at resolveParamValue (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:106:31)
    at async Promise.all (index 0)
    at pipesFn (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:108:13)
    at /home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:43:17
    at /home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-proxy.js:11:32
    at ServerKafka.handleEvent (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/server/server-kafka.js:189:32)
    at Runner.processEachMessage (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/kafkajs/src/consumer/runner.js:231:9)
[Nest] 91122  - 27/01/2023, 14:56:03   ERROR [ServerKafka] ERROR [Runner] Error when calling eachMessage {"timestamp":"2023-01-27T12:56:03.610Z","logger":"kafkajs","topic":"hero.weapon.set","partition":0,"offset":"12","error":{"status":"error","message":"Internal server error"}}
[Nest] 91122  - 27/01/2023, 14:56:05   ERROR [RpcExceptionsHandler] Bad Request Exception
BadRequestException: Bad Request Exception
    at ValidationPipe.exceptionFactory (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/common/pipes/validation.pipe.js:90:20)
    at ValidationPipe.transform (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/common/pipes/validation.pipe.js:66:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at resolveParamValue (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:106:31)
    at async Promise.all (index 0)
    at pipesFn (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:108:13)
    at /home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:43:17
    at /home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-proxy.js:11:32
    at ServerKafka.handleEvent (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/server/server-kafka.js:189:32)
    at Runner.processEachMessage (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/kafkajs/src/consumer/runner.js:231:9)
[Nest] 91122  - 27/01/2023, 14:56:05   ERROR [ServerKafka] ERROR [Runner] Error when calling eachMessage {"timestamp":"2023-01-27T12:56:05.393Z","logger":"kafkajs","topic":"hero.weapon.set","partition":0,"offset":"12","error":{"status":"error","message":"Internal server error"}}
[Nest] 91122  - 27/01/2023, 14:56:08   ERROR [RpcExceptionsHandler] Bad Request Exception
BadRequestException: Bad Request Exception
    at ValidationPipe.exceptionFactory (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/common/pipes/validation.pipe.js:90:20)
    at ValidationPipe.transform (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/common/pipes/validation.pipe.js:66:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at resolveParamValue (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:106:31)
    at async Promise.all (index 0)
    at pipesFn (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:108:13)
    at /home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:43:17
    at /home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-proxy.js:11:32
    at ServerKafka.handleEvent (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/server/server-kafka.js:189:32)
    at Runner.processEachMessage (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/kafkajs/src/consumer/runner.js:231:9)
[Nest] 91122  - 27/01/2023, 14:56:08   ERROR [ServerKafka] ERROR [Runner] Error when calling eachMessage {"timestamp":"2023-01-27T12:56:08.781Z","logger":"kafkajs","topic":"hero.weapon.set","partition":0,"offset":"12","error":{"status":"error","message":"Internal server error"}}
[Nest] 91122  - 27/01/2023, 14:56:08   ERROR [ServerKafka] ERROR [Consumer] Crash: KafkaJSNumberOfRetriesExceeded: Internal server error {"timestamp":"2023-01-27T12:56:08.782Z","logger":"kafkajs","groupId":"hero-consumer-server","retryCount":5,"stack":"KafkaJSNonRetriableError\n  Caused by: undefined"}
[Nest] 91122  - 27/01/2023, 14:56:08     LOG [ServerKafka] INFO [Consumer] Stopped {"timestamp":"2023-01-27T12:56:08.789Z","logger":"kafkajs","groupId":"hero-consumer-server"}
[Nest] 91122  - 27/01/2023, 14:56:08   ERROR [ServerKafka] ERROR [Consumer] Restarting the consumer in 6456ms {"timestamp":"2023-01-27T12:56:08.793Z","logger":"kafkajs","retryCount":5,"retryTime":6456,"groupId":"hero-consumer-server"}
[Nest] 91122  - 27/01/2023, 14:56:15     LOG [ServerKafka] INFO [Consumer] Starting {"timestamp":"2023-01-27T12:56:15.250Z","logger":"kafkajs","groupId":"hero-consumer-server"}
[Nest] 91122  - 27/01/2023, 14:56:18     LOG [ServerKafka] INFO [ConsumerGroup] Consumer has joined the group {"timestamp":"2023-01-27T12:56:18.273Z","logger":"kafkajs","groupId":"hero-consumer-server","memberId":"hero-server-1204f0bb-195b-44f5-a9d4-47d2b391e997","leaderId":"hero-server-1204f0bb-195b-44f5-a9d4-47d2b391e997","isLeader":true,"memberAssignment":{"hero.weapon.set":[0]},"groupProtocol":"RoundRobinAssigner","duration":3017}
[Nest] 91122  - 27/01/2023, 14:56:18   ERROR [RpcExceptionsHandler] Bad Request Exception
BadRequestException: Bad Request Exception
    at ValidationPipe.exceptionFactory (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/common/pipes/validation.pipe.js:90:20)
    at ValidationPipe.transform (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/common/pipes/validation.pipe.js:66:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at resolveParamValue (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:106:31)
    at async Promise.all (index 0)
    at pipesFn (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:108:13)
    at /home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:43:17
    at /home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-proxy.js:11:32
    at ServerKafka.handleEvent (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/server/server-kafka.js:189:32)
    at Runner.processEachMessage (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/kafkajs/src/consumer/runner.js:231:9)
[Nest] 91122  - 27/01/2023, 14:56:18   ERROR [ServerKafka] ERROR [Runner] Error when calling eachMessage {"timestamp":"2023-01-27T12:56:18.288Z","logger":"kafkajs","topic":"hero.weapon.set","partition":0,"offset":"12","error":{"status":"error","message":"Internal server error"}}
[Nest] 91122  - 27/01/2023, 14:56:18   ERROR [RpcExceptionsHandler] Bad Request Exception
BadRequestException: Bad Request Exception
    at ValidationPipe.exceptionFactory (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/common/pipes/validation.pipe.js:90:20)
    at ValidationPipe.transform (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/common/pipes/validation.pipe.js:66:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at resolveParamValue (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:106:31)
    at async Promise.all (index 0)
    at pipesFn (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:108:13)
    at /home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:43:17
    at /home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-proxy.js:11:32
    at ServerKafka.handleEvent (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/server/server-kafka.js:189:32)
    at Runner.processEachMessage (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/kafkajs/src/consumer/runner.js:231:9)
[Nest] 91122  - 27/01/2023, 14:56:18   ERROR [ServerKafka] ERROR [Runner] Error when calling eachMessage {"timestamp":"2023-01-27T12:56:18.622Z","logger":"kafkajs","topic":"hero.weapon.set","partition":0,"offset":"12","error":{"status":"error","message":"Internal server error"}}
[Nest] 91122  - 27/01/2023, 14:56:19   ERROR [RpcExceptionsHandler] Bad Request Exception
BadRequestException: Bad Request Exception
    at ValidationPipe.exceptionFactory (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/common/pipes/validation.pipe.js:90:20)
    at ValidationPipe.transform (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/common/pipes/validation.pipe.js:66:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at resolveParamValue (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:106:31)
    at async Promise.all (index 0)
    at pipesFn (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:108:13)
    at /home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:43:17
    at /home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-proxy.js:11:32
    at ServerKafka.handleEvent (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/server/server-kafka.js:189:32)
    at Runner.processEachMessage (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/kafkajs/src/consumer/runner.js:231:9)
[Nest] 91122  - 27/01/2023, 14:56:19   ERROR [ServerKafka] ERROR [Runner] Error when calling eachMessage {"timestamp":"2023-01-27T12:56:19.222Z","logger":"kafkajs","topic":"hero.weapon.set","partition":0,"offset":"12","error":{"status":"error","message":"Internal server error"}}
[Nest] 91122  - 27/01/2023, 14:56:20   ERROR [RpcExceptionsHandler] Bad Request Exception
BadRequestException: Bad Request Exception
    at ValidationPipe.exceptionFactory (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/common/pipes/validation.pipe.js:90:20)
    at ValidationPipe.transform (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/common/pipes/validation.pipe.js:66:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at resolveParamValue (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:106:31)
    at async Promise.all (index 0)
    at pipesFn (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:108:13)
    at /home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-context-creator.js:43:17
    at /home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/context/rpc-proxy.js:11:32
    at ServerKafka.handleEvent (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/@nestjs/microservices/server/server-kafka.js:189:32)
    at Runner.processEachMessage (/home/felix/workspace/kafka-validation-pipe-bug-reproduction/node_modules/kafkajs/src/consumer/runner.js:231:9)
[Nest] 91122  - 27/01/2023, 14:56:20   ERROR [ServerKafka] ERROR [Runner] Error when calling eachMessage {"timestamp":"2023-01-27T12:56:20.594Z","logger":"kafkajs","topic":"hero.weapon.set","partition":0,"offset":"12","error":{"status":"error","message":"Internal server error"}}
^C
```

**Comment by kamilmysliwiec** [comment]
> It says clearly that all unhandled exceptions of event handlers are considered retriable. I tried then to use the MessagePattern instead of the EventPattern but this acts the same - every exception is retriable.

Fixed in this PR https://github.com/nestjs/nest/pull/11020 - `MessagePattern` will no longer treat errors thrown from the ValidationPipe as retriable.

When it comes to the event handlers, on the other hand, all exceptions are supposed to be retriable. If you don't want the `BadRequestException` to trigger a retry mechanism, simply register the exception filter that processes this exception & ignores it when needed https://docs.nestjs.com/exception-filters
