### ISSUE TITLE
SubscribeMessage not working when run build in local or deply  ? 

### ISSUE THREAD

**Issue by hapo-quannt** [nestjs/nest#11024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

i using nestJs/websocket , when i run it locally, it works fine , but when I deploy , it doesn't work 
terminal : TypeError: this.graphInspector.insertEntrypointDefinition is not a function
how to fix it

### Minimum reproduction code

none

### Steps to reproduce

1, npm i 
2, npm i --save @nestjs/websockets @nestjs/platform-socket.io
3 , npm run build 

### Expected behavior

TypeError: this.graphInspector.insertEntrypointDefinition is not a function

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [X] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [X] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/jwt": "^9.0.0",
    "@nestjs/passport": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/platform-socket.io": "^9.2.1",
    "@nestjs/schedule": "^2.1.0",
    "@nestjs/serve-static": "^3.0.0",
    "@nestjs/swagger": "^6.1.2",
    "@nestjs/typeorm": "^9.0.1",
    "@nestjs/websockets": "^9.3.1",
    "@types/faker": "^6.6.9",
    "aws-sdk": "^2.1281.0",
    "bcrypt": "^5.1.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "faker": "^6.6.6",
    "moment": "^2.29.4",
    "mysql": "^2.18.1",
    "mysql2": "^2.3.3",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "redis": "^4.3.1",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "sharp": "^0.31.2",
    "socket.io": "^4.5.4",
    "typeorm": "^0.3.10",
    "typeorm-seeding": "^1.6.1"
```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
https://github.com/nestjs/nest/issues/11009#issuecomment-1413272994

**Comment by hapo-quannt** [comment]
> [#11009 (comment)](https://github.com/nestjs/nest/issues/11009#issuecomment-1413272994)

it is 9.0.0 , bro

**Comment by micalevisk** [comment]
did you read that comment, bro?

I'm pretty sure you got version mismatch.

If you don't think that is the case, share us a repro.

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by hapo-quannt** [comment]
sorry , my bad and thanks @micalevisk

**Comment by hapo-quannt** [comment]
@micalevisk  sorry to bother,  But it still doesn't work
here is my package.json
`"dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/jwt": "^9.0.0",
    "@nestjs/passport": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/platform-socket.io": "^9.0.0",
    "@nestjs/schedule": "^2.1.0",
    "@nestjs/serve-static": "^3.0.0",
    "@nestjs/swagger": "^6.1.2",
    "@nestjs/typeorm": "^9.0.1",
    "@nestjs/websockets": "^9.0.0",
    "@types/faker": "^6.6.9",
    "aws-sdk": "^2.1281.0",
    "bcrypt": "^5.1.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "faker": "^6.6.6",
    "moment": "^2.29.4",
    "mysql": "^2.18.1",
    "mysql2": "^2.3.3",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "redis": "^4.3.1",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "sharp": "^0.31.2",
    "typeorm": "^0.3.10",
    "typeorm-seeding": "^1.6.1"
  },`

here is my code in gateway
`import {
  SubscribeMessage,
  WebSocketGateway,
  OnGatewayInit,
  WebSocketServer,
  OnGatewayConnection,
  OnGatewayDisconnect,
  MessageBody,
  WsResponse,
} from '@nestjs/websockets';
import { Socket, Server } from 'socket.io';
import { notificationSocketAction } from './enum/notifications.enum';


@WebSocketGateway({ cors: '*' })
export class NotificationGateWay
{

  @WebSocketServer() server: Server;

  @SubscribeMessage('notifications')
  async findAll(@MessageBody() data: any) {
    return { event: 'notifications', data: notificationSocketAction.CREATED }
  }
}`

here is bug

`/home/hacom/Desktop/Crm/hapocrm-nest/node_modules/@nestjs/websockets/web-sockets-controller.js:106
        messageHandlers.forEach(handler => {
                        ^
TypeError: this.graphInspector.insertEntrypointDefinition is not a function
    at /home/hacom/Desktop/Crm/hapocrm-nest/node_modules/@nestjs/websockets/web-sockets-controller.js:108:33
    at Array.forEach (<anonymous>)
    at WebSocketsController.inspectEntrypointDefinitions (/home/hacom/Desktop/Crm/hapocrm-nest/node_modules/@nestjs/websockets/web-sockets-controller.js:106:25)
    at WebSocketsController.subscribeToServerEvents (/home/hacom/Desktop/Crm/hapocrm-nest/node_modules/@nestjs/websockets/web-sockets-controller.js:39:14)
    at WebSocketsController.connectGatewayToServer (/home/hacom/Desktop/Crm/hapocrm-nest/node_modules/@nestjs/websockets/web-sockets-controller.js:30:14)
    at SocketModule.connectGatewayToServer (/home/hacom/Desktop/Crm/hapocrm-nest/node_modules/@nestjs/websockets/socket-module.js:47:35)
    at /home/hacom/Desktop/Crm/hapocrm-nest/node_modules/@nestjs/websockets/socket-module.js:36:38
    at IteratorWithOperators.forEach (/home/hacom/Desktop/Crm/hapocrm-nest/node_modules/iterare/src/iterate.ts:202:13)
    at SocketModule.connectAllGateways (/home/hacom/Desktop/Crm/hapocrm-nest/node_modules/@nestjs/websockets/socket-module.js:36:14)
    at /home/hacom/Desktop/Crm/hapocrm-nest/node_modules/@nestjs/websockets/socket-module.js:31:61`

can you help me ?

**Comment by hapo-quannt** [comment]
@micalevisk  sorry to bother,  But it still doesn't work
here is my package.json
![image](https://user-images.githubusercontent.com/112452601/216546640-88873cda-66a0-4aa8-b2a3-053f692d4aa2.png)


here is my code in gateway
![image](https://user-images.githubusercontent.com/112452601/216546741-56a30553-0652-453a-977b-bdc81a533308.png)


here is bug

![image](https://user-images.githubusercontent.com/112452601/216546864-437c4a1e-7f6f-4210-b1dd-659fb032e71e.png)

can you help me ?

>

**Comment by micalevisk** [comment]
As you're using semver ranges, your package.json doesnt help

Run `npx nest info`

But I can already tell that `@nestjs/websockets` isnt in the same version of `@nestjs/core`
