### ISSUE TITLE
Since version 9.3.3 using vercel/pkg leads to runtime error

### ISSUE THREAD

**Issue by motabass** [nestjs/nest#11083]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

9.3.2 -> 9.3.3

### Describe the regression

The new dependency "@node-rs/xxhash": "^1.3.0" which appeared as dependency of @nestjs/core in my package-lock.json in v9.3.3 throws an runtime error when packaged to a binary with vercel/pkg to target alpine linux:

`
pkg/prelude/bootstrap.js:1876
throw error;
^
Error: Dynamic loading not supported
at process.dlopen (pkg/prelude/bootstrap.js:2255:28)
at Module._extensions..node (node:internal/modules/cjs/loader:1196:18)
at Module.load (node:internal/modules/cjs/loader:988:32)
at Module._load (node:internal/modules/cjs/loader:834:12)
at Module.require (node:internal/modules/cjs/loader:1012:19)
at Module.require (pkg/prelude/bootstrap.js:1855:31)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> (/snapshot/mng-clients_dev/node_modules/@node-rs/xxhash/index.js:161:31)
at Module._compile (pkg/prelude/bootstrap.js:1930:22)
at Module._extensions..js (node:internal/modules/cjs/loader:1166:10) {
code: 'ERR_DLOPEN_FAILED'
}
Node.js v18.5.0
`

i already tried using "linuxstatic" and "node16" for the build with pkg but it leads to the same error.

### Input code

```ts

```

### Expected behavior

Running a nestjs app packaged with vercel/pkg should not throw an error

**Comment by micalevisk** [comment]
this was fixed in v9.3.6

thanks

**Comment by motabass** [comment]
Are you sure i was trying with 9.3.6 at first and still had the issue. I just nailed it down to the one dependency introduced through 9.3.3

**Comment by micalevisk** [comment]
that package was remove here in PR #11073 

@motabass can you run `npx nest info`?

**Comment by micalevisk** [comment]
@motabass actually looks like that version was not published, my bad.

Should be fixed now in 9.3.7

**Comment by motabass** [comment]
Thanks i will give it a try
