### ISSUE TITLE
Can not access REQUEST scoped provider in the exception filter

### ISSUE THREAD

**Issue by ianzone** [nestjs/nest#11196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```
/home/ian/templates/vite-nest/node_modules/.pnpm/@nestjs+core@9.3.9_jrq2rdgfp2sx67wmylmrqliwxe/node_modules/@nestjs/core/injector/instance-links-host.js:24
            throw new unknown_element_exception_1.UnknownElementException(this.getInstanceNameByToken(token));
                  ^

UnknownElementException [Error]: Nest could not find RequestService element (this provider does not exist in the current context)
    at InstanceLinksHost.get (/home/ian/templates/vite-nest/node_modules/.pnpm/@nestjs+core@9.3.9_jrq2rdgfp2sx67wmylmrqliwxe/node_modules/@nestjs/core/injector/instance-links-host.js:24:19)
    at ModuleRef.resolvePerContext (/home/ian/templates/vite-nest/node_modules/.pnpm/@nestjs+core@9.3.9_jrq2rdgfp2sx67wmylmrqliwxe/node_modules/@nestjs/core/injector/abstract-instance-resolver.js:23:38)
    at ModuleRef.resolve (/home/ian/templates/vite-nest/node_modules/.pnpm/@nestjs+core@9.3.9_jrq2rdgfp2sx67wmylmrqliwxe/node_modules/@nestjs/core/injector/module.js:409:29)
    at AppFilter1.catch (/src/app.filter.ts:23:49)
    at ExceptionsHandler.invokeCustomFilters (/home/ian/templates/vite-nest/node_modules/.pnpm/@nestjs+core@9.3.9_jrq2rdgfp2sx67wmylmrqliwxe/node_modules/@nestjs/core/exceptions/exceptions-handler.js:33:26)
    at ExceptionsHandler.next (/home/ian/templates/vite-nest/node_modules/.pnpm/@nestjs+core@9.3.9_jrq2rdgfp2sx67wmylmrqliwxe/node_modules/@nestjs/core/exceptions/exceptions-handler.js:13:18)
    at /home/ian/templates/vite-nest/node_modules/.pnpm/@nestjs+core@9.3.9_jrq2rdgfp2sx67wmylmrqliwxe/node_modules/@nestjs/core/router/router-proxy.js:13:35
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.12.0
 ELIFECYCLE  Command failed with exit code 1.
```

### Minimum reproduction code

https://github.com/ianzone/vite-nest-fastify

### Steps to reproduce

1. degit 'https://github.com/ianzone/vite-nest-fastify' to-check
2. cd to-check
3. pnpm i
4. pnpm run dev
5. GET http://localhost:3000/error

### Expected behavior

app doesn't crash

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

[System Information]
OS Version     : Linux 5.15
NodeJS Version : v18.12.0
PNPM Version    : 7.28.0

[Nest CLI]
Nest CLI Version : 9.2.0

[Nest Platform Information]
platform-fastify version : 9.3.9
swagger version          : 6.2.1
testing version          : 9.3.9
common version           : 9.3.9
config version           : 2.3.1
core version             : 9.3.9

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)
- make this question at [StackOverflow](https://stackoverflow.com/questions/ask?tags=nestjs) instead
