### ISSUE TITLE
Write Response Inside Interceptor Causing Issue

### ISSUE THREAD

**Issue by Ibrahimogod** [nestjs/nest#11313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm trying to build an interceptor to use specific return type and send response code and body depends on this type 
```
export class ResponseInterceptor implements NestInterceptor<IActionResult> {
    intercept(context: ExecutionContext, next: CallHandler<IActionResult>): Observable<any> | Promise<Observable<any>> {
        const ctx = context.switchToHttp();
        const response = ctx.getResponse<FastifyReply>();

        return next.handle().pipe(
            tap(ar => {
                response
                    .code(ar.statusCode)
                    .send(ar.body)
                    .then(() => {
                        response.sent = true;
                    },
                    (err) => {
                        Logger.error(err)
                    })
            })
        )
    }
}
```
error while trying to send response using interceptor
```
{"level":40,"time":1679413744124,"pid":30408,"hostname":"Ibrahimogod-Sub","reqId":"req-1","err":{"type":"FastifyError","message":"Reply was already sent.","stack":"FastifyError: Reply was already sent.\n    at Reply.send (C:\\Users\\IbrahimBadr\\Projects\\SubsBase\\notification-center\\backend\\node_modules\\fastify\\lib\\reply.js:127:26)\n    at FastifyAdapter.reply (C:\\Users\\IbrahimBadr\\Projects\\SubsBase\\notification-center\\backend\\node_modules\\@nestjs\\platform-fastify\\adapters\\fastify-adapter.js:187:29)\n    at RouterResponseController.apply (C:\\Users\\IbrahimBadr\\Projects\\SubsBase\\notification-center\\backend\\node_modules\\@nestjs\\core\\router\\router-response-controller.js:15:36)\n    at C:\\Users\\IbrahimBadr\\Projects\\SubsBase\\notification-center\\backend\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:176:48\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at C:\\Users\\IbrahimBadr\\Projects\\SubsBase\\notification-center\\backend\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:47:13\n    at Object.<anonymous> (C:\\Users\\IbrahimBadr\\Projects\\SubsBase\\notification-center\\backend\\node_modules\\@nestjs\\core\\router\\router-proxy.js:9:17)","name":"FastifyError","code":"FST_ERR_REP_ALREADY_SENT","statusCode":500},"msg":"Reply already sent"}
```

### Minimum reproduction code

https://github.com/subsbase/notification-center/tree/main/backend

### Steps to reproduce

Use below code as `Global Interceptor` and Return `IActionResult` type that contains only `statusCode: HttpStatus;` and `body?: object` from the endpoint handler function 
```
export class ResponseInterceptor implements NestInterceptor<IActionResult> {
    intercept(context: ExecutionContext, next: CallHandler<IActionResult>): Observable<any> | Promise<Observable<any>> {
        const ctx = context.switchToHttp();
        const response = ctx.getResponse<FastifyReply>();

        return next.handle().pipe(
            tap(ar => {
                response
                    .code(ar.statusCode)
                    .send(ar.body)
                    .then(() => {
                        response.sent = true;
                    },
                    (err) => {
                        Logger.error(err)
                    })
            })
        )
    }
}
```

### Expected behavior

Send expected response to use with no errors or exceptions

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.2.0

### Packages versions

```
"dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/config": "^2.3.1",
    "@nestjs/core": "^9.0.0",
    "@nestjs/mongoose": "^9.2.1",
    "@nestjs/platform-fastify": "^9.3.9",
    "mongoose": "^6.10.3",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0"
  },
```

### Node.js version

v18.15.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
