### ISSUE TITLE
While mocking @nestjs/common with jest, getting TypeError: (0 , index_1.Injectable) is not a function

### ISSUE THREAD

**Issue by MansurAliKoroglu** [nestjs/nest#11602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I tested with fresh `npx @nestjs/cli new project` to confirm.

With this code in a test file

```ts
import { Module } from '@nestjs/common';

// import { AppModule } from './app.module';

jest.mock('@nestjs/common');

describe('', () => {
  test('', () => {
    // When there is this, I got that error.
    const mockedModule = jest.mocked(Module);

    // This also causing the same error
    // new AppModule();

    // This does not cause
    // console.log('something')
  });
});
```

I got an error

```
TypeError: (0 , index_1.Injectable) is not a function

    > 1 | import { Module } from '@nestjs/common';
        | ^
      2 |
      3 | // import { AppModule } from './app.module';
      4 |

      at Object.<anonymous> (../node_modules/@nestjs/common/pipes/parse-float.pipe.js:46:28)
      at Object.<anonymous> (../node_modules/@nestjs/common/pipes/index.js:8:22)
      at Object.<anonymous> (../node_modules/@nestjs/common/index.js:21:22)
      at Object.<anonymous> (app.module.spec.ts:1:1)
```

### Minimum reproduction code

*No response*

### Steps to reproduce

1. Create a fresh project `npx @nestjs/cli new testing-project`
2. Create `app.module.spec.ts` file under `src`.
3. Copy paste the code under *Current behaviour* title to `app.module.spec.ts`
4. Run `npm test`

### Expected behavior

I should be able to use jest features on NestJS project with no error.

### Package

- [X] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

^9.0.0

### Packages versions

```json
{
  "name": "test-project",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "29.5.0",
    "@types/node": "18.15.11",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "29.5.0",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "29.0.5",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.2.0",
    "typescript": "^4.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
```

### Node.js version

18.16.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

- @nestjs/cli version to create project: 9.4.2
- npm version: 9.6.5
- node version: 18.16.0
- Operating System: Kubuntu 22.04

**Comment by jmcdo29** [comment]
Why are you mocking `@nestjs/common`?

**Comment by MansurAliKoroglu** [comment]
I was trying to apply some of the concepts discussed by Sandi Metz. [Rails Conf 2013 The Magic Tricks of Testing by Sandi Metz](https://www.youtube.com/watch?v=URSWYvyc42M&pp=ygUfc2FuZHkgbWV0eiB0ZXN0aW5nIG1hZ2ljIHRyaWNrcw%3D%3D)

**Comment by micalevisk** [comment]
this seems to be an issue/limitation on how `Injectable` decorator are being imported into `parse-float.pipe.ts` from `@nestjs/common`:

https://github.com/nestjs/nest/blob/85966703ac57a5b263ab5807033f6ac78548c0ef/packages/common/pipes/parse-float.pipe.ts#L1

but `../index` (or `common/index`) is also importing both `ParseFloatPipe` and `Injectable`. Thus we got a module circularity that Jest doesn't manage to resolve, I guess?

By adding this:

```js
const i = require('../decorators/core/injectable.decorator')
const o = require('../decorators/core/optional.decorator')
index_1.Injectable = i.Injectable;
index_1.Optional = o.Optional;
```

to `node_modules/@nestjs/common/pipes`

I've got this:

![image](https://user-images.githubusercontent.com/13461315/236645385-d87c7af3-069e-40e7-ab61-cd5ddb9d6f47.png)

**Comment by micalevisk** [comment]
@MansurAliKoroglu are you still facing this error? can you please share a repository with your code

**Comment by MansurAliKoroglu** [comment]
I'm still having the same error. Created this repository by following exact same steps as described in issue description.

https://github.com/MansurAliKoroglu/nest-bug-test

**Comment by MansurAliKoroglu** [comment]
Maybe reopen this issue?

**Comment by micalevisk** [comment]
as you can see in your stack trace:

![image](https://github.com/nestjs/nest/assets/13461315/ab17ad4e-68d0-429b-864f-e3721bdb3161)

looks like we need to perform the same fix at `packages/common/pipes/parse-enum.pipe.ts` as well as I did in PR https://github.com/nestjs/nest/pull/11604/files

@MansurAliKoroglu would you like to open a PR to address that? should be a easy fix

**Comment by sejori** [comment]
Hi all, I am seeing the same behaviour when mocking NestJS internals for a module integration test. I have a [mock exports utility](https://github.com/sejori/nestjs-graphql-sample/blob/testing-rework/test/test.utils.ts) that mocks all module exports as `jest.fn()`. 

The purpose of the test is to achieve maximum code coverage and ensure modules are configured correctly without depending on Nest's `Test.createTestingModule` (which we do use for E2E tests).

Test file can be found here: https://github.com/sejori/nestjs-graphql-sample/blob/testing-rework/src/app/app.module.spec.ts

```
FAIL src/app/app.module.spec.ts
  ● Test suite failed to run

    TypeError: (0 , common_1.Injectable) is not a function

      2 | import { PrismaClient } from '@prisma/client';
      3 |
    > 4 | @Injectable()
        |            ^
      5 | export class PrismaService extends PrismaClient implements OnModuleInit {
      6 |   async onModuleInit() {
      7 |     await this.$connect();

      at Object.<anonymous> (src/prisma/services/prisma.service.ts:4:[12](https://github.com/sejori/nestjs-graphql-sample/actions/runs/6468206014/job/17559754254?pr=1#step:6:13))
      at Object.<anonymous> (src/user/services/user.service.ts:5:1)
      at Object.<anonymous> (src/app/services/app.service.ts:3:1)
      at Object.<anonymous> (src/app/app.module.ts:[13](https://github.com/sejori/nestjs-graphql-sample/actions/runs/6468206014/job/17559754254?pr=1#step:6:14):1)
      at Object.<anonymous> (src/app/app.module.spec.ts:13:1)
```

**Comment by sejori** [comment]
@micalevisk @jmcdo29 I tried bumping deps to latest for `@nestjs` modules but issue still persists.

**Comment by micalevisk** [comment]
@sejori please share the steps to reproduce your still

also, try it out without using `dotenv` CLI.

**Comment by jmcdo29** [comment]
[This is probably the issue](https://github.com/sejori/nestjs-graphql-sample/blob/testing-rework/src/app/app.module.spec.ts#L16). Decorators, like `@Injectable()` are technically two fold functions, being decorator factories. Essentially, the `jest.fn()` that `Injectable` is being set should be `Injectable = jest.fn(jest.fn())`. I would __highly__ suggest not using `jest.mock` to mock the `@nestjs/` packages. 

If you don't want to use `@nestjs/testing` that's fine, you can create your controllers and services using `new AppController(new AppService())` or however you want to set this kind of stuff. I don't understand what the reason for *not* depending on that is, but hey, whatever floats your boat there.

**Comment by sejori** [comment]
Hi all, just thought I'd come back with an update. In the end I followed your advice and used `Test.createTestingModule` to test that Module providers, imports and exports are configured correctly. For the providers/resolvers/controllers themselves I simply mocked dependencies and instantiated like: `new AppController(mockAppService)`

You can see the setup here: https://github.com/sejori/nestjs-graphql-sample 🤓 

Coverage is now pretty high, ~90%. Not 100% mainly because not all decorator functions are covered in unit tests. This is to be expected as some decorators are quite hard to test. I am considering using `Reflect.getMetadata` for this, do you know of any resources that might help on this front?

Also, strangely the `createTestingModule` approach is reporting 0 functions covered for `src/app/app.module.ts` but the same approach provides 100% functions covered for other modules. Any idea why that might be?

Clone the repo and run `$ yarn test:cov` to see this for yourselves - thanks for all of your help and advice 👍

**Comment by jzeferino** [comment]
joining a bit late to the party, as of I am writing this i have the most up to date dependencies for nestjs, jest.
i have a test were i create an instance of a class i wrote. that class is annotated with @Inject and I'm facing the error described above.

`
      × Expression expected
       ╭─[/Users/cache.service.ts:3:1]
     3 │ 
     4 │ const TTL_IN_SECONDS = 300 // 5 minutes
     5 │ 
     6 │ @Injectable()
       · ─
     7 │ export class CacheService {
     8 │        private readonly client!: Redis
       ╰────
`

any suggestion?
