### ISSUE TITLE
Nest is throwing an error for an unrelated module when trying to use Inject a service into AuthGuard 

### ISSUE THREAD

**Issue by Ali559** [nestjs/nest#11634]
### Is there an existing issue for this? No

- [X] I have searched the existing issues

### Current behavior

I have an AuthGuard that basically tracks user Authorizations, I wanted to be able to hit the ProfileService and get some data from it on each request that is using the said AuthGuard 

auth.guard.ts
```Javascript
import {
  Injectable,
  CanActivate,
  ExecutionContext,
  Inject,
} from '@nestjs/common';
import { RequestContextService } from '../middlewares';
import { JwtService } from '@nestjs/jwt';
import { Request } from 'express';
import { ProfileService } from 'src/individual-profile/services';
@Injectable()
export class AuthGuard implements CanActivate {
  constructor(
    private readonly requestContextService?: RequestContextService,
    private jwtService?: JwtService,
    @Inject('ProfileService') private profileService?: ProfileService,
  ) {}
  canActivate(context: ExecutionContext): boolean {
    const request: Request = context.switchToHttp().getRequest();
    const token = request.headers?.authorization?.split(' ')[1];
    try {
      const user = this.jwtService.verify(token, {
        secret: process.env.JWT_SECRET.trim(),
        issuer: process.env.JWT_ISSUER.trim(),
      });

      if (!user || !user?._id) return false;
      this.requestContextService.setUserId(user._id);
      return true;
    } catch (error) {
      console.log(error);
      return false;
    }
  }
}
```
the ProfileService that is being injected is a provider for the IndividualProfile module which I have marked as a Global Module and I've also exported the ProfileService in it

individual-profile.module.ts
```Javascript
@Global()
@Module({
  controllers: [
    ProfileController,
  ],
  providers: [
    ProfileRepository,
    ProfileService,
  ],
  exports: [ProfileService],
})
export class IndividualProfileModule implements NestModule {
  configure(consumer: MiddlewareConsumer): any {
    consumer.apply(RequestContextMiddleware).forRoutes('*');
  }
}

```

now the error that I'm seeing is no indication of the above module, whenever I inject the ProfileService into the AuthGuard it throws the following error which has no correlation with any of the two files whatsoever

```
Error: Nest can't resolve dependencies of the LanguageRepository (wizrxConnection/LanguageModel, ?). Please make sure that the argument dependency at index [1] is available in the BadgesModule context.

Potential solutions:
- If dependency is a provider, is it part of the current BadgesModule?
- If dependency is exported from a separate @Module, is that module imported within BadgesModule?
  @Module({
    imports: [ /* the Module containing dependency */ ]
  })

    at Injector.resolveSingleParam (/Users/macbookshop/Desktop/MWizer/projects/wizr-x-server/node_modules/@nestjs/core/injector/injector.js:178:19)
    at resolveParam (/Users/macbookshop/Desktop/MWizer/projects/wizr-x-server/node_modules/@nestjs/core/injector/injector.js:116:49)
    at Array.map (<anonymous>)
    at Injector.resolveConstructorParams (/Users/macbookshop/Desktop/MWizer/projects/wizr-x-server/node_modules/@nestjs/core/injector/injector.js:131:58)
    at Injector.loadInstance (/Users/macbookshop/Desktop/MWizer/projects/wizr-x-server/node_modules/@nestjs/core/injector/injector.js:57:24)
    at Injector.loadProvider (/Users/macbookshop/Desktop/MWizer/projects/wizr-x-server/node_modules/@nestjs/core/injector/injector.js:84:20)
    at /Users/macbookshop/Desktop/MWizer/projects/wizr-x-server/node_modules/@nestjs/core/injector/instance-loader.js:47:62
    at Array.map (<anonymous>)
    at InstanceLoader.createInstancesOfProviders (/Users/macbookshop/Desktop/MWizer/projects/wizr-x-server/node_modules/@nestjs/core/injector/instance-loader.js:47:36)
    at /Users/macbookshop/Desktop/MWizer/projects/wizr-x-server/node_modules/@nestjs/core/injector/instance-loader.js:32:24
```

I've been looking everywhere and couldn't find an answer to resolve my problem.

### Minimum reproduction code

can't provide

### Expected behavior

I expected the error to be based on the `individual-profile.module.ts` file not the `badges.module.ts`, these two files are not related to each other at all, they don't have the same dependencies, the only thing they have in common is that they're both modules inside the app and that's it

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json
{
  "version": "0.0.1",
  "private": true,
  "dependencies": {
    "@nestjs/bull": "^0.6.3",
    "@nestjs/cache-manager": "^1.0.0",
    "@nestjs/common": "^9.0.0",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/jwt": "^10.0.3",
    "@nestjs/mongoose": "^9.2.1",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/schedule": "^2.2.1",
    "@nestjs/swagger": "^6.2.1",
    "bull": "^4.10.4",
    "cache-manager": "^4.0.0",
    "cache-manager-redis-store": "^3.0.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "crypto-js": "^4.1.1",
    "joi": "^17.6.0",
    "mongoose": "^6.8.0",
    "nestjs-typeorm-paginate": "^4.0.2",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "tsc-watch": "^5.0.3"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/cron": "^2.0.1",
    "@types/crypto-js": "^4.1.1",
    "@types/express": "^4.17.13",
    "@types/jest": "28.1.4",
    "@types/joi": "^17.2.3",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.1.2",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.5",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.0.0",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

18.6.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
you have those optional parameters but didn't used `@Optional()`. I guess you should update that

```
private readonly requestContextService?: RequestContextService,
private jwtService?: JwtService,
```

**Comment by Ali559** [comment]
@micalevisk first off, thanks for the response and this is my languageRepository file

```Javascript
@Injectable()
export class LanguageRepository {
  constructor(
    @InjectModel(Language.name, 'wizrx')
    private languageModel: Model<LanguageDocument>,
    private readonly queryRepository: QueryRepository<LanguageDocument>,
  ) { }

  //add pagination
  async find(
    paginationParams: PaginationParams,
  ): Promise<PaginationResponse<Language>> {
    return await this.queryRepository.findAllWithPagination(
      {},
      paginationParams,
      this.languageModel,
    );
  }
  async findByKeyword(
    paginationParams: PaginationParams,
    keyword: string,
  ): Promise<PaginationResponse<Language>> {
    return await this.queryRepository.findAllWithPagination(
      { name: { $regex: `^${keyword}`, $options: 'i' } },
      paginationParams,
      this.languageModel,
    );
  }

  async save(language: Language): Promise<Language> {
    return await this.languageModel.create(language);
  }

  async deleteById(id: string): Promise<Language> {
    return this.languageModel.findByIdAndDelete(id);
  }

  async updateById(id: string, language: Language): Promise<Language> {
    return this.languageModel.findByIdAndUpdate(id, language);
  }

  async findByIds(ids: any) {
    return await this.languageModel.find(
      { _id: { $in: ids } },
      { _id: 0, name: 1, level: 1 },
    );
  }
}

```

**Comment by Ali559** [comment]
```Javascript
import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model, Types } from 'mongoose';
import { Language, LanguageDocument } from '../models';
import {
  QueryRepository,
  PaginationParams,
  PaginationResponse,
} from '../../common';
@Injectable()
export class LanguageRepository {
  constructor(
    @InjectModel(Language.name, 'wizrx')
    private languageModel: Model<LanguageDocument>,
    private readonly queryRepository: QueryRepository<LanguageDocument>,
  ) {}

  //add pagination
  async find(
    paginationParams: PaginationParams,
  ): Promise<PaginationResponse<Language>> {
    return await this.queryRepository.findAllWithPagination(
      {},
      paginationParams,
      this.languageModel,
    );
  }
  async findByKeyword(
    paginationParams: PaginationParams,
    keyword: string,
  ): Promise<PaginationResponse<Language>> {
    return await this.queryRepository.findAllWithPagination(
      { name: { $regex: `^${keyword}`, $options: 'i' } },
      paginationParams,
      this.languageModel,
    );
  }

  async save(language: Language): Promise<Language> {
    return await this.languageModel.create(language);
  }

  async deleteById(id: string): Promise<Language> {
    return this.languageModel.findByIdAndDelete(id);
  }

  async updateById(id: Types.ObjectId, language: Language): Promise<Language> {
    return this.languageModel.findByIdAndUpdate(id, language);
  }

  async findByIds(ids: any) {
    return await this.languageModel.find(
      { _id: { $in: ids } },
      { _id: 0, name: 1, level: 1 },
    );
  }
}

```

**Comment by jmcdo29** [comment]
From the error it looks like you've added your `LanguageRepository` directly to the `providers` of the `BadgesModule`, which is probably not what you're intending to do as that will make Nest create a new instance of the `LanguageRepository` instead of re-using the one from the module where it is supposed to originate from. 

This is more of a configuration issue than it is a bug with the framework, and as such, please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

**Comment by Ali559** [comment]
the Language repository's base module is the Badges Module, I haven't imported it from a different module, also that's not my issue, my issue is why am I seeing the error when I try to inject the profileService into my AuthGuard which has nothing to do with the LanguageRepository or the badges Module

**Comment by Ali559** [comment]
your documentation is very misleading then, but thanks for the help I guess

**Comment by micalevisk** [comment]
@Ali559 the docs are maintained by the community. Feel free to improve it here: https://github.com/nestjs/docs.nestjs.com

**Comment by Ali559** [comment]
I've been trying to solve this problem for two straight weeks, when the issue is not resolved I had to come here and put it down as a bug, I've used every tool imaginable, my question was simple, why does an unrelated error happen when I make an unrelated change:
notice line 17:
<img width="1512" alt="Screenshot 2023-05-17 at 6 45 45 PM" src="https://github.com/nestjs/nest/assets/53957149/f0026f8c-3eea-4187-995e-feed760901e7">
and after the change 
<img width="1512" alt="Screenshot 2023-05-17 at 6 46 14 PM" src="https://github.com/nestjs/nest/assets/53957149/8ca73151-d8a0-4740-98b0-5307f0acc837">

**Comment by jmcdo29** [comment]
I've already explained the error, the second constructor parameter of your `LangaugeRepository` cannot be resolved because there is no injection token and Typescript does not reflect generics, so Nest sees an `undefined` token and gives this generic error. It's a limitation of Typescript and Nest shows how to mitigate it using a [custom provider](https://docs.nestjs.com/fundamentals/custom-providers).

**Comment by Ali559** [comment]
Thank you for the help and excuse my frustration

**Comment by micalevisk** [comment]
@Ali559 you can learn more about that here: https://github.com/nestjs/docs.nestjs.com/pull/2481/files
