### ISSUE TITLE
Failed to connect to websocket using wss

### ISSUE THREAD

**Issue by Tyh2001** [nestjs/nest#11681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I use socket. io to implement websocket, which can connect normally in the development environment. Both the front-end and back-end are deployed to the production environment, but the connection using wss failed.

**err message**

```shell
WebSocket connection to 'wss://xxxxx:7171/socket.io/?EIO=4&transport=websocket' failed:
连接失败 Error: websocket error
    at a5.onError (index-5d19907a.js:12:36135)
    at ws.onerror (index-5d19907a.js:12:42813)
```

<img width="622" alt="013a151162142d640d2484fcaa92851" src="https://github.com/nestjs/nest/assets/73180970/e1da869e-b4a6-4ebb-88d2-c1d8b6124601">

<img width="799" alt="d3710617d8b48ae154023f310f958ff" src="https://github.com/nestjs/nest/assets/73180970/47fc75ae-c6e2-46a5-9f6c-817434994382">

**chat.gateway.ts**

```ts
import {
  WebSocketGateway,
  SubscribeMessage,
  MessageBody,
  ConnectedSocket,
  OnGatewayConnection,
  WebSocketServer,
  OnGatewayInit,
} from '@nestjs/websockets'
import { Socket, Server } from 'socket.io'
import { ChatList } from './entity/chat.entity'
import { InjectRepository } from '@nestjs/typeorm'
import { Repository } from 'typeorm'

@WebSocketGateway(7171, {
  cors: {
    origin: ['https://xxxxx.cn', 'http://localhost:8888'],
    credentials: true,
  },
  transports: ['websocket'],
})
export class ChatGateway implements OnGatewayConnection {
  constructor(
    @InjectRepository(ChatList)
    private chatListEntity: Repository<ChatList>
  ) {}

  @WebSocketServer()
  server: Server = new Server()

  handleConnection(client: Socket) {
    client.join('room')
  }

  @SubscribeMessage('chat')
  async handleMessage(
    @ConnectedSocket() client: Socket,
    @MessageBody() payload
  ) {
    try {
      const newChat = this.chatListEntity.create(JSON.parse(payload))

      await this.chatListEntity.save(newChat)
    } catch (err) {
      console.log(err)
    }

    this.server.to('room').emit('chat', payload)
  }
}
```

**main.ts**

```ts
import { NestFactory } from '@nestjs/core'
import { AppModule } from './app.module'
import { ExpressAdapter } from '@nestjs/platform-express'
import * as express from 'express'
import * as fs from 'fs'
import * as https from 'https'
import { IoAdapter } from '@nestjs/platform-socket.io'
import { ExtendedSocketIoAdapter } from './socket'
import { corsMiddleware } from './middleware'

async function bootstrap() {
  const server = express()

  const app = await NestFactory.create(AppModule, new ExpressAdapter(server))

  app.enableCors()

  app.use(corsMiddleware)

  if (process.env.NODE_ENV === 'production') {
    const httpsOptions = {
      key: fs.readFileSync('/xxxxx/xxxx.key'),
      cert: fs.readFileSync('/xxxxx/xxxx.pem'),
    }

    const httpsServer = await https.createServer(httpsOptions, server)

    app.useWebSocketAdapter(new IoAdapter(httpsServer))

    await app.init()

    await httpsServer.listen(1216, () => {
      console.log('生产环境端口 1216 已经启动')
    })
  } else {
    await app.listen(1216, () => {
      console.log('开发环境 1216 端口已经启动')
    })
  }
}
bootstrap()
```

**Client**

```ts
const socket: Socket = io(import.meta.env.VITE_WEBSOCKET, {
  transports: ['websocket'],
})

socket.on('connect', () => {
  console.log('ok')
})
```

**Nginx**

`/www/server/nginx/conf/nginx.conf`

```shell
server {
    listen 80 ssl;

    ssl_certificate_key /xxx/xxx.key;
    ssl_certificate /xxx/xxx.pem;

    # 可选的 SSL 配置
    ssl_protocols TLSv1.2 TLSv1.3;  # 指定 SSL/TLS 协议版本
    ssl_prefer_server_ciphers on;  # 优先使7171用服务器端密码套件
    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';  # 指定密码套件
    ssl_session_timeout 1d;  # SSL 会话超时时间

    location /socket.io/ {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host;

      proxy_pass http://localhost:7171;

      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }
  }
```

### Minimum reproduction code

https://world.tianyuhao.cn

### Expected behavior

Successfully used wss link

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [X] <code>@nestjs/platform-socket.io</code>
- [X] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [X] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.4.0

### Packages versions

```json
{
  "name": "travel-world-end",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "cross-env NODE_ENV=production nest build",
    "format": "prettier --write \"src/**/*.ts\"",
    "start": "nest start",
    "start:dev": "cross-env NODE_ENV=development nest start --watch",
    "start:debug": "nest start --debug --watch",
    "main": "cross-env NODE_ENV=production node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs-modules/mailer": "^1.8.1",
    "@nestjs/common": "^9.4.0",
    "@nestjs/config": "^2.3.1",
    "@nestjs/core": "^9.4.0",
    "@nestjs/platform-express": "^9.4.0",
    "@nestjs/platform-fastify": "^9.4.2",
    "@nestjs/platform-socket.io": "^9.4.0",
    "@nestjs/platform-ws": "^9.4.0",
    "@nestjs/sequelize": "^9.0.2",
    "@nestjs/serve-static": "^3.0.1",
    "@nestjs/typeorm": "^9.0.1",
    "@nestjs/websockets": "^9.4.0",
    "config": "^3.3.9",
    "cors": "^2.8.5",
    "cross-env": "^7.0.3",
    "dotenv": "^16.0.3",
    "express": "^4.18.2",
    "ioredis": "^5.3.2",
    "multer": "1.4.5-lts.1",
    "mysql2": "^3.2.3",
    "nodemailer": "^6.9.1",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0",
    "socket.io": "^4.6.1",
    "typeorm": "^0.3.15",
    "ws": "^8.13.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.4.2",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.4.0",
    "@types/express": "^4.17.13",
    "@types/jest": "29.5.0",
    "@types/node": "18.15.11",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "29.5.0",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "29.0.5",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.2.0",
    "typescript": "^4.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

18.15.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by shenX-2021** [comment]
try changing Nginx config like:

 `location /socket.io/ {`  -->  `location /socket.io {`

`proxy_pass http://localhost:7171;`  -->  `proxy_pass http://localhost:7171/socket.io;`

**Comment by Tyh2001** [comment]
> 尝试更改 Nginx 配置，例如：
> 
> `location /socket.io/ {` --> `location /socket.io {`
> 
> `proxy_pass http://localhost:7171;` --> `proxy_pass http://localhost:7171/socket.io;`

Not resolved

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
