### ISSUE TITLE
Double initialization protection

### ISSUE THREAD

**Issue by KKSzymanowski** [nestjs/nest#12006]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

By mistake I had `app.init()` twice in my "before each test" hooks in E2E tests and I got weird errors like duplicated GraphQL type. I think it would be useful to have something like the following in the `init()` method:

```js
async init() {
    if (this.isInitialized) {
        throw new Error('App already initialized. Did you call init() twice?');
    }
    // ...
}
```

**Comment by micalevisk** [comment]
like this?

https://github.com/nestjs/nest/blob/d8800d64632480527823472e8139e56f6acc715d/packages/core/nest-application-context.ts#L232-L235

**Comment by KKSzymanowski** [comment]
This is what I'm seeing in `node_modules/@nestjs/core/nest-application.js`:

![image](https://github.com/nestjs/nest/assets/13980973/3a96a0f3-ca8f-4d75-bd72-66cc83dc1ebc)

Am I using an outdated version?

This is for sure the code that was executed twice:
```
      Trace: here
          at GraphQLFactory.mergeWithSchema (/Users/jakub.szymanowski/Code/backoffice/backend/node_modules/@nestjs/graphql/dist/graphql.factory.js:25:17)
          at ApolloDriver.start (/Users/jakub.szymanowski/Code/backoffice/backend/node_modules/@nestjs/apollo/dist/drivers/apollo.driver.js:19:51)
          at GraphQLModule.onModuleInit (/Users/jakub.szymanowski/Code/backoffice/backend/node_modules/@nestjs/graphql/dist/graphql.module.js:105:36)
          at processTicksAndRejections (node:internal/process/task_queues:95:5)
          at callModuleInitHook (/Users/jakub.szymanowski/Code/backoffice/backend/node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:9)
          at Proxy.callInitHook (/Users/jakub.szymanowski/Code/backoffice/backend/node_modules/@nestjs/core/nest-application-context.js:224:13)
HERE ->   at Proxy.init (/Users/jakub.szymanowski/Code/backoffice/backend/node_modules/@nestjs/core/nest-application.js:98:9)
          at initShared (/Users/jakub.szymanowski/Code/backoffice/backend/test/testCase.ts:193:3)
          at Object.<anonymous> (/Users/jakub.szymanowski/Code/backoffice/backend/test/auth/auth.controller.e2e-spec.ts:27:31)
```

**Comment by KKSzymanowski** [comment]
From what I see in the lock file I'm using 9.3.12:

![image](https://github.com/nestjs/nest/assets/13980973/5550e915-924f-4beb-bd67-3090c8f641f1)

**Comment by KKSzymanowski** [comment]
The code you linked to is there in `nest-application-context` but not in `nest-application`. I'm not really familiar with the framework internals, what's the difference between the two?

**Comment by micalevisk** [comment]
yeah
https://github.com/nestjs/nest/blob/d8800d64632480527823472e8139e56f6acc715d/packages/core/nest-application.ts#L179-L183

we can probably do the same as here:

https://github.com/nestjs/nest/blob/d8800d64632480527823472e8139e56f6acc715d/packages/microservices/nest-microservice.ts#L154-L162

not sure why that code isn't there already

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by KKSzymanowski** [comment]
Sure

**Comment by KKSzymanowski** [comment]
@kamilmysliwiec https://github.com/nestjs/nest/pull/12009

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/12009
