### ISSUE TITLE
gRPC example CANCELLED: Call cancelled

### ISSUE THREAD

**Issue by busyhe** [nestjs/nest#12095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

browser：http://localhost:3001/hero/1
nestjs service: ERROR [ExceptionsHandler] 1 CANCELLED: Call cancelled

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/sample/04-grpc

### Steps to reproduce

npm start:dev

### Expected behavior

will success

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
^10.0.0
```

### Node.js version

v19.5.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by busyhe** [comment]
[Nest] 5812  - 07/21/2023, 5:12:00 PM   ERROR [ExceptionsHandler] 1 CANCELLED: Call cancelled
Error: 1 CANCELLED: Call cancelled
    at callErrorFromStatus (/Users/busyhe/workspace/demo/grpc-demo/grpc-service/node_modules/.pnpm/@grpc+grpc-js@1.8.18/node_modules/@grpc/grpc-js/src/call.ts:81:17)
    at Object.onReceiveStatus (/Users/busyhe/workspace/demo/grpc-demo/grpc-service/node_modules/.pnpm/@grpc+grpc-js@1.8.18/node_modules/@grpc/grpc-js/src/client.ts:356:55)
    at Object.onReceiveStatus (/Users/busyhe/workspace/demo/grpc-demo/grpc-service/node_modules/.pnpm/@grpc+grpc-js@1.8.18/node_modules/@grpc/grpc-js/src/client-interceptors.ts:454:34)
    at Object.onReceiveStatus (/Users/busyhe/workspace/demo/grpc-demo/grpc-service/node_modules/.pnpm/@grpc+grpc-js@1.8.18/node_modules/@grpc/grpc-js/src/client-interceptors.ts:416:48)
    at /Users/busyhe/workspace/demo/grpc-demo/grpc-service/node_modules/.pnpm/@grpc+grpc-js@1.8.18/node_modules/@grpc/grpc-js/src/resolving-call.ts:111:24
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/Users/busyhe/workspace/demo/grpc-demo/grpc-service/node_modules/.pnpm/@grpc+grpc-js@1.8.18/node_modules/@grpc/grpc-js/src/client.ts:326:42)
    at ServiceClientImpl.<anonymous> (/Users/busyhe/workspace/demo/grpc-demo/grpc-service/node_modules/.pnpm/@grpc+grpc-js@1.8.18/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
    at Observable._subscribe (/Users/busyhe/workspace/demo/grpc-demo/grpc-service/node_modules/.pnpm/@nestjs+microservices@10.1.0_@grpc+grpc-js@1.8.18_@nestjs+common@10.0.0_@nestjs+core@10.0.0_r_og2jpsxz4pswj2za4meraavjl4/node_modules/@nestjs/microservices/client/client-grpc.js:194:48)
    at Observable._trySubscribe (/Users/busyhe/workspace/demo/grpc-demo/grpc-service/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:244:19)
    at /Users/busyhe/workspace/demo/grpc-demo/grpc-service/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:234:18
    at Object.errorContext (/Users/busyhe/workspace/demo/grpc-demo/grpc-service/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)
    at Observable.subscribe (/Users/busyhe/workspace/demo/grpc-demo/grpc-service/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:220:5)
    at /Users/busyhe/workspace/demo/grpc-demo/grpc-service/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/lastValueFrom.ts:59:12
    at new Promise (<anonymous>)
    at lastValueFrom (/Users/busyhe/workspace/demo/grpc-demo/grpc-service/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/lastValueFrom.ts:56:10)

**Comment by karam1ashqar** [comment]
Happens with me, not all the time but it happens, it's bad

**Comment by busyhe** [comment]
When i restart computer，It's OK
