### ISSUE TITLE
ERROR [WsExceptionsHandler] Cannot read properties of undefined (reading 'logIn')

### ISSUE THREAD

**Issue by kjxbyz** [nestjs/nest#12195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```
[Nest] 68855  - 08/04/2023, 8:13:16 PM   ERROR [WsExceptionsHandler] Cannot read properties of undefined (reading 'logIn')
TypeError: Cannot read properties of undefined (reading 'logIn')
    at authenticate (/Users/ying/workspace/kjxbyz/nestjs-test/node_modules/passport/lib/middleware/authenticate.js:96:21)
    at /Users/ying/workspace/kjxbyz/nestjs-test/node_modules/@nestjs/passport/dist/auth.guard.js:88:3
    at new Promise (<anonymous>)
    at /Users/ying/workspace/kjxbyz/nestjs-test/node_modules/@nestjs/passport/dist/auth.guard.js:80:83
    at WsAuthGuard.canActivate (/Users/ying/workspace/kjxbyz/nestjs-test/node_modules/@nestjs/passport/dist/auth.guard.js:44:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

### Minimum reproduction code

https://github.com/kjxbyz/nestjs-test

### Steps to reproduce

1. Clone the project
2. Request this address `http://127.0.0.1:3001/api/auth/login` to get the token. 
header:
 `__version__`:1
body:
```json
{
     "username": "john",
     "password": "changeme"
}
```
3. Access `ws://127.0.0.1:3001/ws` in postman, and send the message body as follows
```json
{
     "event" : "events",
     "data" : "test"
}
```

### Expected behavior

It is normal to enable the authentication function for ws

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
{
  "name": "nestjs-test",
  "private": true,
  "version": "1.0.0",
  "description": "Nest TypeScript starter repository",
  "license": "MIT",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "generate-schema": "nest start --entryFile generate-schema",
    "start": "nest start",
    "start:dev": "nest build --webpack --webpackPath webpack-hmr.config.cjs --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@apollo/server": "^4.9.0",
    "@nestjs/apollo": "^12.0.7",
    "@nestjs/axios": "^3.0.0",
    "@nestjs/common": "^10.1.3",
    "@nestjs/core": "^10.1.3",
    "@nestjs/graphql": "^12.0.8",
    "@nestjs/jwt": "^10.1.0",
    "@nestjs/passport": "^10.0.0",
    "@nestjs/platform-express": "^10.1.3",
    "@nestjs/platform-ws": "^10.1.3",
    "@nestjs/swagger": "^7.1.6",
    "@nestjs/terminus": "^10.0.1",
    "@nestjs/websockets": "^10.1.3",
    "axios": "^1.4.0",
    "body-parser": "^1.20.2",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "cookie-parser": "^1.4.6",
    "express-session": "^1.17.3",
    "graphql": "^16.7.1",
    "graphql-query-complexity": "^0.12.0",
    "graphql-subscriptions": "^2.0.0",
    "helmet": "^7.0.0",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.1",
    "passport-local": "^1.0.0",
    "redis": "^4.6.7",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1",
    "ws": "^8.13.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.1.11",
    "@nestjs/schematics": "^10.0.1",
    "@nestjs/testing": "^10.1.3",
    "@swc/cli": "^0.1.62",
    "@swc/core": "^1.3.74",
    "@swc/jest": "^0.2.27",
    "@types/body-parser": "^1.19.2",
    "@types/cookie-parser": "^1.4.3",
    "@types/express": "^4.17.17",
    "@types/express-session": "^1.17.7",
    "@types/jest": "^29.5.3",
    "@types/node": "^20.4.7",
    "@types/passport-jwt": "^3.0.9",
    "@types/passport-local": "^1.0.35",
    "@types/supertest": "^2.0.12",
    "@types/webpack-env": "^1.18.1",
    "@types/webpack-node-externals": "^3.0.0",
    "@types/ws": "^8.5.5",
    "@typescript-eslint/eslint-plugin": "^6.2.1",
    "@typescript-eslint/parser": "^6.2.1",
    "eslint": "^8.46.0",
    "eslint-config-prettier": "^8.10.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.6.2",
    "prettier": "^3.0.1",
    "run-script-webpack-plugin": "^0.2.0",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.1",
    "ts-loader": "^9.4.4",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.6",
    "webpack": "^5.88.2",
    "webpack-node-externals": "^3.0.0"
  },
  "engines": {
    "node": ">= 16"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": [
        "@swc/jest"
      ]
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
