### ISSUE TITLE
10.2.1 getMetaKeyByInstanceWrapper Cannot read properties of undefined (reading 'metatype')

### ISSUE THREAD

**Issue by tidytrax** [nestjs/nest#12275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello, i hape updated from 10.1.3(works fine on it) to 10.2.1
I have read the changelog, I didn`t see any break change, or deprecated functions, I could miss it.

NodeJS 20.5.1
NestJS 10.2.1
Typescript 5.1.6

But when i get my app to start I`m getting the bellow error

`TypeError: Cannot read properties of undefined (reading 'metatype')\n    at Function.getMetaKeyByInstanceWrapper`

2023-08-24T02:02:42.128Z info:     Starting Nest application...
2023-08-24T02:02:42.178Z error:    Cannot read properties of undefined (reading 'metatype')

`{"context":"ExceptionHandler","level":"error","message":"Cannot read properties of undefined (reading 'metatype')","stack":["TypeError: Cannot read properties of undefined (reading 'metatype')\n    at Function.getMetaKeyByInstanceWrapper (C:\\Users\\renato\\server\\workspaces\\decea\\local\\decea-via-backend\\node_modules\\.pnpm\\@nestjs+core@10.2.1_@nestjs+common@10.2.1_@nestjs+platform-express@10.2.1_reflect-metadata@0.1.13_rxjs@7.8.1\\node_modules\\@nestjs\\core\\discovery\\discoverable-meta-host-collection.js:79:25)\n    at Function.inspectInstanceWrapper (C:\\Users\\renato\\server\\workspaces\\decea\\local\\decea-via-backend\\node_modules\\.pnpm\\@nestjs+core@10.2.1_@nestjs+common@10.2.1_@nestjs+platform-express@10.2.1_reflect-metadata@0.1.13_rxjs@7.8.1\\node_modules\\@nestjs\\core\\discovery\\discoverable-meta-host-collection.js:53:56)\n    at Function.inspectProvider (C:\\Users\\renato\\server\\workspaces\\decea\\local\\decea-via-backend\\node_modules\\.pnpm\\@nestjs+core@10.2.1_@nestjs+common@10.2.1_@nestjs+platform-express@10.2.1_reflect-metadata@0.1.13_rxjs@7.8.1\\node_modules\\@nestjs\\core\\discovery\\discoverable-meta-host-collection.js:21:21)\n    at NestContainer.addProvider (C:\\Users\\renato\\server\\workspaces\\decea\\local\\decea-via-backend\\node_modules\\.pnpm\\@nestjs+core@10.2.1_@nestjs+common@10.2.1_@nestjs+platform-express@10.2.1_reflect-metadata@0.1.13_rxjs@7.8.1\\node_modules\\@nestjs\\core\\injector\\container.js:153:76)\n    at DependenciesScanner.insertProvider (C:\\Users\\renato\\server\\workspaces\\decea\\local\\decea-via-backend\\node_modules\\.pnpm\\@nestjs+core@10.2.1_@nestjs+common@10.2.1_@nestjs+platform-express@10.2.1_reflect-metadata@0.1.13_rxjs@7.8.1\\node_modules\\@nestjs\\core\\scanner.js:241:35)\n    at C:\\Users\\renato\\server\\workspaces\\decea\\local\\decea-via-backend\\node_modules\\.pnpm\\@nestjs+core@10.2.1_@nestjs+common@10.2.1_@nestjs+platform-express@10.2.1_reflect-metadata@0.1.13_rxjs@7.8.1\\node_modules\\@nestjs\\core\\scanner.js:119:18\n    at Array.forEach (<anonymous>)\n    at DependenciesScanner.reflectProviders (C:\\Users\\renato\\server\\workspaces\\decea\\local\\decea-via-backend\\node_modules\\.pnpm\\@nestjs+core@10.2.1_@nestjs+common@10.2.1_@nestjs+platform-express@10.2.1_reflect-metadata@0.1.13_rxjs@7.8.1\\node_modules\\@nestjs\\core\\scanner.js:118:19)\n    at DependenciesScanner.scanModulesForDependencies (C:\\Users\\renato\\server\\workspaces\\decea\\local\\decea-via-backend\\node_modules\\.pnpm\\@nestjs+core@10.2.1_@nestjs+common@10.2.1_@nestjs+platform-express@10.2.1_reflect-metadata@0.1.13_rxjs@7.8.1\\node_modules\\@nestjs\\core\\scanner.js:99:18)\n    at DependenciesScanner.scan (C:\\Users\\renato\\server\\workspaces\\decea\\local\\decea-via-backend\\node_modules\\.pnpm\\@nestjs+core@10.2.1_@nestjs+common@10.2.1_@nestjs+platform-express@10.2.1_reflect-metadata@0.1.13_rxjs@7.8.1\\node_modules\\@nestjs\\core\\scanner.js:31:9)\n    at C:\\Users\\renato\\server\\workspaces\\decea\\local\\decea-via-backend\\node_modules\\.pnpm\\@nestjs+core@10.2.1_@nestjs+common@10.2.1_@nestjs+platform-express@10.2.1_reflect-metadata@0.1.13_rxjs@7.8.1\\node_modules\\@nestjs\\core\\nest-factory.js:107:17\n    at Function.asyncRun (C:\\Users\\renato\\server\\workspaces\\decea\\local\\decea-via-backend\\node_modules\\.pnpm\\@nestjs+core@10.2.1_@nestjs+common@10.2.1_@nestjs+platform-express@10.2.1_reflect-metadata@0.1.13_rxjs@7.8.1\\node_modules\\@nestjs\\core\\errors\\exceptions-zone.js:22:13)\n    at NestFactoryStatic.initialize (C:\\Users\\renato\\server\\workspaces\\decea\\local\\decea-via-backend\\node_modules\\.pnpm\\@nestjs+core@10.2.1_@nestjs+common@10.2.1_@nestjs+platform-express@10.2.1_reflect-metadata@0.1.13_rxjs@7.8.1\\node_modules\\@nestjs\\core\\nest-factory.js:106:13)\n    at NestFactoryStatic.create (C:\\Users\\renato\\server\\workspaces\\decea\\local\\decea-via-backend\\node_modules\\.pnpm\\@nestjs+core@10.2.1_@nestjs+common@10.2.1_@nestjs+platform-express@10.2.1_reflect-metadata@0.1.13_rxjs@7.8.1\\node_modules\\@nestjs\\core\\nest-factory.js:42:9)\n    at init (C:\\Users\\renato\\server\\workspaces\\decea\\local\\decea-via-backend\\src\\main.ts:56:15)"],"timestamp":"2023-08-24T02:02:42.178Z"}
`

### Minimum reproduction code

https://docs.nestjs.com/

### Expected behavior

the application to start.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.2.1

### Packages versions

```
{
  "name": "api",
  "main": "dist/src/main",
  "scripts": {
    "build": "nest build",
    "start": "nest start",
    "dev": "nest start --watch"
  },
  "dependencies": {
    "@mikro-orm/cli": "^v6.0.0-dev.90",
    "@mikro-orm/core": "^v6.0.0-dev.90",
    "@mikro-orm/migrations": "^v6.0.0-dev.90",
    "@mikro-orm/nestjs": "^5.2.1",
    "@mikro-orm/postgresql": "^v6.0.0-dev.90",
    "@mikro-orm/seeder": "^v6.0.0-dev.90",
    "@nestjs-modules/mailer": "^1.9.1",
    "@nestjs/axios": "^3.0.0",
    "@nestjs/cache-manager": "^2.1.0",
    "@nestjs/common": "^10.2.1",
    "@nestjs/config": "^3.0.0",
    "@nestjs/core": "^10.2.1",
    "@nestjs/jwt": "^10.1.0",
    "@nestjs/passport": "^10.0.0",
    "@nestjs/platform-express": "^10.2.1",
    "@nestjs/schedule": "^3.0.2",
    "@nestjs/swagger": "^7.1.8",
    "bcrypt": "^5.1.1",
    "cache-manager": "^5.2.3",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "compression": "^1.7.4",
    "cookie-parser": "^1.4.6",
    "dayjs": "^1.11.9",
    "exceljs": "^4.3.0",
    "express-basic-auth": "^1.2.1",
    "handlebars": "^4.7.8",
    "jsonwebtoken": "^9.0.1",
    "minio": "^7.1.1",
    "nest-winston": "^1.9.3",
    "nodemailer": "^6.9.4",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.1",
    "passport-local": "^1.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1",
    "swagger-ui-express": "^5.0.0",
    "winston": "^3.10.0",
    "winston-daily-rotate-file": "^4.7.1"
  },
  "devDependencies": {
    "@faker-js/faker": "^8.0.2",
    "@mikro-orm/entity-generator": "v6.0.0-dev.90",
    "@nestjs/cli": "^10.1.14",
    "@nestjs/schematics": "^10.0.2",
    "@nestjs/testing": "^10.2.1",
    "@types/bcrypt": "^5.0.0",
    "@types/cache-manager": "^4.0.2",
    "@types/compression": "^1.7.2",
    "@types/cookie-parser": "^1.4.3",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.3",
    "@types/jsonwebtoken": "^9.0.2",
    "@types/node": "^20.5.0",
    "@types/nodemailer": "^6.4.9",
    "@types/passport-jwt": "^3.0.9",
    "@types/passport-local": "^1.0.35",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^6.4.0",
    "@typescript-eslint/parser": "^6.4.0",
    "dotenv-cli": "^7.3.0",
    "eslint": "^8.47.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "generate-changelog": "^1.8.0",
    "git-commit-msg-linter": "^5.0.4",
    "husky": "^8.0.3",
    "jest": "29.6.2",
    "lint-staged": "^14.0.0",
    "prettier": "^3.0.2",
    "release-it": "^16.1.5",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "29.1.1",
    "ts-loader": "^9.4.4",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typedoc": "^0.24.8",
    "typescript": "^5.1.6"
  }
  }
}
```

### Node.js version

20.5.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by tidytrax** [comment]
Hello thanks for the answer. 
I could fix by removing a service provider from a module, I still look into, i dont know if is some circular injection.

thank you
