### ISSUE TITLE
During testing nest doesn't resolve constructor dependencies

### ISSUE THREAD

**Issue by dormammun** [nestjs/nest#12336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have a controller with one dependency as `AuthenticationService`. This controller works when I run `nest start`. But in the **test mode**, it's failure to resolve dependency.

```ts
import {ok, deepEqual} from 'node:assert/strict'
import {beforeEach, afterEach, describe, it, mock} from 'node:test'

import {Test} from '@nestjs/testing'

import {AuthenticationController} from '@/authentication/authentication.controller/authentication.controller'
import {AuthenticationService} from '@/authentication/services/authentication/authentication.service'

const FAKE_TOKEN = 'FAKE_TOKEN'

describe('AuthenticationController', () => {
  let controller: AuthenticationController
  let authenticationService: AuthenticationService

  beforeEach(async () => {
    const module = await Test.createTestingModule({
      controllers: [AuthenticationController],
      providers: [AuthenticationService],
    }).compile()

    controller = module.get<AuthenticationController>(AuthenticationController)
    authenticationService = module.get<AuthenticationService>(
      AuthenticationService
    )
  })

  afterEach(() => {
    mock.restoreAll()
  })

  describe('register', () => {
    it('returns token', async () => {
      authenticationService.register = mock.fn(() =>
        Promise.resolve({accessToken: FAKE_TOKEN})
      )

      const credentials = {email: 'elliot@e-corp.com', password: 'weiofj'}

      const result = await controller.register(credentials)

      deepEqual((authenticationService.register as any).mock.calls[0].result, {
        accessToken: FAKE_TOKEN,
      })
      deepEqual(result, {accessToken: FAKE_TOKEN})
    })
  })
})
```

```ts
import {Body, Controller, HttpCode, HttpStatus, Post,} from '@nestjs/common'

import {RegisterCredentialsDto} from '@/authentication/dtos/register-credentials.dto'
import {AuthenticationService} from '@/authentication/services/authentication/authentication.service'

@Controller('authentication')
export class AuthenticationController {
  constructor(private readonly authenticationService: AuthenticationService) {}

  @HttpCode(HttpStatus.CREATED)
  @Post('register')
  async register(@Body() credentials: RegisterCredentialsDto) {
    const {accessToken} = await this.authenticationService.register(credentials)

    return {
      accessToken,
    }
  }

  @Post('login')
  login() {
    return {
      accessToken: 'token',
    }
  }
}
```

```ts
import {Injectable} from '@nestjs/common'

import {RegisterCredentialsDto} from '@/authentication/dtos/register-credentials.dto'

@Injectable()
export class AuthenticationService {
  async register(
    credentials: RegisterCredentialsDto
  ): Promise<{accessToken: string}> {
    return {accessToken: 'token'}
  }
}
```

Case 1: Run `node --test --loader tsx ./src/**/*/authentication.controller.spec.ts`.

```sh
  TypeError: "Cannot read properties of undefined (reading 'register')"
      at AuthenticationController.register (/Users/dormammun/Code/Millennium-Falcon/application/services/passport/src/authentication/authentication.controller/authentication.controller.ts:28:60)
      at TestContext.<anonymous> (/Users/dormammun/Code/Millennium-Falcon/application/services/passport/src/authentication/authentication.controller/authentication.controller.spec.ts:39:39)
```

Case 2:  I add a dependency via `@ Inject(AuthenticationService)` - test works
```ts
import {
  Body,
  Controller,
  forwardRef,
  HttpCode,
  HttpStatus,
  Inject,
  Post,
} from '@nestjs/common'

import {RegisterCredentialsDto} from '@/authentication/dtos/register-credentials.dto'
import {AuthenticationService} from '@/authentication/services/authentication/authentication.service'

@Controller('authentication')
export class AuthenticationController {
  constructor(@Inject(AuthenticationService) private readonly authenticationService: AuthenticationService) {}

  @HttpCode(HttpStatus.CREATED)
  @Post('register')
  async register(@Body() credentials: RegisterCredentialsDto) {
    const {accessToken} = await this.authenticationService.register(credentials)

    return {
      accessToken,
    }
  }

  @Post('login')
  login() {
    return {
      accessToken: 'token',
    }
  }
}
```

---
**Investigation**

 I debugged and found that when a constructor dependency without `@Inject(AuthenticationService)`  `selfParams` doesn't return `Object` in 

Case 1: Without `@Inject(AuthenticationService)`

```ts
    reflectConstructorParams(type) {
        const paramtypes = [
            ...(Reflect.getMetadata(constants_1.PARAMTYPES_METADATA, type) || []),
        ];
        const selfParams = this.reflectSelfParams(type);
        selfParams.forEach(({ index, param }) => (paramtypes[index] = param));
        return paramtypes;
    }
```

<img width="692" alt="image" src="https://github.com/nestjs/nest/assets/100094658/6dd7dfe0-5fd1-4b48-a348-3231f9cff05e">

<img width="662" alt="image" src="https://github.com/nestjs/nest/assets/100094658/18e9c863-56f3-4692-ac5e-e2c3a7b67e2c">

Case 2:With `@Inject(AuthenticationService)` 

<img width="677" alt="image" src="https://github.com/nestjs/nest/assets/100094658/c3d88770-ffba-4a25-88c1-da0e87ae2445">

### Minimum reproduction code

https://github.com/Looport/Millennium-Falcon/pull/2/files

### Steps to reproduce

`node --test --loader tsx ./src/**/*/authentication.controller.spec.ts`

### Expected behavior

Controller gets constructor dependencies

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

tsx

### NestJS version

10.2.4

### Packages versions

```json
{
  "private": true,
  "name": "@looport/passport",
  "author": "Vitalii Khotei <khoteiv.dev@gmail.com>",
  "scripts": {
    "===dev===": "===",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "===prod===": "===",
    "build": "nest build",
    "start:prod": "node dist/main",
    "===test===": "===",
    "lint": "eslint \"src/**/*.ts\"",
    "type-check": "tsc --noEmit",
    "test": "node --test --loader tsx ./src/**/*/authentication.controller.spec.ts",
    "test:watch": "node --test --watch --loader tsx ./src/**/**/*.spec.ts",
    "test:debug": "node --test --watch --inspect-brk --loader tsx ./src/**/**/*.spec.ts",
    "test:e2e": "node --test --loader tsx ./src/**/**/*.e2e-spec.ts",
    "test:e2e:watch": "node --test --watch --loader tsx ./src/**/**/*.e2e-spec.ts",
    "test:e2e:debug": "node --test --inspect-brk --watch --loader tsx ./src/**/**/*.e2e-spec.ts",
    "===utils===": "===",
    "format": "pnpm lint --fix"
  },
  "dependencies": {
    "@nestjs/common": "^10.2.4",
    "@nestjs/core": "^10.2.4",
    "@nestjs/platform-fastify": "^10.2.4",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@looport/eslint-config": "workspace:*",
    "@nestjs/cli": "^10.1.17",
    "@nestjs/testing": "^10.2.4",
    "@types/node": "20.5.1",
    "@types/supertest": "^2.0.12",
    "eslint": "^8.42.0",
    "prettier": "^2.8.8",
    "supertest": "^6.3.3",
    "tsx": "^3.12.8",
    "typescript": "^5.1.3"
  },
  "eslintConfig": {
    "extends": [
      "@looport/eslint-config/src/base"
    ],
    "env": {
      "node": true
    }
  },
  "prettier": "@looport/eslint-config/src/.prettierrc.js"
}
```

### Node.js version

v19.9.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

I see you've added a repository, but there's a great deal of configuration already around it. Can you show us with a _minimal_ setup?

**Comment by jmcdo29** [comment]
<details>

<summary>Your reproduction also throws a loader error surrounding ESM.</summary>

```
node --test --loader tsx ./src/**/*/authentication.controller.spec.ts
(node:90713) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
~/application/services/passport/src/authentication/authentication.controller/authentication.controller.spec.ts:1
import {deepEqual} =  require('node:assert/strict')
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1153:20)
    at Module._compile (node:internal/modules/cjs/loader:1197:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async CustomizedModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async loadESM (node:internal/process/esm_loader:40:7)

Node.js v20.5.1
✖ ~/application/services/passport/src/authentication/authentication.controller/authentication.controller.spec.ts (133.929671ms)
  'test failed'

ℹ tests 1
ℹ suites 0
ℹ pass 0
ℹ fail 1
ℹ cancelled 0
ℹ skipped 0
ℹ todo 0
ℹ duration_ms 141.333867

✖ failing tests:

✖ ~/application/services/passport/src/authentication/authentication.controller/authentication.controller.spec.ts (133.929671ms)
  'test failed'
```

</details>

**Comment by dormammun** [comment]
@jmcdo29 Could you check node version? Because loader doesn't work on node@20

**Comment by jmcdo29** [comment]
Then you should set your engines properly ;)

Also, the error changes when you compile with tsc and run the test directly through node, so this is likely an error from what the tsx loader is doing, not something in Nest's control

**Comment by dormammun** [comment]
@jmcdo29 If you compile with `tsc` it will not resolve absolute `paths` like `@/authentication/authentication.controller/authentication.controller` ;)

tsconfig.json
```    json
"paths": {
      "@/*": ["./src/*"]
    },
```

**Comment by dormammun** [comment]
You are right. I build with `nest build` and then run `node --test  ./dist/**/*/authentication.controller.spec.js` and it works.
Thank you :)
