### ISSUE TITLE
ObjecType decorator on nested resolver not working in testing side

### ISSUE THREAD

**Issue by mrasoahaingo** [nestjs/nest#12352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have a error when I launch test on my graphql module:

```
Cannot determine a GraphQL output type for the "width". Make sure your class is decorated with an appropriate decorator.
```

This is the full stack trace:
```
      at OutputTypeFactory.create (node_modules/@nestjs/graphql/dist/schema-builder/factories/output-type.factory.js:19:23)
      at node_modules/@nestjs/graphql/dist/schema-builder/factories/object-type-definition.factory.js:80:53
          at Array.forEach (<anonymous>)
      at node_modules/@nestjs/graphql/dist/schema-builder/factories/object-type-definition.factory.js:79:24
      at resolveObjMapThunk (node_modules/graphql/type/definition.js:504:40)
      at defineFieldMap (node_modules/graphql/type/definition.js:766:20)
      at GraphQLObjectType._fields (node_modules/graphql/type/definition.js:691:26)
      at GraphQLObjectType.getFields (node_modules/graphql/type/definition.js:710:27)
      at collectReferencedTypes (node_modules/graphql/type/schema.js:387:51)
      at new GraphQLSchema (node_modules/graphql/type/schema.js:174:9)
```

This are the main lib versions:
```
nest@9.5.0
node@18.15.0
jest@29.3.1
graphql@16.8.0
```

This is the query I want to build:

```
{
  helloQueries {
    world {
      width
      height
    }
  }
}
```

### GraphQL module
```
@Module({
  imports: [
    LoggerModule,
    GraphQLServerModule.forRootAsync<YogaDriverConfig>({
      imports: [HelloModule],
      driver: YogaDriver,
      useClass: GraphQLService,
    }),
  ],
  providers: [ConfigService],
})
export class GraphQLModule {}
```

### Hello Module
```
@Module({
  providers: [HelloResolver, WorldResolver],
})
export class HelloModule {}
````

### Hello namespace resolver
```
@Resolver()
export class HelloResolver {
  @Query(() => HelloQueries)
  async helloQueries() {
    return HelloQueries;
  }
}
```

### Hello query definition
```
@ObjectType()
export class HelloQueries {}
```

### World resolver on Hello Query object
```

@Resolver(() => HelloQueries)
export class WorldResolver {
  @ResolveField(() => WorldModel)
  world(): WorldModel {
    return {
      width: 'width',
      height: 'height',
    }
  }
}
```

### World object
```
@ObjectType()
export class WorldModel {
  @Field()
  width: string;
  
  @Field()
  height: string;
}
```

This is the test file

```
describe('Test', () => {
  let app: INestApplication;

  beforeEach(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [GraphQLModule],
    })
      .compile();

    app = moduleFixture.createNestApplication();

    await app.init();
  });

  afterAll(async () => {
    await app.close();
  });

  afterEach(async () => {
    jest.clearAllMocks();
  });

  describe('simple test', () => {
    it('should work', async () => {
      expect(true).toBeTruthy();
    });
  });
});
```

Note: the schema is working properly when I start the app

### Minimum reproduction code

no url

### Expected behavior

It should init the testing module and pass the test

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.5.0

### Packages versions

```json

```

### Node.js version

18.15.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
