### ISSUE TITLE
Query root type must be provided. Apollo Server Driver

### ISSUE THREAD

**Issue by saeidjoker** [nestjs/nest#12364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Following the documentation at https://docs.nestjs.com/graphql/quick-start I am unable to start a graphql server with a simple resolver, I see this error:

<img width="723" alt="Screenshot 2023-09-11 at 13 24 21" src="https://github.com/nestjs/nest/assets/20520614/60a9e0c7-1742-4473-8187-bbbb461907c3">

the above error in text format:
```bash
/Users/saeedfarahimohassel/nestjs-apollo-error/node_modules/graphql/type/validate.js:59
    throw new Error(errors.map((error) => error.message).join('\n\n'));
          ^
Error: Query root type must be provided.
    at assertValidSchema (/Users/saeedfarahimohassel/nestjs-apollo-error/node_modules/graphql/type/validate.js:59:11)
    at Function.generateSchemaDerivedData (/Users/saeedfarahimohassel/nestjs-apollo-error/node_modules/@apollo/server/src/ApolloServer.ts:726:22)
    at Object.schemaDerivedDataProvider (/Users/saeedfarahimohassel/nestjs-apollo-error/node_modules/@apollo/server/src/ApolloServer.ts:273:28)
    at new SchemaManager (/Users/saeedfarahimohassel/nestjs-apollo-error/node_modules/@apollo/server/src/utils/schemaManager.ts:79:36)
    at new ApolloServer (/Users/saeedfarahimohassel/nestjs-apollo-error/node_modules/@apollo/server/src/ApolloServer.ts:270:26)
    at ApolloDriver.registerExpress (/Users/saeedfarahimohassel/nestjs-apollo-error/node_modules/@nestjs/apollo/dist/drivers/apollo-base.driver.js:84:24)
    at ApolloDriver.registerServer (/Users/saeedfarahimohassel/nestjs-apollo-error/node_modules/@nestjs/apollo/dist/drivers/apollo.driver.js:36:24)
    at ApolloDriver.start (/Users/saeedfarahimohassel/nestjs-apollo-error/node_modules/@nestjs/apollo/dist/drivers/apollo.driver.js:21:20)
    at GraphQLModule.onModuleInit (/Users/saeedfarahimohassel/nestjs-apollo-error/node_modules/@nestjs/graphql/dist/graphql.module.js:123:36)
    at callModuleInitHook (/Users/saeedfarahimohassel/nestjs-apollo-error/node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:9)
```

### Minimum reproduction code

https://github.com/saeidjoker/nestjs-apollo-error

### Steps to reproduce

1. nest new gql
2. create a new resolver (app.resolver.ts)
3. Install graphql dependencies according to the docs: npm i @nestjs/graphql @nestjs/apollo @apollo/server graphql
4. Add the resolver to the list of providers of the app.module.ts
5. npm run start:dev

### Expected behavior

It appears that resolver is not recognised!

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/graphql

### NestJS version

10.0.0

### Packages versions

```json
{
  "name": "gql",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@apollo/server": "^4.9.3",
    "@nestjs/apollo": "^12.0.7",
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/graphql": "^12.0.8",
    "@nestjs/platform-express": "^10.0.0",
    "graphql": "^16.8.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

18.16.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

Since I thought the problem might be due to not having the latest versions, I went ahead and also checked this issue with these versions:

```json
"dependencies": {
    "@apollo/server": "^4.9.1",
    "@nestjs/apollo": "^12.0.7",
    "@nestjs/common": "^10.2.5",
    "@nestjs/core": "^10.2.5",
    "@nestjs/graphql": "^12.0.7",
    "@nestjs/platform-express": "^10.2.5",
    "graphql": "^16.8.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  },
```

But still the problem exists!

**Comment by Tony133** [comment]
Hi @saeidjoker,

If you add this `autoSchemaFile: true` in the configuration in the Graphql module you should fix the error.

```ts 
    GraphQLModule.forRoot<ApolloDriverConfig>({
      driver: ApolloDriver,
      autoSchemaFile: true
    }),
```

**Comment by saeidjoker** [comment]
Thanks works

**Comment by Ak-ko** [comment]
Be sure the order of the properties of the GraphQLModule,

 imports: [
    GraphQLModule.forRoot({
      driver: ApolloDriver,
      autoSchemaFile: join(process.cwd(), 'src/schema.gql'),
    }),
]

When you put autoSchemaFile under the driver, it works fine.
