### ISSUE TITLE
Version mismatch with @fastify/static v6.11.1 and @nestjs/platform-fastify

### ISSUE THREAD

**Issue by martinvillysson** [nestjs/nest#12392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Latest @fastify/static https://github.com/fastify/fastify-static/releases/tag/v6.11.1 causes issues with @nestjs/platform-fastify because of a version mismatch.

In index.js (fastify-static) https://github.com/fastify/fastify-static/blob/2471a4c2413f7958b0045073e70d81b1bd85b57d/index.js#L555
````
module.exports = fp(fastifyStatic, {
  fastify: '^4.23.0',
  name: '@fastify/static'
})
````

Error message:
/app/node_modules/fastify/lib/pluginUtils.js:124
    throw new FST_ERR_PLUGIN_VERSION_MISMATCH(meta.name, requiredVersion, this.version)
          ^
FastifyError [Error]: fastify-plugin: @fastify/static - expected '^4.23.0' fastify version, '4.22.2' is installed
    at Object.checkVersion (/app/node_modules/fastify/lib/pluginUtils.js:124:11)
    at Object.registerPlugin (/app/node_modules/fastify/lib/pluginUtils.js:139:16)
    at Boot.override (/app/node_modules/fastify/lib/pluginOverride.js:28:57)
    at Plugin.exec (/app/node_modules/avvio/plugin.js:79:33)
    at Boot.loadPlugin (/app/node_modules/avvio/plugin.js:272:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'FST_ERR_PLUGIN_VERSION_MISMATCH',
  statusCode: 500
}

### Minimum reproduction code

https://dontthinkthisisneeded

### Expected behavior

We should not have a version mismatch

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.2.5

### Packages versions

```json

```

### Node.js version

18.15

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by martinvillysson** [comment]
Ah I saw theres a PR already #12389. Closing
