### ISSUE TITLE
Support Fastify route constraints

### ISSUE THREAD

**Issue by Fcmam5** [nestjs/nest#12496]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I want to use Fastify's [route constraints](https://fastify.dev/docs/latest/Reference/Routes/#constraints)

```
  @RouteConstraints({
    host: 'admin.example.com',
  })
```

### Describe the solution you'd like

Add a new `RouteConstraints` decorator

### Teachability, documentation, adoption, migration strategy

NA

### What is the motivation / use case for changing the behavior?

This would cover more of Fastify's features and enriches platform-fastify APIs

**Comment by johaven** [comment]
After some testing, there is an untested case that crashes Nest when using RouteConstraints and version control when version control options are not set.

If I take the example from the doc: 
```ts
@RouteConstraints({ version: '1.2.x' })
```

After accessing any url :

```ts
~/node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.js:62
                if (this.versioningOptions.type === common_1.VersioningType.MEDIA_TYPE) {
                                           ^
TypeError: Cannot read properties of undefined (reading 'type')
    at Object.deriveConstraint (~/node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.js:62:44)
    at Constrainer.eval (eval at _buildDeriveConstraints (~/node_modules/find-my-way/lib/constrainer.js:168:34), <anonymous>:4:36)
    at Constrainer.deriveConstraints (~/node_modules/find-my-way/lib/constrainer.js:62:30)
    at Router.lookup (~/node_modules/find-my-way/index.js:526:42)
    at Server.preRouting (~/node_modules/fastify/fastify.js:905:14)
    at Server.emit (node:events:518:28)
    at parserOnIncoming (node:_http_server:1137:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
```
Might need to make sure the version is set to avoid the error.
