### ISSUE TITLE
DiscoveryService's getProviders and getControllers fail when metadata key is not applied at least once

### ISSUE THREAD

**Issue by germangorodnev** [nestjs/nest#12518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using getProvider/getControllers with `metadataKey` parameter and there is no use of this metadata, i.e. decorator is not applied to any class, -- both methods fail due to [wrappersByMetaKey being undefined](https://github.com/nestjs/nest/blob/master/packages/core/discovery/discoverable-meta-host-collection.ts#L105).

Error:
```
TypeError: Cannot read properties of undefined (reading 'get')
    at DiscoverableMetaHostCollection.getProvidersByMetaKey (/home/projects/nestjs-typescript-starter-9qt4jp/node_modules/@nestjs/core/discovery/discoverable-meta-host-collection.js:46:34)
    at DiscoveryService.getProviders (/home/projects/nestjs-typescript-starter-9qt4jp/node_modules/@nestjs/core/discovery/discovery-service.js:42:98)
    at AppTestModule.onModuleInit (/home/projects/nestjs-typescript-starter-9qt4jp/dist/main.js:38:49)
    at callModuleInitHook (/home/projects/nestjs-typescript-starter-9qt4jp/node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:35)
    at async NestApplication.callInitHook (/home/projects/nestjs-typescript-starter-9qt4jp/node_modules/@nestjs/core/nest-application-context.js:223:13)
    at async NestApplication.init (/home/projects/nestjs-typescript-starter-9qt4jp/node_modules/@nestjs/core/nest-application.js:100:9)
    at async bootstrap (/home/projects/nestjs-typescript-starter-9qt4jp/dist/main.js:55:5)
```

Not sure if this is intended, as they're supposed to behave like filters and could just return an empty array when there are no suitable providers/controllers.

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-discovery-service-issue?file=src%2Fmain.ts

### Steps to reproduce

1. `npm i`
2. `npm run start`
3. See error in the terminal

Then bring back `@DiscoverDecorator` on controller and provider - it will work.

### Expected behavior

These methods could return `[]` instead.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.2.0+

### Packages versions

```json

```

### Node.js version

18.18.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/12519
