### ISSUE TITLE
TypeError: at Reflect.getMetadata

### ISSUE THREAD

**Issue by proger-coder** [nestjs/nest#12906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i try to run
`npm run test:e2e`
I get in terminal:
```
> infocenter@0.0.1 test:e2e
> cross-env NODE_ENV=development jest --config src/test/jest-e2e.json

  [Nest] 14300  - 11.12.2023, 00:35:10     LOG [NestFactory] Starting Nest application...
[Nest] 14300  - 11.12.2023, 00:35:10   ERROR [ExceptionHandler]
TypeError:
  at Reflect.getMetadata (G:\AyratDokumenty\CODING\infocenter\node_modules\reflect-metadata\Reflect.js:354:23)
at DependenciesScanner.isInjectable (G:\AyratDokumenty\CODING\infocenter\node_modules\@nestjs\core\scanner.js:391:26)
at DependenciesScanner.insertModule (G:\AyratDokumenty\CODING\infocenter\node_modules\@nestjs\core\scanner.js:89:18)
at DependenciesScanner.insertOrOverrideModule (G:\AyratDokumenty\CODING\infocenter\node_modules\@nestjs\core\scanner.js:301:21)
at DependenciesScanner.scanForModules (G:\AyratDokumenty\CODING\infocenter\node_modules\@nestjs\core\scanner.js:37:85)
at DependenciesScanner.scan (G:\AyratDokumenty\CODING\infocenter\node_modules\@nestjs\core\scanner.js:27:20)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at G:\AyratDokumenty\CODING\infocenter\node_modules\@nestjs\core\nest-factory.js:107:17
at Function.asyncRun (G:\AyratDokumenty\CODING\infocenter\node_modules\@nestjs\core\errors\exceptions-zone.js:22:13)
at NestFactoryStatic.initialize (G:\AyratDokumenty\CODING\infocenter\node_modules\@nestjs\core\nest-factory.js:106:13)
at NestFactoryStatic.create (G:\AyratDokumenty\CODING\infocenter\node_modules\@nestjs\core\nest-factory.js:42:9)
at start (G:\AyratDokumenty\CODING\infocenter\src\main.ts:16:15)
●  process.exit called with "1"

  14 |
  15 | async function start() {
  > 16 |   const app = await NestFactory.create(AppModule);
  |               ^
    17 |   const configService = app.get(ConfigService);
    18 |   const loggerService = app.get(WinstonLoggerService);
    19 |   const authService = app.get(AuthService);

    at DEFAULT_TEARDOWN (../../node_modules/@nestjs/core/errors/exceptions-zone.js:6:40)
    at Function.asyncRun (../../node_modules/@nestjs/core/errors/exceptions-zone.js:29:13)
    at NestFactoryStatic.initialize (../../node_modules/@nestjs/core/nest-factory.js:106:13)
    at NestFactoryStatic.create (../../node_modules/@nestjs/core/nest-factory.js:42:9)
    at start (../main.ts:16:15)

    RUNS  src/test/app.e2e-spec.ts

```
===
here're files for e2e. 
**jest-e2e.json:**
```
{
  "moduleFileExtensions": ["js", "json", "ts"],
  "rootDir": ".",
  "testEnvironment": "node",
  "testRegex": ".e2e-spec.ts$",
  "transform": {
    "^.+\\.(t|j)s$": "ts-jest"
  }
}
```
---

**app.e2e-spec.ts:**
```
// import 'reflect-metadata';
import { Test, TestingModule } from '@nestjs/testing';
import { INestApplication } from '@nestjs/common';
import * as request from 'supertest';
import { AppModule } from '../app.module';

describe('AppController (e2e)', () => {
  let app: INestApplication;

  beforeEach(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
  });

  it('/ (GET)', () => {
    return request(app.getHttpServer())
      .get('/')
      .expect(200)
      .expect('Hello World!');
  });
});
```
---
string for e2e in package-json:
    "test:e2e": "cross-env NODE_ENV=development jest --config src/test/jest-e2e.json"

### Minimum reproduction code

unfortunately, i cannot define, which set of code can reproduse this issue

### Expected behavior

i expect to see tests working.

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

3.1.1 - 10.2.5 (see package.json)

### Packages versions

```json
{
  "name": "infocenter",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \\\"src/**/*.ts\\\" \\\"src/test/**/*.ts\\\"",
    "start": "nest start",
    "start:dev": "cross-env NODE_ENV=development nest start --watch",
    "start:prod": "cross-env NODE_ENV=production node dist/src/main",
    "prisma:studio:dev": "dotenv -e .env.development -- npx prisma studio",
    "pstudev": "dotenv -e .env.development -- npx prisma studio",
    "prisma:migrate:dev": "dotenv -e .env.development -- prisma migrate dev",
    "pmigdev": "dotenv -e .env.development -- prisma migrate dev",
    "prisma:migrate:prod": "dotenv -e .env.production -- prisma migrate deploy",
    "prisma:seed:dev": "dotenv -e .env.development -- ts-node prisma/seeds/index.ts",
    "pseedev": "dotenv -e .env.development -- ts-node prisma/seeds/index.ts",
    "prisma:seed:prod": "dotenv -e .env.production -- ts-node prisma/seeds/index.ts",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "cross-env NODE_ENV=development jest --config src/test/jest-e2e.json"
  },
  "prisma": {
    "seed": "ts-node prisma/seeds/index.ts"
  },
  "dependencies": {
    "@casl/ability": "^6.5.0",
    "@casl/prisma": "^1.4.1",
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/jwt": "^10.1.1",
    "@nestjs/platform-express": "^10.0.0",
    "@nestjs/swagger": "^7.1.11",
    "class-validator": "^0.14.0",
    "cross-env": "^7.0.3",
    "dotenv": "^16.3.1",
    "dotenv-cli": "^7.3.0",
    "nodemailer": "^6.9.5",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1",
    "winston": "^3.10.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/config": "^3.1.1",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/serve-static": "^4.0.0",
    "@nestjs/testing": "^10.0.0",
    "@prisma/client": "^5.3.0",
    "@types/bcrypt": "^5.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.6.1",
    "@types/nodemailer": "^6.4.10",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.59.11",
    "@typescript-eslint/parser": "^5.59.11",
    "bcrypt": "^5.1.1",
    "class-transformer": "^0.5.1",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^29.5.0",
    "nestjs-prisma": "^0.22.0",
    "prettier": "^2.8.8",
    "prisma": "^5.3.0",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.2.2"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

19.0.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

### Other

i use WebStorm installed on Windows 10. Also i have **_wsl2_** for Windows enabled

**Comment by micalevisk** [comment]
> i cannot define, which set of code can reproduse this issue

and how we could fix something that we can't even reproduce to see if it was fixed :thinking: 

Closing this until someone share a repro or more info.

**Comment by martincode515** [comment]
Could be related to https://github.com/typestack/class-transformer/issues/1584#issuecomment-1665609939

Had similar issue, I saw the issue above, tinkered downgrading Typescript to less than 5, still had an issue. What I realised was it was only throwing this error during my unit test where I directly import a file that uses class-transformer.

To fix the .spec file all I had to do was ```import 'reflect-metadata';``` in the imports of the .spec file to make this shim available.

**Comment by mach-kernel** [comment]
I too am running into this problem (sorry for lack of repo, hope my example is enough -- I just inherited this):

Simple use case:

###### swagger.ts
```ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';

const printSwagger = async () => {
  const app = await NestFactory.create(AppModule);

  // Set up Swagger docs
  const swaggerConfig = new DocumentBuilder()
    .setTitle('foo API')
    .setDescription('It talks to everything! For the user!')
    .setVersion('0.1')
    .build();

  const swaggerDocument = SwaggerModule.createDocument(app, swaggerConfig);

  console.log(swaggerDocument);
}

printSwagger();
```

Invoking via:

```
npx ts-node -r tsconfig-paths/register src/swagger.ts
```

Produces stack:

```
TypeError
    at Reflect.getMetadata (/Users/dstancu/Workspace/view-frontend/backend/node_modules/reflect-metadata/Reflect.js:367:23)
    at DependenciesScanner.isInjectable (/Users/dstancu/Workspace/view-frontend/backend/node_modules/@nestjs/core/scanner.js:391:26)
    at DependenciesScanner.insertModule (/Users/dstancu/Workspace/view-frontend/backend/node_modules/@nestjs/core/scanner.js:89:18)
    at DependenciesScanner.insertOrOverrideModule (/Users/dstancu/Workspace/view-frontend/backend/node_modules/@nestjs/core/scanner.js:301:21)
    at DependenciesScanner.scanForModules (/Users/dstancu/Workspace/view-frontend/backend/node_modules/@nestjs/core/scanner.js:37:85)
    at DependenciesScanner.scan (/Users/dstancu/Workspace/view-frontend/backend/node_modules/@nestjs/core/scanner.js:27:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/dstancu/Workspace/view-frontend/backend/node_modules/@nestjs/core/nest-factory.js:107:17
    at async Function.asyncRun (/Users/dstancu/Workspace/view-frontend/backend/node_modules/@nestjs/core/errors/exceptions-zone.js:22:13)
    at async NestFactoryStatic.initialize (/Users/dstancu/Workspace/view-frontend/backend/node_modules/@nestjs/core/nest-factory.js:106:13)
```

Regular application works fine, so I decided to log out of `DependenciesScanner`:
```
2024-02-02 11:15:12 [info] - Starting Nest application...

isInjectable {
  module: [class InternalCoreModule],
  providers: [
    {
      provide: [class ExternalContextCreator],
      useFactory: [Function: useFactory]
    },
    {
      provide: [class ModulesContainer extends Map],
      useFactory: [Function: useFactory]
    },
    {
      provide: [class HttpAdapterHost],
      useFactory: [Function: useFactory]
    },
    {
      provide: [class LazyModuleLoader],
      useFactory: [Function: lazyModuleLoaderFactory]
    },
    { provide: [Function], useFactory: [Function: useFactory] }
  ],
  exports: [
    [class ExternalContextCreator],
    [class ModulesContainer extends Map],
    [class HttpAdapterHost],
    [class LazyModuleLoader],
    [class SerializedGraph] { INTERNAL_PROVIDERS: [Array] }
  ]
}
isInjectable undefined
isInjectable [class AppModule]
```

Hmm! No idea what could be `undefined` or the impact, but I superstitiously tested this change:

```diff
--- scanner.ts	2024-02-02 11:18:14
+++ newscanner.ts	2024-02-02 11:18:35
@@ -723,6 +723,7 @@
    * @returns `true` if `metatype` is annotated with the `@Injectable()` decorator.
    */
   private isInjectable(metatype: Type<any>): boolean {
+    if (!!!metatype) return false;
     return !!Reflect.getMetadata(INJECTABLE_WATERMARK, metatype);
   }
 
@@ -731,6 +732,7 @@
    * @returns `true` if `metatype` is annotated with the `@Controller()` decorator.
    */
   private isController(metatype: Type<any>): boolean {
+    if (!!!metatype) return false;
     return !!Reflect.getMetadata(CONTROLLER_WATERMARK, metatype);
   }
 
@@ -739,6 +741,7 @@
    * @returns `true` if `metatype` is annotated with the `@Catch()` decorator.
    */
   private isExceptionFilter(metatype: Type<any>): boolean {
+    if (!!!metatype) return false;
     return !!Reflect.getMetadata(CATCH_WATERMARK, metatype);
   }
 ```

And then a good error message follows:
```
2024-02-02 11:19:19 [error] - Nest cannot create the module instance. Often, this is because of a circular dependency between modules. Use forwardRef() to avoid it.

(Read more: https://docs.nestjs.com/fundamentals/circular-dependency)
Scope []
```

I wasn't able to identify a circular dependency, instead I broke out a `makeApp()` function from the `bootstrap()` boilerplate in `main.ts` as so. This app only has one module (tiny), but also replaces the Nest logger to use Winston [as per these instructions](https://www.npmjs.com/package/nest-winston#replacing-the-nest-logger):

```ts
const printSwagger = async () => {
  const app = await makeApp();

  // Set up Swagger docs
  const swaggerConfig = new DocumentBuilder()
    .setTitle('foo API')
    .setDescription('It talks to everything! For the user!')
    .setVersion('0.1')
    .build();

  const swaggerDocument = SwaggerModule.createDocument(app, swaggerConfig);

  console.log(swaggerDocument);
}
```

Doing all the Winston setup in `swagger.ts` also yields a working result. I do not understand why this is the case. I will try to assemble a repo for your team to reproduce, though, I hope this helps in the meantime!
