### ISSUE TITLE
After upgrading from 9.4.3 to 10.3.0 I get "TypeError: Cannot read properties of undefined (reading 'values')" at startup

### ISSUE THREAD

**Issue by horrendo** [nestjs/nest#12957]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

9.4.3 -> 10.3.0

### Describe the regression

Attempting to start the app fails with this:

```
$ ts-node -r tsconfig-paths/register src/main.ts
[Nest] 48172  - 21/12/2023, 7:45:01 pm     LOG [main] Running unsullied app on Node.js v20.10.0.
[Nest] 48172  - 21/12/2023, 7:45:01 pm     LOG [MasterHost] sqlite database found
[Nest] 48172  - 21/12/2023, 7:45:01 pm     LOG [MasterHost] Opening database ./master-host.db
[Nest] 48172  - 21/12/2023, 7:45:01 pm     LOG [NestFactory] Starting Nest application... +15ms
[Nest] 48172  - 21/12/2023, 7:45:01 pm     LOG [InstanceLoader] TemplateModule dependencies initialized +55ms
[Nest] 48172  - 21/12/2023, 7:45:01 pm     LOG [InstanceLoader] AppEventModule dependencies initialized +1ms
[Nest] 48172  - 21/12/2023, 7:45:01 pm     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 48172  - 21/12/2023, 7:45:01 pm     LOG [InstanceLoader] ConfigModule dependencies initialized +3ms
[Nest] 48172  - 21/12/2023, 7:45:01 pm     LOG [InstanceLoader] RedacterModule dependencies initialized +0ms
[Nest] 48172  - 21/12/2023, 7:45:01 pm   ERROR [ExceptionHandler] Cannot read properties of undefined (reading 'values')
TypeError: Cannot read properties of undefined (reading 'values')
    at /Users/stbaldwin/git/unsullied/node_modules/@nestjs-plus/discovery/src/discovery.service.ts:68:50
    at arrayMap (/Users/stbaldwin/git/unsullied/node_modules/lodash/lodash.js:653:23)
    at map (/Users/stbaldwin/git/unsullied/node_modules/lodash/lodash.js:9622:14)
    at Function.flatMap (/Users/stbaldwin/git/unsullied/node_modules/lodash/lodash.js:9325:26)
    at new DiscoveryService (/Users/stbaldwin/git/unsullied/node_modules/@nestjs-plus/discovery/src/discovery.service.ts:67:7)
    at Injector.instantiateClass (/Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/injector.js:365:19)
    at callback (/Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/injector.js:65:45)
    at async Injector.resolveConstructorParams (/Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/injector.js:144:24)
    at async Injector.loadInstance (/Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/injector.js:70:13)
    at async Injector.loadProvider (/Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/injector.js:97:9)
error Command failed with exit code 1.
```
I'm assuming the problem is with our code, but not sure where to start. Here's some versions of various bits. Let me know if you need more info:

```
[1 ~/git/unsullied] grep nestjs package.json
        "@nestjs-plus/discovery": "^2.0.1",
        "@nestjs/common": "^10.3.0",
        "@nestjs/core": "^10.3.0",
        "@nestjs/platform-express": "^10.3.0",
        "@nestjs/cli": "10.2.1",
        "@nestjs/testing": "^10.3.0",
[1 ~/git/unsullied] grep typescript package.json
        "typescript-cacheable": "^3.0.2",
        "@typescript-eslint/eslint-plugin": "<=5.59.9",
        "@typescript-eslint/parser": "<=5.59.9",
        "typescript": "5.3.3",
[1 ~/git/unsullied] node --version
v20.10.0
```

### Input code

```ts

```

### Expected behavior

I'd like for the application to start - just like it did in 9.4.3

**Comment by micalevisk** [comment]
please share the output of `npx nest info`

**Comment by horrendo** [comment]
```
[1 ~/git/unsullied] yarn nest info
yarn run v1.22.21
$ /Users/stbaldwin/git/unsullied/node_modules/.bin/nest info

 _   _             _      ___  _____  _____  _     _____
| \ | |           | |    |_  |/  ___|/  __ \| |   |_   _|
|  \| |  ___  ___ | |_     | |\ `--. | /  \/| |     | |
| . ` | / _ \/ __|| __|    | | `--. \| |    | |     | |
| |\  ||  __/\__ \| |_ /\__/ //\__/ /| \__/\| |_____| |_
\_| \_/ \___||___/ \__|\____/ \____/  \____/\_____/\___/


[System Information]
OS Version     : macOS Unknown
NodeJS Version : v20.10.0
YARN Version    : 1.22.21

[Nest CLI]
Nest CLI Version : 10.2.1

[Nest Platform Information]
platform-express version : 10.3.0
testing version          : 10.3.0
common version           : 10.3.0
core version             : 10.3.0
cli version              : 10.2.1
 version                 : 2.0.2
✨  Done in 0.45s.
```

**Comment by horrendo** [comment]
OS is MacOS 14.2.1 in case it matters.

**Comment by micalevisk** [comment]
please report this to `@nestjs-plus/discovery`

that's nothing to do on our side unless you can share a reproduction.

**Comment by horrendo** [comment]
It turns out the package name has changed from `@nestjs-plus/discovery` to `@golevelup/nestjs-discovery`. Once I removed the old package and installed the new one, everything is ok.
