### ISSUE TITLE
circular dependecy error 

### ISSUE THREAD

**Issue by iKK001** [nestjs/nest#13252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am working with nestJS inside my nodeJs project.

Moreover, I am using additional node-packages, such as  [fireorm](https://fireorm.js.org/#/), [firebase-admin](https://github.com/firebase/firebase-admin-node) and many more...

Everything worked - until the moment where I updated to the newest @nestjs/common package inside my `package.json` file!

Now I keep getting a `circular dependency` error !

And I suspect it is in combination with the  [fireorm](https://fireorm.js.org/#/) library where the newest `@nestjs/common`-library interacts badly with!

Here is the exact error message:

```
.../node_modules/reflect-metadata/Reflect.js:541

var decorated = decorator(target);
                                ^
Error: Token is undefined at index: 1. This often occurs due to circular dependencies.
Ensure there are no circular dependencies in your files or barrel files. 

For more details, refer to https://trilon.io/blog/avoiding-circular-dependencies-in-nestjs.
    at /node_modules/@nestjs/common/decorators/core/inject.decorator.js:39:19
    at /node_modules/nestjs-fireorm/lib/fireorm/fireorm.service.js:12:37
    at DecorateConstructor (/node_modules/reflect-metadata/Reflect.js:541:33)
    at Reflect.decorate (/node_modules/reflect-metadata/Reflect.js:130:24)
    at __decorate (/node_modules/nestjs-fireorm/lib/fireorm/fireorm.service.js:4:92)
    at Object.<anonymous> (/node_modules/nestjs-fireorm/src/fireorm/fireorm.service.ts:8:28)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I realized that by changing the yarn.lock entry, I can make my code run successfully again.

More precisely, if I overwrite the `@nestjs/common`-paragraph inside my yarn.lock file then my projects compiles without any errror again !

Therefore I am 100% sure that the newest version of `@nestjs/common` library is the root cause of the problem !!

Here are two examples, one where it works, and one where it does not work :

This yarn.lock entry works :
```
"@nestjs/common@^10.2.10":
  version "10.3.0"
  resolved "https://registry.yarnpkg.com/@nestjs/common/-/common-10.3.0.tgz#d78f0ff2062d1d53c79c170a79c12a1548e2e598"
  integrity sha512-DGv34UHsZBxCM3H5QGE2XE/+oLJzz5+714JQjBhjD9VccFlQs3LRxo/epso4l7nJIiNlZkPyIUC8WzfU/5RTsQ==
  dependencies:
    uid "2.0.2"
    iterare "1.2.1"
    tslib "2.6.2"
```

This yarn.lock entry will cause the error:
```
"@nestjs/common@^10.3.3":
  version "10.3.3"
  resolved "https://registry.yarnpkg.com/@nestjs/common/-/common-10.3.3.tgz#ba20f756dbed62f5fe29737c42384ad41156c9e9"
  integrity sha512-LAkTe8/CF0uNWM0ecuDwUNTHCi1lVSITmmR4FQ6Ftz1E7ujQCnJ5pMRzd8JRN14vdBkxZZ8VbVF0BDUKoKNxMQ==
  dependencies:
    uid "2.0.2"
    iterare "1.2.1"
    tslib "2.6.2"
```

What is very annoying is the fact that no matter what I place inside the `package.json` files' dependencies, the error persists. I can only get a fully working compilation by mutating the yarn.lock file to the one particular old version (as shown above). 

It seems that the circular-dependency is happening at several version combinations and it might not by other version combinations. Therefore it is a tricky problem.

Do you have any idea what could cause the circular dependency of your `@nestjs/common` library ? 

### Minimum reproduction code

dfd

### Steps to reproduce

1. inside your package.json file, add the dependency
`"@nestjs/common": "^10.3.3",`

2. delete /dist folder
3. delete /node_modules folder
4. delete yarn.lock file
5. execute `yarn`
6. execute `nest build`
7. execute `nest start`

--> code compiles with above error !

### Expected behavior

A new version of `@nestjs/common` is needed in order to make my project compile without circular dependency error !

It needs to compile without error with the following `package.json` dependencies :

```
"@nestjs/common": "^10.2.10",
"@nestjs/config": "^3.1.1",
"@nestjs/core": "^10.2.10",
"@nestjs/platform-express": "^10.1.10",
"@nestjs/schedule": "^4.0.0",
"firebase-admin": "^11.11.1",
"fireorm": "^0.23.3",
"nestjs-fireorm": "^1.1.0",
```

Steps to test:

1. delete /dist folder
2. delete /node_modules folder
3. delete yarn.lock file
4. execute `yarn`
5. execute `nest build`
6. execute `nest start`
--> code should compile without error !

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

fireorm, nestjs-fireorm, firebase-admin

### NestJS version

10.3.3

### Packages versions

```json
{
  "name": "my-project",
  "version": "0.0.1",
  "description": "",
  "private": true,
  "license": "MIT",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
  },
  "engines": {
    "node": "18.x"
  },
  "dependencies": {
    "@google-cloud/firestore": "^7.1.0",
    "@nestjs/common": "^10.2.10",
    "@nestjs/config": "^3.1.1",
    "@nestjs/core": "^10.2.10",
    "@nestjs/platform-express": "^10.1.10",
    "@nestjs/schedule": "^4.0.0",
    "firebase-admin": "^11.11.1",
    "fireorm": "^0.23.3",
    "nestjs-fireorm": "^1.1.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.2.1",
    "@nestjs/schematics": "^10.0.3",
    "@nestjs/testing": "^10.2.10",
    "eslint": "^8.55.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-prettier": "^5.0.1",
    "jest": "^29.7.0",
    "jest-mock": "^29.7.0",
    "prettier": "^3.1.0",
    "ts-jest": "^29.1.1",
    "ts-loader": "^9.5.1",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "5.3.3",
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
```

### Node.js version

18.18.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

The project worked a week ago.

Now due to some changes inside `@nestjs/common` library, I lost already 2 days.

Desperate fix needed inside this library.

The combination nestjs & fireorm & firebase-admin is quite common and needs to compile again in combination !

Thank you.

**Comment by iKK001** [comment]
I found out when the circular dependency came into your version:

As from versoin 10.3.1, you introduced `"reflect-metadata": "^0.1.12",` inside your `peerDependencies`.

And this breaks my project !!!!!!!!!!!!!!!!

Can you please take it out again ?


Here the complete version packages where you can clearly see the change !


```json
10.3.0
            "_npmVersion": "8.19.4",
            "dist": {
                "integrity": "sha512-DGv34UHsZBxCM3H5QGE2XE/+oLJzz5+714JQjBhjD9VccFlQs3LRxo/epso4l7nJIiNlZkPyIUC8WzfU/5RTsQ==",
                "shasum": "d78f0ff2062d1d53c79c170a79c12a1548e2e598",
                "tarball": "https://registry.npmjs.org/@nestjs/common/-/common-10.3.0.tgz",
                "fileCount": 393,
                "unpackedSize": 426673,
                "signatures": [
                    {
                        "keyid": "SHA256:jl3bwswu80PjjokCgh0o2w5c2U4LhQAE57gj9cz1kzA",
                        "sig": "MEUCIQDrdjOUQkXeN+JXNeaxhso2MTcwm+YPUrIk3y5IXOG7egIgQQ4jkLqJZnnclbkE1XFkWkgC1FIR/cjrz9sQbucR2b0="
                    }
                ]
            },
            "_npmUser": {
                "name": "nestjscore",
                "email": "admin@kamilmysliwiec.com"
            },
            "directories": {},
            "maintainers": [
                {
                    "name": "nestjscore",
                    "email": "admin@kamilmysliwiec.com"
                }
            ],
            "_npmOperationalInternal": {
                "host": "s3://npm-registry-packages",
                "tmp": "tmp/common_10.3.0_1702888960765_0.22772730839250732"
            },
            "_hasShrinkwrap": false
        },
```


As you can see, the `reflect-metadata` came in in version 10.3.1:

```json
"10.3.1": {
            "name": "@nestjs/common",
            "version": "10.3.1",
            "description": "Nest - modern, fast, powerful node.js web framework (@common)",
            "author": {
                "name": "Kamil Mysliwiec"
            },
            "homepage": "https://nestjs.com",
            "funding": {
                "type": "opencollective",
                "url": "https://opencollective.com/nest"
            },
            "repository": {
                "type": "git",
                "url": "git+https://github.com/nestjs/nest.git",
                "directory": "packages/common"
            },
            "publishConfig": {
                "access": "public"
            },
            "license": "MIT",
            "dependencies": {
                "iterare": "1.2.1",
                "tslib": "2.6.2",
                "uid": "2.0.2"
            },
            "peerDependencies": {
                "class-transformer": "*",
                "class-validator": "*",
                "reflect-metadata": "^0.1.12",
                "rxjs": "^7.1.0"
            },
            "peerDependenciesMeta": {
                "class-validator": {
                    "optional": true
                },
                "class-transformer": {
                    "optional": true
                }
            },
            "types": "./index.d.ts",
            "gitHead": "c91e21ca169e1d61080db15dfb7816d70bece70c",
            "bugs": {
                "url": "https://github.com/nestjs/nest/issues"
            },
            "_id": "@nestjs/common@10.3.1",
            "_nodeVersion": "16.20.0",
            "_npmVersion": "8.19.4",
            "dist": {
                "integrity": "sha512-YuxeIlVemVQCuXMkNbBpNlmwZgp/Cu6dwCOjki63mhyYHEFX48GNNA4zZn5MFRjF4h7VSceABsScROuzsxs9LA==",
                "shasum": "7aa5a0ffbd0123533adc1cfee8fd184b74bc2fc1",
                "tarball": "https://registry.npmjs.org/@nestjs/common/-/common-10.3.1.tgz",
                "fileCount": 393,
                "unpackedSize": 427346,
                "signatures": [
                    {
                        "keyid": "SHA256:jl3bwswu80PjjokCgh0o2w5c2U4LhQAE57gj9cz1kzA",
                        "sig": "MEUCIQDIGxTJEjeDJB2G1I0HXCkvgIYLdtItUOwTVWRwNMC23AIgQj28Tn/cODJgtdyJr6zo9aXpvfnM+jFBwbDp7CTP/Y0="
                    }
                ]
            },
            "_npmUser": {
                "name": "nestjscore",
                "email": "admin@kamilmysliwiec.com"
            },
            "directories": {},
            "maintainers": [
                {
                    "name": "nestjscore",
                    "email": "admin@kamilmysliwiec.com"
                }
            ],
            "_npmOperationalInternal": {
                "host": "s3://npm-registry-packages",
                "tmp": "tmp/common_10.3.1_1706019996257_0.5297590788757622"
            },
            "_hasShrinkwrap": false
        **},**
```
