### ISSUE TITLE
Error cause is not logged in dev:watch mode

### ISSUE THREAD

**Issue by dmitryrn** [nestjs/nest#13267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I change tsconfig.json target to ES2022

I throw an error in onModuleInit in a service:

```
    onModuleInit() {
        try {
            this.method()
        } catch (error) {
            throw new Error('test 123', { cause: error })
        }
    }

    method() {
        throw new Error('cause 456')
    }

```

I run: `nest start --watch`

In the terminal I see that the cause is not logged:
```
[1:27:41 PM] Starting compilation in watch mode...

[1:27:41 PM] Found 0 errors. Watching for file changes.

[Nest] 465258  - 02/27/2024, 1:27:42 PM     LOG [NestFactory] Starting Nest application...
[Nest] 465258  - 02/27/2024, 1:27:42 PM     LOG [InstanceLoader] AppModule dependencies initialized +5ms
[Nest] 465258  - 02/27/2024, 1:27:42 PM     LOG [RoutesResolver] AppController {/}: +3ms
[Nest] 465258  - 02/27/2024, 1:27:42 PM     LOG [RouterExplorer] Mapped {/, GET} route +1ms

/home/user/projects/repro/src/app.controller.ts:12
            throw new Error('test 123', { cause: error })
                  ^
Error: test 123
    at AppController.onModuleInit (/home/user/projects/repro/src/app.controller.ts:12:19)
    at MapIterator.iteratee (/home/user/projects/repro/node_modules/@nestjs/core/hooks/on-module-init.hook.js:22:43)
    at MapIterator.next (/home/user/projects/repro/node_modules/iterare/src/map.ts:9:39)
    at IteratorWithOperators.next (/home/user/projects/repro/node_modules/iterare/src/iterate.ts:19:28)
    at Function.from (<anonymous>)
    at IteratorWithOperators.toArray (/home/user/projects/repro/node_modules/iterare/src/iterate.ts:227:22)
    at callOperator (/home/user/projects/repro/node_modules/@nestjs/core/hooks/on-module-init.hook.js:23:10)
    at callModuleInitHook (/home/user/projects/repro/node_modules/@nestjs/core/hooks/on-module-init.hook.js:43:23)
    at NestApplication.callInitHook (/home/user/projects/repro/node_modules/@nestjs/core/nest-application-context.js:223:50)
    at NestApplication.init (/home/user/projects/repro/node_modules/@nestjs/core/nest-application.js:100:9)
^C
```

When I run `nest build` and then `node dist/main`, I have the expected stack trace:
```
> repro@0.0.1 build
> nest build


> repro@0.0.1 start:prod
> node dist/main

[Nest] 465382  - 02/27/2024, 1:27:45 PM     LOG [NestFactory] Starting Nest application...
[Nest] 465382  - 02/27/2024, 1:27:45 PM     LOG [InstanceLoader] AppModule dependencies initialized +5ms
[Nest] 465382  - 02/27/2024, 1:27:45 PM     LOG [RoutesResolver] AppController {/}: +4ms
[Nest] 465382  - 02/27/2024, 1:27:45 PM     LOG [RouterExplorer] Mapped {/, GET} route +1ms
/home/user/projects/repro/dist/app.controller.js:25
            throw new Error('test 123', { cause: error });
                  ^

Error: test 123
    at AppController.onModuleInit (/home/user/projects/repro/dist/app.controller.js:25:19)
    at MapIterator.iteratee (/home/user/projects/repro/node_modules/@nestjs/core/hooks/on-module-init.hook.js:22:43)
    ... 6 lines matching cause stack trace ...
    at NestApplication.callInitHook (/home/user/projects/repro/node_modules/@nestjs/core/nest-application-context.js:223:50)
    at async NestApplication.init (/home/user/projects/repro/node_modules/@nestjs/core/nest-application.js:100:9) {
  [cause]: Error: cause 456
      at AppController.method (/home/user/projects/repro/dist/app.controller.js:29:15)
      at AppController.onModuleInit (/home/user/projects/repro/dist/app.controller.js:22:18)
      at MapIterator.iteratee (/home/user/projects/repro/node_modules/@nestjs/core/hooks/on-module-init.hook.js:22:43)
      at MapIterator.next (/home/user/projects/repro/node_modules/iterare/lib/map.js:13:39)
      at IteratorWithOperators.next (/home/user/projects/repro/node_modules/iterare/lib/iterate.js:21:28)
      at Function.from (<anonymous>)
      at IteratorWithOperators.toArray (/home/user/projects/repro/node_modules/iterare/lib/iterate.js:180:22)
      at callOperator (/home/user/projects/repro/node_modules/@nestjs/core/hooks/on-module-init.hook.js:23:10)
      at callModuleInitHook (/home/user/projects/repro/node_modules/@nestjs/core/hooks/on-module-init.hook.js:43:23)
      at NestApplication.callInitHook (/home/user/projects/repro/node_modules/@nestjs/core/nest-application-context.js:223:50)
}

Node.js v21.6.2
```

### Minimum reproduction code

https://github.com/dmitryrn/nestrepro

### Steps to reproduce

clone the reproduction code;
run `npm run start:dev`;
see that error's cause is not logged;
run `npm run build && npm run start:prod`;
see that error's cause is logged.

### Expected behavior

Seeing an error cause while in `nest start --watch` mode

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

^10.0.0

### Packages versions

```json
    "@nestjs/common": "^10.0.0",
    "@nestjs/config": "^3.2.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",

    "typescript": "^5.1.3"
```

### Node.js version

v21.6.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

While I was creating a reproduction repo, I realized that since you have ES2021 in your default tsconfig.json, that means you don't have to support ES2022. But still it would be nice to have error's cause to be logged.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?
