### ISSUE TITLE
dependency injection does not work.

### ISSUE THREAD

**Issue by titsex** [nestjs/nest#13354]
### Current behavior

I wanted to bring top-level await to the project, reconfigured the configuration, tried to restart the project, but alas, the dependency inversion broke down.

### Minimum reproduction code

https://github.com/titsex/cool-e-commerce

### Expected behavior

The correct inversion of dependencies.

The fact is that the service is undefined inside the controller.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

- [X] <code>reflect-metadata</code>

### NestJS version

10.3.5

### Packages versions

```json
{
    "name": "cool-e-commerce",
    "description": "cool-e-commerce",
    "version": "1.0.0",
    "type": "module",
    "author": "titsex",
    "license": "MIT",
    "scripts": {
        "fix": "eslint ./src --fix",
        "type:check": "tsc --project ./tsconfig.json",
        "start": "pnpm type:check && tsx --require dotenv/config src/main.ts",
        "dev": "pnpm type:check && tsx watch --require dotenv/config src/main.ts"
    },
    "devDependencies": {
        "@types/node": "^20.11.30",
        "@typescript-eslint/eslint-plugin": "^7.3.1",
        "@typescript-eslint/parser": "^7.3.1",
        "dotenv": "^16.4.5",
        "eslint": "^8.57.0",
        "eslint-config-prettier": "^9.1.0",
        "eslint-plugin-prettier": "^5.1.3",
        "prettier": "^3.2.5",
        "tsx": "^4.7.1",
        "typescript": "^5.4.3"
    },
    "dependencies": {
        "@nestjs/common": "^10.3.5",
        "@nestjs/core": "^10.3.5",
        "@nestjs/platform-fastify": "^10.3.5",
        "reflect-metadata": "^0.2.1",
        "rxjs": "^7.8.1"
    }
}

```

### Node.js version

21.7.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

[Nest] 13688  - 23.03.2024, 22:21:10   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'test')

Controller:
```typescript
import { ApplicationService } from './application.service'
import { Controller, Get } from '@nestjs/common'

@Controller()
export class ApplicationController {
    constructor(private readonly applicationService: ApplicationService) {}

    @Get()
    public async test() {
        return await this.applicationService.test()
    }
}
```

Service:
```typescript
import { Injectable } from '@nestjs/common'

@Injectable()
export class ApplicationService {
    constructor() {}

    public async test() {}
}
```

Module:
```typescript
import { ApplicationController } from './application.controller'
import { ApplicationService } from './application.service'
import { ConfigModule } from '@config/config.module'
import { Module } from '@nestjs/common'

@Module({
    imports: [ConfigModule],
    controllers: [ApplicationController],
    providers: [ApplicationService],
})
export class ApplicationModule {}
```

Bootstrap (main.ts):
```typescript
import { FastifyAdapter, NestFastifyApplication } from '@nestjs/platform-fastify'
import { ApplicationModule } from './application.module'
import { ConfigService } from '@config/config.service'
import { NestFactory } from '@nestjs/core'

const fastifyAdapter = new FastifyAdapter()
const application = await NestFactory.create<NestFastifyApplication>(ApplicationModule, fastifyAdapter)

const configService = application.get<ConfigService>(ConfigService)
const config = configService.get()

await application.listen(config.port)
```

tsconfig:
```json
{
    "compilerOptions": {
        "target": "ES2022",
        "module": "ES2022",
        "moduleResolution": "Node",
        "strict": true,
        "noUnusedLocals": true,
        "noFallthroughCasesInSwitch": true,
        "forceConsistentCasingInFileNames": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "skipLibCheck": true,
        "noEmit": true,
        "paths": {
            "@config/*": ["./src/config/*"],
            "@core/*": ["./src/core/*"],
        }
    },
    "include": ["./src/**/*"]
}
```

Traceback:
```bash
TypeError: Cannot read properties of undefined (reading 'test')
    at ApplicationController.test (file:///.../src/application.controller.ts:1:690)
    at ...\node_modules\.pnpm\@nestjs+core@10.3.5_@nestjs+common@10.3.5_reflect-metadata@0.2.1_rxjs@7.8.1\node_modules\@nestjs\core\router\router-execution-context.js:38:29
    at InterceptorsConsumer.intercept (...\node_modules\.pnpm\@nestjs+core@10.3.5_@nestjs+common@10.3.5_reflect-metadata@0.2.1_rxjs@7.8.1\node_modules\@nestjs\core\interceptors\interceptors-consumer.js:12:20)
    at ...\node_modules\.pnpm\@nestjs+core@10.3.5_@nestjs+common@10.3.5_reflect-metadata@0.2.1_rxjs@7.8.1\node_modules\@nestjs\core\router\router-execution-context.js:46:60
    at Object.<anonymous> (...\node_modules\.pnpm\@nestjs+core@10.3.5_@nestjs+common@10.3.5_reflect-metadata@0.2.1_rxjs@7.8.1\node_modules\@nestjs\core\router\router-proxy.js:9:23)
    at preHandlerCallback (...\node_modules\.pnpm\fastify@4.26.2\node_modules\fastify\lib\handleRequest.js:137:37)
    at validationCompleted (...\node_modules\.pnpm\fastify@4.26.2\node_modules\fastify\lib\handleRequest.js:121:5)
    at preValidationCallback (...\node_modules\.pnpm\fastify@4.26.2\node_modules\fastify\lib\handleRequest.js:98:5)
    at handler (...\node_modules\.pnpm\fastify@4.26.2\node_modules\fastify\lib\handleRequest.js:75:7)
    at handleRequest (...\node_modules\.pnpm\fastify@4.26.2\node_modules\fastify\lib\handleRequest.js:24:5)
```

**Comment by micalevisk** [comment]
everything went fine here running both `start` and `dev` npm-scripts
![image](https://github.com/nestjs/nest/assets/13461315/ac8e3207-87b4-4e93-9bb2-21cb56462c91)

please share the exact steps to reproduce your issue

**Comment by micalevisk** [comment]
I manage to get that undefined but it worked when you have `noEmit: false` in your `tsconfig.json`

**Comment by titsex** [comment]
> I manage to get that undefined but it worked when you have `noEmit: false` in your `tsconfig.json`. Not sure why tho

Indeed, noEmit: false solved my problem. Thank you!
