### ISSUE TITLE
Watch mode is broken 

### ISSUE THREAD

**Issue by ritbl** [nestjs/nest#13393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I created empty project with nest cli, run in dev mode ("yarn run start:dev").
When I make any change to code, reload fails

[2:05:08 AM] File change detected. Starting incremental compilation...

[2:05:08 AM] Found 0 errors. Watching for file changes.

node:internal/child_process:421
    throw new ErrnoException(err, 'spawn');
    ^

Error: spawn EBADF
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:761:9)
    at <my-local-path>/node_modules/tree-kill/index.js:33:18
    at buildProcessTree (/Users/am/dev/level/nest-02/node_modules/tree-kill/index.js:90:14)
    at <my-local-path>/node_modules/tree-kill/index.js:113:11
    at Array.forEach (<anonymous>)
    at ChildProcess.onClose (<my-local-path>/node_modules/tree-kill/index.js:108:31)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11) {
  errno: -9,
  code: 'EBADF',
  syscall: 'spawn'
}

Node.js v20.12.1
error Command failed with exit code 1.

### Minimum reproduction code

-

### Expected behavior

Reload should work

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.3.7

### Packages versions

```json

```

### Node.js version

20.12.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by ritbl** [comment]
Okay, I found I had pgrep installed by homebrew

```bash
$ which pgrep
/opt/homebrew/bin/pgrep
```

after removing it

```bash
 brew remove pgrep
```

Reload started to work
