### ISSUE TITLE
Throwing an exception still leads to a crash

### ISSUE THREAD

**Issue by JulienZeng** [nestjs/nest#13560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I throw an exception using a custom exception filter, the instance crashes.
Throwing BusinessException exceptions in all my services leads to a crash.

### Minimum reproduction code

https://github.com/Graduation-Design-of-Julien/Club-Admin

### Expected behavior

How can I resolve it?

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.3.0

### Packages versions

```json
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/jwt": "^10.2.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/passport": "^10.0.3",
    "@nestjs/platform-express": "^10.0.0",
    "@nestjs/typeorm": "^10.0.2",
    "bcrypt": "^5.1.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.1",
    "express-session": "^1.18.0",
    "fs": "0.0.1-security",
    "mysql2": "^3.9.7",
    "passport": "^0.7.0",
    "passport-jwt": "^4.0.1",
    "passport-local": "^1.0.0",
    "path": "^0.12.7",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1",
    "typeorm": "^0.3.20",
    "yaml": "^2.4.2"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/bcrypt": "^5.0.2",
    "@types/express": "^4.17.17",
    "@types/express-session": "^1.18.0",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/passport-jwt": "^4.0.1",
    "@types/passport-local": "^1.0.38",
    "@types/supertest": "^6.0.0",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
```

### Node.js version

18.18

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
@JulienZeng can you share the exact file where's the exception is being raised? your repro is too big. Also, we need the steps to reproduce

I'll reopen this you're ready

**Comment by JulienZeng** [comment]
> 您能否共享引发异常的确切文件？你的复制品太大了。此外，我们需要重现问题的步骤
> 
> 我会重新打开这个，你准备好了

When I use `throw new BusinessException`, 
console
```
BusinessException: 通知不存在。
    at F:\Program\ClubManagementSys\club-admin\src\system\notification\notification.service.ts:238:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

```
And then crash.

This is how i use it
```
        throw new BusinessException({
          code: BUSINESS_ERROR_CODE.NO_EXIST,
          message: '通知不存在。',
        });
```

**Comment by JulienZeng** [comment]
@micalevisk 
`base.exception.filter.ts`
```ts
// 处理统一异常
import { Request, Response } from 'express';
import {
  ArgumentsHost,
  Catch,
  ExceptionFilter,
  HttpStatus,
  ServiceUnavailableException,
} from '@nestjs/common';

@Catch()
export class AllExceptionsFilter implements ExceptionFilter {
  catch(exception: Error, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse<Response>();
    const request = ctx.getRequest<Request>();
    // 非 HTTP 标准异常处理。
    response.status(HttpStatus.SERVICE_UNAVAILABLE).json({
      statusCode: HttpStatus.SERVICE_UNAVAILABLE,
      timestamp: new Date().toISOString(),
      path: request.url,
      message: new ServiceUnavailableException().getResponse(),
    });
  }
}

```
`business.exception.ts`
```ts
// 处理业务运行中预知且主动抛出的异常
import { HttpException, HttpStatus } from '@nestjs/common';
import { BUSINESS_ERROR_CODE } from '../constants/business.error.codes.constants';

type BusinessError = {
  code: number;
  message: string;
};
export class BusinessException extends HttpException {
  constructor(err: BusinessError | string) {
    if (typeof err === 'string') {
      err = {
        code: BUSINESS_ERROR_CODE.COMMON,
        message: err,
      };
    }
    super(err, HttpStatus.OK);
  }

  static throwForbidden() {
    throw new BusinessException({
      code: BUSINESS_ERROR_CODE.ACCESS_FORBIDDEN,
      message: '无此权限！',
    });
  }
}

```
`http.exception.filter.ts`
```ts
// 处理HTTP类型的接口相关异常
import {
  ExceptionFilter,
  Catch,
  ArgumentsHost,
  HttpException,
  HttpStatus,
} from '@nestjs/common';
import { Request, Response } from 'express';
import { BusinessException } from './business.exception';

@Catch(HttpException)
export class HttpExceptionFilter implements ExceptionFilter {
  catch(exception: HttpException, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse<Response>();
    const request = ctx.getRequest<Request>();
    const status = exception.getStatus();

    // 处理业务异常
    if (exception instanceof BusinessException) {
      const error = exception.getResponse();
      response.status(HttpStatus.OK).send({
        data: null,
        status: error['code'],
        message: error['message'],
        success: false,
      });
      return;
    }

    response.status(status).json({
      statusCode: status,
      timestamp: new Date().toISOString(),
      path: request.url,
      message: exception.getResponse(),
    });
  }
}

```
`main.ts`
```ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { TransformInterceptor } from './common/interceptor/transform.interceptor';
import { ValidationPipe } from '@nestjs/common';
import { AllExceptionsFilter } from './common/exceptions/base.exception.filter';
import { HttpExceptionFilter } from './common/exceptions/http.exception.filter';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  // 全局路由前缀
  app.setGlobalPrefix('cms');
  // 统一响应体格式
  app.useGlobalInterceptors(new TransformInterceptor());
  // 自动验证请求参数
  app.useGlobalPipes(new ValidationPipe());
  // 全局异常过滤器
  app.useGlobalFilters(new AllExceptionsFilter(), new HttpExceptionFilter());

  app.enableCors();
  await app.listen(3000);
}
bootstrap();

``

**Comment by micalevisk** [comment]
I'd like to know how to reproduce the issue just like you're doing.

Share the steps like:

1. `npm i`
2. `npm run start:dev`
3. `curl foobar`

**Comment by JulienZeng** [comment]
1. `npm i`
2. `npm run start:dev`
3. Accessing an endpoint, such as...
```js
// use axios
var axios = require('axios');
var qs = require('qs');
var data = qs.stringify({
   'notificationID': 'Notification-00009' 
});
var config = {
   method: 'post',
   url: 'http://localhost:3000/cms/notification/deleteSend',
   headers: { 
      'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJVQ1MtMDAwMDEiLCJ1c2VyUm9sZSI6NiwiaWF0IjoxNzE1Mzc5MjIxLCJleHAiOjE3MTU0MDgwMjF9.2lgcdo0t8tA-IkHZ44xp5htoD7ZTUUTxeLEHfnAKp68', 
      'User-Agent': 'Apifox/1.0.0 (https://apifox.com)', 
      'Accept': '*/*', 
      'Host': 'localhost:3000', 
      'Connection': 'keep-alive', 
      'Content-Type': 'application/x-www-form-urlencoded'
   },
   data : data
};

axios(config)
.then(function (response) {
   console.log(JSON.stringify(response.data));
})
.catch(function (error) {
   console.log(error);
});
```
4. And then, get request
```
{
    "status": 0,
    "message": "success",
    "success": true
}
```
5. But nest crashes
```
[Nest] 34204  - 2024/05/11 06:14:24     LOG [NestApplication] Nest application successfully started +5ms
2
BusinessException: 通知不存在。
    at F:\Program\ClubManagementSys\club-admin\src\system\notification\notification.service.ts:238:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Comment by micalevisk** [comment]
but there's no `notification.service.ts` file in your repository

also nothing with `deleteSend`

**Comment by JulienZeng** [comment]
sorry, i am not push it before.

**Comment by micalevisk** [comment]
you missed a `return` or `await` here:

![image](https://github.com/nestjs/nest/assets/13461315/6d61ad28-25d6-48b0-80a6-d58834041919)

So your exception was uncaught. NestJS has nothing do deal with that.

**Comment by JulienZeng** [comment]
so i need to use replace `then/catch` with `async/await`?

**Comment by micalevisk** [comment]
no

you can use both

please take some time to learn JS

**Comment by JulienZeng** [comment]
ok, i will, and thank you for your help.
