### ISSUE TITLE
Cannot read properties of undefined (reading 'get') in a test of service using Configservice in constructor

### ISSUE THREAD

**Issue by petermilan** [nestjs/nest#13868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

if I try to write a test for a service, which uses ConfigService, I am getting
```
➜  workspace git:(master) ✗ node --import tsx --test --experimental-test-coverage src/tmpModule/tmpModule.service.spec.ts
✖ TmpModule (12.15932ms)
  TypeError [Error]: Cannot read properties of undefined (reading 'get')
      at TmpModule (/project/workspace/src/tmpModule/tmpModule.service.ts:9:37)
      at TestingInjector.instantiateClass (/project/workspace/node_modules/@nestjs/core/injector/injector.js:365:19)
      at callback (/project/workspace/node_modules/@nestjs/core/injector/injector.js:65:45)
      at async TestingInjector.resolveConstructorParams (/project/workspace/node_modules/@nestjs/core/injector/injector.js:144:24)
      at async TestingInjector.loadInstance (/project/workspace/node_modules/@nestjs/core/injector/injector.js:70:13)
      at async TestingInjector.loadProvider (/project/workspace/node_modules/@nestjs/core/injector/injector.js:97:9)
      at async /project/workspace/node_modules/@nestjs/core/injector/instance-loader.js:56:13
      at async Promise.all (index 3)
      at async TestingInstanceLoader.createInstancesOfProviders (/project/workspace/node_modules/@nestjs/core/injector/instance-loader.js:55:9)
      at async /project/workspace/node_modules/@nestjs/core/injector/instance-loader.js:40:13

ℹ Warning: Could not report code coverage. TypeError: Cannot read properties of undefined (reading 'line')
ℹ tests 1
ℹ suites 0
ℹ pass 0
ℹ fail 1
ℹ cancelled 0
ℹ skipped 0
ℹ todo 0
ℹ duration_ms 677.880737

✖ failing tests:

test at src/tmpModule/tmpModule.service.spec.ts:2:923
✖ TmpModule (12.15932ms)
  TypeError [Error]: Cannot read properties of undefined (reading 'get')
      at TmpModule (/project/workspace/src/tmpModule/tmpModule.service.ts:9:37)
      at TestingInjector.instantiateClass (/project/workspace/node_modules/@nestjs/core/injector/injector.js:365:19)
      at callback (/project/workspace/node_modules/@nestjs/core/injector/injector.js:65:45)
      at async TestingInjector.resolveConstructorParams (/project/workspace/node_modules/@nestjs/core/injector/injector.js:144:24)
      at async TestingInjector.loadInstance (/project/workspace/node_modules/@nestjs/core/injector/injector.js:70:13)
      at async TestingInjector.loadProvider (/project/workspace/node_modules/@nestjs/core/injector/injector.js:97:9)
      at async /project/workspace/node_modules/@nestjs/core/injector/instance-loader.js:56:13
      at async Promise.all (index 3)
      at async TestingInstanceLoader.createInstancesOfProviders (/project/workspace/node_modules/@nestjs/core/injector/instance-loader.js:55:9)
      at async /project/workspace/node_modules/@nestjs/core/injector/instance-loader.js:40:13
```

### Minimum reproduction code

https://codesandbox.io/p/devbox/polished-platform-55pcvg?file=%2Fsrc%2FtmpModule%2FtmpModule.service.spec.ts
### Steps to reproduce

- check the link to the sandbox
- run `node --import tsx --test --experimental-test-coverage src/tmpModule/tmpModule.service.spec.ts` (the command fails as well without coverage: `node --import tsx --test src/tmpModule/tmpModule.service.spec.ts`)
- mentioned error will happen

Not sure if I am doing something wrong, Ive tried to use the config as provider, tried the mocking examples from nestjs docs
But no matter what I do, `this.config` is undefined

### Expected behavior

the this.config in the test should not be undefined

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```
[System Information]
OS Version     : Linux 6.1.43
NodeJS Version : v20.9.0
YARN Version    : 1.22.19 

[Nest CLI]
Nest CLI Version : 10.4.2 

[Nest Platform Information]
platform-express version : 10.3.10
schematics version       : 10.1.3
testing version          : 10.3.10
common version           : 10.3.10
config version           : 3.2.3
core version             : 10.3.10
cli version              : 10.4.2
```

### Node.js version

v20.9.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Node "built-in TypeScript support" does not support some of the most important TS features that we rely on. You shouldn't be using it yet
