### ISSUE TITLE
TypeError: response.status is not a function | TypeError: res.hasHeader is not a function

### ISSUE THREAD

**Issue by ChronoBoot** [nestjs/nest#14168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Can not use APP_FILTER provider.

I found this when trying to implement Sentry:
https://github.com/getsentry/sentry-javascript/issues/14348

Either (with Fastify)
```json
{
  "errors": [
    {
      "message": "res.hasHeader is not a function",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "findCoordsAddress"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "TypeError: res.hasHeader is not a function",
          "    at Reply.getHeader (/node_modules/@nestjs/platform-fastify/node_modules/fastify/lib/reply.js:237:34)",
          "    at FastifyAdapter.reply (/node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.js:191:26)",
          "    at BaseExceptionFilter.handleUnknownError (/node_modules/@nestjs/core/exceptions/base-exception-filter.js:46:28)",
          "    at BaseExceptionFilter.catch (/node_modules/@nestjs/core/exceptions/base-exception-filter.js:17:25)",
          "    at ExternalExceptionsHandler.invokeCustomFilters (/node_modules/@nestjs/core/exceptions/external-exceptions-handler.js:31:32)",
          "    at ExternalExceptionsHandler.next (/node_modules/@nestjs/core/exceptions/external-exceptions-handler.js:14:29)",
          "    at Object.findCoordsAddress (/node_modules/@nestjs/core/helpers/external-proxy.js:14:42)",
          "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
        ]
      }
    }
  ],
  "data": null
}
```

Or with express :
```json
{
  "errors": [
    {
      "message": "response.status is not a function",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "findCoordsAddress"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "TypeError: response.status is not a function",
          "    at ExpressAdapter.reply (/node_modules/@nestjs/platform-express/adapters/express-adapter.js:28:22)",
          "    at BaseExceptionFilter.handleUnknownError (/node_modules/@nestjs/core/exceptions/base-exception-filter.js:46:28)",
          "    at BaseExceptionFilter.catch (/node_modules/@nestjs/core/exceptions/base-exception-filter.js:17:25)",
          "    at ExternalExceptionsHandler.invokeCustomFilters (/node_modules/@nestjs/core/exceptions/external-exceptions-handler.js:31:32)",
          "    at ExternalExceptionsHandler.next (/node_modules/@nestjs/core/exceptions/external-exceptions-handler.js:14:29)",
          "    at Object.findCoordsAddress (/node_modules/@nestjs/core/helpers/external-proxy.js:14:42)",
          "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
        ]
      }
    }
  ],
  "data": null
}
```

### Minimum reproduction code

https://github.com/ChronoBoot/minimal-reproduction-bug-nestjs-app-filter-node-v22

### Steps to reproduce

1. nest new test-project

Add any resolver that throw an error (example):
```
import { Query, Resolver } from '@nestjs/graphql';

@Resolver()
export class FindPlaceResolver {
  @Query(() => String)
  async findCoordsAddress(
  ): Promise<void> {
    throw new SyntaxError();
  }
}
```
Import it into you app.module.ts along with a base exception filter and default GraphQL setup:
```
import { ApolloDriver, ApolloDriverConfig } from '@nestjs/apollo'
import { Module } from '@nestjs/common'
import { APP_FILTER, BaseExceptionFilter } from '@nestjs/core'
import { GraphQLModule } from '@nestjs/graphql'
import { join } from 'path'
import { FindPlaceResolver } from './find-place/find-place.resolver'


@Module({
  imports: [
    GraphQLModule.forRoot<ApolloDriverConfig>({
      autoSchemaFile: join(process.cwd(), 'schema.gql'),
      driver: ApolloDriver
    })
  ],
  providers: [
    {
      provide: APP_FILTER,
      useClass: BaseExceptionFilter,
    },
    FindPlaceResolver
  ],
})
export class AppModule {}
```

Than 
`yarn start`

Call the graphql request (by default at http://localhost:3000/graphql)
```
query {
  findCoordsAddress
}
```

If you want to have the fastify version, you just have to install the following:
yarn add fastify @nestjs/platform-fastify @as-integrations/fastify

And change your main.ts with:
```
import { NestFactory } from '@nestjs/core'
import {
  FastifyAdapter,
  NestFastifyApplication,
} from '@nestjs/platform-fastify'
import 'reflect-metadata'
import { AppModule } from './app.module'

async function bootstrap() {
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter(),
  );
  await app.listen(3000);
}
bootstrap()
```

### Expected behavior

Having the actual error displayed:

```
{
  "errors": [
    {
      "message": "",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "findCoordsAddress"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "SyntaxError",
          "    at FindPlaceResolver.findCoordsAddress (/src/find-place.resolver.ts:8:11)",
          "    at /node_modules/@nestjs/core/helpers/external-context-creator.js:69:29",
          "    at InterceptorsConsumer.intercept (/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:12:20)",
          "    at target (/node_modules/@nestjs/core/helpers/external-context-creator.js:74:60)",
          "    at Object.findCoordsAddress (/node_modules/@nestjs/core/helpers/external-proxy.js:9:30)",
          "    at field.resolve (/node_modules/@apollo/server/src/utils/schemaInstrumentation.ts:82:22)",
          "    at executeField (/node_modules/graphql/execution/execute.js:492:20)",
          "    at executeFields (/node_modules/graphql/execution/execute.js:414:22)",
          "    at executeOperation (/node_modules/graphql/execution/execute.js:344:14)",
          "    at execute (/node_modules/graphql/execution/execute.js:136:20)"
        ]
      }
    }
  ],
  "data": null
}
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.4.8

### Packages versions

```json
{
  "name": "base-filter-test",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@apollo/server": "^4.11.2",
    "@as-integrations/fastify": "^2.1.1",
    "@nestjs/apollo": "^12.2.1",
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/graphql": "^12.2.1",
    "@nestjs/platform-express": "^10.0.0",
    "@nestjs/platform-fastify": "^10.4.8",
    "fastify": "^5.1.0",
    "graphql": "^16.9.0",
    "reflect-metadata": "^0.2.0",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^6.0.0",
    "@typescript-eslint/eslint-plugin": "^8.0.0",
    "@typescript-eslint/parser": "^8.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^7.0.0",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  },
  "packageManager": "yarn@1.22.22+sha1.ac34549e6aa8e7ead463a7407e1c7390f61a6610"
}

```

### Node.js version

22.1.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
