### ISSUE TITLE
[GRPC duplex stream] Issue with duplex stream, close connection after received first message

### ISSUE THREAD

**Issue by gawsoftpl** [nestjs/nest#14259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

After update my dependencies in monorepo I received issue only with duplex grpc stream. 

I want to send from client 4 messages to server.

When I send first message from client to server with grpc stream, server received first message, but client after sent first message close connection. Client not receive any response and do not send next 3 messages.

In reproduction repo (https://github.com/gawsoftpl/nestjs-grpc-duplex-stream-issue) in `appController.ts` Client after send first message fire requestStream$ complete method. I dont know why  :
```js
    requestStream$.subscribe({
      next: onNext,
      complete: onComplete,
    });
```

Client |Message 1 |-> Server (received), response sent by server to client not received
Client |Message 2 |-> Server (not received, channel closed)
Client |Message 3 |-> Server (not received, channel closed)
Client |Message 4 |-> Server (not received, channel closed)

## Test protobuffer
```protobuffer
syntax = "proto3";

package requestshistory;

service RequestsHistoryService {
  // Add new request history
  // Send requests to add group by params
  rpc Create(stream RequestCreateRequest) returns (stream RequestsCreateResponse) {};
}

message RequestCreateRequest{
    string request_id = 1;
}

message RequestsCreateResponse {
    string request_id = 1;
    bool success = 2;
}
```
# Logs with
GRPC_VERBOSITY=DEBUG
GRPC_TRACE=all

## Logs from server
```sh
pnpm start:dev
[Nest] 329536  - 12/03/2024, 9:40:39 AM     LOG [NestFactory] Starting Nest application...
[Nest] 329536  - 12/03/2024, 9:40:39 AM     LOG [InstanceLoader] AppModule dependencies initialized +7ms
D 2024-12-03T08:40:39.768Z | v1.12.3 329536 | server | (1) Server constructed
D 2024-12-03T08:40:39.769Z | v1.12.3 329536 | server | (1) bindAsync port=0.0.0.0:5556
D 2024-12-03T08:40:39.770Z | v1.12.3 329536 | dns_resolver | Resolver constructed for target dns:0.0.0.0:5556
D 2024-12-03T08:40:39.771Z | v1.12.3 329536 | dns_resolver | Returning IP address for target dns:0.0.0.0:5556
D 2024-12-03T08:40:39.778Z | v1.12.3 329536 | server | (1) Attempting to bind 0.0.0.0:5556
D 2024-12-03T08:40:39.783Z | v1.12.3 329536 | server | (1) Successfully bound 0.0.0.0:5556
[Nest] 329536  - 12/03/2024, 9:40:39 AM     LOG [NestMicroservice] Nest microservice successfully started +92ms
(node:329536) DeprecationWarning: Calling start() is no longer necessary. It can be safely omitted.
(Use `node --trace-deprecation ...` to show where the warning was created)
D 2024-12-03T08:40:45.905Z | v1.12.3 329536 | server | (1) Connection established by client 127.0.0.1:58338
D 2024-12-03T08:40:45.910Z | v1.12.3 329536 | server | (1) Received call to method /requestshistory.RequestsHistoryService/Create at address null
D 2024-12-03T08:40:45.911Z | v1.12.3 329536 | server_call | Request to /requestshistory.RequestsHistoryService/Create received headers {"grpc-accept-encoding":["identity,deflate,gzip"],"accept-encoding":["identity"],"user-agent":["grpc-node-js/1.12.3"],"content-type":["application/grpc"],"te":["trailers"]}
D 2024-12-03T08:40:45.911Z | v1.12.3 329536 | server_call | Request to /requestshistory.RequestsHistoryService/Create start called
D 2024-12-03T08:40:45.912Z | v1.12.3 329536 | server_call | Request to /requestshistory.RequestsHistoryService/Create startRead called
D 2024-12-03T08:40:45.913Z | v1.12.3 329536 | server_call | Request to /requestshistory.RequestsHistoryService/Create received data frame of size 8
{ request_id: '1' }
D 2024-12-03T08:40:45.916Z | v1.12.3 329536 | server_call | Request to /requestshistory.RequestsHistoryService/Create sent data frame of size 10
D 2024-12-03T08:40:45.917Z | v1.12.3 329536 | server_call | Request to /requestshistory.RequestsHistoryService/Create startRead called
D 2024-12-03T08:40:45.918Z | v1.12.3 329536 | server_call | Request to method /requestshistory.RequestsHistoryService/Create ended with status code: OK details: OK
D 2024-12-03T08:40:45.919Z | v1.12.3 329536 | server_call | Request to /requestshistory.RequestsHistoryService/Create received data frame of size 8
D 2024-12-03T08:40:45.919Z | v1.12.3 329536 | server_call | Request to /requestshistory.RequestsHistoryService/Create startRead called
D 2024-12-03T08:40:45.919Z | v1.12.3 329536 | server_call | Request to /requestshistory.RequestsHistoryService/Create received data frame of size 8
D 2024-12-03T08:40:45.919Z | v1.12.3 329536 | server_call | Request to /requestshistory.RequestsHistoryService/Create startRead called
D 2024-12-03T08:40:45.919Z | v1.12.3 329536 | server_call | Request to /requestshistory.RequestsHistoryService/Create received data frame of size 8
D 2024-12-03T08:40:45.919Z | v1.12.3 329536 | server_call | Request to /requestshistory.RequestsHistoryService/Create startRead called
D 2024-12-03T08:40:45.921Z | v1.12.3 329536 | server_call | Request to method /requestshistory.RequestsHistoryService/Create stream closed with rstCode 0
```

## Logs from client
```sh
node client.js
D 2024-12-03T08:42:32.145Z | v1.12.3 332325 | resolving_load_balancer | dns:localhost:5556 IDLE -> IDLE
D 2024-12-03T08:42:32.146Z | v1.12.3 332325 | connectivity_state | (1) dns:localhost:5556 IDLE -> IDLE
D 2024-12-03T08:42:32.147Z | v1.12.3 332325 | dns_resolver | Resolver constructed for target dns:localhost:5556
D 2024-12-03T08:42:32.150Z | v1.12.3 332325 | channel | (1) dns:localhost:5556 Channel constructed with options {}
D 2024-12-03T08:42:32.151Z | v1.12.3 332325 | channel_stacktrace | (1) Channel constructed 
    at new InternalChannel (/tmp/nestjs/testproject/node_modules/.pnpm/@grpc+grpc-js@1.12.3/node_modules/@grpc/grpc-js/build/src/internal-channel.js:262:23)
    at new ChannelImplementation (/tmp/nestjs/testproject/node_modules/.pnpm/@grpc+grpc-js@1.12.3/node_modules/@grpc/grpc-js/build/src/channel.js:35:32)
    at new Client (/tmp/nestjs/testproject/node_modules/.pnpm/@grpc+grpc-js@1.12.3/node_modules/@grpc/grpc-js/build/src/client.js:66:36)
    at new ServiceClientImpl (/tmp/nestjs/testproject/node_modules/.pnpm/@grpc+grpc-js@1.12.3/node_modules/@grpc/grpc-js/build/src/make-client.js:58:5)
    at main (/tmp/nestjs/testproject/client.js:17:19)
    at Object.<anonymous> (/tmp/nestjs/testproject/client.js:53:1)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
D 2024-12-03T08:42:32.151Z | v1.12.3 332325 | channel | (1) dns:localhost:5556 createResolvingCall [0] method="/requestshistory.RequestsHistoryService/Create", deadline=Infinity
D 2024-12-03T08:42:32.151Z | v1.12.3 332325 | resolving_call | [0] Created
D 2024-12-03T08:42:32.152Z | v1.12.3 332325 | resolving_call | [0] Deadline: Infinity
D 2024-12-03T08:42:32.152Z | v1.12.3 332325 | resolving_call | [0] start called
D 2024-12-03T08:42:32.153Z | v1.12.3 332325 | dns_resolver | Looking up DNS hostname localhost
D 2024-12-03T08:42:32.154Z | v1.12.3 332325 | resolving_load_balancer | dns:localhost:5556 IDLE -> CONNECTING
D 2024-12-03T08:42:32.155Z | v1.12.3 332325 | connectivity_state | (1) dns:localhost:5556 IDLE -> CONNECTING
D 2024-12-03T08:42:32.155Z | v1.12.3 332325 | channel | (1) dns:localhost:5556 callRefTimer.ref | configSelectionQueue.length=1 pickQueue.length=0
D 2024-12-03T08:42:32.155Z | v1.12.3 332325 | resolving_call | [0] write() called with message of length 3
D 2024-12-03T08:42:32.156Z | v1.12.3 332325 | resolving_call | [0] startRead called
D 2024-12-03T08:42:32.156Z | v1.12.3 332325 | dns_resolver | Resolved addresses for target dns:localhost:5556: [127.0.0.1:5556]
D 2024-12-03T08:42:32.157Z | v1.12.3 332325 | pick_first | updateAddressList([127.0.0.1:5556])
D 2024-12-03T08:42:32.157Z | v1.12.3 332325 | pick_first | connectToAddressList([127.0.0.1:5556])
D 2024-12-03T08:42:32.158Z | v1.12.3 332325 | subchannel | (1) 127.0.0.1:5556 Subchannel constructed with options {}
D 2024-12-03T08:42:32.158Z | v1.12.3 332325 | subchannel_refcount | (1) 127.0.0.1:5556 refcount 0 -> 1
D 2024-12-03T08:42:32.158Z | v1.12.3 332325 | subchannel_refcount | (1) 127.0.0.1:5556 refcount 1 -> 2
D 2024-12-03T08:42:32.158Z | v1.12.3 332325 | pick_first | Start connecting to subchannel with address 127.0.0.1:5556
D 2024-12-03T08:42:32.158Z | v1.12.3 332325 | pick_first | IDLE -> CONNECTING
D 2024-12-03T08:42:32.158Z | v1.12.3 332325 | resolving_load_balancer | dns:localhost:5556 CONNECTING -> CONNECTING
D 2024-12-03T08:42:32.158Z | v1.12.3 332325 | connectivity_state | (1) dns:localhost:5556 CONNECTING -> CONNECTING
D 2024-12-03T08:42:32.159Z | v1.12.3 332325 | channel | (1) dns:localhost:5556 callRefTimer.unref | configSelectionQueue.length=0 pickQueue.length=0
D 2024-12-03T08:42:32.159Z | v1.12.3 332325 | subchannel | (1) 127.0.0.1:5556 IDLE -> CONNECTING
D 2024-12-03T08:42:32.161Z | v1.12.3 332325 | transport | dns:localhost:5556 creating HTTP/2 session to 127.0.0.1:5556
D 2024-12-03T08:42:32.162Z | v1.12.3 332325 | channel | (1) dns:localhost:5556 createRetryingCall [1] method="/requestshistory.RequestsHistoryService/Create"
D 2024-12-03T08:42:32.162Z | v1.12.3 332325 | resolving_call | [0] Created child [1]
D 2024-12-03T08:42:32.162Z | v1.12.3 332325 | retrying_call | [1] start called
D 2024-12-03T08:42:32.162Z | v1.12.3 332325 | channel | (1) dns:localhost:5556 createLoadBalancingCall [2] method="/requestshistory.RequestsHistoryService/Create"
D 2024-12-03T08:42:32.163Z | v1.12.3 332325 | retrying_call | [1] Created child call [2] for attempt 1
D 2024-12-03T08:42:32.163Z | v1.12.3 332325 | load_balancing_call | [2] start called
D 2024-12-03T08:42:32.163Z | v1.12.3 332325 | load_balancing_call | [2] Pick called
D 2024-12-03T08:42:32.163Z | v1.12.3 332325 | load_balancing_call | [2] Pick result: QUEUE subchannel: null status: undefined undefined
D 2024-12-03T08:42:32.163Z | v1.12.3 332325 | channel | (1) dns:localhost:5556 callRefTimer.ref | configSelectionQueue.length=0 pickQueue.length=1
D 2024-12-03T08:42:32.163Z | v1.12.3 332325 | retrying_call | [1] startRead called
D 2024-12-03T08:42:32.164Z | v1.12.3 332325 | load_balancing_call | [2] startRead called
D 2024-12-03T08:42:32.164Z | v1.12.3 332325 | retrying_call | [1] write() called with message of length 8
D 2024-12-03T08:42:32.164Z | v1.12.3 332325 | resolving_call | [0] write() called with message of length 3
D 2024-12-03T08:42:32.164Z | v1.12.3 332325 | load_balancing_call | [2] write() called with message of length 8
D 2024-12-03T08:42:32.164Z | v1.12.3 332325 | retrying_call | [1] write() called with message of length 8
D 2024-12-03T08:42:32.165Z | v1.12.3 332325 | resolving_call | [0] write() called with message of length 3
D 2024-12-03T08:42:32.165Z | v1.12.3 332325 | retrying_call | [1] write() called with message of length 8
D 2024-12-03T08:42:32.165Z | v1.12.3 332325 | resolving_call | [0] write() called with message of length 3
D 2024-12-03T08:42:32.165Z | v1.12.3 332325 | retrying_call | [1] write() called with message of length 8
D 2024-12-03T08:42:32.165Z | v1.12.3 332325 | resolving_call | [0] halfClose called
D 2024-12-03T08:42:32.165Z | v1.12.3 332325 | retrying_call | [1] halfClose called
D 2024-12-03T08:42:32.169Z | v1.12.3 332325 | subchannel | (1) 127.0.0.1:5556 CONNECTING -> READY
D 2024-12-03T08:42:32.169Z | v1.12.3 332325 | pick_first | Pick subchannel with address 127.0.0.1:5556
D 2024-12-03T08:42:32.169Z | v1.12.3 332325 | subchannel_refcount | (1) 127.0.0.1:5556 refcount 2 -> 3
D 2024-12-03T08:42:32.169Z | v1.12.3 332325 | subchannel_refcount | (1) 127.0.0.1:5556 refcount 3 -> 2
D 2024-12-03T08:42:32.169Z | v1.12.3 332325 | pick_first | CONNECTING -> READY
D 2024-12-03T08:42:32.169Z | v1.12.3 332325 | resolving_load_balancer | dns:localhost:5556 CONNECTING -> READY
D 2024-12-03T08:42:32.169Z | v1.12.3 332325 | channel | (1) dns:localhost:5556 callRefTimer.unref | configSelectionQueue.length=0 pickQueue.length=0
D 2024-12-03T08:42:32.169Z | v1.12.3 332325 | load_balancing_call | [2] Pick called
D 2024-12-03T08:42:32.169Z | v1.12.3 332325 | load_balancing_call | [2] Pick result: COMPLETE subchannel: (1) 127.0.0.1:5556 status: undefined undefined
D 2024-12-03T08:42:32.170Z | v1.12.3 332325 | connectivity_state | (1) dns:localhost:5556 CONNECTING -> READY
D 2024-12-03T08:42:32.171Z | v1.12.3 332325 | transport_flowctrl | (1) 127.0.0.1:5556 local window size: 65535 remote window size: 65535
D 2024-12-03T08:42:32.171Z | v1.12.3 332325 | transport_internals | (1) 127.0.0.1:5556 session.closed=false session.destroyed=false session.socket.destroyed=false
D 2024-12-03T08:42:32.172Z | v1.12.3 332325 | load_balancing_call | [2] Created child call [3]
D 2024-12-03T08:42:32.172Z | v1.12.3 332325 | subchannel_call | [3] write() called with message of length 8
D 2024-12-03T08:42:32.172Z | v1.12.3 332325 | subchannel_call | [3] sending data chunk of length 8
D 2024-12-03T08:42:32.173Z | v1.12.3 332325 | load_balancing_call | [2] write() called with message of length 8
D 2024-12-03T08:42:32.173Z | v1.12.3 332325 | subchannel_call | [3] write() called with message of length 8
D 2024-12-03T08:42:32.173Z | v1.12.3 332325 | subchannel_call | [3] sending data chunk of length 8
D 2024-12-03T08:42:32.173Z | v1.12.3 332325 | load_balancing_call | [2] write() called with message of length 8
D 2024-12-03T08:42:32.173Z | v1.12.3 332325 | subchannel_call | [3] write() called with message of length 8
D 2024-12-03T08:42:32.173Z | v1.12.3 332325 | subchannel_call | [3] sending data chunk of length 8
D 2024-12-03T08:42:32.173Z | v1.12.3 332325 | load_balancing_call | [2] write() called with message of length 8
D 2024-12-03T08:42:32.174Z | v1.12.3 332325 | subchannel_call | [3] write() called with message of length 8
D 2024-12-03T08:42:32.174Z | v1.12.3 332325 | subchannel_call | [3] sending data chunk of length 8
D 2024-12-03T08:42:32.174Z | v1.12.3 332325 | load_balancing_call | [2] halfClose called
D 2024-12-03T08:42:32.174Z | v1.12.3 332325 | subchannel_call | [3] end() called
D 2024-12-03T08:42:32.174Z | v1.12.3 332325 | subchannel_call | [3] calling end() on HTTP/2 stream
D 2024-12-03T08:42:32.176Z | v1.12.3 332325 | transport | (1) 127.0.0.1:5556 local settings acknowledged by remote: {"headerTableSize":4096,"enablePush":true,"initialWindowSize":65535,"maxFrameSize":16384,"maxConcurrentStreams":4294967295,"maxHeaderListSize":4294967295,"maxHeaderSize":4294967295,"enableConnectProtocol":false}
D 2024-12-03T08:42:32.177Z | v1.12.3 332325 | subchannel_call | [3] Received server headers:
                :status: 200
                content-type: application/grpc+proto
                grpc-accept-encoding: identity,deflate,gzip
                grpc-encoding: identity
                date: Tue, 03 Dec 2024 08:42:32 GMT

D 2024-12-03T08:42:32.177Z | v1.12.3 332325 | load_balancing_call | [2] Received metadata
D 2024-12-03T08:42:32.177Z | v1.12.3 332325 | retrying_call | [1] Received metadata from child [2]
D 2024-12-03T08:42:32.178Z | v1.12.3 332325 | retrying_call | [1] Committing call [2] at index 0
D 2024-12-03T08:42:32.178Z | v1.12.3 332325 | resolving_call | [0] Received metadata
D 2024-12-03T08:42:32.178Z | v1.12.3 332325 | subchannel_call | [3] receive HTTP/2 data frame of length 10
D 2024-12-03T08:42:32.179Z | v1.12.3 332325 | subchannel_call | [3] parsed message of length 10
D 2024-12-03T08:42:32.179Z | v1.12.3 332325 | subchannel_call | [3] pushing to reader message of length 10
D 2024-12-03T08:42:32.179Z | v1.12.3 332325 | load_balancing_call | [2] Received message
D 2024-12-03T08:42:32.179Z | v1.12.3 332325 | retrying_call | [1] Received message from child [2]
D 2024-12-03T08:42:32.179Z | v1.12.3 332325 | resolving_call | [0] Received message
D 2024-12-03T08:42:32.180Z | v1.12.3 332325 | resolving_call | [0] Finished filtering received message
{ request_id: '1', success: true }
D 2024-12-03T08:42:32.182Z | v1.12.3 332325 | resolving_call | [0] startRead called
D 2024-12-03T08:42:32.182Z | v1.12.3 332325 | retrying_call | [1] startRead called
D 2024-12-03T08:42:32.182Z | v1.12.3 332325 | load_balancing_call | [2] startRead called
D 2024-12-03T08:42:32.182Z | v1.12.3 332325 | subchannel_call | [3] Received server trailers:
                grpc-status: 0
                grpc-message: OK

D 2024-12-03T08:42:32.183Z | v1.12.3 332325 | subchannel_call | [3] received status code 0 from server
D 2024-12-03T08:42:32.183Z | v1.12.3 332325 | subchannel_call | [3] received status details string "OK" from server
D 2024-12-03T08:42:32.183Z | v1.12.3 332325 | subchannel_call | [3] ended with status: code=0 details="OK"
D 2024-12-03T08:42:32.183Z | v1.12.3 332325 | load_balancing_call | [2] Received status
D 2024-12-03T08:42:32.184Z | v1.12.3 332325 | load_balancing_call | [2] ended with status: code=0 details="OK" start time=2024-12-03T08:42:32.163Z
D 2024-12-03T08:42:32.184Z | v1.12.3 332325 | retrying_call | [1] Received status from child [2]
D 2024-12-03T08:42:32.184Z | v1.12.3 332325 | retrying_call | [1] state=COMMITTED handling status with progress PROCESSED from child [2] in state ACTIVE
D 2024-12-03T08:42:32.184Z | v1.12.3 332325 | retrying_call | [1] ended with status: code=0 details="OK" start time=2024-12-03T08:42:32.162Z
D 2024-12-03T08:42:32.184Z | v1.12.3 332325 | resolving_call | [0] Received status
D 2024-12-03T08:42:32.184Z | v1.12.3 332325 | resolving_call | [0] ended with status: code=0 details="OK"
Stream ended.
D 2024-12-03T08:42:32.185Z | v1.12.3 332325 | subchannel_call | [3] HTTP/2 stream closed with code 0
```

### Minimum reproduction code

https://github.com/gawsoftpl/nestjs-grpc-duplex-stream-issue

### Steps to reproduce

# Server
```sh
git clone
https://github.com/gawsoftpl/nestjs-grpc-duplex-stream-issue
pnpm install
pnpm start:dev
```

# client
```sh
node client.js
```

### Expected behavior

Should send 4 messages and received responses from server.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.4.12

### Packages versions

```json
    "@grpc/grpc-js": "^1.12.3",
    "@grpc/proto-loader": "^0.7.13",
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/microservices": "^10.4.12",
    "@nestjs/platform-express": "^10.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
```

### Node.js version

22.11.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/commit/b1b262f4c36a1b7f420bf487047513e6ee4552d6 

Fixed in 10.4.13
