### ISSUE TITLE
Issue running app with gateway.

### ISSUE THREAD

**Issue by salan1** [nestjs/nest#155]
Output from console when trying to implement a single gateway. An empty gateway does the same output, works fine without the gateway.  Am I missing something?

```[Nest] 3271   - 2017-9-15 21:33:19   [NestFactory] Starting Nest application...
[Nest] 3271   - 2017-9-15 21:33:19   [InstanceLoader] ApplicationModule dependencies initialized
[Nest] 3271   - 2017-9-15 21:33:19   [InstanceLoader] UsersModule dependencies initialized
[Nest] 3271   - 2017-9-15 21:33:19   [NestApplication] Nest application successfully started
Error: listen EACCES 0.0.0.0:80
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at Server.setupListenHandle [as _listen2] (net.js:1305:19)
    at listenInCluster (net.js:1370:12)
    at Server.listen (net.js:1466:7)
    at Server.listen.Server.attach (/Users/alan/Desktop/untitled folder 2/Cryptohaven/node_modules/socket.io/lib/index.js:237:9)
    at new Server (/Users/alan/Desktop/untitled folder 2/Cryptohaven/node_modules/socket.io/lib/index.js:56:17)
    at Server (/Users/alan/Desktop/untitled folder 2/Cryptohaven/node_modules/socket.io/lib/index.js:42:41)
    at IoAdapter.create (/Users/alan/Desktop/untitled folder 2/Cryptohaven/node_modules/@nestjs/websockets/adapters/io-adapter.js:11:16)
    at SocketServerProvider.getServerOfNamespace (/Users/alan/Desktop/untitled folder 2/Cryptohaven/node_modules/@nestjs/websockets/socket-server-provider.js:25:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nest-typescript-starter@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nest-typescript-starter@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above. ```

**Comment by kamilmysliwiec** [comment]
Hi @salan1,
I suppose you're not able to run a server using 80 port. Just change the port, e.g. let's use 8080 instead.

**Comment by salan1** [comment]
Thanks worked.
