### ISSUE TITLE
Cant create a custom exception filter (metatype is not a contructor)

### ISSUE THREAD

**Issue by jhonatanTeixeira** [nestjs/nest#1635]
i got the following exception filter:

```typescript
import { BaseExceptionFilter, HTTP_SERVER_REF } from '@nestjs/core';
import { ArgumentsHost, Catch, HttpServer, Inject } from '@nestjs/common';
import * as newrelic from 'newrelic';
import * as express from 'express';

@Catch()
export class NewRelicReportFilter extends BaseExceptionFilter {
    constructor(
        @Inject(HTTP_SERVER_REF) applicationRef: HttpServer,
    ) {
        super(applicationRef);
    }

    catch(exception: any, host: ArgumentsHost): void {
        const request: express.Request = host.switchToHttp().getRequest();
        newrelic.noticeError(exception, {...request.query, ...request.body, user: request.user});
        super.catch(exception, host);
    }
}
```

i register the exception filter like this on my app module:

```typescript
    providers: [
        {
            provide: APP_FILTER,
            useClass: NewRelicReportFilter,
        },
    ],
```

and when i boot the app i get this:
```
[Nest] 9224   - 2019-3-13 11:33:27   [ExceptionHandler] metatype is not a constructor +3ms
TypeError: metatype is not a constructor
    at Injector.instantiateClass (/home/jhonatan/projects/api-facs/node_modules/@nestjs/core/injector/injector.js:214:19)
    at callback (/home/jhonatan/projects/api-facs/node_modules/@nestjs/core/injector/injector.js:67:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 1: 0x8db900 node::Abort() [/home/jhonatan/n/bin/node]
 2: 0x96dd09  [/home/jhonatan/n/bin/node]
 3: 0xb5f33f  [/home/jhonatan/n/bin/node]
 4: 0xb5fea9 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [/home/jhonatan/n/bin/node]
 5: 0x5962825be1d 
[nodemon] app crashed - waiting for file changes before starting...
Aborted (core dumped)
```
isit a configuration problem? implementation problem? or a bug?

Thanks

**Comment by jhonatanTeixeira** [comment]
my bad the error was elsewhere

**Comment by adambarthelson** [comment]
@jhonatanTeixeira were you able to get NestJS working with New Relic.  Trying to assist a team member having issues with it.

**Comment by jgradzki** [comment]
I need add newrelic to nest.js app too, does someone got any tip?
