### ISSUE TITLE
supertest + graphql + mutation error

### ISSUE THREAD

**Issue by baronTommy** [nestjs/nest#1915]
## I'm submitting a...
Bug report

## Current behavior
supertest + graphql + mutation

text: 'Must provide query string.',

```
console.log test/app.e2e-spec.ts:37
{ Error: cannot POST /graphql (400)
    at Response.Object.<anonymous>.Response.toError (/Volumes/workspace/todo/server/node_modules/superagent/lib/node/response.js:94:15)
    at Response.Object.<anonymous>.ResponseBase._setStatusProperties (/Volumes/workspace/todo/server/node_modules/superagent/lib/response-base.js:123:16)
    at new Response (/Volumes/workspace/todo/server/node_modules/superagent/lib/node/response.js:41:8)
    at Test.Object.<anonymous>.Request._emitResponse (/Volumes/workspace/todo/server/node_modules/superagent/lib/node/index.js:752:20)
    at IncomingMessage.parser (/Volumes/workspace/todo/server/node_modules/superagent/lib/node/index.js:916:38)
    at IncomingMessage.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
    status: 400,
    text: 'Must provide query string.',
    method: 'POST',
    path: '/graphql' }
```

## Minimal reproduction of the problem with instructions
https://github.com/baron-todo-app/server/blob/master/test/app.e2e-spec.ts#L31-L38

## Environment
https://github.com/baron-todo-app/server/blob/master/package.json

mac
```
node -v
v11.10.1
```

Others:  
https://github.com/baron-todo-app/server/blob/master/test/app.e2e-spec.ts#L22-L28  
query succeeds  

&

Succeeds even with graphql editor

![2019-04-02 at 13 03](https://user-images.githubusercontent.com/16768208/55375727-34999f00-5548-11e9-89cd-aeb299c2a757.png)

**Comment by desktoping** [comment]
i think it should be `.send({ query: '{ mutation { ... }'})`

**Comment by baronTommy** [comment]
😂


```ts
  it('addTask', async () => {
    const r = await request(app.getHttpServer())
      .post('/graphql')
      // .send({ mutation: 'addTask(AddTask: {title: "hoge"}) ' });
      .send({ query: `
            {
                mutation {
                    addTask(AddTask: {title: "hoge"})
                }
            }
      ` })
    console.log(r.error);
  });
```

```
console.log test/app.e2e-spec.ts:43
    { Error: cannot POST /graphql (400)
        at Response.Object.<anonymous>.Response.toError (/Volumes/workspace/todo/server/node_modules/superagent/lib/node/response.js:94:15)
        at Response.Object.<anonymous>.ResponseBase._setStatusProperties (/Volumes/workspace/todo/server/node_modules/superagent/lib/response-base.js:123:16)
        at new Response (/Volumes/workspace/todo/server/node_modules/superagent/lib/node/response.js:41:8)
        at Test.Object.<anonymous>.Request._emitResponse (/Volumes/workspace/todo/server/node_modules/superagent/lib/node/index.js:752:20)
        at parser (/Volumes/workspace/todo/server/node_modules/superagent/lib/node/index.js:916:38)
        at IncomingMessage.res.on (/Volumes/workspace/todo/server/node_modules/superagent/lib/node/parsers/json.js:19:7)
        at IncomingMessage.emit (events.js:202:15)
        at endReadableNT (_stream_readable.js:1129:12)
        at processTicksAndRejections (internal/process/next_tick.js:76:17)
      status: 400,
      text:
       '{"errors":[{"message":"Cannot query field \\"mutation\\" on type \\"Query\\".","locations":[{"line":3,"column":17}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["Cannot query field \\"mutation\\" on type \\"Query\\".","","GraphQL request (3:17)","2:             {","3:                 mutation {","                   ^","4:                     addTask(AddTask: {title: \\"hoge\\"})","","    at Object.Field (/Volumes/workspace/todo/server/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:64:31)","    at Object.enter (/Volumes/workspace/todo/server/node_modules/graphql/language/visitor.js:334:29)","    at Object.enter (/Volumes/workspace/todo/server/node_modules/graphql/language/visitor.js:385:25)","    at visit (/Volumes/workspace/todo/server/node_modules/graphql/language/visitor.js:252:26)","    at Object.validate (/Volumes/workspace/todo/server/node_modules/graphql/validation/validate.js:63:22)","    at validate (/Volumes/workspace/todo/server/node_modules/apollo-server-core/src/requestPipeline.ts:338:22)","    at Object.<anonymous> (/Volumes/workspace/todo/server/node_modules/apollo-server-core/src/requestPipeline.ts:214:32)","    at Generator.next (<anonymous>)","    at fulfilled (/Volumes/workspace/todo/server/node_modules/apollo-server-core/dist/requestPipeline.js:4:58)","    at processTicksAndRejections (internal/process/next_tick.js:81:5)"]}}}]}\n',
      method: 'POST',
      path: '/graphql' }
```

**Comment by baronTommy** [comment]
@desktoping 
Thank you

```ts
  it('addTask', async () => {
    const r = await request(app.getHttpServer())
      .post('/graphql')
      // .send({ mutation: 'addTask(AddTask: {title: "hoge"}) ' });
      .send({query: `
        mutation {  addTask(AddTask: {title: "hoge"})  { id }  }
      `})
    console.log(r.error);
  });
```
