### ISSUE TITLE
Can not use custom scalar as parameter in resolver

### ISSUE THREAD

**Issue by IskanderMustafin** [nestjs/nest#1935]
## I'm submitting a...

<pre><code>
[ x] Bug report
</code></pre>

## Current behavior

I downloaded GraphQL  sample using `type-graphql`, created custom Scalar type for mongo's ObjectId: 

```
import { CustomScalar, Scalar } from '@nestjs/graphql';
import { Kind } from 'graphql';
import { ObjectId } from 'mongodb';

@Scalar('ObjectId', (type) => ObjectId)
export class ObjectIdScalar implements CustomScalar<string, ObjectId> {
    description = 'Mongo ObjectID scalar';
    parseValue(value: string): ObjectId {
        return new ObjectId(value); // value from the client
    }
    serialize(value: ObjectId): string {
        return value.toHexString(); // value sent to the client
    }
    parseLiteral(ast: any): ObjectId {
        if (ast.kind === Kind.STRING) {
            return new ObjectId(ast.value); // value from the client query
        }
        return null;
    }
}

```
Custom scalar is imported and declared as provider of Nest module.

Now I'm trying to use this custom scalar as argument of resolver. 
```
    @Query((returns) => ReviewType)
    async reviewById(@Args('id') id: ObjectId): Promise<ReviewType> {
        ...
    }
```

Also tried like this: 

```
    @Query((returns) => ReviewType)
    async reviewById(@Args({name: 'id', type: () => ObjectId}) id: ObjectId): Promise<ReviewType> {
}
```

In both cases I'm getting following exception: 

> The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefinedThe first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined {
  "stack": "TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined\n    at Function.from (buffer.js:207:11)\n    at new Buffer (buffer.js:182:17)\n    at TransformOperationExecutor.transform (class-transformer\\TransformOperationExecutor.js:112:32)\n    at _loop_1 (class-transformer\\TransformOperationExecutor.js:215:45)\n    at TransformOperationExecutor.transform (class-transformer\\TransformOperationExecutor.js:240:17)\n    at ClassTransformer.plainToClass (class-transformer\\ClassTransformer.js:17:25)\n    at Object.plainToClass (class-transformer\\index.js:20:29)\n    at ValidationPipe.transform (@nestjs\\common\\pipes\\validation.pipe.js:107:41)\n    at transforms.reduce (@nestjs\\core\\pipes\\pipes-consumer.js:15:28)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
> 

Since stacktrace mentions about Validation pipes, I tried to comment out  `app.useGlobalPipes` in `main.ts`

```
    // app.useGlobalPipes(new ValidationPipe());
```
and after commenting out it started to work without problems.

=============================================

And may be another problem also can be related to this: when I tried to use enums as parameters of resolvers, it  also was problematic: 

```
enum Direction {
  Up = "u",
  Down = "d"
}
...
//somewhere else 

registerEnumType(Direction, {
  name: "Direction", // this one is mandatory
  description: "The basic directions", // this one is optional
});
...
// and in resolver

@Args({ name: 'direction', type: () => Direction }) direction: Direction
```
In this case `direction` parameter is set to `Down` or `Up` string instead of `u` or `d` string (i.e. I'm getting Enum's key instead of Enum value). 

As a workaround I used this: 
```
// in resolver
     @Args(
         { name: 'direction', type: () => Direction },
         new EnumPipeTransform(direction)
     )

// enum transformer class

export class EnumPipeTransform implements PipeTransform {
    constructor(private enumType: any) {}

    transform(value: any, metadata: ArgumentMetadata) {
        const res = EnumUtils.getEnumValueByKey(this.enumType, value);
        console.log(`res ${res}`);
        return res;
    }
}


```
## Expected behavior

Should not throw such error and should work correctly with enums; 

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by zhenwenc** [comment]
You may want to post to [NestJS GraphQL issues](https://github.com/nestjs/graphql/issues).
