### ISSUE TITLE
[Question] Middleware dependencies.

### ISSUE THREAD

**Issue by thohoh** [nestjs/nest#222]
Hello. I'm trying to inject specific Logger component into my LoggerMiddleware depending on env variable.

1. **LoggerMiddleware**
```[typescript]
export const TLogger = Symbol('ILogger');

@Middleware()
export class LoggerMiddleware implements NestMiddleware {
    constructor(@Inject(TLogger) private logger: ILogger) {

    }
    resolve(...args: any[]): ExpressMiddleware {
        return (req, res, next) => {
            this.logger.info(`${req.method} ${req.originalUrl}`);
            next();
        };
    }
}
```
2. **Provider**
```[typescript]
export const loggerProvider = {
    provide: TLogger,
    useFactory: async (env: Environment, consoleLogger, stagingLogger) => {
        if (env.getMode() === 'local') {
            return consoleLogger;
        } else {
            return stagingLogger;
        }
    },
    inject: [Environment, ConsoleLogger, StagingLogger]
};
```
3. **LoggerModule**
```[typescript]
@Module({
    modules: [CommonModule], // CommonModule exports Environment component
    components: [
        ConsoleLogger,
        StagingLogger,
        loggerProvider,
        LoggerMiddleware
    ],
    exports: [LoggerMiddleware, loggerProvider, ConsoleLogger, StagingLogger]
})
export class LoggerModule {

}
```

4. **Trying to apply**
```[typescript]
@Module({
    modules: [
        LoggerModule
    ]
})
export class ApplicationModule implements NestModule {
    configure(consumer: MiddlewaresConsumer): void {
        consumer.apply(LoggerMiddleware).forRoutes(
          { path: '/', method: RequestMethod.ALL },
        );
    }
}
```
5. **Getting the following**:
```
[Nest] 2184   - 2017-11-1 08:14:09   [NestFactory] Starting Nest application...
[Nest] 2184   - 2017-11-1 08:14:09   [InstanceLoader] ApplicationModule dependencies initialized +18ms
[Nest] 2184   - 2017-11-1 08:14:09   [ExceptionHandler] Nest can't resolve dependencies of the LoggerMiddleware. Please verify whether all of them are available in the current context.
Error: Nest can't resolve dependencies of the LoggerMiddleware. Please verify whether all of them are available in the current context.
    at Injector.<anonymous> (/Users/x/Projects/twitter-clone/server/node_modules/@nestjs/core/injector/injector.js:156:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/x/Projects/twitter-clone/server/node_modules/@nestjs/core/injector/injector.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
 1: node::Abort() [/usr/local/bin/node]
 2: node::Chdir(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 3: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/local/bin/node]
 4: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 5: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 6: 0x2efd6d70437d

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

6. I can't figure out what went wrong since the error message isn't quite informative.
    How do I implements the following injection logic with Nest? Thank you.

**Comment by ArtworkAD** [comment]
@thohoh How did you solve this? Facing a similar issue...

**Comment by thohoh** [comment]
@ArtworkAD There was a mistake in modules' configurations, I don't remember where exactly. Track all of the dependencies you've got and you'll figure it out yourself.
