### ISSUE TITLE
path alias not working 

### ISSUE THREAD

**Issue by techaks** [nestjs/nest#2398]
```

{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es6",
    "sourceMap": true,
    "allowSyntheticDefaultImports": true,
    "outDir": "./dist",
    "baseUrl": "src/",
    "incremental": true,
    "paths": {
      "*": ["./*"],
      "@src/*": [
        "*"
      ],
      "@shared/*": ["shared/*"],
      "@api/*": ["apis/*"],
    }
  },
  "exclude": ["node_modules", "dist"]
}
```

```

Error: Cannot find module '@shared/api-exception.model'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/shambhawi/Documents/voopik-server/dist/apis/auth-apis/logins/logins.controller.js:26:31)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/shambhawi/Documents/voopik-server/dist/apis/auth-apis/logins/logins.module.js:12:29)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@1.0.0 start:prod: `node dist/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the server@1.0.0 start:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions.

**Comment by yidafu** [comment]
hi, I solved a similar problem from this [comment](https://github.com/dividab/tsconfig-paths/issues/86#issuecomment-504649241). Hope it is useful.
