### ISSUE TITLE
sample/03-microservices does not start

### ISSUE THREAD

**Issue by rhlsthrm** [nestjs/nest#2407]
## Current behavior
Running `npm i` followed by `npm start` in the `sample/03-microservices` directory throws an error:
```
$ npm start                                                                                                             

> nest-typescript-starter@1.0.0 start /Users/rahul/Desktop/connext/connext/nest/sample/03-microservices
> ts-node src/main.ts

[Nest] 43193   - 06/17/2019, 10:42 AM   [NestFactory] Starting Nest application...
[Nest] 43193   - 06/17/2019, 10:42 AM   [InstanceLoader] ApplicationModule dependencies initialized +25ms
[Nest] 43193   - 06/17/2019, 10:42 AM   [InstanceLoader] ClientsModule dependencies initialized +1ms
[Nest] 43193   - 06/17/2019, 10:42 AM   [ExceptionHandler] Nest can't resolve dependencies of the MathController (MATH_SERVICE, ?). Please make sure that the argument at index [1] is available in the MathModule context. +4ms
Error: Nest can't resolve dependencies of the MathController (MATH_SERVICE, ?). Please make sure that the argument at index [1] is available in the MathModule context.
    at Injector.resolveSingleParam (/Users/rahul/Desktop/connext/connext/nest/sample/03-microservices/node_modules/@nestjs/core/injector/injector.js:129:19)
    at resolveParam (/Users/rahul/Desktop/connext/connext/nest/sample/03-microservices/node_modules/@nestjs/core/injector/injector.js:96:49)
    at Array.map (<anonymous>)
    at Injector.resolveConstructorParams (/Users/rahul/Desktop/connext/connext/nest/sample/03-microservices/node_modules/@nestjs/core/injector/injector.js:112:58)
    at Injector.loadInstance (/Users/rahul/Desktop/connext/connext/nest/sample/03-microservices/node_modules/@nestjs/core/injector/injector.js:78:20)
    at Injector.loadController (/Users/rahul/Desktop/connext/connext/nest/sample/03-microservices/node_modules/@nestjs/core/injector/injector.js:26:20)
    at Promise.all.map (/Users/rahul/Desktop/connext/connext/nest/sample/03-microservices/node_modules/@nestjs/core/injector/instance-loader.js:49:90)
    at Array.map (<anonymous>)
    at InstanceLoader.createInstancesOfControllers (/Users/rahul/Desktop/connext/connext/nest/sample/03-microservices/node_modules/@nestjs/core/injector/instance-loader.js:49:53)
    at Promise.all.map (/Users/rahul/Desktop/connext/connext/nest/sample/03-microservices/node_modules/@nestjs/core/injector/instance-loader.js:29:24)
```

## Input Code
https://github.com/nestjs/nest/tree/master/sample/03-microservices

## Expected behavior
Sample should start up without errors.

## Environment

<pre><code>
Nest version: 6.3.1

 
For Tooling issues:
- Node version: v10.16.0
- Platform:  Mac

**Comment by kamilmysliwiec** [comment]
Fixed! Thanks for reporting :)
