### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Generating schema error

### ISSUE THREAD

**Issue by aguerram** [nestjs/nest#2462]
## Current behavior

Hello there it's my first time submitting an issue in  github, I've just started learning nestjs,
created new app using **nest new app**,
I followed the example of integrating GraphQL in the documentation as it is, 
but getting this message, PS: didn't add anything to my code just copying the example in the documentation.
`
(node:4632) UnhandledPromiseRejectionWarning: Error: Generating schema error
[0]     at Function.<anonymous> (E:\workspace\projects\anime-site\app\node_modules\type-graphql\dist\schema\schema-generator.js:20:27)
[0]     at Generator.next (<anonymous>)
[0]     at fulfilled (E:\workspace\projects\anime-site\app\node_modules\tslib\tslib.js:107:62)
[0]     at processTicksAndRejections (internal/process/task_queues.js:89:5)
[0] (node:4632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[0] (node:4632) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

## Input Code
this is my main module app.module.ts
```ts
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import {GraphQLModule} from '@nestjs/graphql'
@Module({
  imports: [
    GraphQLModule.forRoot({
      autoSchemaFile: true
    })
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```
This is my package.json
```json
"dependencies": {
    "@nestjs/common": "^6.3.2",
    "@nestjs/core": "^6.3.2",
    "@nestjs/graphql": "^6.2.4",
    "@nestjs/platform-express": "^6.3.2",
    "@playlyfe/gql": "^2.6.1",
    "apollo-server-express": "^2.6.7",
    "graphql": "^14.4.0",
    "graphql-tools": "^4.0.5",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^2.6.3",
    "rxjs": "^6.5.2",
    "type-graphql": "^0.17.4"
  },
```
## Expected behavior

Normally when I enter enter **http://localhost:3000/graphql** I should see the playground of graphql, but the local server turns to be not working, because of the error.

**Comment by aguerram** [comment]
Sorry my bad, I didn't create a resolver, for those who had the same issue, you've just to create a resolver, just follow to the next section in the documentation Graphql Resolver of nestjs and It will work 👍
