### ISSUE TITLE
Is overrideGuard working ?

### ISSUE THREAD

**Issue by pairmix** [nestjs/nest#2515]
Hi there,
I'd like to override AuthGuard but it' doesn't work.

adresses.controller.ts
````
import {Controller, Get, Param, Req, UseGuards} from '@nestjs/common';
import { ObjectId } from 'mongodb';
import { AdressesService } from './adresses.service';
import {ApiOperation, ApiBearerAuth} from '@nestjs/swagger';
import {AuthGuard} from '@nestjs/passport';
import {Identity} from '../auth/identity.decorator';

@Controller('adresses')
@ApiBearerAuth()
@UseGuards(AuthGuard())
export class AdressesController {
  constructor(private readonly adresseService: AdressesService) {}

  @Get('/countries')
  @ApiOperation({ title: 'Titre', description: 'Description' })
  countries() {
    return this.adresseService.getPaysOptions();
  }
````
adresses.e2e-spec.ts
````
import * as request from 'supertest';
import { Test, TestingModule } from '@nestjs/testing';
import { INestApplication } from '@nestjs/common';
import {AdressesModule} from "./adresses.module";
import {AuthGuard} from '@nestjs/passport';

describe('AdresseController E2E', () => {
  let app: INestApplication;

  beforeAll(async () => {
    const module: TestingModule = await Test.createTestingModule({
      imports: [
        AdressesModule
      ],
    })
        .overrideGuard(AuthGuard)
        .useValue({ canActivate: () => true })
        .compile();

    app = module.createNestApplication();
    await app.init();
  });

  it(`/GET adresses/countries`, async () => {
    return request(app.getHttpServer())
        .get('/adresses/countries')
        .expect(200);
  });

  afterAll(async () => {
    await app.close();
  });
});
````

It doesn't work, because i get 401 code instead of 200:
````
$jest src/adresses/adresses.e2e.spec.ts
ts-jest[versions] (WARN) Version 23.6.0 of jest installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=24.0.0 <25.0.0). Please do not report issues in ts-jest if you are using unsupported versions.
 FAIL  src/adresses/adresses.e2e-spec.ts (14.722s)
  AdresseController E2E
    ✕ /GET adresses/countries (22ms)

  ● AdresseController E2E › /GET adresses/countries

    expected 200 "OK", got 401 "Unauthorized"

      at Test.Object.<anonymous>.Test._assertStatus (../node_modules/supertest/lib/test.js:268:12)
      at Test.Object.<anonymous>.Test._assertFunction (../node_modules/supertest/lib/test.js:283:11)
      at Test.Object.<anonymous>.Test.assert (../node_modules/supertest/lib/test.js:173:18)
      at Server.localAssert (../node_modules/supertest/lib/test.js:131:12)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        14.745s, estimated 16s
Ran all test suites matching /src\/adresses\/adresses.e2e.spec.ts/i.
````

Can anyone tell me what i do wrong ?
David

**Comment by pairmix** [comment]
$nest --version                
6.5.0

**Comment by pairmix** [comment]
My bad!
````
.overrideGuard(AuthGuard())
````
instead of 
````
.overrideGuard(AuthGuard)
````

**Comment by waqasshargeel** [comment]
I'm having a similar issue, how did you fix it?

**Comment by jogelin** [comment]
> I'm having a similar issue, how did you fix it? - I used AuthGuard()
> 
> * Found the error, if your module has two controllers then you're unable to override AuthGuard()

I have exactly the same issue with 2 graphQL resolvers ! 

If I specify only one, it works but if I specify 2 resolvers in my testingModule...it doesn't...

@waqasshargeel Did you fix it ?

**Comment by tbhanson96** [comment]
@jogelin I fixed this by making another class called `MyAuthGuard` which implements CanActivate. Then in my providers section of the module i was injecting it in:

```
    {
      provide: MyAuthGuard,
      useValue: new (AuthGuard('jwt'))(),
    }
```
This seems to work. You just override `MyAuthGuard` in your tests.
