### ISSUE TITLE
Stage 2 decorators cannot be used to decorate parameters

### ISSUE THREAD

**Issue by yeongjet** [nestjs/nest#2560]
## Current behavior
```
 babel-node --extensions .ts --config-file ./babel.config.js -- src/main.ts --debug

C:\Users\Administrator\AppData\Roaming\npm\node_modules\@babel\core\lib\transformation\normalize-file.js:209
    throw err;
    ^

SyntaxError: D:\project\mazongguan_nestjs\packages\bp\src\bp.controller.ts: Stage 2 decorators cannot be used to decorate parameters (17:18)    

  15 | 
  16 |     @Get(':id')
> 17 |     async findOne(@Param('id', new UserIDPipe()) id): Promise<BP> {
     |                   ^
  18 |         console.log(`get member: ${id}`)
  19 |         return await this.bpService.findOne(id)
  20 |     }
    at Object.raise (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:6325:17)       
    at Object.parseBindingList (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7958:16)
    at Object.parseFunctionParams (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:10557:24)
    at Object.parseFunctionParams (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:5556:11)
    at Object.parseMethod (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:9346:10) 
    at Object.pushClassMethod (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:10804:30)
    at Object.pushClassMethod (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:5526:11)
    at Object.parseClassMemberWithIsStatic (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:10748:14)
    at Object.parseClassMemberWithIsStatic (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:5425:11)
    at Object.parseClassMember (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:10668:10)

```

## Input Code

babel.config.js:
```js
module.exports = {
    presets: ["@babel/preset-env", "@babel/preset-typescript"],
    sourceMaps: "inline",
    plugins: [
        ["@babel/plugin-proposal-decorators", {decoratorsBeforeExport: true}],
        "@babel/plugin-proposal-optional-chaining",
        "@babel/plugin-proposal-class-properties"
    ],
    ignore: ["./node_modules"]
};
```

## Expected behavior
no error

## Possible Solution
Using this config?
```js
{
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose" : true }]
  ]
}
```

## Environment

<pre><code>
Nest version: 6.4.1

 
For Tooling issues:
- Node version: v10.16.0 
- Platform:  Windows

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Yes, only `legacy` option (for decorators) is supported.
