### ISSUE TITLE
Error when using decorator in param

### ISSUE THREAD

**Issue by yeongjet** [nestjs/nest#2576]
## Current behavior
```
> @mazongguan/bp@0.0.1 start D:\program\mazongguan_nestjs\packages\bp
> babel-node --extensions .ts --config-file ./babel.config.js -- src/main.ts --debug

D:\program\mazongguan_nestjs\packages\bp\src\bp.controller.ts:38
      regeneratorRuntime.mark(function _callee(@(0, _common.Body)()
                                               ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Module._compile (C:\Users\wingzit\AppData\Roaming\npm\node_modules\@babel\node\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Object.newLoader [as .ts] (C:\Users\wingzit\AppData\Roaming\npm\node_modules\@babel\node\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
```

## Input Code

bp.controller.ts:
```ts
@Controller('bp')
export class BPController {
    constructor(private readonly bpService: BPService) {}

    @Post()
    async create(@Body() bpSignUpDto: BPDto.SignUpDto) {
        this.bpService.signUp(bpSignUpDto)
    }
}
```
babel.config.js:
```js
module.exports = {
    presets: ["@babel/preset-env", "@babel/preset-typescript"],
    sourceMaps: "inline",
    plugins: [
        ["@babel/plugin-proposal-decorators", { "legacy": true }],
        ["@babel/plugin-proposal-class-properties", { "loose" : true }],
        "@babel/plugin-proposal-optional-chaining"
    ],
    ignore: ["./node_modules"]
};
```
package.json:
```
{
  "scripts": {
    "build": "babel --extensions .ts --ignore node_modules dist . -d ./dist",
    "start:dist": "babel-node dist/src/main.js",
    "start:ts-node": "ts-node -r tsconfig-paths/register src/main.ts",
    "start": "babel-node --extensions .ts --config-file ./babel.config.js -- src/main.ts --debug"
  }
}
```
I got the error above when run script: `npm start` but it run success by runing `npm run start:ts-node`

## Expected behavior

Run success
## Possible Solution

using offical typescript complier instead babel?
## Environment

<pre><code>
Nest version: 6.4.1

 
For Tooling issues:
- Node version: 12.1.0  
- Platform:  Windows

**Comment by kamilmysliwiec** [comment]
It works with an official TypeScript compiler. I'd rather suggest asking this question in the Babel repository.
