### ISSUE TITLE
MongoDb entity update ?

### ISSUE THREAD

**Issue by pairmix** [nestjs/nest#2655]
Hi there,
I'm trying to update an entity but it seems that it tries to insert.

````
@Injectable()
export class AdminService {
    constructor(
        @InjectRepository(Candidat) private readonly candidatRepository: MongoRepository<Candidat>,
    ) {}

async upgradeCandidatWithPhoto() {
const candidat = await this.candidatRepository.findOne({
            where: {
                _id: new ObjectId('5d30289c2baf282802038f6c'),
            },
        });
         await this.candidatRepository.save(candidat); =>trying to insert a new document with same _id 
}
}
````

````
(node:8508) UnhandledPromiseRejectionWarning: BulkWriteError: E11000 duplicate key error collection: pair
mix.candidats index: _id_ dup key: { : ObjectId('5d30289c2baf282802038f6c') }                            
    at OrderedBulkOperation.handleWriteError (C:\Data\Projects\nestjs\node_modules\mongodb\lib\bulk\commo
n.js:1112:11)                                                                                            
    at resultHandler (C:\Data\Projects\nestjs\node_modules\mongodb\lib\bulk\common.js:501:23)            
    at C:\Data\Projects\nestjs\node_modules\mongodb-core\lib\connection\pool.js:397:18                   
    at process._tickCallback (internal/process/next_tick.js:61:11)                                       
(node:8508) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either b
y throwing inside of an async function without a catch block, or by rejecting a promise which was not han
dled with .catch(). (rejection id: 2)                                                                    
(node:8508) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, pro
mise rejections that are not handled will terminate the Node.js process with a non-zero exit code.       
````

What i do wrong ?

**Comment by pairmix** [comment]
My primary key is "_id", NOT "id".
I think update doesn't work because of this.

**Comment by pairmix** [comment]
oups it'a typeorm issue, sorry
