### ISSUE TITLE
Cannot start with npm run start:prod

### ISSUE THREAD

**Issue by kuangshp** [nestjs/nest#2673]
My code development environment was fine, so was the packaged build, but I reported an error when I ran NPM run start:prod

```js
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/11.14.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start:prod' ]
2 info using npm@6.10.0
3 info using node@v11.14.0
4 verbose run-script [ 'prestart:prod', 'start:prod', 'poststart:prod' ]
5 info lifecycle demo03@0.0.1~prestart:prod: demo03@0.0.1
6 verbose lifecycle demo03@0.0.1~prestart:prod: unsafe-perm in lifecycle true
7 verbose lifecycle demo03@0.0.1~prestart:prod: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/shuiping.kuang/Documents/aaron/web/node/nest-demo/demo03/node_modules/.bin:/bin:/usr/bin:/usr/local/bin:/usr/local/Cellar/node:/Users/shuiping.kuang/Library/Android/sdk/emulator:/Users/shuiping.kuang/Library/Android/sdk/tools:/Users/shuiping.kuang/Documents/software/phantomjs-2.1.1-macosx/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Users/shuiping.kuang/Library/Android/sdk/emulator:/Users/shuiping.kuang/Library/Android/sdk/tools:/bin:/usr/bin:/usr/local/bin:/usr/local/Cellar/node:/Users/shuiping.kuang/Library/Android/sdk/emulator:/Users/shuiping.kuang/Library/Android/sdk/tools:/Users/shuiping.kuang/Documents/software/phantomjs-2.1.1-macosx/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/usr/local/Cellar/node:/Users/shuiping.kuang/Library/Android/sdk/emulator:/Users/shuiping.kuang/Library/Android/sdk/tools:/Users/shuiping.kuang/Documents/software/phantomjs-2.1.1-macosx/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/usr/local/chromedriver:/Users/shuiping.kuang/Library/Android/sdk/tools/bin:/Users/shuiping.kuang/Library/Android/sdk/platform-tools:/usr/local/chromedriver:/Users/shuiping.kuang/Library/Android/sdk/tools:/Users/shuiping.kuang/Library/Android/sdk/tools/bin:/Users/shuiping.kuang/Library/Android/sdk/platform-tools:/Users/shuiping.kuang/Library/Android/sdk/emulator:/Users/shuiping.kuang/Library/Android/sdk/tools:/Users/shuiping.kuang/Library/Android/sdk/tools/bin:/Users/shuiping.kuang/Library/Android/sdk/platform-tools:/Users/shuiping.kuang/Library/Android/sdk/emulator:/usr/local/chromedriver:/Users/shuiping.kuang/Library/Android/sdk/tools:/Users/shuiping.kuang/Library/Android/sdk/tools/bin:/Users/shuiping.kuang/Library/Android/sdk/platform-tools:/Users/shuiping.kuang/Library/Android/sdk/emulator
8 verbose lifecycle demo03@0.0.1~prestart:prod: CWD: /Users/shuiping.kuang/Documents/aaron/web/node/nest-demo/demo03
9 silly lifecycle demo03@0.0.1~prestart:prod: Args: [ '-c', 'rimraf dist && npm run build' ]
10 silly lifecycle demo03@0.0.1~prestart:prod: Returned: code: 0  signal: null
11 info lifecycle demo03@0.0.1~start:prod: demo03@0.0.1
12 verbose lifecycle demo03@0.0.1~start:prod: unsafe-perm in lifecycle true
13 verbose lifecycle demo03@0.0.1~start:prod: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/shuiping.kuang/Documents/aaron/web/node/nest-demo/demo03/node_modules/.bin:/bin:/usr/bin:/usr/local/bin:/usr/local/Cellar/node:/Users/shuiping.kuang/Library/Android/sdk/emulator:/Users/shuiping.kuang/Library/Android/sdk/tools:/Users/shuiping.kuang/Documents/software/phantomjs-2.1.1-macosx/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Users/shuiping.kuang/Library/Android/sdk/emulator:/Users/shuiping.kuang/Library/Android/sdk/tools:/bin:/usr/bin:/usr/local/bin:/usr/local/Cellar/node:/Users/shuiping.kuang/Library/Android/sdk/emulator:/Users/shuiping.kuang/Library/Android/sdk/tools:/Users/shuiping.kuang/Documents/software/phantomjs-2.1.1-macosx/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/usr/local/Cellar/node:/Users/shuiping.kuang/Library/Android/sdk/emulator:/Users/shuiping.kuang/Library/Android/sdk/tools:/Users/shuiping.kuang/Documents/software/phantomjs-2.1.1-macosx/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/usr/local/chromedriver:/Users/shuiping.kuang/Library/Android/sdk/tools/bin:/Users/shuiping.kuang/Library/Android/sdk/platform-tools:/usr/local/chromedriver:/Users/shuiping.kuang/Library/Android/sdk/tools:/Users/shuiping.kuang/Library/Android/sdk/tools/bin:/Users/shuiping.kuang/Library/Android/sdk/platform-tools:/Users/shuiping.kuang/Library/Android/sdk/emulator:/Users/shuiping.kuang/Library/Android/sdk/tools:/Users/shuiping.kuang/Library/Android/sdk/tools/bin:/Users/shuiping.kuang/Library/Android/sdk/platform-tools:/Users/shuiping.kuang/Library/Android/sdk/emulator:/usr/local/chromedriver:/Users/shuiping.kuang/Library/Android/sdk/tools:/Users/shuiping.kuang/Library/Android/sdk/tools/bin:/Users/shuiping.kuang/Library/Android/sdk/platform-tools:/Users/shuiping.kuang/Library/Android/sdk/emulator
14 verbose lifecycle demo03@0.0.1~start:prod: CWD: /Users/shuiping.kuang/Documents/aaron/web/node/nest-demo/demo03
15 silly lifecycle demo03@0.0.1~start:prod: Args: [ '-c', 'node dist/main.js' ]
16 silly lifecycle demo03@0.0.1~start:prod: Returned: code: 1  signal: null
17 info lifecycle demo03@0.0.1~start:prod: Failed to exec start:prod script
18 verbose stack Error: demo03@0.0.1 start:prod: `node dist/main.js`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
18 verbose stack     at EventEmitter.emit (events.js:193:13)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:193:13)
18 verbose stack     at maybeClose (internal/child_process.js:999:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
19 verbose pkgid demo03@0.0.1
20 verbose cwd /Users/shuiping.kuang/Documents/aaron/web/node/nest-demo/demo03
21 verbose Darwin 18.5.0
22 verbose argv "/usr/local/Cellar/node/11.14.0/bin/node" "/usr/local/bin/npm" "run" "start:prod"
23 verbose node v11.14.0
24 verbose npm  v6.10.0
25 error code ELIFECYCLE
26 error errno 1
27 error demo03@0.0.1 start:prod: `node dist/main.js`
27 error Exit status 1
28 error Failed at the demo03@0.0.1 start:prod script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]
```
It seems that npm-lifecycle has errors

**Comment by kamilmysliwiec** [comment]
Please, use [StackOverflow](https://stackoverflow.com/questions/tagged/nestjs) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
