### ISSUE TITLE
HttpService post request returns "Internal server error (500)"

### ISSUE THREAD

**Issue by Tolga-FNT** [nestjs/nest#2819]
## Current behavior

When I try to use a post request to send data, I get to see the following error popping up:
```
Error: Request failed with status code 500
    at createError (/Users/omega/Development/crypto-provider-api/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/omega/Development/crypto-provider-api/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/omega/Development/crypto-provider-api/node_modules/axios/lib/adapters/http.js:237:11)
```
This is the data part:

```
data: 'Parse: ' +
      'org.apache.tomcat.util.http.fileupload.FileUploadBase$InvalidContentTypeException: ' +
      "the request doesn't contain a multipart/form-data or multipart/mixed " +
      'stream, content type header is application/json'
```

## Input Code

```ts
private async broadcastTransaction( tx: string ) {
        const data = JSON.stringify({tx});
        console.log(data);
        
        return await this.http.post( `https://blockchain.info/pushtx`, data,
        { headers: { 'Content-Type': 'application/json' }, method:'POST', data:null } )
        .toPromise()
        .catch( e => {
            console.log( e );
            throw new InternalServerErrorException( e );
        } );
    }
```

## Expected behavior
I was expecting to see a message saying that the transaction is submitted.

## Environment

<pre><code>
Nest version: 
```
"@nestjs/common": "^6.0.0",
    "@nestjs/core": "^6.0.0",
    "@nestjs/jwt": "^6.1.1",
    "@nestjs/passport": "^6.1.0",
    "@nestjs/platform-express": "^6.0.0",
    "@nestjs/typeorm": "^6.1.3",
```

 
For Tooling issues:
- Node version: v12.4.0
- Platform:  Mac

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
