### ISSUE TITLE
Error: Cannot find module '@nest/core/utils/shared.utils'

### ISSUE THREAD

**Issue by lmorningstar116** [nestjs/nest#2871]
If I try to use the microservice as in the documentation, an error occurs.
`Error: Cannot find module '@nest/core/utils/shared.utils'`

main.ts
```
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { Transport } from '@nest/microservices';

async function bootstrap() {
  const app = await NestFactory.createMicroservice(AppModule, {
    transport: Transport.TCP,
  });
  // tslint:disable-next-line:no-console
  await app.listen(() => console.log('Scheduler microservice is running...'));
}
bootstrap();
```

console
```
[0] Error: Cannot find module '@nest/core/utils/shared.utils'
[0] Require stack:
[0] - C:\_DEV\_iisystem\scheduler\node_modules\@nest\microservices\client\client-proxy.js
[0] - C:\_DEV\_iisystem\scheduler\node_modules\@nest\microservices\client\index.js
[0] - C:\_DEV\_iisystem\scheduler\node_modules\@nest\microservices\index.js
[0] - C:\_DEV\_iisystem\scheduler\dist\main.js
[0]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
[0]     at Module.require (internal/modules/cjs/loader.js:683:19)
[0]     at require (internal/modules/cjs/helpers.js:16:16)
[0]     at Object.<anonymous> (C:\_DEV\_iisystem\scheduler\node_modules\@nest\microservices\client\client-proxy.js:3:24)
[0]     at Module._compile (internal/modules/cjs/loader.js:776:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
[0]     at Module.load (internal/modules/cjs/loader.js:643:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
[0]     at Module.require (internal/modules/cjs/loader.js:683:19) {
[0]   code: 'MODULE_NOT_FOUND',
[0]   requireStack: [
[0]     'C:\\_DEV\\_iisystem\\scheduler\\node_modules\\@nest\\microservices\\client\\client-proxy.js',
[0]     'C:\\_DEV\\_iisystem\\scheduler\\node_modules\\@nest\\microservices\\client\\index.js',
[0]     'C:\\_DEV\\_iisystem\\scheduler\\node_modules\\@nest\\microservices\\index.js',
[0]     'C:\\_DEV\\_iisystem\\scheduler\\dist\\main.js'
[0]   ]
[0] }
```

**Comment by kamilmysliwiec** [comment]
You are using the wrong namespace - `@nest` instead of `@nestjs`. I'll contact NPM

**Comment by lmorningstar116** [comment]
Thank. My mistake
