### ISSUE TITLE
ForwardRef Results in __webpack_require__ Reference Error

### ISSUE THREAD

**Issue by JCHHeilmann** [nestjs/nest#2958]
## Current behavior
I have an Authentication Module and a User Module. Both depend on each others user/ authenticationService. So I'm using forwardRef to work around the circular dependency, but it isn't working. If I remove either side of the circular dependency it does work. 

I get the warning about circular dependencies even though I'm using `forwardRef`.
```
WARNING in Circular dependency detected:
apps\backend\src\app\authentication\authentication.service.ts -> apps\backend\src\app\users\users.service.ts -> apps\backend\src\app\authentication\authentication.service.ts

WARNING in Circular dependency detected:
apps\backend\src\app\users\users.service.ts -> apps\backend\src\app\authentication\authentication.service.ts -> apps\backend\src\app\users\users.service.ts 
```

Then after a few seconds I get this output:
```
ist\apps\backend\main.js:840
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "UsersService", function() { return UsersService; });
                                                                                                       ^
ReferenceError: UsersService is not defined
    at Module.UsersService (C:\Users\UserName\projects\projectName\dist\apps\backend\main.js:840:104)
    at Module../apps/backend/src/app/authentication/authentication.service.ts (C:\Users\UserName\projects\projectName\dist\apps\backend\webpack:\apps\backend\src\app\authentication\authentication.service.ts:11:36)
    at __webpack_require__ (C:\Users\UserName\projects\projectName\dist\apps\backend\webpack:\webpack\bootstrap:19:1)
    at Module../apps/backend/src/app/users/users.service.ts (C:\Users\UserName\projects\projectName\dist\apps\backend\main.js:851:96)
    at __webpack_require__ (C:\Users\UserName\projects\projectName\dist\apps\backend\webpack:\webpack\bootstrap:19:1)
    at Module../apps/backend/src/app/users/users.resolver.ts (C:\Users\UserName\projects\projectName\dist\apps\backend\main.js:734:73)
    at __webpack_require__ (C:\Users\UserName\projects\projectName\dist\apps\backend\webpack:\webpack\bootstrap:19:1)
    at Module../apps/backend/src/app/users/users.module.ts (C:\Users\UserName\projects\projectName\dist\apps\backend\main.js:681:73)
    at __webpack_require__ (C:\Users\UserName\projects\projectName\dist\apps\backend\webpack:\webpack\bootstrap:19:1)
    at Module../apps/backend/src/app/authentication/authentication.module.ts (C:\Users\UserName\projects\projectName\dist\apps\backend\main.js:155:77)
    at __webpack_require__ (C:\Users\UserName\projects\projectName\dist\apps\backend\webpack:\webpack\bootstrap:19:1)
    at Module../apps/backend/src/app/app.module.ts (C:\Users\UserName\projects\projectName\dist\apps\backend\main.js:107:95)
    at __webpack_require__ (C:\Users\UserName\projects\projectName\dist\apps\backend\webpack:\webpack\bootstrap:19:1)
    at Module../apps/backend/src/main.ts (C:\Users\UserName\projects\projectName\dist\apps\backend\webpack:\apps\backend\src\main.ts:1:1)
    at __webpack_require__ (C:\Users\UserName\projects\projectName\dist\apps\backend\webpack:\webpack\bootstrap:19:1)
    at Object.0 (C:\Users\UserName\projects\projectName\dist\apps\backend\main.js:999:18)
    at __webpack_require__ (C:\Users\UserName\projects\projectName\dist\apps\backend\webpack:\webpack\bootstrap:19:1)
    at C:\Users\UserName\projects\projectName\dist\apps\backend\webpack:\webpack\bootstrap:83:1
    at Object.<anonymous> (C:\Users\UserName\projects\projectName\dist\apps\backend\main.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

### authentication.module.ts
```ts
import { forwardRef, Global, Module } from '@nestjs/common';
import { JwtModule } from '@nestjs/jwt';
import { PassportModule } from '@nestjs/passport';
import { UsersModule } from '../users/users.module';

import { AuthenticationService } from './authentication.service';
import { GqlAuthGuard } from './guards/jwt.auth.guard';
import { JwtStrategy } from './jwt.strategy';

@Module({
  imports: [
    PassportModule.register({ defaultStrategy: 'jwt' }),
    JwtModule.register({
      secretOrPrivateKey: 'secretKey',
      signOptions: {
        expiresIn: 3600,
      },
    }),
    forwardRef(() => UsersModule),
  ],
  providers: [AuthenticationService, JwtStrategy, GqlAuthGuard],
  exports: [PassportModule, AuthenticationService, GqlAuthGuard],
})
export class AuthenticationModule {}
```

### users.module.ts

```ts
import { forwardRef, Module } from '@nestjs/common';
import { TypegooseModule } from 'nestjs-typegoose';

import { AuthenticationModule } from '../authentication/authentication.module';
import { ImageUploadModule } from '../image-upload/image-upload.module';
import { User } from './models/User';
import { UserResolver } from './users.resolver';
import { UsersService } from './users.service';

@Module({
  imports: [
    TypegooseModule.forFeature([User]),
    forwardRef(() => AuthenticationModule),
    ImageUploadModule,
  ],
  providers: [UsersService, UserResolver],
  exports: [UsersService],
})
export class UsersModule {}
```

### app.module.ts
```ts
import { Module } from '@nestjs/common';
import { GraphQLModule } from '@nestjs/graphql';
import { TypegooseModule } from 'nestjs-typegoose';

import { AuthenticationModule } from './authentication/authentication.module';
import { ImageUploadModule } from './image-upload/image-upload.module';
import { UsersModule } from './users/users.module';

@Module({
  imports: [
    TypegooseModule.forRoot('mongodb://localhost:27017/projectName'),
    AuthenticationModule,
    GraphQLModule.forRoot({ autoSchemaFile: 'schema.gql', context: ({ req }) => ({ req }) }),
    UsersModule,
    ImageUploadModule,
  ],
  controllers: [],
  providers: [],
})
export class AppModule {}
```

### authentication.service.ts

```ts
import { forwardRef, Inject, Injectable } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';

import { UsersService } from '../users/users.service';
import { JwtPayload } from './interfaces/jwt-payload.interface';

@Injectable()
export class AuthenticationService {
  constructor(
    @Inject(forwardRef(() => UsersService))
    private readonly usersService: UsersService,
    private readonly jwtService: JwtService,
  ) {}

  async signPayload(payload: JwtPayload) {
    const accessToken = this.jwtService.sign(payload, { expiresIn: '12h' });
    return accessToken;
  }

  async validateUser(payload: JwtPayload): Promise<any> {
    return await this.usersService.findByEmail(payload.email);
  }
}
```

### user.service.ts

```ts
import { forwardRef, HttpException, HttpStatus, Inject, Injectable } from '@nestjs/common';
import { compare, genSalt, hash } from 'bcryptjs';
import { ObjectId } from 'mongodb';
import { InjectModel } from 'nestjs-typegoose';
import { ModelType } from 'typegoose';

import { AuthenticationService } from '../authentication/authentication.service';
import { JwtPayload } from '../authentication/interfaces/jwt-payload.interface';
import { ImageUploadService } from '../image-upload/image-upload.service';
import { AlterUserDto } from './dto/alter-user.dto';
import { LoginResponseTo } from './dto/login-response.dto';
import { LoginDto } from './dto/login.dto';
import { SignUpDto } from './dto/sign-up.dto';
import { User } from './models/User';

@Injectable()
export class UsersService {
  constructor(
    @InjectModel(User)
    private readonly userModel: ModelType<User>,
    @Inject(forwardRef(() => AuthenticationService))
    private readonly authService: AuthenticationService,
    private readonly imageUploadService: ImageUploadService,
  ) {}

  async findById(id: ObjectId | string): Promise<User | null> {
    return this.userModel.findById(id).exec();
  }

  async findAll(): Promise<User[]> {
    return this.userModel.find().exec();
  }

  async findByEmail(email: string): Promise<User | null> {
    const result = await this.userModel.find({ email }).exec();
    if (result) {
      return result[0];
    } else {
      return null; // TODO: throw exception
    }
  }

  async signUp(signUpDto: SignUpDto): Promise<User> {
    let { password } = signUpDto;

    const salt = await genSalt();
    password = await hash(password, salt);

    const imageUrl = await this.imageUploadService.singleFileUpload(signUpDto.profilePicture, {
      folder: 'profile_pictures',
      width: 300,
      height: 300,
      crop: 'fill',
      gravity: 'faces',
    });

    // add hashed password to user object
    const createdUser = new this.userModel({
      ...signUpDto,
      password,
      profilePicture: imageUrl,
      verified: false,
    });

    return createdUser.save();
  }

  async login(loginDto: LoginDto): Promise<LoginResponseTo> {
    const { email, password } = loginDto;

    const user = await this.findByEmail(email);

    // user not found
    if (!user) {
      throw new HttpException('Invalid Credentials', HttpStatus.NOT_FOUND);
    }

    const isMatch = await compare(password, user.password);

    // wrong password
    if (!isMatch) {
      throw new HttpException('Invalid Credentials', HttpStatus.BAD_REQUEST);
    }

    const payload: JwtPayload = {
      email: user.email,
    };

    const token = await this.authService.signPayload(payload);

    return { token, user };
  }

  async alter(alterUserDto: AlterUserDto): Promise<User | null> {
    const user = { // TODO: improve using spread operator
      firstName: alterUserDto.firstName,
      lastName: alterUserDto.lastName,
      email: alterUserDto.email,
      profilePicture: alterUserDto.profilePicture,
      homeTown: alterUserDto.homeTown,
    };
    if (alterUserDto._id === '') {
      const createdAccommodation = new this.userModel(user);
      return await createdAccommodation.save();
    }
    return this.userModel.findByIdAndUpdate(alterUserDto._id, user);
  }
}
```

## Expected behavior
I expect the circular dependency warning to go away, since I'm using forwardRef and I expect the server to start and run.

## Possible Solution
I copied parts of this code from a different project where it worked exactly this way.

I already tried downgrading package versions, reinstalling everything...

## Environment

<pre><code>
Nest version: 6.6.7
 
For Tooling issues:
- Node version: v10.16.0
- Platform:  Windows, but also tried on Mac with same issue
Others:
The project was setup with nrwl (nx cli)
</code></pre>

**Comment by kamilmysliwiec** [comment]
@JCHHeilmann I'm sorry, but this issue is not related to NestJS itself :( Try looking for a solution in the webpack github. You can also check out our [Discord](https://discord.gg/G7Qnnhy) channel (support).
