### ISSUE TITLE
Swagget and CRUD causes UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by mreschke** [nestjs/nest#3022]
## Current behavior
Brand new NestJS project inside a new Nrwl NX repo.  Built 3 entities/modules and endpoints, all working perfectly.  Added swagger to main.ts, working perfectly.  Then I simply added CRUD from your docs and converted one single module into CRUD and now swagger crashes.  If I comment out swagger setup in main.ts, no issues.  

## Input Code

Main.ts

```ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app/app.module';
import { config } from './config';
import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  const globalPrefix = 'api/v1';
  app.setGlobalPrefix(globalPrefix);
  const options = new DocumentBuilder()
    .setTitle('Wiki')
    .setDescription('Wiki API')
    .setVersion('1.0')
    //.addTag('wiki')
    .setBasePath('api/v1')
    .setSchemes('https')
    .build();
  const document = SwaggerModule.createDocument(app, options);
  SwaggerModule.setup('swagger', app, document);

  const port = process.env.port || 9010;
  await app.listen(port, () => {
    console.log('Listening at http://localhost:' + port + '/' + globalPrefix);
  });
}
bootstrap();
```

## Expected behavior
Nest server should not error.  Both Swagger and CRUD should work together.

## NestJS Server Error

```
(node:74972) UnhandledPromiseRejectionWarning: TypeError: 
    at Object.getMetadata (~/Code/nx/node_modules/reflect-metadata/Reflect.js:354:23)
    at exploreModelProperties (~/Code/nx/node_modules/@nestjs/swagger/dist/explorers/api-parameters.explorer.js:43:27)
    at Object.exports.exploreModelDefinition (~/Code/nx/node_modules/@nestjs/swagger/dist/explorers/api-parameters.explorer.js:81:29)
    at lodash_1.mapValues.lodash_1.mapValues.response (~/Code/nx/node_modules/@nestjs/swagger/dist/explorers/api-response.explorer.js:65:44)
    at ~/Code/nx/node_modules/@nestjs/swagger/node_modules/lodash/lodash.js:13401:38
    at ~/Code/nx/node_modules/@nestjs/swagger/node_modules/lodash/lodash.js:4905:15
    at baseForOwn (~/Code/nx/node_modules/@nestjs/swagger/node_modules/lodash/lodash.js:2990:24)
    at Function.mapValues (~/Code/nx/node_modules/@nestjs/swagger/node_modules/lodash/lodash.js:13400:7)
    at mapResponsesToSwaggerResponses (~/Code/nx/node_modules/@nestjs/swagger/dist/explorers/api-response.explorer.js:42:96)
    at exports.exploreApiResponseMetadata (~/Code/nx/node_modules/@nestjs/swagger/dist/explorers/api-response.explorer.js:20:16)
(node:74972) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:74972) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kamilmysliwiec** [comment]
What do you mean by CRUD? @nestjsx/crud package?

Please, provide a minimal repository which reproduces your issue.

**Comment by mreschke** [comment]
Yes nestjsx crud causes the error in combination with swagger.  I will build a fresh mini repo and test soon.

**Comment by kamilmysliwiec** [comment]
Please, report this issue here then https://github.com/nestjsx/crud/issues (with reproduction repository) :)

**Comment by mreschke** [comment]
The problem was my 3 controllers were NOT  `implements CrudController<XysModel> {`.  So I simply did not quite have nestjxs/crud implemented fully.
