### ISSUE TITLE
New TS project hot reloading does not work

### ISSUE THREAD

**Issue by mdurakovic** [nestjs/nest#3056]
## Current behavior

Hot reloading does not work

## Input Code
Followed instructions to setup new TS starter project
```
$ git clone https://github.com/nestjs/typescript-starter.git myProject
$ cd project
$ npm install
$ npm run start:dev
```

## Expected behavior
Expecting hot reloading to work properly. Change "Hello world" in boilerplate generated app.service.ts to  "Hello worlds" and you will get this in console:

```events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1279:14)
    at listenInCluster (net.js:1327:12)
    at Server.listen (net.js:1414:7)
    at ExpressAdapter.listen (C:\Users\a\Desktop\Projects\Eves\administration\evesAdministration\node_modules\@nestjs\platform-express\adapters\express-adapter.js:44:32)
    at NestApplication.listen (C:\Users\a\Desktop\Projects\Eves\administration\evesAdministration\node_modules\@nestjs\core\nest-application.js:141:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1306:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

Image for proof:

![image](https://user-images.githubusercontent.com/49903867/65803327-9301ac00-e17e-11e9-83a1-e20b2979f120.png)

Restarted my laptop, repeated, issue still there. Tried with kebab-case named project, still same issue.
 
For Tooling issues:
- Node version: v10.16.0
- Platform: Windows

**Comment by kamilmysliwiec** [comment]
Thanks for reporting! Please, try to update `@nestjs/cli` and `@nestjs/schematics` to their latest versions

**Comment by mdurakovic** [comment]
I did, both cli and schematics are latest versions but issue is still present. 

![image](https://user-images.githubusercontent.com/49903867/65814134-43eb6380-e1de-11e9-8572-5304662fa8b8.png)

**Comment by kamilmysliwiec** [comment]
Have you updated only global versions of packages? If you run `npm run start:dev`, it will use your local packages instead (so you have to update them as well)

**Comment by mdurakovic** [comment]
yes, they are updated too

![image](https://user-images.githubusercontent.com/49903867/65814230-5ade8580-e1df-11e9-8bf9-8aed6962865c.png)

**Comment by johnbiundo** [comment]
@mdurakovic it looks like you don't have the latest versions installed in your `node_modules`.  Here's what I have after doing a fresh install:

```javascript
  "devDependencies": {
    "@nestjs/cli": "^6.9.0",
    "@nestjs/schematics": "^6.7.0",
    "@nestjs/testing": "^6.7.1",
    "@types/express": "^4.17.1",
    "@types/jest": "^24.0.18",
    "@types/node": "^12.7.5",
...
```

Can you upgrade and try again?  We **did** see an error like this in an earlier version, but I believe it's fixed in @latest.

**Comment by mdurakovic** [comment]
Thank you, I missed it. Simple `npm update` and hot reloading now works properly. Too bad this issue is present right from start of making new project, but lucky not a big problem
