### ISSUE TITLE
graphql AuthGaurd not working in any module but the main AuthModule

### ISSUE THREAD

**Issue by electather** [nestjs/nest#3143]
## Current behavior
i setup my authentication logic as shown bellow. the code works fine in my auth module (where everything is initialized) but whenever i try to use this guard anywhere else it just doesn't work. the route is completely unprotected and i don't get the user.
ps. i have imported the Auth Module.

## Input Code
```ts
@Injectable()
export class JwtStrategy extends PassportStrategy(Strategy) {
  constructor(
    readonly configService: ConfigService,
    private readonly userRepository: UserRepository,
  ) {
    super({
      jwtFromRequest: ExtractJwt.fromAuthHeaderAsBearerToken(),
      secretOrKey: configService.get('JWT_SECRET_KEY'),
    });
  }

  async validate({ iat, exp, id }: JwtPayload) {
    const timeDiff = exp - iat;
    if (timeDiff <= 0) {
      throw new UnauthorizedException();
    }

    const user = await this.userRepository.get(id);
    if (!user) {
      throw new UnauthorizedException();
    }

    delete user.password;
    return user;
  }
}
```
```ts
@Injectable()
export class GqlAuthGuard extends AuthGuard('jwt') {
  getRequest(context: ExecutionContext) {
    const ctx = GqlExecutionContext.create(context);
    return ctx.getContext().req;
  }
}
```

resolver located in Auth module which works as expected
```ts
  @Query(() => User)
  @UseGuards(GqlAuthGuard)
  async getUser(@GetUser() user: User, @GetFields() fields) {
    return user;
  }
```
resolver located in another module which it's authentication logic is broken
```ts
  @Mutation(() => BlogPostComment)
  @UseGuards(GqlAuthGuard)
  async addBlogPostComment(
    @GetUser() user: User,
  ) {
    return user;
  }
```

## Expected behavior
`UseGuards` must restrict the route like the one in auth module. it just doesn't seem to work 

## Environment

<pre><code>
Nest version: 6.6.7

</code></pre>

**Comment by joeyslack** [comment]
Have you tried `@Mutation(returns => BlogPostComment` instead of  `@Mutation(() => BlogPostComment)`

**Comment by electather** [comment]
> Have you tried `@Mutation(returns => BlogPostComment` instead of `@Mutation(() => BlogPostComment)`

@joeyslack mutation itself works fine. everything works except authentication.

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by electather** [comment]
@kamilmysliwiec . i was trying to create the minimal repository and something odd happened. after i removed every other module and unnecessary columns in entities it started working. i was getting user object. so i redid everything this time step by step and it seems like one of my modules was causing the problem. and it does not make any sense! 
i got more detailed and it seems this modules resolver is causing this. everything works fine without the resolver. and everything breaks apart when i re add it. 
the code for the resolver ( which is almost identical to most of my other resolvers at this point)
```ts
@Resolver(() => Book)
export class BookResolver {
  constructor(private readonly bookService: BookService) {}

  @Query(() => Book)
  async getBook(
    @Args({ name: 'id', type: () => Int }) id: number,
    @GetFields() fields: IAddAttr,
  ) {
    return this.bookService.getBookById(id, fields);
  }

  @Query(() => PaginatedBookResponse)
  async getBooks(
    @Args({
      name: 'startCursor',
      type: () => Int,
      defaultValue: 0,
      description: 'start Cursor',
    })
    startCursor: number,
    @Args({
      name: 'endCursor',
      type: () => Int,
      nullable: true,
      description: 'end Cursor',
    })
    endCursor: number,
    @Args({
      name: 'limit',
      type: () => Int,
      nullable: true,
      defaultValue: 10,
      description: 'limits the amount of displayed items',
    })
    limit: number,
    @Args({
      name: 'search',
      nullable: true,
      defaultValue: '',
      description: 'optional search string used for searching book names',
      type: () => String,
    })
    search: string,
    @GetFields() fields: IAddAttr,
  ) {
    const poet = await this.bookService.getBooks(
      startCursor,
      endCursor,
      limit,
      search,
      fields,
    );
    return poet;
  }
}
```
ps. i was not able to reproduce the problem when i tried stripping my other modules. so is it okay if i provide private access to the repo if you need it?

**Comment by electather** [comment]
strange ... i was just playing with the code and just adding `  @UseGuards(GqlAuthGuard)
` to any route, seems fixed the problem. i have no idea why!
```ts
@Resolver(() => Book)
export class BookResolver {
  constructor(private readonly bookService: BookService) {}

  @Query(() => Book)
  async getBook(
    @Args({ name: 'id', type: () => Int }) id: number,
    @GetFields() fields: IAddAttr,
  ) {
    return this.bookService.getBookById(id, fields);
  }

  @UseGuards(GqlAuthGuard)
  @Query(() => PaginatedBookResponse)
  async getBooks(
    @Args({
      name: 'startCursor',
      type: () => Int,
      defaultValue: 0,
      description: 'start Cursor',
    })
    startCursor: number,
    @Args({
      name: 'endCursor',
      type: () => Int,
      nullable: true,
      description: 'end Cursor',
    })
    endCursor: number,
    @Args({
      name: 'limit',
      type: () => Int,
      nullable: true,
      defaultValue: 10,
      description: 'limits the amount of displayed items',
    })
    limit: number,
    @Args({
      name: 'search',
      nullable: true,
      defaultValue: '',
      description: 'optional search string used for searching book names',
      type: () => String,
    })
    search: string,
    @GetFields() fields: IAddAttr,
  ) {
    const poet = await this.bookService.getBooks(
      startCursor,
      endCursor,
      limit,
      search,
      fields,
    );
    return poet;
  }
}
```

now both queries are working as expected (  well i don't want to guard this route. but i'll find a way around it.)

**Comment by kamilmysliwiec** [comment]
I'm not sure how we can help without having a public, small reproduction repository.

**Comment by electather** [comment]
@kamilmysliwiec problem is i can't make it small. ( i tried but just removing BookModule fixes problems and creating something new with the same module does not seem to reproduce the problem. I have no idea how to reproduce the same problem)
 whatever the problem is. it's all of them together. and now i have another problem
in my BookResolver if i add the following query it works fine
```ts
  @Query(() => Int)
  async dummy() {
    return 22;
  }
```
response 
```
{
  "data": {
    "dummy": 22
  }
}
```
now if i change it to mutation. 
```ts
  @Mutation(() => Int)
  async dummy() {
    return 22;
  }
```
i get 
```ts
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Mutation.dummy.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "dummy"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field Mutation.dummy.",
            "    at completeValue (D:\\Development\\Projects\\Ghazalgoo 2.0\\server\\node_modules\\graphql\\execution\\execute.js:560:13)",
            "    at completeValueCatchingError (D:\\Development\\Projects\\Ghazalgoo 2.0\\server\\node_modules\\graphql\\execution\\execute.js:495:19)",
            "    at resolveField (D:\\Development\\Projects\\Ghazalgoo 2.0\\server\\node_modules\\graphql\\execution\\execute.js:435:10)",
            "    at D:\\Development\\Projects\\Ghazalgoo 2.0\\server\\node_modules\\graphql\\execution\\execute.js:244:18",
            "    at D:\\Development\\Projects\\Ghazalgoo 2.0\\server\\node_modules\\graphql\\jsutils\\promiseReduce.js:23:10",
            "    at Array.reduce (<anonymous>)",
            "    at promiseReduce (D:\\Development\\Projects\\Ghazalgoo 2.0\\server\\node_modules\\graphql\\jsutils\\promiseReduce.js:20:17)",
            "    at executeFieldsSerially (D:\\Development\\Projects\\Ghazalgoo 2.0\\server\\node_modules\\graphql\\execution\\execute.js:241:37)",
            "    at executeOperation (D:\\Development\\Projects\\Ghazalgoo 2.0\\server\\node_modules\\graphql\\execution\\execute.js:219:55)",
            "    at executeImpl (D:\\Development\\Projects\\Ghazalgoo 2.0\\server\\node_modules\\graphql\\execution\\execute.js:104:14)"
          ]
        }
      }
    }
  ],
  "data": null
}
```
since the problem is isolated to the same module i think they are related. 
here is the full project repository. 
https://github.com/electather/ghazalgoo

**Comment by kamilmysliwiec** [comment]
Without a minimal repository that reproduces your issue, we can't help you. The repo you shared is a normal application with multiple modules.
