### ISSUE TITLE
Cannot handle multiple connections. Crash upon startup

### ISSUE THREAD

**Issue by caiusCitiriga** [nestjs/nest#3295]
## Current behavior
On startup the application crashes with the following message:
```
[Nest] 14515   - 10/30/2019, 9:25:23 PM   [ExceptionHandler] Multiple text records not allowed +74ms
MongoParseError: Multiple text records not allowed
    at QueryReqWrap.callback (/Users/caiuscitiriga/Code/topevo/ShellyServices/node_modules/mongodb/lib/core/uri_parser.js:93:27)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:204:10)
```

#### DatabaseProviders:

```ts
import * as mongoose from 'mongoose';
import { ConfigService } from '../config/services/config.service';
import { Config } from '../config/enums/config.enum';

const stdConfig: mongoose.ConnectionOptions = {
    poolSize: 20,
    useCreateIndex: true,
    useNewUrlParser: true,
    useFindAndModify: false,
    useUnifiedTopology: true,
};

export const databaseProviders = [
    {
        inject: [ConfigService],
        provide: Config.TOURISM_DB_CONN,
        useFactory: async (configSvc: ConfigService): Promise<any> =>
            mongoose.createConnection(configSvc.get(Config.TOURISM_DB_CONN), stdConfig),
    },
    {
        inject: [ConfigService],
        provide: Config.IDENTITY_DB_CONN,
        useFactory: async (configSvc: ConfigService): Promise<any> =>
            mongoose.createConnection(configSvc.get(Config.IDENTITY_DB_CONN), stdConfig),
    },
    {
        inject: [ConfigService],
        provide: Config.IMAGES_PROC_DB_CONN,
        useFactory: async (configSvc: ConfigService): Promise<any> =>
            mongoose.createConnection(configSvc.get(Config.IMAGES_PROC_DB_CONN), stdConfig),
    },
    {
        inject: [ConfigService],
        provide: Config.NOMINATIM_DB_CONN,
        useFactory: async (configSvc: ConfigService): Promise<any> =>
            mongoose.createConnection(configSvc.get(Config.NOMINATIM_DB_CONN), stdConfig),
    },
    {
        inject: [ConfigService],
        provide: Config.ORGANIZATIONS_DB_CONN,
        useFactory: async (configSvc: ConfigService): Promise<any> =>
            mongoose.createConnection(configSvc.get(Config.ORGANIZATIONS_DB_CONN), stdConfig),
    },
    {
        inject: [ConfigService],
        provide: Config.REPORTS_DB_CONN,
        useFactory: async (configSvc: ConfigService): Promise<any> =>
            mongoose.createConnection(configSvc.get(Config.REPORTS_DB_CONN), stdConfig),
    },
    {
        inject: [ConfigService],
        provide: Config.GHOST_PINS_DB_CONN,
        useFactory: async (configSvc: ConfigService): Promise<any> =>
            mongoose.createConnection(configSvc.get(Config.GHOST_PINS_DB_CONN), stdConfig),
    },
    {
        inject: [ConfigService],
        provide: Config.DEVICES_DB_CONN,
        useFactory: async (configSvc: ConfigService): Promise<any> =>
            mongoose.createConnection(configSvc.get(Config.DEVICES_DB_CONN), stdConfig),
    },
    {
        inject: [ConfigService],
        provide: Config.PREFERENCES_DB_CONN,
        useFactory: async (configSvc: ConfigService): Promise<any> =>
            mongoose.createConnection(configSvc.get(Config.PREFERENCES_DB_CONN), stdConfig),
    },
    {
        inject: [ConfigService],
        provide: Config.FUELS_DB_CONN,
        useFactory: async (configSvc: ConfigService): Promise<any> =>
            mongoose.createConnection(configSvc.get(Config.FUELS_DB_CONN), stdConfig),
    },
    {
        inject: [ConfigService],
        provide: Config.PTS_DB_CONN,
        useFactory: async (configSvc: ConfigService): Promise<any> =>
            mongoose.createConnection(configSvc.get(Config.PTS_DB_CONN), stdConfig),
    },
    {
        inject: [ConfigService],
        provide: Config.STATIC_WALLET_CARDS_DB_CONN,
        useFactory: async (configSvc: ConfigService): Promise<any> =>
            mongoose.createConnection(configSvc.get(Config.STATIC_WALLET_CARDS_DB_CONN), stdConfig),
    },
];
```

#### Connections providers:
```ts
export const ImagesProcessorIconsConnectionProvider = {
    provide: ModelsProviders.ICONS_INDEXES,
    useFactory: (connection: Connection) => connection.model('IIconIndex', IconsIndexesSchema),
    inject: [Config.IMAGES_PROC_DB_CONN],
};

/**
 * Used for images indexes collection
 */
export const ImagesProcessorImagesConnectionProvider = {
    provide: ModelsProviders.IMAGES_INDEXES,
    useFactory: (connection: Connection) => connection.model('IImageIndex', ImagesIndexesSchema),
    inject: [Config.IMAGES_PROC_DB_CONN],
};

export const NominatimConnectionProvider = {
    provide: ModelsProviders.NOMINATIM,
    useFactory: (connection: Connection) => connection.model('INominatim', NominatimSchema),
    inject: [Config.NOMINATIM_DB_CONN],
};

export const IdentityConnectionProvider = {
    provide: ModelsProviders.USERS,
    useFactory: (connection: Connection) => connection.model('IUser', UsersSchema),
    inject: [Config.IDENTITY_DB_CONN],
};

export const ReportsConnectionProvider = {
    provide: ModelsProviders.REPORTS,
    useFactory: (connection: Connection) => connection.model('IReport', ReportSchema),
    inject: [Config.REPORTS_DB_CONN],
};

export const ReportsTypesConnectionProvider = {
    provide: ModelsProviders.REPORTS_TYPES,
    useFactory: (connection: Connection) => connection.model('IReportType', ReportTypesSchema),
    inject: [Config.REPORTS_DB_CONN],
};

export const GhostPinsConnectionProvider = {
    provide: ModelsProviders.GHOST_PINS,
    useFactory: (connection: Connection) => connection.model('IGhostPin', GhostPinSchema),
    inject: [Config.GHOST_PINS_DB_CONN],
};
export const GhostPinsFeedbacksConnectionProvider = {
    provide: ModelsProviders.GHOST_PINS_FEEDBACKS,
    useFactory: (connection: Connection) => connection.model('IGhostPinFeedback', GhostPinFeedbackSchema),
    inject: [Config.GHOST_PINS_DB_CONN],
};

export const OrganizationsConnectionProvider = {
    provide: ModelsProviders.ORGANIZATIONS,
    useFactory: (connection: Connection) => connection.model('IOrganization', OrganizationSchema),
    inject: [Config.ORGANIZATIONS_DB_CONN],
};

export const DevicesConnectionProvider = {
    provide: ModelsProviders.DEVICES,
    useFactory: (connection: Connection) => connection.model('IDevice', DeviceSchema),
    inject: [Config.DEVICES_DB_CONN],
};

export const PreferencesConnectionProvider = {
    provide: ModelsProviders.PREFERENCES,
    useFactory: (connection: Connection) => connection.model('IPreference', PreferencesSchema),
    inject: [Config.PREFERENCES_DB_CONN],
};

export const FuelsConnectionProvider = {
    provide: ModelsProviders.FUELS,
    useFactory: (connection: Connection) => connection.model('ICompoundFuelManager', CompoundFuelsManagersSchema),
    inject: [Config.FUELS_DB_CONN],
};

export const SWMGUpdateConnectionProvider = {
    provide: ModelsProviders.SWMG_UPDATE,
    useFactory: (connection: Connection) => connection.model('ISWMGUpdate', SWMGUpdatesSchema),
    inject: [Config.PTS_DB_CONN],
};

export const ReferenceTilesConnectionProvider = {
    provide: ModelsProviders.REFERENCE_TILES,
    useFactory: (connection: Connection) => connection.model('IMapTile', ReferenceTilesSchema),
    inject: [Config.PTS_DB_CONN],
};

export const UsersDistributionConnectionProvider = {
    provide: ModelsProviders.USERS_DISTRIBUTION,
    useFactory: (connection: Connection) => connection.model('IUserDistribution', UsersDistributionSchema),
    inject: [Config.PTS_DB_CONN],
};

export const AliveTilesConnectionProvider = {
    provide: ModelsProviders.ALIVE_TILES,
    useFactory: (connection: Connection) => connection.model('IAliveTile', AliveTilesSchema),
    inject: [Config.PTS_DB_CONN],
};

export const UsersHeartbeatsConnectionProvider = {
    provide: ModelsProviders.USERS_HEARTBEATS,
    useFactory: (connection: Connection) => connection.model('IUserHeartbeat', UserLastHeartbeatsSchema),
    inject: [Config.PTS_DB_CONN],
};

export const TourismEntitiesConnectionProvider = {
    provide: ModelsProviders.TOURISM_ENTITIES,
    useFactory: (connection: Connection) => connection.model('ITourismEnhancedEntity', TourismSchema),
    inject: [Config.TOURISM_DB_CONN],
};

export const TourismCorruptedEntitiesConnectionProvider = {
    provide: ModelsProviders.TOURISM_CORRUPTED_ENTITIES,
    useFactory: (connection: Connection) => connection.model('ITourismCorruptedEntity', WikipediaUnintegrableEntitiesSchema),
    inject: [Config.TOURISM_DB_CONN],
};

export const StaticWalletCardsConnectionProvider = {
    provide: ModelsProviders.STATIC_WALLET_CARDS,
    useFactory: (connection: Connection) => connection.model('IWalletCard', WalletCardSchema),
    inject: [Config.STATIC_WALLET_CARDS_DB_CONN],
};

```

## Expected behavior
The application should successfully startup, and connect to the db

## Environment

<pre><code>
Nest version: 6.8.4
 
For Tooling issues:
- Node version: 12
- Platform: Mac

Others:
On linux this thing does not occur. Also (pretty strange) if I connect my mbp to the cellular hotspot it works! WTF?

**Comment by caiusCitiriga** [comment]
Ok, that strange thing made me think... and looking better at the error I saw a `(dns.js:204:10)` at the end. So I thought... what would happen setting the Google's DNS `8.8.8.8, 8.8.8.4` on my mac?

Boom! It worked. 
Anyways, it's pretty WTF...
