### ISSUE TITLE
Bug with passport-strategy: TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by djfabrix** [nestjs/nest#3332]
## Bug Report
passport-activedirectory throw an Exception on application start.

## Current behavior

When Nest.js application starts, throw the following exception:
```ts
TypeError: Class extends value undefined is not a constructor or null
    at Object.PassportStrategy 
    at Object.<anonymous> 
    at Module._compile (module.js:652:30)
    at Module.m._compile
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] 
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
```

This is my code:

AuthModule
```ts
import { Module } from '@nestjs/common';
import { AuthController } from './auth.controller';
import { AuthService } from './auth.service';
import { AdStrategy } from "./strategies/ad.strategy";
import {PassportModule} from '@nestjs/passport';

@Module({
  imports: [PassportModule],
  controllers: [AuthController],
  providers: [AuthService, AdStrategy]
})

export class AuthModule {

}

```

AdStrategy (strategies/ad.strategy.ts)
```ts
import {Strategy} from "passport-activedirectory";
import {AuthService} from "../auth.service";
import {PassportStrategy} from '@nestjs/passport';
import {Injectable} from "@nestjs/common";

@Injectable()
export class AdStrategy extends PassportStrategy(Strategy, 'activedirectory') {

    constructor(private readonly authService: AuthService) {
        super({
            integrated: false,
            ldap: {
                url: 'ldap://my.domain.com',
                baseDN: 'DC=my,DC=domain,DC=com',
                username: 'readuser@my.domain.com',
                password: 'readuserspassword'
            }
        });
    }

    async validate(profile, ad): Promise<any> {
         // TODO
         const user = this.authService.validateUser(username, password);
        if (!user) {
            throw new UnauthorizedException();
        }
        return user;
    }
}

```

## Expected behavior
I expect the application run without exception.

## Environment
Nest version: 6.0.0

 For Tooling issues:
- Node version: v8.11.2
- Platform:  Mac

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.
