### ISSUE TITLE
Error: Cannot find module 'class-transformer'

### ISSUE THREAD

**Issue by gerry-christiansen** [nestjs/nest#3405]
## Current behavior

After installing the class-transformer npm module, whenever I reference the plainToClass method, I get the following runtime error:

const class_transformer_1 = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module 'class-transformer'"); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
                                                                                                                                                                              ^

Error: Cannot find module 'class-transformer'
    at webpackMissingModule (/Users/a597485/projects/dap/iac/app/dist/apps/iac-pap/main.js:221:93)
    at Object.<anonymous> (/Users/a597485/projects/dap/iac/app/dist/apps/iac-pap/main.js:221:185)
    at __webpack_require__ (/Users/a597485/projects/dap/iac/app/dist/apps/iac-pap/main.js:20:30)
    at Object.<anonymous> (/Users/a597485/projects/dap/iac/app/dist/apps/iac-pap/main.js:185:23)
    at __webpack_require__ (/Users/a597485/projects/dap/iac/app/dist/apps/iac-pap/main.js:20:30)
    at Object.<anonymous> (/Users/a597485/projects/dap/iac/app/dist/apps/iac-pap/main.js:147:26)
    at __webpack_require__ (/Users/a597485/projects/dap/iac/app/dist/apps/iac-pap/main.js:20:30)
    at Object.<anonymous> (/Users/a597485/projects/dap/iac/app/dist/apps/iac-pap/main.js:95:22)
    at __webpack_require__ (/Users/a597485/projects/dap/iac/app/dist/apps/iac-pap/main.js:20:30)
    at /Users/a597485/projects/dap/iac/app/dist/apps/iac-pap/main.js:84:18

## Input Code
import { Injectable } from '@nestjs/common'
import {plainToClass} from 'class-transformer'
import {Person} from './Person'

@Injectable()
export class AppService {
  getHello(): string {
    const o = JSON.parse('{"name": "Gerry"}')
     const p = plainToClass(Person, o)
    global.console.log('Person name: ' + p.name)
    return 'Hello World!'
  }
}

## Environment

    "@nestjs/common": "^6.7.2",
    "@nestjs/core": "^6.7.2",

Others:
This is a mono-repo nestjs project.  I have created a test project (non-mono) and it is not a problem in that environment.  Suspect it may be issue with mono-repo for some reason.

The odd thing is I can import and use the class-validator module (same author).  I've also read that you use the class-transformer inside the ValidationPipe.  If so, is there a conflict here with me installing separate?

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.
