### ISSUE TITLE
Can't mock custom Validator in end-to-end tests

### ISSUE THREAD

**Issue by atanasovdragan** [nestjs/nest#3426]
## Current behavior
I have an e2e test which is testing a certain route correct responsiveness.  The issue is that I have a DTO class as a dependency of that particular controller method and the DTO class is using a custom Validator which is checking some values from a database in order to validate the request. The custom validator is calling another service class which is doing some of the business logic through this validation process. The problem is that when I'm trying to execute the e2e tests, my tests are failing because of this additional service method in the custom validator with the current message:

```
 FAIL  test/e2e/campaigns/campaigns-controller.e2e-spec.ts (5.281s)
  ● CampaignsController (e2e) › (POST) to /campaigns/update should update campaign data

    expected 201 "Created", got 500 "Internal Server Error"

      at Test.Object.<anonymous>.Test._assertStatus (../../node_modules/supertest/lib/test.js:268:12)
      at Test.Object.<anonymous>.Test._assertFunction (../../node_modules/supertest/lib/test.js:283:11)
      at Test.Object.<anonymous>.Test.assert (../../node_modules/supertest/lib/test.js:173:18)
      at Server.localAssert (../../node_modules/supertest/lib/test.js:131:12)

Test Suites: 1 failed, 2 passed, 3 total
Tests:       1 failed, 5 passed, 6 total
Snapshots:   0 total
Time:        5.602s
Ran all test suites.
[Nest] 20343   - 11/18/2019, 1:11:22 PM   [ExceptionHandler] Cannot read property 'getKeywordMaxBids' of undefined
TypeError: Cannot read property 'getKeywordMaxBids' of undefined
    at BidsValidator.<anonymous> (~/Projects/MyProject/src/modules/campaigns/main/validators/BidsValidator.ts:79:42)
    at Generator.next (<anonymous>)
    at ~/Projects/MyProject/src/modules/campaigns/main/validators/BidsValidator.ts:16:71
    at new Promise (<anonymous>)
    at Object.<anonymous>.__awaiter (~/Projects/MyProject/src/modules/campaigns/main/validators/BidsValidator.ts:12:12)
    at BidsValidator.validate (~/Projects/MyProject/src/modules/campaigns/main/validators/BidsValidator.ts:32:16)
    at ~/Projects/MyProject/src/validation/ValidationExecutor.ts:236:78
    at Array.forEach (<anonymous>)
    at ~/Projects/MyProject/src/validation/ValidationExecutor.ts:225:18
    at Array.forEach (<anonymous>)
    at ValidationExecutor.Object.<anonymous>.ValidationExecutor.customValidations (~/Projects/MyProject/src/validation/ValidationExecutor.ts:222:19)
    at ~/Projects/MyProject/src/validation/ValidationExecutor.ts:105:18
    at Array.forEach (<anonymous>)
    at ValidationExecutor.Object.<anonymous>.ValidationExecutor.execute (~/Projects/MyProject/src/validation/ValidationExecutor.ts:80:39)
    at Validator.Object.<anonymous>.Validator.coreValidate (~/Projects/MyProject/src/validation/Validator.ts:34:18)
    at Validator.Object.<anonymous>.Validator.validate (~/Projects/MyProject/src/validation/Validator.ts:59:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! MyProject@0.85.4 test:e2e: `jest --config ./test/e2e/jest-e2e.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the MyProject@0.85.4 test:e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/me/.npm/_logs/2019-11-18T12_11_22_884Z-debug.log
```

## Input Code
This is how my test looks like

```ts
beforeAll(async () => {
    const module = await Test.createTestingModule({
      imports: [AppModule, CampaignsModule],
    })
      .overrideProvider(CampaignsService)
      .useValue(campaignsService)
      .overrideProvider(BidsService)
      .useValue(bidsService)
      .overrideProvider(BidsValidator)
      .useValue(bidsValidator)
      .compile();

    app = module.createNestApplication();
    app.useGlobalPipes(new ValidationPipe());
    await app.init();
    campaignsService = app
      .select(CampaignsModule)
      .get<CampaignsService>(CampaignsService);
    bidsService = app.select(CampaignsModule).get<BidsService>(BidsService);
    bidsValidator = app
      .select(CampaignsModule)
      .get<BidsValidator>(BidsValidator);
});

it('(POST) to /campaigns/update should update campaign data', async () => {
    const updatedResultData: unknown = createdCampaignData;
    const updateData = updateCampaignData;
    const keywordMaximumBid: GetMaxBidsInterface[] = [
      {
        _id: 3,
        bid: 5,
      },
    ];
    
    jest
      .spyOn(campaignsService, 'validateCampaignProducts')
      .mockImplementation(async () => true);

    jest
      .spyOn(bidsService, 'getKeywordMaxBids')
      .mockImplementation(async () => keywordMaximumBid);

    jest.spyOn(bidsValidator, 'validate').mockImplementation(async () => true);

    jest
      .spyOn(campaignsService, 'update')
      .mockImplementation(async () => updatedResultData as Campaign);

    const response = await request(app.getHttpServer())
      .post('/campaigns/update')
      .send(updateData)
      .expect(201);

    const responseData = response.body;

    expect(responseData.success).toBeTruthy();
    expect(responseData).toHaveProperty('message');
    expect(typeof responseData.data).toBe('object');
});
```

## Expected behavior
As far as you can see I am trying to mock the custom validator and even the service that I am using in that validator, but I am still not able to make it working. I guess, I am expecting to mock the validator class while I am trying to test the controller method successfully as I am doing that for any other provider class.

Nest version: 6.8.0
 
For Tooling issues:
- Node version: 12.13.0
- Platform:  Linux

Others:
I am not really sure if this is really a bug within the the framework, but if it's not, then certainly, some guidance about such cases would be very helpful :)

**Comment by kamilmysliwiec** [comment]
Are you using `class-validator` custom validators?

**Comment by atanasovdragan** [comment]
Yes, I'm using `class-validator` custom validation class.

**Comment by kamilmysliwiec** [comment]
So in this case, you should rather ask this question in the class-validator repo - if there is a way to somehow mock validators from external files during tests.
