### ISSUE TITLE
GraphQL union types: UnhandledPromiseRejectionWarning / TypeError

### ISSUE THREAD

**Issue by stonymahony** [nestjs/nest#3440]
## Bug Report
GraphQL union types are not working as expected and as described in Apollo documentation.

## Current behavior
When I set up a simple resolver to query a user, it should return either a user or, in case of any erros, an defined error type.

But what I get is this:
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of undefined
    at C:\X\node_modules\type-graphql\dist\schema\schema-generator.js:65:129
    at Array.map (<anonymous>)
    at types (C:\X\node_modules\type-graphql\dist\schema\schema-generator.js:65:50)
    at resolveThunk (C:\X\node_modules\graphql\type\definition.js:438:40)
    at defineTypes (C:\X\node_modules\graphql\type\definition.js:837:15)
    at GraphQLUnionType.getTypes (C:\X\node_modules\graphql\type\definition.js:806:26)
    at typeMapReducer (C:\X\node_modules\graphql\type\schema.js:272:28)
    at typeMapReducer (C:\X\node_modules\graphql\type\schema.js:286:20)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (C:\X\node_modules\graphql\type\schema.js:145:28)
    at Function.generateFromMetadataSync (C:\X\node_modules\type-graphql\dist\schema\schema-generator.js:31:24)
    at Function.<anonymous> (C:\X\node_modules\type-graphql\dist\schema\schema-generator.js:16:33)
    at Generator.next (<anonymous>)
    at C:\X\node_modules\tslib\tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\X\node_modules\tslib\tslib.js:106:16)

## Input Code
**Resolver**

```ts
/**
   * Returns User for given ID.
   */
  @Query(() => UserResultGQL)
  @UseGuards(GqlAuthGuard)
  async getUser(@Args('id') id: string): Promise<typeof UserResultGQL> {
    return await this.usersService.getOne(id);
  }
```

*Service**
```ts
/**
   * Returns User for given ID.
   */
  async getOne(id: string): Promise<UserGQL | GenericErrorGQL> {
    try {
     return await this.userModel.findById(id).exec();
    } catch (e) {
      throw  new GenericErrorGQL(404, 'Ooooops', 'uniqueErrorId');
    }
  }
```

*Type definitions**
```ts
export class GenericErrorGQL {
  @Field()
  readonly status: number;
  @Field()
  readonly message: string;
  @Field()
  readonly errorId: string;

  constructor(status: number, message: string, errorId: string) {
    this.status = status;
    this.message = message;
    this.errorId = errorId;
  }
}

@ObjectType()
export class UserGQL {
  @Field(() => ID)
  readonly _id: string;

  @Field()
  readonly username: string;

  @Field()
  readonly email: string;
}

export const UserResultGQL = createUnionType({
  name: 'UserResultGQL',
  types: () => [UserGQL, GenericErrorGQL]
});
```

## Expected behavior
I expected Apollo to detect whether I was getting a UserGQL or a GenericErrorGQL back and working correctly.

## Possible Solution
After some research I suspect the error is that nest or the GraphQL module do not handle the union types correctly.

## Environment
"@nestjs/common": "^6.10.1",
"@nestjs/core": "^6.10.1",
"@nestjs/graphql": "^6.5.3",
"@nestjs/platform-fastify": "^6.10.1",
"apollo-server-fastify": "^2.9.5",
"graphql": "^14.5.8",
"graphql-tools": "^4.0.5",
"type-graphql": "^0.17.5"

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.
