### ISSUE TITLE
Validation Pipe not working with files when fastify adapter uses

### ISSUE THREAD

**Issue by Wizp** [nestjs/nest#3449]
## Current behavior
For file upload uses "fastify-file-upload" version "2.0.1".
When value in `ValidationPipe.transform` includes file object `plainToClass` function try to run `mv` function in transformation process. Because it differs from `/express-fileupload/lib/fileFactory.js` implementation it fail. 

Here is exception:
`(node:28208) UnhandledPromiseRejectionWarning: TypeError: path must be a string or Buffer
    at Object.fs.open (fs.js:650:11)
    at WriteStream.open (fs.js:2220:6)
    at new WriteStream (fs.js:2206:10)
    at Object.fs.createWriteStream (fs.js:2160:10)
    at saveBufferToFile (/<path>/node_modules/express-fileupload/lib/utilities.js:178:20)
    at /<path>/node_modules/express-fileupload/lib/fileFactory.js:33:5
    at new Promise (<anonymous>)
    at Object.mv (/<path>/node_modules/express-fileupload/lib/fileFactory.js:63:11)
    at _loop_1 (/<path>/node_modules/class-transformer/TransformOperationExecutor.js:146:47)
    at TransformOperationExecutor.transform (/<path>/node_modules/class-transformer/TransformOperationExecutor.js:260:17)
    at _loop_1 (/<path>/node_modules/class-transformer/TransformOperationExecutor.js:235:45)
    at TransformOperationExecutor.transform (/<path>/node_modules/class-transformer/TransformOperationExecutor.js:260:17)
    at ClassTransformer.plainToClass (/<path>/node_modules/class-transformer/ClassTransformer.js:17:25)
    at Object.plainToClass (/<path>/node_modules/class-transformer/index.js:20:29)
    at ValidationPipe.transform (/<path>/dist/modules/common/validation.pipe.js:25:44)
    at transforms.reduce (/<path>/node_modules/@nestjs/core/pipes/pipes-consumer.js:15:33)
    at <anonymous>`

## Input Code
```ts
import * as fileUpload from 'fastify-file-upload';
.
.
export async function bootstrap() {

  const fastifyAdapter = new FastifyAdapter();
  fastifyAdapter.register(fileUpload, {
    limits: { fileSize: 10 * 1024 * 1024 },
  });
.
.
```

## Expected behavior
Not fails while validation transform

## Possible Solution
For now I remove file object field from validation value, but it's crutch.

## Environment

<pre><code>
    "@nestjs/common": "6.8.2",
    "@nestjs/core": "6.8.2",
    "@nestjs/platform-fastify": "6.8.2",
    "class-transformer": "0.2.3",
    "class-validator": "0.10.0",
    "fastify-file-upload": "2.0.1",
 
For Tooling issues:
- Node version: v9.11.2
- Platform:  Ubuntu 18.04 lts

Others:
</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by Wizp** [comment]
https://github.com/Wizp/minimal-repository
