### ISSUE TITLE
Trouble using defaultStrategy with PassportModule

### ISSUE THREAD

**Issue by marceloclp** [nestjs/nest#3490]
## Bug Report
When using `PassportModule.register({ defaultStrategy: 'strategy' })`, removing the strategy name from `@UseGuards(AuthGuard)` doesn't work.

## Current behavior
Throws the following error:
```
[Nest] 20652   - 11/28/2019, 1:23:30 PM   [ExceptionsHandler] Cannot read property 'challenge' of undefined +2654ms
TypeError: Cannot read property 'challenge' of undefined
    at allFailed (D:\...\node_modules\passport\lib\middleware\authenticate.js:107:52)
    at attempt (D:\...\node_modules\passport\lib\middleware\authenticate.js:180:28)
    at authenticate (D:\...\node_modules\passport\lib\middleware\authenticate.js:362:7)
    at Promise (D:\...\node_modules\@nestjs\passport\dist\auth.guard.js:83:3)
    at new Promise (<anonymous>)
    at D:\...\node_modules\@nestjs\passport\dist\auth.guard.js:75:83
    at MixinAuthGuard.<anonymous> (D:\...\node_modules\@nestjs\passport\dist\auth.guard.js:47:36)
    at Generator.next (<anonymous>)
    at D:\...\node_modules\@nestjs\passport\dist\auth.guard.js:19:71
    at new Promise (<anonymous>)
```

## Input Code

```ts
// auth.module.ts
import { Module, HttpModule } from '@nestjs/common';
import { PassportModule } from '@nestjs/passport';
import AuthService from './auth.service';
import BearerStrategy from './strategies/bearer.strategy';
import UsersModule from '../users/users.module';

@Module({
  imports: [UsersModule, HttpModule, PassportModule.register({ defaultStrategy: 'bearer' })],
  providers: [AuthService, BearerStrategy],
  exports: [AuthService],
})
export default class AuthModule {}


// bearer.strategy.ts
import { Strategy } from 'passport-http-bearer';
import { PassportStrategy } from '@nestjs/passport';
import { Injectable, UnauthorizedException } from '@nestjs/common';
import { ObjectId } from 'mongodb';
import AuthService from '../auth.service';

@Injectable()
export default class BearerStrategy extends PassportStrategy(Strategy, 'bearer') {
  constructor(private readonly authService: AuthService) {
    super({ passReqToCallback: true });
  }

  async validate(req, token: string): Promise<any> {
    const bearerObject = await this.authService.validateBearerToken(token);

    if (!bearerObject.active) throw new UnauthorizedException();

    return { id: new ObjectId(bearerObject.sub) };
  }
}
```

## Expected behavior
When using `@UseGuards(AuthGuard())`, the BearerStrategy should be called.

## Environment

<pre><code>
Nest version: 6.8.4

 
For Tooling issues:
- Node version: 10.15.3  
- Platform:  Windows

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Add `PassportModule` to `exports`:
```
 exports: [AuthService, PassportModule],
```

**Comment by marceloclp** [comment]
Is there any particular reason to why is it required to export the `PassportModule`? Because it isn't done on the [docs here](https://docs.nestjs.com/techniques/authentication#default-strategy).

**Comment by kamilmysliwiec** [comment]
https://docs.nestjs.com/modules

**Comment by marceloclp** [comment]
Ok, got it. Maybe I can write a PR to update the default strategy example to include the export?
