### ISSUE TITLE
Attempting to cluster a nestjs application causes clusters to exit with a module not found error

### ISSUE THREAD

**Issue by bot101** [nestjs/nest#3547]
## Current behavior
Attempting to start a clustered Nestjs application causes all the created clusters as well as the master cluster to crash if the application has a helper class (DTO class in my case).

The application runs OK if clustering is disabled.

## Input Code

```ts
import * as cluster from 'cluster';
import * as os from 'os';
import { Logger } from '@nestjs/common';

if (cluster.isMaster) {
  const cpuCount = os.cpus().length;

  for (let i = 0; i < cpuCount; i += 1) {
    cluster.fork();
  }

  cluster.on( 'online', worker => {
    Logger.log( 'Worker ' + worker.process.pid + ' is online.' );
  });
  cluster.on( 'exit',  ({ process }, code, signal ) => {
    Logger.log( 'worker ' + process.pid + ' died.' );
  });
} else {
  async function bootstrap() {
    const app = await NestFactory.create(AppModule);
    app.enableCors({
      origin: ['(((http|https){1}:\/\/)?(www\.)?(web\.siteurl)\.com\/?){1}'],
    });
    app.enableCors();
    // app.use(express.static(join(__dirname, 'public')));
    // app.useGlobalFilters(new InternalServerErrorExceptionFilter());
    app.useGlobalPipes(new ValidationPipe());
    app.use(bodyParser.json({limit: '50mb'}));
    app.use(bodyParser.urlencoded({limit: '50mb', extended: true}));
    await app.listen(process.env.PORT || 3000); 
  }
  bootstrap();
}

//###########DTO Class################
import { IsEmail, IsNotEmpty, IsString, IsNumber, IsArray, ValidateNested } from 'class-validator';
import { Type } from 'class-transformer';
// tslint:disable-next-line: max-classes-per-file
export class Pie {
  @IsString()
  iconUrl?: string;
  @IsString()
  @IsNotEmpty()
  title: string;
  @IsNumber()
  @IsNotEmpty()
  ratio: number;
  @IsString()
  @IsNotEmpty()
  color: string;
}

// tslint:disable-next-line: max-classes-per-file
export class Column {
  @IsNumber()
  @IsNotEmpty()
  inflow: number;
  @IsNumber()
  @IsNotEmpty()
  outflow: number;
  @IsNumber()
  @IsNotEmpty()
  total: number;
}

// tslint:disable-next-line: max-classes-per-file
export class ChartPayloadDTO {

  @IsNotEmpty()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => Pie)
  pie: Pie[];

  @IsNotEmpty()
  @ValidateNested({ each: true })
  @Type(() => Column)
  column: Column;
}


//#############Error Message #####################
Error: Cannot find module 'src/dto/chartpayload.dto'
Require stack:
- C:\Users\PC\desktop\project\src\controllers\mail-grapher\mail-grapher.controller.ts
- C:\Users\PC\desktop\project\src\app.module.ts
- C:\Users\PC\desktop\project\src\main.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\PC\desktop\project\src\controllers\mail-grapher\mail-grapher.controller.ts:7:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Module.m._compile (C:\Users\PC\Desktop\project\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\PC\Desktop\kuda-subscribe\node_modules\ts-node\src\index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\PC\desktop\project\src\app.module.ts:13:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Module.m._compile (C:\Users\PC\Desktop\project\node_modules\ts-node\src\index.ts:439:23)
```

## Expected behavior
Application is expected to start with clusters running successfully

## Environment

<pre><code>
Nest version: 6.0.0

 
For Tooling issues:
- Node version: 12.13.1
- Platform:   Windows

</code></pre>

**Comment by kamilmysliwiec** [comment]
> Cannot find module 'src/dto/chartpayload.dto'

You shouldn't use absolute imports.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by bot101** [comment]
Thanks, will post to discord right away

> Cannot find module 'src/dto/chartpayload.dto'
Will fix and try again.
