### ISSUE TITLE
app.select is broken after upgrade to 6.10.6

### ISSUE THREAD

**Issue by gibsonjoshua55** [nestjs/nest#3550]
## Regression
After upgrading from 6.10.5 to 6.10.6 you can no longer select a module from from the app context.

## Potential Commit/PR that introduced the regression**
Introduced by some commit in tag [6.10.6](https://github.com/nestjs/nest/releases/tag/v6.10.6)

## Describe the regression
When selecting a module from an app context, the following error occurs:
```
[Nest] 26113   - 12/05/2019, 10:09:06 AM   [ExceptionHandler] Nest could not select the given module (it does not exist in current context) +6ms
Error: Nest could not select the given module (it does not exist in current context)
    at NestApplication.select (/Users/joshgibson/maestro/projects/six-ten-six-example/node_modules/@nestjs/core/nest-application-context.js:39:19)
    at /Users/joshgibson/maestro/projects/six-ten-six-example/node_modules/@nestjs/core/nest-factory.js:112:40
    at Function.run (/Users/joshgibson/maestro/projects/six-ten-six-example/node_modules/@nestjs/core/errors/exceptions-zone.js:8:13)
    at Proxy.<anonymous> (/Users/joshgibson/maestro/projects/six-ten-six-example/node_modules/@nestjs/core/nest-factory.js:111:46)
    at bootstrap (/Users/joshgibson/maestro/projects/six-ten-six-example/src/main.ts:14:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

## Input Code
```ts
import { Module } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';

@Module({})
export class TestModule {}

@Module({
  imports: [TestModule],
})
export class AppModule {}

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.select(TestModule);
  await app.listen(3000);
}
bootstrap();
```

## Expected behavior/code
This code should bootstrap correctly, but instead it results in the above error.

## Environment
<pre><code>
Nest version: 6.10.5 -> 6.10.6

For Tooling issues:
- Node version: v12.8.1
- Platform:  Mac

</code></pre>

**Comment by kamilmysliwiec** [comment]
Fixed in 6.10.7. Thanks for reporting!
