### ISSUE TITLE
Cannot convert a Symbol value to a string when Symbol dependency is unmet

### ISSUE THREAD

**Issue by jacob87o2** [nestjs/nest#3649]
## Current behavior
```
[Nest] 5722   - 12/16/2019, 11:09:26 AM   [ExceptionHandler] Cannot convert a Symbol value to a string +1ms
TypeError: Cannot convert a Symbol value to a string
    at Object.exports.UNKNOWN_DEPENDENCIES_MESSAGE
...
```

## Input Code
```ts
const SOME_DEPENDENCY = Symbol('SOME_DEPENDENCY');
@Injectable()
export class SomeProvider {
  @Inject(SOME_DEPENDENCY)
  private someDependency;
}
```

## Expected behavior
```
[Nest] 6309   - 12/16/2019, 11:49:48 AM   [ExceptionHandler] Nest can't resolve dependencies of the SomeProvider. Please make sure that the "someDependency" property is available in the current context.

Potential solutions:
- If Symbol(SOME_DEPENDENCY) is a provider, is it part of the current SomeModule?
- If Symbol(SOME_DEPENDENCY) is exported from a separate @Module, is that module imported within SomeModule?
  @Module({
    imports: [ /* the Module containing Symbol(SOME_DEPENDENCY) */ ]
  })
```

## Possible Solution
If dependency is defined with a Symbol, `toString()` should be called, when constructing 'Unknown Dependencies' error message.

Seems there already was a similar problem here: 
https://github.com/nestjs/nest/issues/1551

**Edit: I created a PR with possible solution, but it needs to be reviewed.**
https://github.com/nestjs/nest/pull/3653

## Environment

<pre><code>
Nest version: 6.7.2
 
For Tooling issues:
- Node version: 10.16.3
- Platform:  macOS Catalina

Others:
YARN Version: 1.15.2
</code></pre>

**Comment by idanberman** [comment]
For me it happen only when i'm adding the controller to the module (even if the controller is empty with no dependencies).

`
@Module({
  imports: [],
  providers: [VendorsService],
  controllers: [VendorsController],
})
export class VendorsModule {}
`

`

@Controller(`vendors`)
export class VendorsController {
  constructor(
    @Inject()
    private readonly vendorsService: VendorsService,
  ) {}
  @Get()
  async getFind(): Promise<SuccessResponse<Vendor[]>> {
    return await this.vendorsService.find();
  }
}
`

or same behavior 
`
@Controller(`vendors`)
export class VendorsController {
  // constructor(
  //   @Inject()
  //   private readonly vendorsService: VendorsService,
  // ) {}
  // @Get()
  // async getFind(): Promise<SuccessResponse<Vendor[]>> {
  //   return await this.vendorsService.find();
  // }
}

`[Nest] 13494   - 12/19/2019, 2:27:11 AM   [ExceptionHandler] Cannot convert a Symbol value to a string +0ms
TypeError: Cannot convert a Symbol value to a string
    at Object.exports.UNKNOWN_DEPENDENCIES_MESSAGE (/home/idan/project-runner-backend/node_modules/@nestjs/core/errors/messages.js:36:8)
    at new UnknownDependenciesException (/home/idan/project-runner-backend/node_modules/@nestjs/core/errors/exceptions/unknown-dependencies.exception.js:7:26)
    at Injector.lookupComponentInParentModules (/home/idan/project-runner-backend/node_modules/@nestjs/core/injector/injector.js:190:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Injector.resolveComponentInstance (/home/idan/project-runner-backend/node_modules/@nestjs/core/injector/injector.js:146:33)
    at async resolveParam (/home/idan/project-runner-backend/node_modules/@nestjs/core/injector/injector.js:100:38)
    at async Promise.all (index 0)
    at async Injector.resolveConstructorParams (/home/idan/project-runner-backend/node_modules/@nestjs/core/injector/injector.js:115:27)
    at async Injector.loadInstance (/home/idan/project-runner-backend/node_modules/@nestjs/core/injector/injector.js:79:9)
    at async Injector.loadProvider (/home/idan/project-runner-backend/node_modules/@nestjs/core/injector/injector.js:36:9)`

**Comment by kamilmysliwiec** [comment]
6.10.13
