### ISSUE TITLE
 send file from microservice

### ISSUE THREAD

**Issue by Mauricio320** [nestjs/nest#3800]
from the main api making connection to my microservice to request a file
Controller
 ```
@Get(':filePath')
  async file(@Param('filePath') path) {
		return await this.uploadService.getFile(path)
  }
```

Service
`	getFile(filePaht: string) {
		return this.client.send('filePath', filePaht)
	}`

from the microservice
controller 
` @MessagePattern('filePath')
  async getFile(@Body() path: any, @Res() res) {
    return res.sendFile(path, { root: 'uploads' });
  }`

ERROR
`TypeError: Cannot read property 'sendFile' of null
[0]     at AppController.<anonymous> (C:\Users\btria\OneDrive\Documents\proyectos\MICROSERVICIOS\upload\dist\app.controller.js:44:24)
[0]     at Generator.next (<anonymous>)
[0]     at C:\Users\btria\OneDrive\Documents\proyectos\MICROSERVICIOS\upload\dist\app.controller.js:19:71
[0]     at new Promise (<anonymous>)
[0]     at __awaiter (C:\Users\btria\OneDrive\Documents\proyectos\MICROSERVICIOS\upload\dist\app.controller.js:15:12)
[0]     at AppController.getFile (C:\Users\btria\OneDrive\Documents\proyectos\MICROSERVICIOS\upload\dist\app.controller.js:43:16)
[0]     at C:\Users\btria\OneDrive\Documents\proyectos\MICROSERVICIOS\upload\node_modules\@nestjs\microservices\context\rpc-context-creator.js:43:33
[0]     at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
