### ISSUE TITLE
Pipe file chunk over http response results in a TypeError

### ISSUE THREAD

**Issue by mehdikwa** [nestjs/nest#3835]
## Bug Report
I'm trying pipe contents of a file over http but I'm getting an error at api call. My nest app is wrapped  on Fastify adapter.

The app fails with stacktrace
```
_stream_readable.js:638
  dest.on('unpipe', onunpipe);
       ^

TypeError: dest.on is not a function
    at ReadStream.Readable.pipe (_stream_readable.js:638:8)
    at ReadStream.readStream.on (/Users/medi/Documents/wkdir/mygit/site-map-api/dist/server.js:9017:32)
    at ReadStream.emit (events.js:189:13)
    at lazyFs.open (internal/fs/streams.js:120:10)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
```

## Current behavior
Open a file for streaming and pipe result over http response, using either **FastifyReply** or express **Response**, it fails with error **TypeError: dest.on is not a function** and file is not streamed. 

## Input Code

```controller.ts
@Controller('api/v1/site-map')
@ApiTags('❤ API > Contents site-map')
export class SitemapExportController {
  constructor() {}

  @Get()
  @ApiBearerAuth()
  @HttpCode(HttpStatus.OK)
  @ApiOkResponse({description: http.STATUS_CODES[200]})
  @ApiUnauthorizedResponse({description: http.STATUS_CODES[401]})
  @ApiInternalServerErrorResponse({description: http.STATUS_CODES[500]})
  async loadContentSupportPublications(@Res() response: FastifyReply<unknown>): Promise<void> {
    const readStream = fs.createReadStream('./dist/test');
    readStream.on('open', () => {
      readStream.pipe(response);
    });

    readStream.on('error', (err: Error) => {
      console.log(err);
    });
}
```

## Expected behavior
Be able to pipe file chunk over response

## Environment

```
    "@nestjs/common": "6.10.12",
    "@nestjs/core": "6.10.12",
    "@nestjs/platform-fastify": "6.10.12",
    "@nestjs/swagger": "4.0.9",
    "class-transformer": "0.2.3",
    "class-validator": "0.11.0",
    "env-var": "5.2.0",
    "fastify": "2.11.0",
    "fastify-swagger": "2.5.0",
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
