### ISSUE TITLE
Errors being raised when validation rules return values

### ISSUE THREAD

**Issue by webnoob** [nestjs/nest#3844]
## Current behavior
I'm using `class-validator` to validate my DTO's. If I use something like `@MinLength(4)` in a field then the validation error is returned to the client but I'm also getting this in the console:

```
(node:2472) UnhandledPromiseRejectionWarning: Error: Error encoding trace: root.child.error.message: string expected
    at EngineReportingAgent.<anonymous> (C:\SourceCode\myProject\api\node_modules\apollo-engine-reporting\dist\agent.js:76:23)
    at Generator.next (<anonymous>)
    at C:\SourceCode\myProject\api\node_modules\apollo-engine-reporting\dist\agent.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\SourceCode\myProject\api\node_modules\apollo-engine-reporting\dist\agent.js:4:12)
    at EngineReportingAgent.addTrace (C:\SourceCode\myProject\api\node_modules\apollo-engine-reporting\dist\agent.js:64:16)
    at C:\SourceCode\myProject\api\node_modules\apollo-engine-reporting\dist\extension.js:64:18
    at C:\SourceCode\myProject\api\node_modules\graphql-extensions\dist\index.js:79:21
    at Object.<anonymous> (C:\SourceCode\myProject\api\node_modules\apollo-server-core\dist\requestPipeline.js:198:13)
    at Generator.next (<anonymous>)
(node:2472) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2472) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Input Code

```ts
// Resolver
@Mutation(returns => PenName)
  @UseGuards(new RoleAuthGuard(AppRolePermissions.CreateBooks))
  createPenName (@Args() dto: PenNameCrudDto): Promise<PenName> {
    return this.penNameService.create(dto)
  }

// DTO:
@ArgsType()
export default class PenNameCrudDto {
  @Field(type => Int, { nullable: true })
  id?: number

  @Field(type => String, { nullable: true })
  @MaxLength(200)
  @MinLength(4)
  name?: string

  @Field({ nullable: true })
  bio?: string

  @Field({ nullable: true })
  image?: string

  @Field({ nullable: true })
  facebookLink?: string

  @Field({ nullable: true })
  bookbubLink?: string

  @Field({ nullable: true })
  twitterLink?: string
}
```

## Expected behavior
No error in the console.

## Possible Solution
Not a solution but more information, digging into the `apollo-egine-report` lib, I added a console log to get more info about this error and have this:

```
[{"responseName":"createPenName","type":"PenName!","startTime":"3829401","endTime":"33366701","error":[{"message":{"statusCode":400,"error":"Bad Request","message":[{"target":{"name":""},"value":"","property":"name","children":[],"constraints":{"minLength":"name must be longer than or equal to 4 characters"}}]},"location":[{"line":2,"column":3}],"json":"{\"message\":{\"statusCode\":400,\"error\":\"Bad Request\",\"message\":[{\"target\":{\"name\":\"\"},\"value\":\"\",\"property\":\"name\",\"children\":[],\"constraints\":{\"minLength\":\"name must be longer than or equal to 4 characters\"}}]},\"locations\":[{\"line\":2,\"column\":3}],\"path\":[\"createPenName\"]}"}],"parentType":"Mutation"}]
```

I see this is an object and the console error is reporting it's expecting a string.

## Environment

<pre><code>
Nest version: 6.10.14

 
For Tooling issues:
- Node version: 12
- Platform:  Window 10

Others:

</code></pre>

**Comment by webnoob** [comment]
On reflection, I wonder if the underlying cause of this issue is me doing
```ts
@Field(type => String, { nullable: true })
  @MaxLength(200)
  @MinLength(4)
  name?: string
```
Allowing it to be null but also having a `MinLength(4)`

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
