### ISSUE TITLE
Nestjs unable to resolve dependency

### ISSUE THREAD

**Issue by bhushan629** [nestjs/nest#3861]
## Current behavior
I am getting below issue while executing test case

*Nest can't resolve dependencies of the AWSSecretManagerStringConfigTest (?). Please make sure that the argument testString at index [0] is available in the _RootTestModule context.*

I am using all latest version of nestjs packages

**Error Logs:**

<br>
**AWSModule (SecretsManager Service) › Should have plain string secret**

```
all-test         | 
all-test         |     Nest can't resolve dependencies of the AWSSecretManagerStringConfigTest (?). Please make sure that the argument testString at index [0] is available in the _RootTestModule context.
all-test         | 
all-test         |     Potential solutions:
all-test         |     - If testString is a provider, is it part of the current _RootTestModule?
all-test         |     - If testString is exported from a separate @Module, is that module imported within _RootTestModule?
all-test         |       @Module({
all-test         |         imports: [ /* the Module containing testString */ ]
all-test         |       })
all-test         | 
all-test         |       at Injector.lookupComponentInParentModules (node_modules/@nestjs/core/injector/injector.js:190:19)
all-test         |       at Injector.resolveComponentInstance (node_modules/@nestjs/core/injector/injector.js:146:33)
all-test         |       at resolveParam (node_modules/@nestjs/core/injector/injector.js:100:38)
all-test         |           at async Promise.all (index 0)
all-test         |       at Injector.resolveConstructorParams (node_modules/@nestjs/core/injector/injector.js:115:27)
all-test         |       at Injector.loadInstance (node_modules/@nestjs/core/injector/injector.js:79:9)
all-test         |       at Injector.loadProvider (node_modules/@nestjs/core/injector/injector.js:36:9)
all-test         |           at async Promise.all (index 3)
all-test         |       at InstanceLoader.createInstancesOfProviders (node_modules/@nestjs/core/injector/instance-loader.js:41:9)
all-test         |       at node_modules/@nestjs/core/injector/instance-loader.js:27:13
```
## Input Code

GITHUB LINK: https://github.com/bhushan629/aws

<br>

**TestCases:**
<br>
<br>
**THIS TEST CASE IS WORKING CORRECTLY FOR ME**
```ts
test('Shold have plain string secret', async () => {
    const response: AWS.SecretsManager.GetSecretValueResponse = {
      SecretString: 'hello',
    };

    AWSMock.setSDKInstance(AWS);
    AWSMock.mock('SecretsManager', 'getSecretValue', Promise.resolve(response));
    const module: TestingModule = await Test.createTestingModule({
      imports: [
        AWSModule.forServices([{ serviceName: 'secrets-manager' }]),
        AWSModule.forServicesFeature([
          { serviceName: 'secrets-manager', confiiguration: [{ secretName: 'testString', secretType: 'plain' }] },
        ]),
      ],
    }).compile();
    const plainString = module.get('testString');
    expect(plainString).toEqual('hello');
    AWSMock.restore();
  });
```
<br>

but when i tried to execute below test case its giving me error
```ts
test('Should have plain string secret', async () => {
    const response: AWS.SecretsManager.GetSecretValueResponse = {
      SecretString: 'hello',
    };

    AWSMock.setSDKInstance(AWS);
    AWSMock.mock('SecretsManager', 'getSecretValue', Promise.resolve(response));
    const module: TestingModule = await Test.createTestingModule({
      imports: [
        AWSModule.forServices([{ serviceName: 'secrets-manager' }]),
        AWSModule.forServicesFeature([
          { serviceName: 'secrets-manager', confiiguration: [{ secretName: 'testString', secretType: 'plain' }] },
        ]),
      ],
      providers: [AWSSecretManagerStringConfigTest],
    }).compile();
    const awsSecretManagerStringConfigTest = module.get(AWSSecretManagerStringConfigTest);
    expect(awsSecretManagerStringConfigTest).toBeInstanceOf(AWSSecretManagerStringConfigTest);
    expect(awsSecretManagerStringConfigTest.getSecret()).toEqual('hello');
    AWSMock.restore();
  });
```
<br>

**AWSSecretManagerStringConfigTest.ts**
```ts
import { Injectable, Inject } from '@nestjs/common';

@Injectable()
export class AWSSecretManagerStringConfigTest {
  constructor(@Inject('testString') private readonly secret: string) {}

  getSecret(): string {
    return this.secret;
  }
}

```
## Environment

<pre><code>
Nest version: 6.10.14

 
For Tooling issues:
- Node version: 12.14.0
- Platform: Mac

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
