### ISSUE TITLE
Unable to extend tsconfig.json from an NPM package

### ISSUE THREAD

**Issue by joncursi** [nestjs/nest#3998]
I am trying to extend my root `tsconfig.json` from a shared configuration inside an npm module:

```json
{
  ...
  "extends": "./node_modules/@joncursi/eslint-config/tsconfig.json"
  ...
}
```

However, this prevents nest from properly starting the app. `nest start` results in:

```shell
➜  nest-base git:(master) ✗ npm run start    

> @joncursi/nest-base@1.0.0 start /Users/joncursi/Sites/joncursi/nest-base
> nest start

internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module '/Users/joncursi/Sites/joncursi/nest-base/dist/main'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

I can get around this by changing the `extends` declaration to:

```json
{
  ...
  "extends": "node_modules/@joncursi/eslint-config/tsconfig.json"
  ...
}
```

(without the `./` in front), however this in-turn breaks ESLint:

```shell
0:0  error  Parsing error: File 'node_modules/@joncursi/eslint-config/tsconfig.json' not found
```

It seems I can't have my cake and eat it too, meaning I can't have `nest` and `eslint` using the same `tsconfig.json` that's extended from an npm package.

I'm using Nest `v6.11.5`.

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.
