### ISSUE TITLE
Exception Raised in microservice pattern name during  Debugging 

### ISSUE THREAD

**Issue by techaks** [nestjs/nest#4066]
> Getting Exception in Microservice Event Name "check_shipping_charge"

>  "@nest-middlewares/compression": "^6.0.0",
>     "@nest-middlewares/cors": "^6.0.1",
>     "@nest-middlewares/helmet": "^6.0.0",
>     "@nest-middlewares/morgan": "^6.0.0",
>     "@nestjs/common": "^6.8.3",
>     "@nestjs/config": "^0.0.8",
>     "@nestjs/core": "^6.8.3",
>     "@nestjs/jwt": "^6.1.1",
>     "@nestjs/microservices": "^6.10.14",
>     "@nestjs/mongoose": "^6.1.2",
>     "@nestjs/passport": "^6.1.0",
>     "@nestjs/platform-express": "^6.11.6",
>     "@nestjs/platform-socket.io": "^6.10.13",
>     "@nestjs/swagger": "^3.1.0",
>     "@nestjs/websockets": "^6.10.13",
> 

syntaxError: Unexpected token d in JSON at position 0
    at JSON.parse (<anonymous>)
    at ServerTCP.getRouteFromPattern (/Users/akashgupta/Projects/voopik-enterprise/node_modules/@nestjs/microservices/server/server.js:107:33)
    at ServerTCP.getHandlerByPattern (/Users/akashgupta/Projects/voopik-enterprise/node_modules/@nestjs/microservices/server/server.js:26:28)
    at ServerTCP.handleMessage (/Users/akashgupta/Projects/voopik-enterprise/node_modules/@nestjs/microservices/server/server-tcp.js:42:30)
    at Socket.<anonymous> (/Users/akashgupta/Projects/voopik-enterprise/node_modules/@nestjs/microservices/server/server-tcp.js:30:70)
    at Socket.emit (events.js:210:5)
    at JsonSocket.handleMessage (/Users/akashgupta/Projects/voopik-enterprise/node_modules/@nestjs/microservices/helpers/json-socket.js:102:21)
    at JsonSocket.handleData (/Users/akashgupta/Projects/voopik-enterprise/node_modules/@nestjs/microservices/helpers/json-socket.js:81:22)
    at JsonSocket.onData (/Users/akashgupta/Projects/voopik-enterprise/node_modules/@nestjs/microservices/helpers/json-socket.js:52:18)
    at Socket.emit (events.js:210:5)

![Screenshot 2020-02-14 at 12 11 49 PM](https://user-images.githubusercontent.com/11151000/74507772-6844a400-4f23-11ea-8f65-4891e410f58f.png)

**Comment by kamilmysliwiec** [comment]
To communicate with NestJS from external services, your messages have to fulfill a specific interface. You can read more here https://trilon.io/blog/using-nestjs-microservices-with-laravel
