### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Gowtham029** [nestjs/nest#4183]
## Bug Report
Hi All,

When I try to retrieve image from one URL and sending the response. I am getting the following error.

**controller.file.ts**
 ````
@Get("/:id/photo")
  @Header("Content-Type", "image/png")
  @ApiResponse({ status: HttpStatus.OK, description: "Get user photo" })
  @ApiResponse({ status: HttpStatus.NOT_FOUND, description: "Not found" })
  @ApiParam({ name: "id" })
  async getUserPhoto(@Param() parameter, @Res() response): Promise<any> {
    const result = await this.userService.getUserPhoto(parameter.id);
    return result.data.pipe(response);
  }
````
**service.file.ts**
````
 async getUserPhoto(userId: string): Promise<AxiosResponse> {
    try {
      const URL = "https://example.com";
      return await this.httpService.axiosRef({
        url: `${URL }/photo/{userId}`,
        method: "GET",
        responseType: "stream",
      });
    } catch (error) {
      throw new HttpException("Image Not Found", HttpStatus.NOT_FOUND);
    }
  }
````
This code was worked with 
```@nest/common - 6.8.3```

I updated to ``` @nest/common - 6.11.1 ``` and getting the following error.

**Error**
````
RangeError: Maximum call stack size exceeded at baseClone (path\node_modules\lodash.clonedeep\index.js:841:19)
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at write_ (_http_outgoing.js:632:17)
    at ServerResponse.write (_http_outgoing.js:624:15)
    at IncomingMessage.ondata (_stream_readable.js:753:22)
    at IncomingMessage.emit (events.js:219:5)
    at IncomingMessage.EventEmitter.emit (domain.js:482:12)
    at IncomingMessage.Readable.read (_stream_readable.js:553:10)
    at flow (_stream_readable.js:1022:34)
    at resume_ (_stream_readable.js:1003:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
````

Please help me to solve this.

Thanks.

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by kowthalganesh** [comment]
@Get("/:id/photo")
 @Header("Content-Type", "image/png")
 @ApiResponse({ status: HttpStatus.OK, description: "Get user photo" })
 @ApiResponse({ status: HttpStatus.NOT_FOUND, description: "Not found" })
 @ApiParam({ name: "id" })
 async getUserPhoto(@Param() parameter, @Res() response): Promise<any> {
   const result = await this.userService.getUserPhoto(parameter.id);
   result.data.pipe(response);
        **return new Promise((resolve, reject) => {
            response.on("finish", resolve);
            response.on("error", reject);
        });**
 }

This will solve the problem

**Comment by kowthalganesh** [comment]
https://stackoverflow.com/questions/56286086/download-image-from-url-by-nestjs

**Comment by Gowtham029** [comment]
@kowthalganesh It works well.

Thanks.

**Comment by btd1337** [comment]
`Nest.js version: 7.6.15`

```ts
// src/app.module

@Module({
    imports: [WinstonModule.forRoot(winstonConfig) ]
})
```

```ts
// winston.config
export const winstonConfig: WinstonModuleOptions = {
	levels: winston.config.npm.levels,
	level: 'verbose',
	transports: [
		new winston.transports.Console({
			format: winston.format.combine(
				winston.format.timestamp(),
				nestWinstonModuleUtilities.format.nestLike(),
			),
		}),
		new winston.transports.File({
			level: 'verbose',
			filename: 'application.log',
			dirname: 'logs',
		}),
	],
};
```
---

If `winstonConfig` is inside `src/config` this error occur:

```
[Nest] 96   - 04/03/2021, 4:18:41 AM   [ExceptionHandler] Maximum call stack size exceeded +2152ms
RangeError: Maximum call stack size exceeded
    at decorated.bindCustomHelpers (/home/node/app/node_modules/nestjs-config/dist/module/config.service.js:237:22)
    at /home/node/app/node_modules/nestjs-config/dist/module/config.service.js:246:46
    at Array.reduce (<anonymous>)
    at decorated.bindCustomHelpers (/home/node/app/node_modules/nestjs-config/dist/module/config.service.js:238:36)
    at /home/node/app/node_modules/nestjs-config/dist/module/config.service.js:246:46
    at Array.reduce (<anonymous>)
    at decorated.bindCustomHelpers (/home/node/app/node_modules/nestjs-config/dist/module/config.service.js:238:36)
    at /home/node/app/node_modules/nestjs-config/dist/module/config.service.js:246:46
    at Array.reduce (<anonymous>)
    at decorated.bindCustomHelpers (/home/node/app/node_modules/nestjs-config/dist/module/config.service.js:238:36)
[nodemon] app crashed - waiting for file changes before starting...
```

But if `winstonConfig` is inside any other folder in `src` the project is compiled normally.

**Comment by jmcdo29** [comment]
@btd1337 that looks to be related to `nestjs-config` which is a community module, not managed by the core team
