### ISSUE TITLE
(ServeStatic Module) TypeError: Cannot read property 'getInstance' of null

### ISSUE THREAD

**Issue by abhishek6262** [nestjs/nest#4196]
## Bug Report
Recently, I tried to implement the Serve Static module and I received a warning in the console as given below.

```bash
(node:277) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getInstance' of null
web_1    |     at ExpressLoader.register (/usr/src/app/node_modules/@nestjs/serve-static/dist/loaders/express.loader.js:17:33)
web_1    |     at ServeStaticModule.<anonymous> (/usr/src/app/node_modules/@nestjs/serve-static/dist/serve-static.module.js:87:25)
web_1    |     at Generator.next (<anonymous>)
web_1    |     at /usr/src/app/node_modules/@nestjs/serve-static/dist/serve-static.module.js:20:71
web_1    |     at new Promise (<anonymous>)
web_1    |     at __awaiter (/usr/src/app/node_modules/@nestjs/serve-static/dist/serve-static.module.js:16:12)
web_1    |     at ServeStaticModule.onModuleInit (/usr/src/app/node_modules/@nestjs/serve-static/dist/serve-static.module.js:85:16)
web_1    |     at Object.callModuleInitHook (/usr/src/app/node_modules/@nestjs/core/hooks/on-module-init.hook.js:50:35)
web_1    |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
web_1    |     at async NestMicroservice.callInitHook (/usr/src/app/node_modules/@nestjs/core/nest-application-context.js:153:13)
web_1    |     at async NestMicroservice.registerModules (/usr/src/app/node_modules/@nestjs/microservices/nest-microservice.js:44:13)
web_1    | (node:277) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
web_1    | (node:277) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Current behaviour

Giving up warning in the console.

## Input Code

```ts
import { ServeStaticModule } from '@nestjs/serve-static';

@Module({
  imports: [
    ServeStaticModule.forRoot({   // Serves static files available in the public directory.
      exclude: [
        '/api*',
        '/docs*',
      ],
      renderPath: join(__dirname, '..', 'public'),
      rootPath: join(__dirname, '..', 'public'),
      serveRoot: '/public',
      serveStaticOptions: {
        cacheControl: true,
      },
    }),
  ],
})
export class AppModule { }
```

## Expected behaviour
The warning should be handled.

## Environment

<pre><code>
Nest version: 6.14.2
 
For Tooling issues:
- Node version: v13.6.0
- Platform:  Windows 10
</code></pre>

**Comment by kamilmysliwiec** [comment]
Update the `@nestjs/core` and the `@nestjs/platform-express` to the latest versions.

**Comment by abhishek6262** [comment]
I have updated the packages @kamilmysliwiec. But still, the error persists.

**Comment by shirshak55** [comment]
@abhishek6262 for static asset i would recommend using nginx directly tho. Single threaded js may not scale properly?

**Comment by abhishek6262** [comment]
This doesn't seem to be the issue of NGINX @shirshak55.

**Comment by maximgeerinck** [comment]
Same issue, running with platform-express and core on version 7.0.7
