### ISSUE TITLE
How to validate nested request object using DTOS ?

### ISSUE THREAD

**Issue by fuserabin** [nestjs/nest#4327]
Input format:
```
{
	"location": {
		"locationName": "something 3",
		"locationDescription": "asdfsdf ",
		"airportCode": "asdfs",
		"locationCode": "airportcode",
		"locationType": "INTERNATIONAL"
	},
	"address": {
		"country": 2,
		"city": 2,
		"state": 2,
		"lat": 2.2,
		"lng": 3.2
	}
}
```

My location.dto.ts

```
import { IsNotEmpty, IsInt, IsString, IsOptional, IsNumber, IsEnum, ValidateNested } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

import { QueryDto } from 'shared/dto/query.dto';

import { LocationTypeEnum } from 'location/interfaces';
import { Type } from 'class-transformer';
import { CreateAddressDTO } from 'address/dtos';

export class CreateLocationDTO {
  @IsNotEmpty()
  @IsString()
  @ApiPropertyOptional()
  locationName: string;

  @IsOptional()
  @IsNotEmpty()
  @IsString()
  @ApiPropertyOptional()
  locationDescription: string;

  @IsOptional()
  @IsString()
  @ApiPropertyOptional()
  airportCode: string;

  @IsNotEmpty()
  @IsString()
  @ApiProperty()
  locationCode: string;

  @IsOptional()
  @IsString()
  @ApiPropertyOptional()
  iataCode: string;

  @IsNotEmpty()
  @IsEnum(LocationTypeEnum, { message: 'Location type must be INTERNATIONAL or DOMESTIC' })
  @ApiProperty()
  locationType: string;
}

export class CreateLocatinoInputDTO {
  @IsNotEmptyObject()
  @ValidateNested()
  @Type(() => CreateLocationDTO)
  readonly location: CreateLocationDTO;
  
  @IsNotEmptyObject()
  @ValidateNested()
  @Type(() => CreateAddressDTO)
  readonly address: CreateAddressDTO;
}
```

My Location Controller
```
@Post()
  @UsePipes(
    new ValidationPipe({
      whitelist: true,
      transform: true
    })
  )
  @ApiOperation({ summary: 'Create new location' })
  @ApiCreatedResponse({
    description: 'The record has been successfully created.',
    status: 201,
    type: CreateLocatinoInputDTO
  })
  @ApiResponse({ status: 403, description: 'Forbidden request' })
  async create(@Body() locationData: CreateLocatinoInputDTO) {
    return locationData;
  }
```

Isn't this suppose to validate each keys from input? But when I remove one key it's showing following error

```
(node:30552) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at exception.message.message.map (/home/devrabin/Documents/projects/fusemachines/dist/shared/http-exception.filter.js:25:36)
    at Array.map (<anonymous>)
    at HttpExceptionFilter.catch (/home/devrabin/Documents/projects/fusemachines/dist/shared/http-exception.filter.js:24:48)
    at ExceptionsHandler.invokeCustomFilters (/home/devrabin/Documents/projects/fusemachines/node_modules/@nestjs/core/exceptions/exceptions-handler.js:31:26)
    at ExceptionsHandler.next (/home/devrabin/Documents/projects/fusemachines/node_modules/@nestjs/core/exceptions/exceptions-handler.js:12:18)
    at /home/devrabin/Documents/projects/fusemachines/node_modules/@nestjs/core/router/router-proxy.js:12:35
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:30552) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30552) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

I am confused !!

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
