### ISSUE TITLE
I'm using default gateway and log this error in terminal!

### ISSUE THREAD

**Issue by msttamuk** [nestjs/nest#4336]
(node:20453) UnhandledPromiseRejectionWarning: TypeError: this.contextUtils.getContextFactory is not a function
    at WsContextCreator.getMetadata (/home/mostafa/Workspace/BehineGostar/Tamuk/mobile/node_modules/@nestjs/websockets/context/ws-context-creator.js:73:50)
    at WsContextCreator.create (/home/mostafa/Workspace/BehineGostar/Tamuk/mobile/node_modules/@nestjs/websockets/context/ws-context-creator.js:28:68)
    at /home/mostafa/Workspace/BehineGostar/Tamuk/mobile/node_modules/@nestjs/websockets/web-sockets-controller.js:31:43
    at Array.map (<anonymous>)
    at WebSocketsController.subscribeToServerEvents (/home/mostafa/Workspace/BehineGostar/Tamuk/mobile/node_modules/@nestjs/websockets/web-sockets-controller.js:28:55)
    at WebSocketsController.mergeGatewayAndServer (/home/mostafa/Workspace/BehineGostar/Tamuk/mobile/node_modules/@nestjs/websockets/web-sockets-controller.js:24:14)
    at SocketModule.combineGatewayAndServer (/home/mostafa/Workspace/BehineGostar/Tamuk/mobile/node_modules/@nestjs/websockets/socket-module.js:45:35)
    at /home/mostafa/Workspace/BehineGostar/Tamuk/mobile/node_modules/@nestjs/websockets/socket-module.js:34:38
    at Array.forEach (<anonymous>)
    at SocketModule.combineAllGateways (/home/mostafa/Workspace/BehineGostar/Tamuk/mobile/node_modules/@nestjs/websockets/socket-module.js:34:14)
(node:20453) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:20453) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by msttamuk** [comment]
solved this by **upgrade** to **7.0.0** version.

**Comment by webcat12345** [comment]
Same problem, fixed by upgrading to `@nestjs/common` and `@nestjs/core` to `7.0.7`
