### ISSUE TITLE
ParseArrayPipe `optional = true` throws `TypeError: value.map is not a function`

### ISSUE THREAD

**Issue by avocraft** [nestjs/nest#4380]
## Current behavior
Havin the `optional: true` key in `ParseArrayPipe` will throw `TypeError: value.map is not a function`

```
TypeError: value.map is not a function
    at ParseArrayPipe.transform (@nestjs\common\pipes\parse-array.pipe.js:62:45)
    at @nestjs\core\pipes\pipes-consumer.js:15:33
    at async resolveParamValue (@nestjs\core\router\router-execution-context.js:141:23)
    at async Promise.all (index 0)
    at async pipesFn (@nestjs\core\router\router-execution-context.js:144:13)
    at async @nestjs\core\router\router-execution-context.js:36:30
    at async @nestjs\core\router\router-execution-context.js:45:28
    at async @nestjs\core\router\router-proxy.js:8:17
```

```ts
  @Get('/api/morechildren')
  async getMoreChildren(
    @Query(
      'children',
      new ParseArrayPipe({
        optional: true,
        items: String,
        separator: ','
      }),
    )
    children: string[],
  ): Promise<any> {
    console.log(children);
    return 'haha';
  }
```

```ts
skipUndefinedProperties: true,
skipMissingProperties: true,
skipNullProperties: true,
```
Setting this did also not change the behavior

## Expected behavior
`ParseArrayPipe` should not throw `TypeError: value.map is not a function` if `optional` is set to true. It should skip validation.

## Environment

<pre><code>
Nest version: 7.0.4
 
For Tooling issues:
- Node version: v13.10.1
- Platform:  Windows
</code></pre>

**Comment by kamilmysliwiec** [comment]
Fixed in 7.0.5
