### ISSUE TITLE
when i create an app container with nestjs it gives me this error when i run the container

### ISSUE THREAD

**Issue by JorgeBrs** [nestjs/nest#4484]
FROM node:12.13-alpine As development

WORKDIR /app

ADD package.json /app/package.json
RUN npm config set registry http://registry.npmjs.org
RUN npm install 

ADD . /app

EXPOSE 3000

CMD ["npm", "run", "start"]

Error: 

TypeError: Cannot read property 'constructor' of undefined
    at Object.<anonymous> (/app/node_modules/cli-highlight/src/theme.ts:4:26)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/app/node_modules/cli-highlight/src/index.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository.
