### ISSUE TITLE
Use a topological sort for module lifecycle hooks

### ISSUE THREAD

**Issue by akaRem** [nestjs/nest#4599]
## Bug Report

When there are 2 or more modules which expose services which require each other to work, the init sequence does not look at actual dependencies, but run init in reverse order of module definition.

see: https://github.com/nestjs/nest/blob/master/packages/core/nest-application-context.ts#L212
(thanks to Map spec, the order of module defs are defined by insert order)

For example, this snippet will not work
```typescript
@Module({
  imports: [
    // provides docker connector
    DockerModule.forRoot(), 
    // provides database container, wants DockerService from ^
    DockerizedDatabaseModule.forRoot(), 
    // provides orm, wants DatabaseService from ^
    OrmModule.forRoot(), 
    // rest ..
    AuthModule,
    ...
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```
Instead it should be
```typescript
@Module({
  imports: [
    AuthModule,
    ...
    OrmModule.forRoot(),
    DockerizedDatabaseModule.forRoot(),
    DockerModule.forRoot(),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

The problem with this behaviour is that:
- it's not documented
- it's a bit confusing — the framework can autoinject dependencies and has init hooks, but hook execution order is disconnected from actual injection.
- while this logic tries to mimic reverse graph walk, in fact, this approximation is not correct and sometimes does not work
- the order of module definition matters

The most annoying thing is that you need to track not only module dependencies but also order in which they are defined across all files in case they have async init methods.

The good thing, however, is that it doesn't just fire all onModuleInit at once, so there is no need to write synchronisation logic for async initialisation of various components.

If there are no plans to introduce "real" dependency resolution for async initialisation, it would be nice to have a note in documentation so that behaviour will be defined and will not surprise.

## Environment

<pre><code>
[System Information]
OS Version     : macOS Mojave
NodeJS Version : v13.11.0
YARN Version    : 1.13.0

[Nest CLI]
Nest CLI Version : 7.1.2

[Nest Platform Information]
platform-express version : 7.0.0
common version           : 7.0.0
core version             : 7.0.0
</code></pre>

**Comment by jmcdo29** [comment]
Would you be able to provide a reproduction of the module's not providing the dependencies expected?

**Comment by akaRem** [comment]
Example:

```typescript
import { Test } from '@nestjs/testing';
import { DynamicModule, Injectable, OnModuleInit } from '@nestjs/common';

@Injectable()
class BB implements OnModuleInit {
  public field: string;
  async onModuleInit() {
    this.field = 'a-field';
  }
}

class B {
  static forRoot(): DynamicModule {
    return {
      module: B,
      global: true,
      providers: [BB],
      exports: [BB],
    };
  }
}

@Injectable()
class AA implements OnModuleInit {
  public field: string;
  constructor(private bb: BB) {}
  async onModuleInit() {
    this.field = this.bb.field;
  }
}

class A {
  static forRoot(): DynamicModule {
    return {
      module: A,
      global: true,
      imports: [B],
      providers: [AA],
    };
  }
}
describe('Example', () => {
  it('will error', async () => {
    const module = await Test.createTestingModule({
      imports: [
        // BB.field will be set after AA.onModuleInit()
        B.forRoot(), // 2nd onModuleInit call
        // AA in A wants BB.field, which will not be set yet
        A.forRoot(), // 1st onModuleInit call
      ],
    }).compile();
    await module.init();
    expect(module.get(AA).field).toEqual('a-field');
  });

  it('will not error', async () => {
    const module = await Test.createTestingModule({
      imports: [
        // AA in A wants BB.field, which will be set
        A.forRoot(), // 2nd onModuleInit call
        // BB.field will be set
        B.forRoot(), // 1st onModuleInit call
      ],
    }).compile();
    await module.init();
    expect(module.get(AA).field).toEqual('a-field');
  });
});
```

Output:
```
 FAIL  src/example.spec.ts
  ● Example › will error

    expect(received).toEqual(expected) // deep equality

    Expected: "a-field"
    Received: undefined

      51 |     }).compile();
      52 |     await module.init();
    > 53 |     expect(module.get(AA).field).toEqual('a-field');
         |                                  ^
      54 |   });
      55 | 
      56 |   it('will not error', async () => {

      at Object.<anonymous> (example.spec.ts:53:34)
```

W/o dynamic/global modules:

```typescript
import { Test } from '@nestjs/testing';
import {
  Injectable,
  OnModuleInit,
  Module,
} from '@nestjs/common';

@Injectable()
class BB implements OnModuleInit {
  public field: string;
  async onModuleInit() {
    this.field = 'a-field';
  }
}

@Module({
  providers: [BB],
  exports: [BB],
})
class B {}

@Injectable()
class AA implements OnModuleInit {
  public field: string;
  constructor(private bb: BB) {}
  async onModuleInit() {
    this.field = this.bb.field;
  }
}
@Module({
  imports: [B],
  providers: [AA],
})
class A {}
describe('Example', () => {
  it('will error', async () => {
    const module = await Test.createTestingModule({
      imports: [
        // BB.field will be set after AA.onModuleInit()
        B, // 2nd onModuleInit call
        // AA in A wants BB.field, which will not be set yet
        A, // 1st onModuleInit call
      ],
    }).compile();
    await module.init();
    expect(module.get(AA).field).toEqual('a-field');
  });

  it('will not error', async () => {
    const module = await Test.createTestingModule({
      imports: [
        // AA in A wants BB.field, which will be set
        A, // 2nd onModuleInit call
        // BB.field will be set
        B, // 1st onModuleInit call
      ],
    }).compile();
    await module.init();
    expect(module.get(AA).field).toEqual('a-field');
  });
});
```

Output:
```
 FAIL  src/example.spec.ts
  ● Example › will error

    expect(received).toEqual(expected) // deep equality

    Expected: "a-field"
    Received: undefined

      45 |     }).compile();
      46 |     await module.init();
    > 47 |     expect(module.get(AA).field).toEqual('a-field');
         |                                  ^
      48 |   });
      49 | 
      50 |   it('will not error', async () => {

      at Object.<anonymous> (example.spec.ts:47:34)
```

**Comment by akaRem** [comment]
There is also problem with async factories, which are fulfilled before `onModuleInit` stage, so if they have any dependencies with deferred initialisation, the dependencies will be injected uninitialised.

```typescript
import { Test } from '@nestjs/testing';
import { Injectable, OnModuleInit, Module } from '@nestjs/common';

@Injectable()
class BB implements OnModuleInit {
  public field: string;
  async onModuleInit() {
    this.field = 'a-field';
  }
}

@Module({
  providers: [BB],
  exports: [BB],
})
class B {}

const AA = Symbol();

@Module({
  imports: [B],
  providers: [
    {
      provide: AA,
      useFactory: async (bb: BB) => {
        return bb.field;
      },
      inject: [BB],
    },
  ],
})
class A {}

describe('Example', () => {
  it('A then B will error', async () => {
    const module = await Test.createTestingModule({
      imports: [
        // BB.field will be set after AA is created
        B,
        // AA in A wants BB.field, which will not be set
        A,
      ],
    }).compile();
    await module.init();
    expect(module.get(AA)).toEqual('a-field');
  });

  it('B then A will error', async () => {
    const module = await Test.createTestingModule({
      imports: [
        // AA in A wants BB.field, which will be set
        A,
        // BB.field will be set after AA is created
        B,
      ],
    }).compile();
    await module.init();
    expect(module.get(AA)).toEqual('a-field');
  });
});
```
Output:
```
 FAIL  src/example.spec.ts
  ● Example › A then B will error

    expect(received).toEqual(expected) // deep equality

    Expected: "a-field"
    Received: undefined

      43 |     }).compile();
      44 |     await module.init();
    > 45 |     expect(module.get(AA)).toEqual('a-field');
         |                            ^
      46 |   });
      47 | 
      48 |   it('B then A will error', async () => {

      at Object.<anonymous> (example.spec.ts:45:28)

  ● Example › B then A will error

    expect(received).toEqual(expected) // deep equality

    Expected: "a-field"
    Received: undefined

      56 |     }).compile();
      57 |     await module.init();
    > 58 |     expect(module.get(AA)).toEqual('a-field');
         |                            ^
      59 |   });
      60 | });
      61 | 

      at Object.<anonymous> (example.spec.ts:58:28)
```

A module should probably expose its exports after all services ran through `onModuleInit` and module ran through `onModuleInit`, only in this case we can be 100% sure that exports are initialised.

**Comment by kamilmysliwiec** [comment]
We don't use a topological sort for lifecycle hooks. However, we use it for middlewares (or rather their applying order). It should be pretty easy to change then.

**Comment by BrunnerLivio** [comment]
@kamilmysliwiec I think that would enable #2460. I raised this there as well. Your question there was:
> What about circular dependencies? 😄

How are we going to handle this?

**Comment by kamilmysliwiec** [comment]
Similarly to how it's handled for middleware - it takes the shortest distance then, but it shouldn't be a huge issue here (if one defines circular dependencies, topological sort doesn't make any sense either way) ;)

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/6236

**Comment by timbo-tj** [comment]
Can we get an update on this, because I am in the same boat as Brian. My services dependancies are being destroyed before the service itself. This seems wrong. If we set up our services A -> B -> C, then we should tear down C -> B -> A
