### ISSUE TITLE
Error in OnModuleInit does not exit app

### ISSUE THREAD

**Issue by andreialecu** [nestjs/nest#4715]
## Bug Report

I think this is a regression of https://github.com/nestjs/nest/issues/914#issue-345432908

## Current behavior

Seems that an error happening in `OnModuleInit` is not exiting the process, and instead just leaves it hung.

```
[Nest] 3001   - 05/02/2020, 1:31:24 AM   [InstanceLoader] TypegooseModule dependencies initialized +1ms
[Nest] 3001   - 05/02/2020, 1:31:24 AM   [InstanceLoader] UserModule dependencies initialized +0ms
[Nest] 3001   - 05/02/2020, 1:31:24 AM   [RoutesResolver] AppController {}: +3ms
[Nest] 3001   - 05/02/2020, 1:31:24 AM   [RouterExplorer] Mapped {, GET} route +1ms
(node:3001) UnhandledPromiseRejectionWarning: Error: test
    at ConfigService.onModuleInit (/home/aandrei/projects/x-server/dist/config/config.service.js:25:15)
    at MapIterator.iteratee (/home/aandrei/projects/x-server/node_modules/@nestjs/core/hooks/on-module-init.hook.js:21:43)
    at MapIterator.next (/home/aandrei/projects/x-server/node_modules/iterare/lib/map.js:13:39)
    at IteratorWithOperators.next (/home/aandrei/projects/x-server/node_modules/iterare/lib/iterate.js:21:28)
    at Function.from (<anonymous>)
    at IteratorWithOperators.toArray (/home/aandrei/projects/x-server/node_modules/iterare/lib/iterate.js:180:22)
    at callOperator (/home/aandrei/projects/x-server/node_modules/@nestjs/core/hooks/on-module-init.hook.js:22:10)
    at Object.callModuleInitHook (/home/aandrei/projects/x-server/node_modules/@nestjs/core/hooks/on-module-init.hook.js:42:23)
    at NestApplication.callInitHook (/home/aandrei/projects/x-server/node_modules/@nestjs/core/nest-application-context.js:152:27)
    at async NestApplication.init (/home/aandrei/projects/x-server/node_modules/@nestjs/core/nest-application.js:88:9)
    at async NestApplication.listen (/home/aandrei/projects/x-server/node_modules/@nestjs/core/nest-application.js:139:33)
    at async bootstrap (/home/aandrei/projects/x-server/dist/main.js:7:5)
(node:3001) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3001) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Input Code

```ts
@Injectable()
export class ConfigService implements OnModuleInit {
  async onModuleInit() {
    throw new Error("test");
  }
}
```

## Expected behavior

I believe the process should exit.

## Environment

<pre><code>
Nest version: 7.0.9

**Comment by kamilmysliwiec** [comment]
I can't reproduce your issue (i can catch this exception in the `bootstrap` function). 

Please provide a minimum reproduction repository.

**Comment by andreialecu** [comment]
Indeed, I didn't realize that the error bubbles properly to `bootstrap`. Perhaps the default template for `nest new app` could be updated to do something like this, or it could be added to the documentation:

```ts
async function bootstrap() {
  try {
    const app = await NestFactory.create(AppModule);
    await app.listen(3000);
  } catch (err) {
    console.error(`Failed to initialize, due to ${err}`);
    process.exit(1);
  }
}```

**Comment by rhyek** [comment]
Just hit this myself. @kamilmysliwiec what are your thoughts on @andreialecu's suggestion to have that or something similar be the default bootstrap function?

**Comment by andresberrios** [comment]
Just had the same issue, not realizing this. It's worth at least mentioning it in here: https://docs.nestjs.com/fundamentals/lifecycle-events
