### ISSUE TITLE
Failed execution production bundled (NX project) file in place without node_modules

### ISSUE THREAD

**Issue by vladborsh** [nestjs/nest#4778]
## Current behavior
I have built nest.js project in production mode in NX repository `ng build intern-app --configuration=production`. It works perfectly when i try to run bundled file in inside my project folder. But when I try run the same bundled script outside the project folder, for example on AWS instance, it fails. At first it logs in condole that application is bootstrapped correctly (database connection success, route mounting, etc.) but after first request it fails. It happens in any place where I don't have node_modules, just js bundle that I want to run. 

It seems like nest.js try to find lazy loaded module and can't figure out how I can disable that behavior for production and have just single executive file.

## Expected behavior
Just have executive bundled single *.js file that I can run at any place without any additional node modules or external dependencies

## Environment

angular.json
```json
   "architect": {
        "build": {
          "builder": "@nrwl/node:build",
          "options": {
            "outputPath": "dist/apps/intern-api",
            "main": "apps/intern-api/src/main.ts",
            "tsConfig": "apps/intern-api/tsconfig.app.json",
            "assets": ["apps/intern-api/src/assets"]
          },
          "configurations": {
            "production": {
              "optimization": true,
              "extractLicenses": true,
              "inspect": false,
              "fileReplacements": [
                {
                  "replace": "apps/intern-api/src/environments/environment.ts",
                  "with": "apps/intern-api/src/environments/environment.prod.ts"
                }
              ],
              "externalDependencies": [
                "@nestjs/core",
                "@nestjs/microservices",
                "@nestjs/platform-express",
                "class-transformer",
                "class-validator",
                "cache-manager"
              ]
            }
          }
        },
```
build output

```
ng build intern-api --configuration=production

Starting type checking service...
Using 1 worker with 2048MB memory limit
Hash: 15e1aa04a35e1890638f
Version: webpack 4.29.0
Time: 49984ms
Built at: 05/11/2020 3:25:00 PM
               Asset      Size  Chunks                    Chunk Names
3rdpartylicenses.txt   231 KiB          [emitted]         
             main.js  12.5 MiB       0  [emitted]  [big]  main
         main.js.map  12.8 MiB       0  [emitted]         main
Entrypoint main [big] = main.js main.js.map
  [0] ./node_modules/tslib/tslib.es6.js 11.2 KiB {0} [built]
  [1] ./node_modules/@nestjs/common/index.js 695 bytes {0} [built]
  [2] ./libs/data/src/index.ts 3.23 KiB {0} [built]
 [17] ./node_modules/@nestjs/mongoose/index.js 187 bytes {0} [built]
 [23] ./node_modules/rxjs/_esm2015/index.js 3.26 KiB {0} [built]
 [35] ./apps/intern-api/src/app/broadcast/broadcast.module.ts 378 bytes {0} [built]
 [53] external "path" 42 bytes {0} [built]
[287] ./apps/intern-api/src/app/logger/logger.service.ts 1.21 KiB {0} [built]
[377] external "@nestjs/core" 42 bytes {0} [built]
[922] ./apps/intern-api/src/app/app.module.ts 2.5 KiB {0} [built]
[980] ./node_modules/@nestjs/platform-ws/index.js 337 bytes {0} [built]
[981] ./node_modules/cookie-parser/index.js 3.58 KiB {0} [built]
[982] ./node_modules/express-rate-limit/lib/express-rate-limit.js 5.24 KiB {0} [built]
[983] multi ./apps/intern-api/src/main.ts 28 bytes {0} [built]
[984] ./apps/intern-api/src/main.ts 1.15 KiB {0} [built]
    + 2512 hidden modules

WARNING in ./libs/data/src/index.ts 18:0-80
"export 'StudentIdentificationDto' was not found in './lib/dto/student-identification.dto'
 @ ./apps/intern-api/src/app/logger/logger.service.ts
 @ ./apps/intern-api/src/main.ts
 @ multi ./apps/intern-api/src/main.ts

WARNING in ./node_modules/mongoose/lib/index.js 9:32-68
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/mongoose/index.js
 @ ./apps/intern-api/src/app/data-access/log-item/log-item.schema.ts
 @ ./apps/intern-api/src/app/data-access/log-item/log-item.module.ts
 @ ./apps/intern-api/src/app/logger/logger.module.ts
 @ ./apps/intern-api/src/app/app.module.ts
 @ ./apps/intern-api/src/main.ts
 @ multi ./apps/intern-api/src/main.ts

WARNING in ./node_modules/@nestjs/common/utils/load-package.util.js 8:39-59
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@nestjs/common/serializer/class-serializer.interceptor.js
 @ ./node_modules/@nestjs/common/serializer/index.js
 @ ./node_modules/@nestjs/common/index.js
 @ ./apps/intern-api/src/app/logger/logger.service.ts
 @ ./apps/intern-api/src/main.ts
 @ multi ./apps/intern-api/src/main.ts

WARNING in ./node_modules/express/lib/view.js 65:17-29
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/express/lib/application.js
 @ ./node_modules/express/lib/express.js
 @ ./node_modules/express/index.js
 @ ./apps/intern-api/src/app/router/user/user.controller.ts
 @ ./apps/intern-api/src/app/router/router.module.ts
 @ ./apps/intern-api/src/app/app.module.ts
 @ ./apps/intern-api/src/main.ts
 @ multi ./apps/intern-api/src/main.ts

WARNING in ./node_modules/require_optional/index.js 67:22-46
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/mongodb/lib/core/utils.js
 @ ./node_modules/mongodb/lib/core/cursor.js
 @ ./node_modules/mongodb/lib/command_cursor.js
 @ ./node_modules/mongodb/index.js
 @ ./node_modules/mongoose/lib/index.js
 @ ./node_modules/mongoose/index.js
 @ ./apps/intern-api/src/app/data-access/log-item/log-item.schema.ts
 @ ./apps/intern-api/src/app/data-access/log-item/log-item.module.ts
 @ ./apps/intern-api/src/app/logger/logger.module.ts
 @ ./apps/intern-api/src/app/app.module.ts
 @ ./apps/intern-api/src/main.ts
 @ multi ./apps/intern-api/src/main.ts

WARNING in ./node_modules/require_optional/index.js 77:26-50
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/mongodb/lib/core/utils.js
 @ ./node_modules/mongodb/lib/core/cursor.js
 @ ./node_modules/mongodb/lib/command_cursor.js
 @ ./node_modules/mongodb/index.js
 @ ./node_modules/mongoose/lib/index.js
 @ ./node_modules/mongoose/index.js
 @ ./apps/intern-api/src/app/data-access/log-item/log-item.schema.ts
 @ ./apps/intern-api/src/app/data-access/log-item/log-item.module.ts
 @ ./apps/intern-api/src/app/logger/logger.module.ts
 @ ./apps/intern-api/src/app/app.module.ts
 @ ./apps/intern-api/src/main.ts
 @ multi ./apps/intern-api/src/main.ts

WARNING in ./node_modules/require_optional/index.js 85:37-69
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/mongodb/lib/core/utils.js
 @ ./node_modules/mongodb/lib/core/cursor.js
 @ ./node_modules/mongodb/lib/command_cursor.js
 @ ./node_modules/mongodb/index.js
 @ ./node_modules/mongoose/lib/index.js
 @ ./node_modules/mongoose/index.js
 @ ./apps/intern-api/src/app/data-access/log-item/log-item.schema.ts
 @ ./apps/intern-api/src/app/data-access/log-item/log-item.module.ts
 @ ./apps/intern-api/src/app/logger/logger.module.ts
 @ ./apps/intern-api/src/app/app.module.ts
 @ ./apps/intern-api/src/main.ts
 @ multi ./apps/intern-api/src/main.ts

WARNING in ./node_modules/@nestjs/platform-ws/node_modules/ws/lib/buffer-util.js
Module not found: Error: Can't resolve 'bufferutil' in '/var/lib/jenkins/workspace/intern-app-pipeline_develop/node_modules/@nestjs/platform-ws/node_modules/ws/lib'
 @ ./node_modules/@nestjs/platform-ws/node_modules/ws/lib/buffer-util.js
 @ ./node_modules/@nestjs/platform-ws/node_modules/ws/lib/websocket.js
 @ ./node_modules/@nestjs/platform-ws/node_modules/ws/index.js
 @ ./node_modules/@nestjs/platform-ws/adapters/ws-adapter.js
 @ ./node_modules/@nestjs/platform-ws/adapters/index.js
 @ ./node_modules/@nestjs/platform-ws/index.js
 @ ./apps/intern-api/src/main.ts
 @ multi ./apps/intern-api/src/main.ts

WARNING in ./node_modules/mongodb/lib/operations/connect.js
Module not found: Error: Can't resolve 'mongodb-client-encryption' in '/var/lib/jenkins/workspace/intern-app-pipeline_develop/node_modules/mongodb/lib/operations'
 @ ./node_modules/mongodb/lib/operations/connect.js
 @ ./node_modules/mongodb/lib/mongo_client.js
 @ ./node_modules/mongodb/index.js
 @ ./node_modules/mongoose/lib/index.js
 @ ./node_modules/mongoose/index.js
 @ ./apps/intern-api/src/app/data-access/log-item/log-item.schema.ts
 @ ./apps/intern-api/src/app/data-access/log-item/log-item.module.ts
 @ ./apps/intern-api/src/app/logger/logger.module.ts
 @ ./apps/intern-api/src/app/app.module.ts
 @ ./apps/intern-api/src/main.ts
 @ multi ./apps/intern-api/src/main.ts

WARNING in ./node_modules/@nestjs/platform-ws/node_modules/ws/lib/validation.js
Module not found: Error: Can't resolve 'utf-8-validate' in '/var/lib/jenkins/workspace/intern-app-pipeline_develop/node_modules/@nestjs/platform-ws/node_modules/ws/lib'
 @ ./node_modules/@nestjs/platform-ws/node_modules/ws/lib/validation.js
 @ ./node_modules/@nestjs/platform-ws/node_modules/ws/lib/sender.js
 @ ./node_modules/@nestjs/platform-ws/node_modules/ws/index.js
 @ ./node_modules/@nestjs/platform-ws/adapters/ws-adapter.js
 @ ./node_modules/@nestjs/platform-ws/adapters/index.js
 @ ./node_modules/@nestjs/platform-ws/index.js
 @ ./apps/intern-api/src/main.ts
 @ multi ./apps/intern-api/src/main.ts
```

```
- @nestjs/core: 6.2.4
 
For Tooling issues:
- Angular CLI: 8.2.0
- Node: 10.14.2
- @nrwl/node: 8.0.0
- OS: darwin x64
```

Others:

fragment of error log

```

Error: Cannot find module '@nestjs/core'
0|app  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
0|app  |     at Module.Hook._require.Module.require (/Users/vlad/.nvm/versions/node/v10.14.2/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
0|app  |     at require (internal/modules/cjs/helpers.js:22:18)
0|app  |     at Object.<anonymous> (/Users/vlad/Documents/dev/package/dist/apps/intern-api/webpack:/external "@nestjs/core":1:1)
0|app  |     at __webpack_require__ (/Users/vlad/Documents/dev/package/dist/apps/intern-api/webpack:/webpack/bootstrap:19:1)
0|app  |     at Module.Object.defineProperty.value (/Users/vlad/Documents/dev/package/dist/apps/intern-api/webpack:/apps/intern-api/src/main.ts:1:1)
0|app  |     at __webpack_require__ (/Users/vlad/Documents/dev/package/dist/apps/intern-api/webpack:/webpack/bootstrap:19:1)
0|app  |     at Object.<anonymous> (/Users/vlad/Documents/dev/package/dist/apps/intern-api/main.js:131127:18)
0|app  |     at __webpack_require__ (/Users/vlad/Documents/dev/package/dist/apps/intern-api/webpack:/webpack/bootstrap:19:1)
0|app  |     at extendStatics (/Users/vlad/Documents/dev/package/dist/apps/intern-api/webpack:/webpack/bootstrap:83:1)
0|app  | Error: Cannot find module '@nestjs/core'
0|app  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
0|app  |     at Module.Hook._require.Module.require (/Users/vlad/.nvm/versions/node/v10.14.2/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
0|app  |     at require (internal/modules/cjs/helpers.js:22:18)
0|app  |     at Object.<anonymous> (/Users/vlad/Documents/dev/package/dist/apps/intern-api/webpack:/external "@nestjs/core":1:1)
0|app  |     at __webpack_require__ (/Users/vlad/Documents/dev/package/dist/apps/intern-api/webpack:/webpack/bootstrap:19:1)
0|app  |     at Module.Object.defineProperty.value (/Users/vlad/Documents/dev/package/dist/apps/intern-api/webpack:/apps/intern-api/src/main.ts:1:1)
0|app  |     at __webpack_require__ (/Users/vlad/Documents/dev/package/dist/apps/intern-api/webpack:/webpack/bootstrap:19:1)
0|app  |     at Object.<anonymous> (/Users/vlad/Documents/dev/package/dist/apps/intern-api/main.js:131127:18)

```

**Comment by jmcdo29** [comment]
There's a lengthy discussion about this available at at [#1706](https://github.com/nestjs/nest/issues/1706). That was back in Nest v6, but the same applies (mostly) for v7.

**Comment by vladborsh** [comment]
I tried solution with `externalDependencies` option in architect config, but unfortunately this doesn't help me. Of course tried to build it without this options but result is the same

**Comment by MrBacony** [comment]
Same on my side. We solved this with a workaround and added a package.json to the dist folder with all dependencies and a start script:

"scripts": {
    "start": "npm i && node main.js"
  }

its a hassle, because we have to keep both package.json files in sync.

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the Nx repository. This isn't related to NestJS, but rather to how Nx performs the build process.
