### ISSUE TITLE
Error when overriding transient providers

### ISSUE THREAD

**Issue by willsoto** [nestjs/nest#4800]
## Current behavior
When overriding a `TRANSIENT` provider in tests in a `factory` provider, an error is thrown from ReflectMetadata.

```
    TypeError:

      at Object.getMetadata (../node_modules/reflect-metadata/Reflect.js:354:23)
      at Injector.reflectConstructorParams (../node_modules/@nestjs/core/injector/injector.js:120:36)
      at Injector.resolveConstructorParams (../node_modules/@nestjs/core/injector/injector.js:90:20)
      at Injector.loadInstance (../node_modules/@nestjs/core/injector/injector.js:80:20)
      at Injector.loadProvider (../node_modules/@nestjs/core/injector/injector.js:37:20)
      at Injector.lookupComponentInImports (../node_modules/@nestjs/core/injector/injector.js:223:28)
      at Injector.lookupComponentInParentModules (../node_modules/@nestjs/core/injector/injector.js:189:44)
      at Injector.lookupComponent (../node_modules/@nestjs/core/injector/injector.js:186:21)
      at Injector.resolveComponentInstance (../node_modules/@nestjs/core/injector/injector.js:147:44)
      at Injector.resolveSingleParam (../node_modules/@nestjs/core/injector/injector.js:136:21)
```

## Input Code
Reproduction: https://github.com/willsoto/transient-provider-bug

```ts
yarn install
yarn test
```

(Potentially) relevant bits:

- https://github.com/willsoto/transient-provider-bug/blob/9ccd74192dccc1af63f332522bab08127bf43478/src/app.controller.spec.ts#L13-L16
- https://github.com/willsoto/transient-provider-bug/blob/9ccd74192dccc1af63f332522bab08127bf43478/src/factory-provider.ts#L5-L13

## Expected behavior
I would expect to be able to override transient providers in tests via `overrideProvider`

## Possible Solution

N/A

## Environment

<pre><code>
"@nestjs/common": "~7.0.11",
"@nestjs/core": "~7.0.11",
"@nestjs/testing": "~7.0.11",
"reflect-metadata": "~0.1.13",

 
For Tooling issues:
- Node version: 12.16.3
- Platform:  Mac

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Fixed in the latest version. Thanks for reporting!
