### ISSUE TITLE
Error: No valid exports main found for '/data/learn/nestjs-learn/nest-rest-api/node_modules/uuid'

### ISSUE THREAD

**Issue by dhaneesh-r** [nestjs/nest#4824]
## Current behavior
Getting this error for a newly generated project.
```
npm run start

> nest-rest-api@0.0.1 start /data/learn/nestjs-learn/nest-rest-api
> nest start

internal/modules/cjs/loader.js:621
  throw e;
  ^

Error: No valid exports main found for '/data/learn/nestjs-learn/nest-rest-api/node_modules/uuid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/data/learn/nestjs-learn/nest-rest-api/node_modules/@nestjs/common/decorators/core/injectable.decorator.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1128:30) {
  code: 'MODULE_NOT_FOUND'
}

```

## Environment

<pre><code>
Nest version: 7.1.5
 
For Tooling issues:
- Node version: 13.3.0
- Platform:  Linux(Ubuntu 20.04)

</code></pre>

**Comment by jmcdo29** [comment]
Duplicate of [nest-cli#724](https://github.com/nestjs/nest-cli/issues/724)

**Comment by dhaneesh-r** [comment]
> Duplicate of [nest-cli#724](https://github.com/nestjs/nest-cli/issues/724)
