### ISSUE TITLE
my call back fuction call mult itime

### ISSUE THREAD

**Issue by arjun-707** [nestjs/nest#4838]
my call back fuction call mult itime

router.get('/sql',function(req,res,next){

 GetTesterData(function(err,data){  if(err) { callback(err,null);} else{
      res.json({"status":200,"data":data});
    }
  });

  function GetTesterData(callback){
      db.all("SELECT * FROM assign_scan where user_id=?",14,function(err,rows){
        rows.forEach((row) => {
              var sid=row.scan_id;
              db.all('SELECT * FROM testing_report WHERE status=? AND scan_id=?', [0,sid], (err, rows) => {
               callback(err,rows);   // my call back fuction call multitimes so that i will face this type of error
              });
           });
      });
   }
});

i am getting this error

rror [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (D:\node\test\myapp\node_modules\express\lib\response.js:767:10)
    at ServerResponse.send (D:\node\test\myapp\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (D:\node\test\myapp\node_modules\express\lib\response.js:267:15)
    at D:\node\test\myapp\routes\index.js:39:11
    at Statement.db.all (D:\node\test\myapp\routes\index.js:51:16)
--> in Database#all('SELECT * FROM testing_report WHERE status=? AND scan_id=?', [ 0, 1 ], [Function])
    at rows.forEach (D:\node\test\myapp\routes\index.js:50:18)
    at Array.forEach (<anonymous>)
    at Statement.<anonymous> (D:\node\test\myapp\routes\index.js:48:14)

how it solve

_Originally posted by @anshu300 in https://github.com/nestjs/nest/issues/1061#issuecomment-509586619_

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/NestJS) for support. We are using GitHub for bug reports and feature requests.
