### ISSUE TITLE
Cannot convert a Symbol value to a string when export a symbol

### ISSUE THREAD

**Issue by OpportunityLiu** [nestjs/nest#4856]
## Current behavior

```
[Nest] 31120   - 2020-05-29 12:10:38   [ExceptionHandler] Cannot convert a Symbol value to a string +24ms
TypeError: Cannot convert a Symbol value to a string
    at Object.exports.UNKNOWN_EXPORT_MESSAGE (***\node_modules\@nestjs\core\errors\messages.js:83:153)
    at new UnknownExportException (***\node_modules\@nestjs\core\errors\exceptions\unknown-export.exception.js:7:26)
    at Module.validateExportedProvider (***\node_modules\@nestjs\core\injector\module.js:271:19)
    at addExportedUnit (***\node_modules\@nestjs\core\injector\module.js:238:67)
    at Module.addExportedProvider (***\node_modules\@nestjs\core\injector\module.js:243:20)
    at NestContainer.addExportedProvider (***\node_modules\@nestjs\core\injector\container.js:121:19)
    at DependenciesScanner.insertExportedProvider (***\node_modules\@nestjs\core\scanner.js:208:24)
    at ***\node_modules\@nestjs\core\scanner.js:116:50
    at Array.forEach (<anonymous>)
    at DependenciesScanner.reflectExports (***\node_modules\@nestjs\core\scanner.js:116:17)
```
## Input Code

```ts
const SOME_DEPENDENCY = Symbol('SOME_DEPENDENCY');
@Module({exports: [SOME_DEPENDENCY]})
export class SomeModule {
}
```

## Expected behavior

```
Nest cannot export a provider/module that is not a part of the currently processed module (SomeModule). Please verify whether the exported Symbol(SOME_DEPENDENCY) is available in this particular context.

Possible Solutions:
- Is Symbol(SOME_DEPENDENCY) part of the relevant providers/imports within SomeModule?
`
```
## Possible Solution

See #3649, it might be the same problem.

## Environment

<pre><code>
Nest version: 7.1.1

 
For Tooling issues:
- Node version: 12.13.0  
- Platform: Windows  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Thanks for reporting! Fixed in this commit https://github.com/nestjs/nest/commit/75e110f4c094b5056b2bb5d4404e2a68d23ceda6 Will be published as part of the next patch release :)
