### ISSUE TITLE
Unable to run Nest app with GraphQL in Docker

### ISSUE THREAD

**Issue by munjalpatel** [nestjs/nest#4888]
## Current behavior
1. Set up a simple app with code-first GraphQL as follow:
2. Build Docker image using the Dockerfile below
3. Run the container and notice error

> Here is a repo with a minimal code to re-produce this error
> https://github.com/munjalpatel/nest-graphql-docker
> Do the following to re-produce:
> ```shell
> git clone git@github.com:munjalpatel/nest-graphql-docker.git
> docker build -t nest-graphql-docker .
> docker run -it nest-graphql-docker
> ```

** It runs completely fine on local dev machine. Fails in Docker.

## Related Code
**main.ts**
```ts
import { NestFactory } from '@nestjs/core';
import {
  FastifyAdapter,
  NestFastifyApplication,
} from '@nestjs/platform-fastify';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter({ logger: true }),
  );

  await app.listen(5600);
}

bootstrap();
```

**app.module.ts**
```ts
import { Module } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import { GraphQLModule } from '@nestjs/graphql';
import { TwitterModule } from './twitter/twitter.module';
import { HealthController } from './health/health.controller';

@Module({
  imports: [
    TwitterModule,
    ConfigModule.forRoot(),
    GraphQLModule.forRoot({
      debug: process.env.NODE_ENV !== 'production',
      playground: process.env.NODE_ENV !== 'production',
      autoSchemaFile: 'schema.gql',
      include: [TwitterModule],
    }),
  ],
  controllers: [HealthController],
})
export class AppModule {}
```

**twitter.module.ts**
```ts
import { Module } from '@nestjs/common';
import { TwitterResolver } from './twitter.resolver';

@Module({
  providers: [TwitterResolver],
})
export class TwitterModule {}
```

**twitter.resolver.ts**
```ts
import { Resolver, Args, Query } from '@nestjs/graphql';
import { TwitterData } from './models/model';

@Resolver(() => TwitterData)
export class TwitterResolver {
  @Query(() => TwitterData)
  twitterData(@Args('searchTerm') searchTerm: string) {
    return { searchTerm, totalTweets: 1000 };
  }
}
```

***model.ts***
```ts
import { ObjectType } from '@nestjs/graphql';

@ObjectType()
export class TwitterData {
  searchTerm: string;
  totalTweets: number;
}
```

***Dockerfile***
```Dockerfile
FROM node:12.16-alpine As builder
ARG NPM_TOKEN
WORKDIR /usr/src/app
RUN npm install -g rimraf request @nestjs/cli
COPY package*.json ./
COPY .npmrc ./
RUN echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" >> .npmrc && npm ci && rm -f .npmrc
COPY . .
ENV NODE_ENV=production
RUN npm run build

FROM node:12.16-alpine
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/schema.gql ./schema.gql
CMD ["node", "dist/main"]
EXPOSE 5600
```

**Deps from package.json**
```json
"dependencies": {
    "@grpc/proto-loader": "^0.5.4",
    "@nestjs/common": "^7.0.0",
    "@nestjs/config": "^0.5.0",
    "@nestjs/core": "^7.0.0",
    "@nestjs/graphql": "^7.4.0",
    "@nestjs/microservices": "^7.1.0",
    "@nestjs/platform-fastify": "^7.1.0",
    "apollo-server-fastify": "^2.14.1",
    "class-transformer": "^0.2.3",
    "class-validator": "^0.11.1",
    "graphql": "^14.2.1",
    "graphql-tools": "^6.0.3",
    "grpc": "^1.24.2",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^6.5.4"
  },
  "devDependencies": {
    "@nestjs/cli": "^7.0.0",
    "@nestjs/schematics": "^7.0.0",
    "@nestjs/testing": "^7.0.0",
    "@types/express": "^4.17.3",
    "@types/jest": "25.1.4",
    "@types/node": "^13.9.1",
    "@types/supertest": "^2.0.8",
    "@typescript-eslint/eslint-plugin": "^2.23.0",
    "@typescript-eslint/parser": "^2.23.0",
    "commitizen": "^4.1.2",
    "cz-conventional-changelog": "^3.2.0",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.10.0",
    "eslint-plugin-import": "^2.20.1",
    "husky": "^4.2.5",
    "jest": "^25.1.0",
    "lint-staged": "^10.2.6",
    "prettier": "^1.19.1",
    "supertest": "^4.0.2",
    "ts-jest": "25.2.1",
    "ts-loader": "^6.2.1",
    "ts-node": "^8.6.2",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^3.7.4",
    "validate-commit-email": "^1.0.1"
  },
```

## Expected behavior
Server should run without any error. However, I am getting the following error:
```
[Nest] 8   - 06/07/2020, 9:31:50 PM   [NestFactory] Starting Nest application...
[Nest] 8   - 06/07/2020, 9:31:50 PM   [InstanceLoader] AppModule dependencies initialized +136ms
[Nest] 8   - 06/07/2020, 9:31:50 PM   [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 8   - 06/07/2020, 9:31:50 PM   [InstanceLoader] TwitterModule dependencies initialized +1ms
[Nest] 8   - 06/07/2020, 9:31:50 PM   [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 8   - 06/07/2020, 9:31:50 PM   [InstanceLoader] GraphQLSchemaBuilderModule dependencies initialized +1ms
[Nest] 8   - 06/07/2020, 9:31:50 PM   [InstanceLoader] GraphQLModule dependencies initialized +1ms
[Nest] 8   - 06/07/2020, 9:31:50 PM   [RoutesResolver] HealthController {/healthz}: +5ms
[Nest] 8   - 06/07/2020, 9:31:50 PM   [RouterExplorer] Mapped {/healthz, GET} route +4ms
[
  GraphQLError: Type TwitterData must define one or more fields.
      at SchemaValidationContext.reportError (/usr/src/app/node_modules/graphql/type/validate.js:90:19)
      at validateFields (/usr/src/app/node_modules/graphql/type/validate.js:251:13)
      at validateTypes (/usr/src/app/node_modules/graphql/type/validate.js:226:7)
      at validateSchema (/usr/src/app/node_modules/graphql/type/validate.js:54:3)
      at graphqlImpl (/usr/src/app/node_modules/graphql/graphql.js:79:62)
      at /usr/src/app/node_modules/graphql/graphql.js:28:59
      at new Promise (<anonymous>)
      at Object.graphql (/usr/src/app/node_modules/graphql/graphql.js:26:10)
      at GraphQLSchemaFactory.<anonymous> (/usr/src/app/node_modules/@nestjs/graphql/dist/schema-builder/graphql-schema.factory.js:50:56)
      at Generator.next (<anonymous>)
]
(node:8) UnhandledPromiseRejectionWarning: Error: Schema generation error (code-first approach)
    at GraphQLSchemaFactory.<anonymous> (/usr/src/app/node_modules/@nestjs/graphql/dist/schema-builder/graphql-schema.factory.js:52:31)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/node_modules/tslib/tslib.js:111:62)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:8) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Environment

<pre><code>
Nest version: ^7.0.0
 
For Tooling issues:
- Node version: v12.16.3
- Platform:  Linux bcce9c349120 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 Linux
</code></pre>

![image](https://user-images.githubusercontent.com/2717686/83980912-28d50580-a8ce-11ea-9b5f-dafb63d99437.png)

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository

**Comment by munjalpatel** [comment]
@jmcdo29 here is the repro instructions:

```shell
git clone git@github.com:munjalpatel/nest-graphql-docker.git
docker build -t nest-graphql-docker .
docker run -it nest-graphql-docker
```

**Comment by jmcdo29** [comment]
In your `.dockerignore` you are ignoring the `nest-cli.json`. This file tells the nest cli what plugins to use , including the `graphql` plugin necessary to decorate your fields automagically.

For more support , please use our [Discord](https://discord.gg/nestjs) as we are using GitHub for Bug Reports and Feature Requests.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
