### ISSUE TITLE
Nest can't resolve dependencies

### ISSUE THREAD

**Issue by rrml** [nestjs/nest#5096]
## Bug Report
I have problems when I try to rename my entity class `User Entity` to `User`, this generates an error. I can use another name but I can't use `User`
## Current behavior

``` 
[ExceptionHandler] Nest can't resolve dependencies of the ProjectUserRepository (?, Sequelize). Please make sure that the argument ProjectUserRepository at index [0] is available in the ProjectModule context.
shield-v2_1        | 2020-07-15T19:38:41.208442157Z 
shield-v2_1        | 2020-07-15T19:38:41.208446215Z Potential solutions:
shield-v2_1        | 2020-07-15T19:38:41.208448961Z - If ProjectUserRepository is a provider, is it part of the current ProjectModule?
shield-v2_1        | 2020-07-15T19:38:41.208452589Z - If ProjectUserRepository is exported from a separate @Module, is that module imported within ProjectModule?
shield-v2_1        | 2020-07-15T19:38:41.208456017Z   @Module({
shield-v2_1        | 2020-07-15T19:38:41.208458568Z     imports: [ /* the Module containing ProjectUserRepository */ ]
shield-v2_1        | 2020-07-15T19:38:41.208461177Z   })
shield-v2_1        | 2020-07-15T19:38:41.208463663Z  +106ms
shield-v2_1        | 2020-07-15T19:38:41.208466466Z Error: Nest can't resolve dependencies of the ProjectUserRepository (?, Sequelize). Please make sure that the argument ProjectUserRepository at index [0] is available in the ProjectModule context.
shield-v2_1        | 2020-07-15T19:38:41.208469457Z 
shield-v2_1        | 2020-07-15T19:38:41.208471899Z Potential solutions:
shield-v2_1        | 2020-07-15T19:38:41.208474416Z - If ProjectUserRepository is a provider, is it part of the current ProjectModule?
shield-v2_1        | 2020-07-15T19:38:41.208477337Z - If ProjectUserRepository is exported from a separate @Module, is that module imported within ProjectModule?
shield-v2_1        | 2020-07-15T19:38:41.208480159Z   @Module({
shield-v2_1        | 2020-07-15T19:38:41.208482626Z     imports: [ /* the Module containing ProjectUserRepository */ ]
shield-v2_1        | 2020-07-15T19:38:41.208485207Z   })
shield-v2_1        | 2020-07-15T19:38:41.208487647Z 
shield-v2_1        | 2020-07-15T19:38:41.208490849Z     at Injector.lookupComponent (/app/node_modules/@nestjs/core/injector/injector.js:180:19)
shield-v2_1        | 2020-07-15T19:38:41.208493861Z     at Injector.resolveComponentInstance (/app/node_modules/@nestjs/core/injector/injector.js:148:44)
shield-v2_1        | 2020-07-15T19:38:41.208497883Z     at Injector.resolveSingleParam (/app/node_modules/@nestjs/core/injector/injector.js:137:21)
shield-v2_1        | 2020-07-15T19:38:41.208501727Z     at resolveParam (/app/node_modules/@nestjs/core/injector/injector.js:102:49)
shield-v2_1        | 2020-07-15T19:38:41.208516511Z     at Array.map (<anonymous>)
shield-v2_1        | 2020-07-15T19:38:41.208519560Z     at Injector.resolveConstructorParams (/app/node_modules/@nestjs/core/injector/injector.js:117:58)
shield-v2_1        | 2020-07-15T19:38:41.208522426Z     at Injector.loadInstance (/app/node_modules/@nestjs/core/injector/injector.js:81:20)
shield-v2_1        | 2020-07-15T19:38:41.208526073Z     at Injector.loadProvider (/app/node_modules/@nestjs/core/injector/injector.js:38:20)
shield-v2_1        | 2020-07-15T19:38:41.208529912Z     at Promise.all.wrappers.map.item (/app/node_modules/@nestjs/core/injector/instance-loader.js:43:62)
shield-v2_1        | 2020-07-15T19:38:41.208533615Z     at Array.map (<anonymous>)
shield-v2_1        | 2020-07-15T19:38:41.208536263Z     at InstanceLoader.createInstancesOfProviders (/app/node_modules/@nestjs/core/injector/instance-loader.js:43:36)
shield-v2_1        | 2020-07-15T19:38:41.208539781Z     at Promise.all.map (/app/node_modules/@nestjs/core/injector/instance-loader.js:28:24)
shield-v2_1        | 2020-07-15T19:38:41.208542502Z     at Array.map (<anonymous>)
shield-v2_1        | 2020-07-15T19:38:41.208545081Z     at InstanceLoader.createInstances (/app/node_modules/@nestjs/core/injector/instance-loader.js:27:49)
shield-v2_1        | 2020-07-15T19:38:41.208547776Z     at InstanceLoader.createInstancesOfDependencies (/app/node_modules/@nestjs/core/injector/instance-loader.js:17:20)
shield-v2_1        | 2020-07-15T19:38:41.208550464Z     at exceptions_zone_1.ExceptionsZone.asyncRun (/app/node_modules/@nestjs/core/nest-factory.js:82:38)
shield-v2_1        | 2020-07-15T19:38:41.208553131Z     at process._tickCallback (internal/process/next_tick.js:68:7)
shield-v2_1        | 2020-07-15T19:38:41.208555717Z     at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
shield-v2_1        | 2020-07-15T19:38:41.208558374Z     at startup (internal/bootstrap/node.js:285:19)
shield-v2_1        | 2020-07-15T19:38:41.208560977Z     at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```
## Input Code

user.ts
```ts
import {Column, Model, Table} from 'sequelize-typescript';

@Table({tableName: 'users'})
export default class User extends Model<User> {
  @Column
  username: string;

  @Column
  email: string;

  @Column({field: 'full_name'})
  fullName: string;

  @Column({field: 'is_app_account'})
  isAppAccount: number;

  @Column({field: 'created_at'})
  createdAt: Date;

  @Column({field: 'updated_at'})
  updatedAt: Date;

  @Column({field: 'manager_id'})
  managerId: number;
}
```
user.repository.ts
```ts
import {Injectable} from '@nestjs/common';
import {InjectModel} from '@nestjs/sequelize';
import {Sequelize} from 'sequelize-typescript';

import User from './user';
import BaseRepository from '../../common/base.repository';

@Injectable()
export default class UserRepository extends BaseRepository {
  constructor(
    @InjectModel(User)
    protected model: typeof User,
    protected sequelize: Sequelize,
  ) {
    super(model, sequelize);
  }
}

```

index.ts
```ts
import {Module, INestApplication} from '@nestjs/common';
import {SequelizeModule} from '@nestjs/sequelize';
import {DocumentBuilder, SwaggerModule, OpenAPIObject} from '@nestjs/swagger';

import InteractionModule from '../interactions';

import User from './user';

import UserRepository from './user.repository';

@Module({
  imports: [
    SequelizeModule.forFeature([User]),
    InteractionModule,
  ],
  controllers: [],
  providers: [UserRepository],
  exports: [UserRepository],
})
export default class UserModule {}

export {
  User,
};

export const optionApiUsers = new DocumentBuilder()
  .setTitle('Users')
  .setDescription('The users API description')
  .setVersion('1.0')
  .addTag('users')
  .build();

export const userDocument = (app: INestApplication): OpenAPIObject => (
  SwaggerModule.createDocument(app, optionApiUsers, {
    include: [UserModule],
  })
);
```
app.module.ts
```ts
import {
  Module,
  MiddlewareConsumer,
  NestModule, RequestMethod,
} from '@nestjs/common';

import {
  connectionToCoreDB,
  connectionToInteractionDB,
} from './config/database/getConnectionOptions';

import AppController from './app.controller';

import {InteractionEntity} from './apis/interactions';
import UserModule, {User} from './apis/users';
import ProjectModule, {Project, ProjectUser} from './apis/projects';

import SetCurrentUserMiddleware from './middlewares/setCurrentUser.middleware';

@Module({
  imports: [
    connectionToCoreDB([
      User,
      Project,
      ProjectUser,
    ]),
    connectionToInteractionDB([InteractionEntity]),
    UserModule,
    ProjectModule,
  ],
  controllers: [AppController],
})
export default class AppModule implements NestModule {
  // eslint-disable-next-line class-methods-use-this
  configure(consumer: MiddlewareConsumer): void {
    consumer.apply(SetCurrentUserMiddleware).forRoutes({
      path: '*', method: RequestMethod.ALL,
    });
  }
}


 ``` 
## Expected behavior

No error when I use the name `User` in my file` user.ts`
## Possible Solution

I can change the class name to

user.ts
```ts
// this works 
import {Column, Model, Table} from 'sequelize-typescript';

@Table({tableName: 'users'})
export default class Example extends Model<Example> {
  @Column
  username: string;

  @Column
  email: string;

  @Column({field: 'full_name'})
  fullName: string;

  @Column({field: 'is_app_account'})
  isAppAccount: number;

  @Column({field: 'created_at'})
  createdAt: Date;

  @Column({field: 'updated_at'})
  updatedAt: Date;

  @Column({field: 'manager_id'})
  managerId: number;
}

// this works too
export default class X extends Model<X> {
  @Column
  username: string;

  @Column
  email: string;

  @Column({field: 'full_name'})
  fullName: string;

  @Column({field: 'is_app_account'})
  isAppAccount: number;

  @Column({field: 'created_at'})
  createdAt: Date;

  @Column({field: 'updated_at'})
  updatedAt: Date;

  @Column({field: 'manager_id'})
  managerId: number;
}

 ```
## Environment

<pre><code>
Nest version: ^7.0.0

 
For Tooling issues:
- Node version: 10.13  
- Platform:  Ubuntu 20.04 

Others:

</code></pre>

package.json

```json
{
  "name": "shield-v2",
  "version": "0.0.1",
  "description": "",
  "author": "Devtools",
  "license": "MIT",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "compodoc": "npx compodoc -p tsconfig.json -s -r 9000",
    "start": "nest start",
    "start-dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\"",
    "lint:fix": "lint --fix",
    "test": "jest --colors",
    "test:watch": "jest --watch",
    "test:unit": "jest --coverage --colors",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^7.0.0",
    "@nestjs/core": "^7.0.0",
    "@nestjs/platform-express": "^7.0.0",
    "@nestjs/sequelize": "^0.1.0",
    "@nestjs/swagger": "^4.5.11",
    "class-transformer": "^0.2.3",
    "class-validator": "^0.12.2",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "express-jwt": "^6.0.0",
    "mysql2": "^2.1.0",
    "newrelic": "^4.8.0",
    "node-meli-pass": "^1.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^6.5.4",
    "sequelize": "^5.13.0",
    "sequelize-typescript": "^1.0.0-alpha.9",
    "swagger-ui-express": "^4.1.4",
    "url-slug": "^2.3.1"
  },
  "devDependencies": {
    "@compodoc/compodoc": "^1.1.11",
    "@nestjs/cli": "^7.0.0",
    "@nestjs/schematics": "^7.0.0",
    "@nestjs/testing": "^7.3.2",
    "@types/express": "^4.17.6",
    "@types/jest": "25.2.3",
    "@types/node": "^13.9.1",
    "@types/sequelize": "^4.28.9",
    "@types/supertest": "^2.0.9",
    "@typescript-eslint/eslint-plugin": "^3.6.1",
    "@typescript-eslint/parser": "3.0.2",
    "eslint": "7.1.0",
    "eslint-config-airbnb-typescript": "^8.0.2",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-import": "^2.22.0",
    "husky": "^4.2.5",
    "jest": "^24.9.0",
    "prettier": "^1.19.1",
    "supertest": "^4.0.2",
    "ts-jest": "26.1.0",
    "ts-loader": "^6.2.2",
    "ts-node": "^8.10.2",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^3.9.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".spec.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}


 ```

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support) for help and support. We are using GitHub to track Feature Requests, Bug Reports and regressions.

**Comment by rrml** [comment]
> I have problems when I try to rename my entity class `User Entity` to `User`, this generates an error. I can use another name but I can't use `User`
