### ISSUE TITLE
ClassSerializerInterceptor causing class-transformer to throw TypeError when used with @Res() decorator

### ISSUE THREAD

**Issue by nickythorne** [nestjs/nest#5144]
## Bug Report

`ClassSerializerInterceptor` attempts to serialise the `ServerResponse` when the `@Res()` decorator is used in a controller method. This results in `class-transformer` throwing a TypeError, such as the following:

> TypeError: Cannot read property 'parser' of undefined
    at Object.resetHeadersTimeoutOnReqEnd [as end] (_http_server.js:746:30)
    at _loop_1 (/service/node_modules/class-transformer/TransformOperationExecutor.js:146:47)
    at TransformOperationExecutor.transform (/service/node_modules/class-transformer/TransformOperationExecutor.js:260:17)
    at _loop_1 (/service/node_modules/class-transformer/TransformOperationExecutor.js:232:45)
    at TransformOperationExecutor.transform (/service/node_modules/class-transformer/TransformOperationExecutor.js:260:17)
    at _loop_1 (/service/node_modules/class-transformer/TransformOperationExecutor.js:232:45)
    at TransformOperationExecutor.transform (/service/node_modules/class-transformer/TransformOperationExecutor.js:260:17)
    at ClassTransformer.classToPlain (/service/node_modules/class-transformer/ClassTransformer.js:9:25)
    at Object.classToPlain (/service/node_modules/class-transformer/index.js:12:29)
    at ClassSerializerInterceptor.transformToPlain (/service/node_modules/@nestjs/common/serializer/class-serializer.interceptor.js:43:34)

## Input Code

```ts
@Entity()
@TableInheritance({column: {type: 'varchar', name: 'type'}})
export abstract class Entity {

    @PrimaryGeneratedColumn({ name: 'block_id' })
    @Exclude()
    id: number;

    @Column({ name: 'uuid', nullable: false, unique: true })
    @Generated("uuid")
    uuid: string;

    @Column({ name: 'name', unique: true, nullable: false })
    name: string;

    @Column()
    label: string;

}
```
```ts
@Controller("test")
@UseInterceptors(ClassSerializerInterceptor)
export class TestController {

    constructor(private contextService: ContextService) {
    }

    @Get()
    getRootContext(@Res() response: Response) {
       return this.sendContextResponse(response,
           () => this.contextService.getRootContext())
    }

    private async sendContextResponse(response: Response<any>, getContext: () => Promise<Context | undefined>) {
        const context = await getContext();
        return (context === undefined) ?
            response.sendStatus(404).send() :
            response.send(context);
    }

}
```
## Expected behavior

`ClassSerializerInterceptor` should work with `@Res()` and not attempt to serialise the ServerResponse. 

## Environment

NextJs v7.0.0
Node v11.10.1

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository.

**Comment by qiuzuhui** [comment]
has same issue, ClassSerializerInterceptor can't work with @Req,  Is there anyway to ignore ClassSerializerInterceptor for some control function after set it as global interceptor?

**Comment by jmcdo29** [comment]
https://github.com/nestjs/nest/issues/5144#issuecomment-663595508
