### ISSUE TITLE
Generating migrations is flaky.

### ISSUE THREAD

**Issue by Dud3core-webdev** [nestjs/nest#5149]
I had set up migrations recently and got it working, all of a sudden it has broken and now I cannot create any migrations without this error: 

```
C:\Users\marc\Documents\Projects\mf-dev-server>typeorm migration:generate -n logger
Error during migration generation:
Error: No connection options were found in any orm configuration files.
    at ConnectionOptionsReader.<anonymous> (C:\Users\marc\Documents\Projects\mf-dev-server\node_modules\typeorm\connection\ConnectionOptionsReader.js:34:35)
    at step (C:\Users\marc\Documents\Projects\mf-dev-server\node_modules\typeorm\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\Users\marc\Documents\Projects\mf-dev-server\node_modules\typeorm\node_modules\tslib\tslib.js:122:57)
    at fulfilled (C:\Users\marc\Documents\Projects\mf-dev-server\node_modules\typeorm\node_modules\tslib\tslib.js:112:62)
```
I have an environment provider that I share cross application: 

```environment.provider.ts```
```JS
import {EnvironmentClass} from "./environment.class";

export const environmentProvider = {
    provide: 'environment',
    useFactory: () : EnvironmentClass => {

        return new EnvironmentClass({
            databaseHost: process.env.DATABASE_HOST,
            databaseName: process.env.DATABASE_NAME,
            databasePassword: process.env.DATABASE_PASSWORD,
            databasePort: parseInt(process.env.DATABASE_PORT),
            databaseUserName: process.env.DATABASE_USERNAME,
            githubAccessToken: process.env.GITHUB_ACCESS_TOKEN,
            typeOrmEntitiesPath: process.env.TYPEORM_ENTITIES, // not in use yet
            typeOrmMigrationsPath: process.env.TYPEORM_MIGRATIONS, // not being used yet
            defaultEmailClientId: process.env.DEFAULT_EMAIL_KEY,
            defaultEmailPassword: process.env.DEFAULT_EMAIL_PASSWORD,
            defaultEmail: process.env.DEFAULT_EMAIL_ADDRESS
        })
    }
}

```

I use this to set up my database connections depending on environment: 

```js
import {TypeOrmModuleOptions} from "@nestjs/typeorm/dist/interfaces/typeorm-options.interface";
import {env} from 'custom-env';
import {EnvironmentClass} from "./modules/shared/environment/environment.class";

env('development');
export const buildDatabaseConfig = (environment: EnvironmentClass): TypeOrmModuleOptions => {
    return {
        type: 'mysql',
        username: environment.databaseUserName,
        password: environment.databasePassword,
        name: environment.databaseName,
        host: environment.databaseHost,
        port: environment.databasePort,
        database: environment.databaseName,
        entities: ["dist/database/entities/**/*.entity{.ts,.js}"],
        migrations: ['dist/database/migrations/*{.ts,.js}'],
        synchronize: false,
        autoLoadEntities: true,
        migrationsRun: true
    }
}

```

and my app.module:

```js
import { Module} from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { MfWebDevModule } from './mf-web-dev/mf-web-dev.module';
import { EmailModule } from './modules/email/email.module';
import {ConsilliumModule} from './consillium/consillium.module';
import {buildDatabaseConfig} from "./database-config.factory";
import {ControlPanelModule} from "./control-panel/control-panel.module";
import {SharedModule} from "./modules/shared/shared.module";

@Module({
  imports: [
    ControlPanelModule,
    ConsilliumModule,
    MfWebDevModule,
    EmailModule,
    TypeOrmModule.forRootAsync({
      useFactory: buildDatabaseConfig,
      inject: ['environment'],
      imports: [SharedModule]
    })
  ]
})
export class AppModule {}

```

I cannot figure out why this has regressed. I've seen in other posts that people have been resolving issues using a typeormconfig.json file, but this seems like a workaround rather than a fix. Does anyone have any idea why this may have regressed? The only thing I can think of is that I've changed libraries for environment loading. I've gone from EasyConfigModule to custom-env. 

Thanks guys.

**Comment by kamilmysliwiec** [comment]
Please, report this in the typeorm repo https://github.com/typeorm/typeorm
