### ISSUE TITLE
Config service error when starting application with cache-manager-redis-store

### ISSUE THREAD

**Issue by tedroeloffzen** [nestjs/nest#5194]
## Current behavior
When i try to start my app with cache-manager-redis-store a TypeError is thrown.
This is thrown inside the ConfigService in the reduce-callback in bindCustomHelpers(config) 

```
TypeError: Cannot set property create of #<Object> which has only a getter
    at /node_modules/nestjs-config/dist/module/config.service.js:241:39
    at Array.reduce (<anonymous>)
    at decorated.bindCustomHelpers (/node_modules/nestjs-config/dist/module/config.service.js:238:36)
    at /node_modules/nestjs-config/dist/module/config.service.js:246:46
    at Array.reduce (<anonymous>)
    at decorated.bindCustomHelpers (/node_modules/nestjs-config/dist/module/config.service.js:238:36)
    at /node_modules/nestjs-config/dist/module/config.service.js:246:46
    at Array.reduce (<anonymous>)
    at decorated.bindCustomHelpers /node_modules/nestjs-config/dist/module/config.service.js:238:36)
    at new ConfigService (/node_modules/nestjs-config/dist/module/config.service.js:35:14)
```

## Input Code

cache.config.ts
```ts
import * as redisStore from 'cache-manager-redis-store';

function createOptions() {
    return {
      store: redisStore,
      host: process.env.REDIS_IP,
      port: process.env.REDIS_PORT,
      db: process.env.REDIS_DB,
      ttl: 900
    };
}

const options = createOptions();

export default options;
```

## Expected behavior
No error is thrown

## Environment

<pre><code>
Nest version: 7.2.0
TypeScript version: 3.9.2
Cache-manager-redis-store version: 2.0.0

</code></pre>

**Comment by kamilmysliwiec** [comment]
`nestjs-config` is not maintained by the official NestJS organization. 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
