### ISSUE TITLE
Injecting Service cause Gateway crash

### ISSUE THREAD

**Issue by alexander-mozolevsky** [nestjs/nest#5208]
## Bug Report
I'm trying to inject service as dependency to Gateway, but each time I try to do that - app crashes.

## Current behavior

Get error each time while trying to inject any service.
It seems that `this.<any injected module>` does not exist in that file after dependency injection.
```
/usr/src/app/node_modules/rxjs/internal/util/hostReportError.js:4
server_1    |     setTimeout(function () { throw err; }, 0);
server_1    |                              ^
server_1    | 
server_1    | TypeError: Cannot read property 'log' of undefined
server_1    |     at SocketGateway.afterInit (/usr/src/app/dist/gateways/socket.gateway.js:26:21)
server_1    |     at SafeSubscriber.__tryOrUnsub (/usr/src/app/node_modules/rxjs/internal/Subscriber.js:205:16)
server_1    |     at SafeSubscriber.next (/usr/src/app/node_modules/rxjs/internal/Subscriber.js:143:22)
server_1    |     at Subscriber._next (/usr/src/app/node_modules/rxjs/internal/Subscriber.js:89:26)
server_1    |     at Subscriber.next (/usr/src/app/node_modules/rxjs/internal/Subscriber.js:66:18)
server_1    |     at ReplaySubject._subscribe (/usr/src/app/node_modules/rxjs/internal/ReplaySubject.js:76:28)
server_1    |     at ReplaySubject.Observable._trySubscribe (/usr/src/app/node_modules/rxjs/internal/Observable.js:44:25)
server_1    |     at ReplaySubject.Subject._trySubscribe (/usr/src/app/node_modules/rxjs/internal/Subject.js:102:51)
server_1    |     at ReplaySubject.Observable.subscribe (/usr/src/app/node_modules/rxjs/internal/Observable.js:30:22)
server_1    |     at WebSocketsController.subscribeInitEvent (/usr/src/app/node_modules/@nestjs/websockets/web-sockets-controller.js:60:19)
```

## Input Code

```ts

/gateways/socket.gateway.ts

@WebSocketGateway()
export class SocketGateway implements OnGatewayInit, OnGatewayConnection, OnGatewayDisconnect {
  constructor(
    private readonly messagesService: MessagesService <--- this leads to crash
  ) { }

  private readonly logger = new Logger();

  afterInit(server: any) {
    this.logger.log('afterInit'); <--- TypeError: Cannot read property 'log' of undefined
    this.messagesService.saveInstance() <--- This won't work too: TypeError: Cannot read property 'saveInstance' of undefined
  }
}



/modules/messages.module.ts

@Module({
	imports: [TypeOrmModule.forFeature([MessageEntity])],
	controllers: [MessagesController],
	providers: [MessagesService],
	exports: [MessagesService],
})
export class MessagesModule { }



/app.module.ts

@Module({
	imports: [MessagesModule,],
	providers: [SocketGateway],
	exports: [],
})
export class AppModule { }

```

## Expected behavior

The `MessagesService` should be available in the Gateway

## Possible Solution

Did not find any possible solution for now.

## Environment

<pre><code>
Nest version: 7.0.0

 
For Tooling issues:
- Node version: 14.6.0
- Platform: Mac

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by hassan-badat** [comment]
Is there a solution to this?

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
