### ISSUE TITLE
FastifyError message/statusCode is ignored

### ISSUE THREAD

**Issue by mohd-akram** [nestjs/nest#5224]
## Current behavior
When Fastify throws an error, it adds the `statusCode` field to the error object. NestJS ignores this field (and the error message) and always sets the response code to 500.

## Input Code

[Repo](https://github.com/mohd-akram/nestjs-swagger-typeorm-repro)

`npm run start:dev`, then `curl -da=b localhost:3000`

## Expected behavior
The `statusCode` and error message are passed through.

## Environment

<pre><code>
Nest version: 7.0.0

</code></pre>

**Comment by kamilmysliwiec** [comment]
Can you please provide more information?

**Comment by mohd-akram** [comment]
When I do a `curl -da=b localhost:3000` on the linked repo, I get this response:

```
{"statusCode":500,"message":"Internal server error"}
```

And the log shows this:

```
FastifyError: Unsupported Media Type: application/x-www-form-urlencoded
    at ContentTypeParser.run (/home/mohamed/Development/nest-fastify-statuscode/node_modules/fastify/lib/contentTypeParser.js:95:16)
    at handleRequest (/home/mohamed/Development/nest-fastify-statuscode/node_modules/fastify/lib/handleRequest.js:35:39)
    at runPreParsing (/home/mohamed/Development/nest-fastify-statuscode/node_modules/fastify/lib/route.js:358:5)
    at next (/home/mohamed/Development/nest-fastify-statuscode/node_modules/fastify/lib/hooks.js:155:7)
    at Object.runMiddie (/home/mohamed/Development/nest-fastify-statuscode/node_modules/middie/index.js:46:7)
    at hookIterator (/home/mohamed/Development/nest-fastify-statuscode/node_modules/fastify/lib/hooks.js:218:10)
    at next (/home/mohamed/Development/nest-fastify-statuscode/node_modules/fastify/lib/hooks.js:159:20)
    at hookRunner (/home/mohamed/Development/nest-fastify-statuscode/node_modules/fastify/lib/hooks.js:178:3)
    at Object.routeHandler [as handler] (/home/mohamed/Development/nest-fastify-statuscode/node_modules/fastify/lib/route.js:326:7)
    at Router.lookup (/home/mohamed/Development/nest-fastify-statuscode/node_modules/find-my-way/index.js:351:14)
```

The response should instead be:

```
{"statusCode":415,"message":"Unsupported Media Type"}
```

The `FastifyError` thrown by fastify has `statusCode` and `message` properties with the correct values, but the default exception filter seems to ignore them and returns a generic response instead.

**Comment by underfisk** [comment]
After upgrading to the latest version of Fastify adapter/Core, it got unsupported media also for Posts but since Nestjs provides an abstracted adapter it should manage that.
@kamilmysliwiec From what i read about the new formbody, they only parse application/json media and other media types need to be explicitly enabled on the plugin

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/5990
