### ISSUE TITLE
express_1.default is not a function using Nestjs with ExpressAdapter

### ISSUE THREAD

**Issue by koolamusic** [nestjs/nest#5356]
## Current behavior

Trying the use the recipe for running multiple servers in nest according to this FAQ https://docs.nestjs.com/faq/multiple-servers

## Terminal response

```sh
(node:6955) UnhandledPromiseRejectionWarning: TypeError: express_1.default is not a function
    at fun (/home/koolamusic/Tmp/cube-api-nest/dist/main.js:10:37)
    at Object.<anonymous> (/home/koolamusic/Tmp/cube-api-nest/dist/main.js:15:1)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
(node:6955) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6955) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```ts  main.ts
import { INestApplication } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { ExpressAdapter } from '@nestjs/platform-express';
import http from 'http';
import fs from 'fs';

/* ----Middleware---- */
import express, { Application, Request, Response } from 'express';


import { AppModule as ApplicationModule } from './app.module';

const httpsOptions = {
	key: fs.readFileSync('./secrets/private-key.pem'),
	cert: fs.readFileSync('./secrets/public-certificate.pem')
};

async function bootstrap() {
	const server: Application = express();
	const app = await NestFactory.create(ApplicationModule, new ExpressAdapter(server));
	await app.init();

	http.createServer(server).listen(3000);
	  https.createServer(httpsOptions, server).listen(443);
}
bootstrap();

```

## Expected behavior
Should have had Nestjs up and running

## Possible Solution
Add new recipes on the docs for running multiple express servers or using middlewares

## Environment

<pre><code>
packages from package.json
```json
 "@nestjs/common": "^7.0.0",
    "@nestjs/core": "^7.0.0",
    "@nestjs/platform-express": "^7.4.3",
    "express": "^4.17.1",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^6.5.4"
```

For Tooling issues:
- Node version: v12.14.1
- Platform:  Linux

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
