### ISSUE TITLE
FastifyAdapter is not normalizing the global prefix (using nestjs-pino)

### ISSUE THREAD

**Issue by antoinedmc** [nestjs/nest#5568]
## Current behavior

When I try to use the `nestjs-pino` Logger, the global prefix normalization by FastifyAdapter does not fit.
It does not remove `/` and `*` at the beginning and at the end of the global prefix.
Example: `/v1*` is normalized as `/v1*`.

## Error

The following error occurs when the app performs the routes resolvers

```
(node:22261) UnhandledPromiseRejectionWarning: TypeError: Unexpected MODIFIER at 12, expected END
    at mustConsume (/Users/antoinedmc/Projects/frizbiz/frizbiz-pro-back/node_modules/middie/node_modules/path-to-regexp/src/index.ts:157:11)
    at parse (/Users/antoinedmc/Projects/frizbiz/frizbiz-pro-back/node_modules/middie/node_modules/path-to-regexp/src/index.ts:228:5)
    at stringToRegexp (/Users/antoinedmc/Projects/frizbiz/frizbiz-pro-back/node_modules/middie/node_modules/path-to-regexp/src/index.ts:495:25)
    at pathToRegexp (/Users/antoinedmc/Projects/frizbiz/frizbiz-pro-back/node_modules/middie/node_modules/path-to-regexp/src/index.ts:617:10)
    at Object.use (/Users/antoinedmc/Projects/frizbiz/frizbiz-pro-back/node_modules/middie/engine.js:23:16)
    at Object.use (/Users/antoinedmc/Projects/frizbiz/frizbiz-pro-back/node_modules/middie/index.js:30:21)
    at /Users/antoinedmc/Projects/frizbiz/frizbiz-pro-back/node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.js:131:27
    at MiddlewareModule.registerHandler (/Users/antoinedmc/Projects/frizbiz/frizbiz-pro-back/node_modules/@nestjs/core/middleware/middleware-module.js:138:9)
    at MiddlewareModule.bindHandler (/Users/antoinedmc/Projects/frizbiz/frizbiz-pro-back/node_modules/@nestjs/core/middleware/middleware-module.js:96:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at /Users/antoinedmc/Projects/frizbiz/frizbiz-pro-back/node_modules/@nestjs/core/middleware/middleware-module.js:84:13
    at async Promise.all (index 0)
    at MiddlewareModule.registerRouteMiddleware (/Users/antoinedmc/Projects/frizbiz/frizbiz-pro-back/node_modules/@nestjs/core/middleware/middleware-module.js:78:9)
    at registerRouteMiddleware (/Users/antoinedmc/Projects/frizbiz/frizbiz-pro-back/node_modules/@nestjs/core/middleware/middleware-module.js:71:13)
    at async Promise.all (index 0)
    at MiddlewareModule.registerMiddlewareConfig (/Users/antoinedmc/Projects/frizbiz/frizbiz-pro-back/node_modules/@nestjs/core/middleware/middleware-module.js:73:9)
```

## Input Code

```ts
import { Logger } from 'nestjs-pino';
import { FastifyAdapter } from '@nestjs/platform-fastify';

    ...

async function bootstrap() {
    const fastifyAdapter = new FastifyAdapter();
    const app = await NestFactory.create(AppModule, fastifyAdapter, {
        logger: false,
      });
    app.useLogger(app.get(Logger));

    ...

}
bootstrap();

```

## Expected behavior

The global prefix normalization by FastifyAdapter may remove `/` and `*` at the beginning and at the end of the global prefix.
Example: `/v1*` may be normalized as `v1`.

## Possible Solution

The above solution worked for us.

In `package/platform-fastify/adapters/fastify-adapter.ts`

Update line 265

`const normalizedPath = path === '/*' ? '' : path;`

Into

`const normalizedPath = path.substring(1, path.length - 1);`

## Environment
<pre><code>
Node version: 12.18.4
Nest version: 7.4.4
Fastify version: 3.6.0
nestjs-pino version 1.2.0
</code></pre>

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository

**Comment by antoinedmc** [comment]
Hi @jmcdo29, here is a repository to reproduce the error.

https://github.com/antoinedmc/fastify-adapter-bug

Creating this repo I found that `nestjs-pino` uses `@nestjs/common` and `@nestjs/core` v6.6.7 but `@nestjs/fastify-platform` v7.0.0, so I fixed all these versions to v7.4.4. The problem still exists.

**Comment by jmcdo29** [comment]
It looks like the problem is how `nest-pino` [sets up the middleware to run on the routes](https://github.com/iamolegga/nestjs-pino/blob/master/src/LoggerCoreModule.ts#L20). Nest even has it documented that for Fastify, instead of using `'*'` the `forRoutes` should use `(.*)`. It looks like you can set this yourself in one of the module's options.

**Comment by antoinedmc** [comment]
Ok, I set up the `forRoutes` with `(.*)` and it solved the problem. Thank you @jmcdo29 !
