### ISSUE TITLE
NATS event handler throw an error when no response subject provided

### ISSUE THREAD

**Issue by borovik96** [nestjs/nest#5575]
## Bug Report
Relates to https://github.com/nestjs/nest/issues/4874

## Current behavior
When an event subscriber using @MessagePattern() gets request without reply subject an error will be thrown from NATS that the subject is missing.

```
/tmp/node_modules/nats/lib/nats.js:1619
      throw (new NatsError(BAD_SUBJECT_MSG, BAD_SUBJECT))
      ^
NatsError: Subject must be supplied
    at Client.publish (/tmp/node_modules/nats/lib/nats.js:1619:14)
    at /tmp/node_modules/@nestjs/microservices/server/server-nats.js:77:30
    at /tmp/node_modules/@nestjs/microservices/server/server.js:37:50
    at Array.forEach (<anonymous>)
    at /tmp/node_modules/@nestjs/microservices/server/server.js:37:32
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  code: 'BAD_SUBJECT',
  chainedError: undefined
}
```

## Input Code
```ts
@MessagePattern('message')
async messageListener(@Payload() data): Promise<void> {
  console.log('data', data);
}
```

## Expected behavior
Controllers with decorator `MessagePattern` can handle not only request/reply messages but also messages with no reply channel (pub/sub).

## Possible Solution
https://github.com/nestjs/nest/pull/5530

## Environment

<pre><code>
Nest version: 7.2.0
 
For Tooling issues:
- Node version: v12.19.0
- Platform:  Mac, Linux
</code></pre>

**Comment by borovik96** [comment]
Fixed in https://github.com/nestjs/nest/pull/5530
