### ISSUE TITLE
Error thrown from inside catch block during shutdown

### ISSUE THREAD

**Issue by almarro1** [nestjs/nest#5669]
## Bug Report
In some cases, with the shutdown hooks enabled, the ```listenToShutDownSignals``` method fails leaving the app in a zombie state.

## Current behavior
The error that shows up on the console says: 
```
(node:11188) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'stack' of undefined
    at process.cleanup (...\node_modules\@nestjs\core\nest-application-context.js:134:87)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:11188) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 15)
(node:11188) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
After some debugging, the problem is located in the catch block of the mentioned function:
 ```
/**
     * Listens to shutdown signals by listening to
     * process events
     *
     * @param {string[]} signals The system signals it should listen to
     */
    listenToShutdownSignals(signals) {
        const cleanup = async (signal) => {
            try {
                signals.forEach(sig => process.removeListener(sig, cleanup));
                await this.callDestroyHook();
                await this.callBeforeShutdownHook(signal);
                await this.dispose();
                await this.callShutdownHook(signal);
                process.kill(process.pid, signal);
            }
            catch (err) {
                common_1.Logger.error(constants_1.MESSAGES.ERROR_DURING_SHUTDOWN, err.stack, NestApplicationContext.name);
                console.error(err);
                process.exit(1);
            }
        };
        this.shutdownCleanupRef = cleanup;
        signals.forEach((signal) => {
            this.activeShutdownSignals.push(signal);
            process.on(signal, cleanup);
        });
    }
``` 

since ```err``` is undefined and the expression ```err.stack``` throws another error.

## Expected behavior

The catch block should not throw additional exceptions

## Possible Solution

To verify the err variable is defined.

## Environment

<pre><code>
Nest version: 7.5.1

For Tooling issues:
- Node version:12.17.0
- Platform:  Win10 64Bits

</code></pre>

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue? Changing `err.stack` to `err?.stack` should be enough

**Comment by almarro1** [comment]
> Would you like to create a PR for this issue? Changing `err.stack` to `err?.stack` should be enough

Done.

**Comment by kamilmysliwiec** [comment]
Lets track this here https://github.com/nestjs/nest/pull/5670
