### ISSUE TITLE
UnhandledPromiseRejectionWarning upon deleting queue using RabbitMQ Microservice

### ISSUE THREAD

**Issue by zvaehn** [nestjs/nest#5683]
## Bug Report

```
(node:16452) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'content' of 'message' as it is null.
    at ServerRMQ.handleMessage (/Users/user/custom-nest-project/nest-microservice-error/node_modules/@nestjs/microservices/server/server-rmq.js:71:17)
    at channel.consume.noAck.noAck (/Users/user/custom-nest-project/nest-microservice-error/node_modules/@nestjs/microservices/server/server-rmq.js:65:51)
    at ConfirmChannel.BaseChannel.dispatchMessage (/Users/user/custom-nest-project/nest-microservice-error/node_modules/amqplib/lib/channel.js:484:12)
    at ConfirmChannel.BaseChannel.handleCancel (/Users/user/custom-nest-project/nest-microservice-error/node_modules/amqplib/lib/channel.js:497:15)
    at ConfirmChannel.emit (events.js:310:20)
    at ConfirmChannel.C.accept (/Users/user/custom-nest-project/nest-microservice-error/node_modules/amqplib/lib/channel.js:409:17)
    at Connection.mainAccept [as accept] (/Users/user/custom-nest-project/nest-microservice-error/node_modules/amqplib/lib/connection.js:64:33)
    at Socket.go (/Users/user/custom-nest-project/nest-microservice-error/node_modules/amqplib/lib/connection.js:478:48)
    at Socket.emit (events.js:310:20)
    at emitReadable_ (_stream_readable.js:543:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
(node:16452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16452) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Current behavior

If the RabbitMQ microservice is connected and the queue gets deleted the error message pops up.
I found no way to catch this exception.

## Input Code

Zipped Code:
[nest-microservice-error.zip](https://github.com/nestjs/nest/files/5517075/nest-microservice-error.zip)

Repository:
https://github.com/zvaehn/nestjs-5683-reproduction-setup

run it by:
- npm install
- docker-compose up
- npm run start:dev

## Expected behavior

If you kill the custom_queue via lets say http://localhost:15672/#/queues the error message appears.
The application is still running though, but does not reassign the queue.

## Possible Solution

I'd like to catch and react on this error.

## Environment
<pre><code>
"@nestjs/common": "^7.5.1",
"@nestjs/core": "^7.5.1",
"@nestjs/microservices": "^7.5.1",
"@nestjs/platform-express": "^7.5.1",
"amqp-connection-manager": "^3.2.1",
"amqplib": "^0.6.0",
</code></pre>

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository (as a Github/Gitlab repo)

**Comment by zvaehn** [comment]
I've updated the Issue Description.
(https://github.com/zvaehn/nestjs-5683-reproduction-setup)

**Comment by zvaehn** [comment]
Did you have a change to have a look at it?

**Comment by poulad** [comment]
I also faced this issue. Looking into a PR at the moment.
Since NestJS is using [`amqp-connection-manager`], I expect it to run the `setup` function again which means deleted queue will be declared again based on the configurations provided.

[`amqp-connection-manager`]: https://github.com/jwalton/node-amqp-connection-manager

**Comment by poulad** [comment]
I'm not sure if this is a expected behavior according to AMQP or RabbitMQ docs. Passing a `null` message to the callback like this could also be a bug in [`amqplib`] package.

[`amqplib`]: https://github.com/squaremo/amqp.node

**Comment by poulad** [comment]
Never mind, `amqplib` is behaving as expected according to its docs.

See [Channel#consume]
> If the consumer is cancelled by RabbitMQ, the message callback will be invoked with null.

Also see squaremo/amqp.node#497

[Channel#consume]: https://www.squaremobius.net/amqp.node/channel_api.html#channel_consume
