### ISSUE TITLE
@nestjs/mongoose Populate does not work on field having array of ObjectIds

### ISSUE THREAD

**Issue by baharalidurrani** [nestjs/nest#5716]
## Current behavior
While following Nest docs regarding to [MongoDB](https://docs.nestjs.com/techniques/mongodb#model-injection) and mongoose, [mongoose.populate()](https://mongoosejs.com/docs/populate.html) does not work for an array of ObjectIds of a specific Collection. 

## Input Code
Quoting official [Docs](https://docs.nestjs.com/techniques/mongodb#model-injection):

> In case there are multiple owners, your property configuration should look as follows:

```ts
@Prop({ type: [Types.ObjectId], ref: Owner.name })
owner: Owner[];
```

## Expected behavior
Now if I run
```ts
const catWithOwners = await catModel.findById(id).populate('owner');
```
I should get a cat document with a populated list for all the related Owners.
But instead, get an empty array.

## Possible Solution
After a lot of hit and trial, I changed the model to:
```ts
@Prop({ type: [{ type: Types.ObjectId, ref: Owner.name }] })
owner: Owner[];
```
and now the populate method started working.
My final model is something like:
```ts
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';
import { ICat } from 'src/types';
import { Owner } from './owner.schema';

export type CatDocument = Cat & Document;

@Schema()
export class Cat implements ICat {
  @Prop()
  name: string;

  @Prop({ type: [{ type: Types.ObjectId, ref: Owner.name }] })
  owner: Owner[];
}

export const CatSchema = SchemaFactory.createForClass(Cat);
```
I request updating the docs or fixing the bug.

## Environment

<pre><code>
"@nestjs/core": "^7.5.1",
"@nestjs/mongoose": "^7.0.3",
 
For Tooling issues:
- Node version: v14.15.0
- Platform:  Linux, ubuntu 20.04

</code></pre>

**Comment by jmcdo29** [comment]
Would you like to make a PR to update the docs?

**Comment by kamilmysliwiec** [comment]
Fixed

**Comment by baharalidurrani** [comment]
Thanks, @kamilmysliwiec 
The [change](https://github.com/nestjs/docs.nestjs.com/commit/5ff5ffc788464ca925587d69695dc2a282e05d4f) is live now.

**Comment by har17bar** [comment]
Environment:
 ```
node-version: v14.15.1
Ubuntu 18.04.5 LTS
"@nestjs/core": "^7.5.5",
    "@nestjs/mongoose": "^7.1.2",`
````
conversatiom.schema.ts
```
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';
import { CONVERSATION_STATUS } from './conversation-status.constant';
import { Tag } from '../tag/tag.schema';

export type ConversationDocument = Conversation & Document;

@Schema()
export class Conversation {
  @Prop({ required: true })
  _id: Types.ObjectId;

  @Prop({ required: true })
  workspace: Types.ObjectId;

  @Prop()
  assignee?: string;

  @Prop({ default: false })
  priority?: boolean;

  @Prop({
    default: CONVERSATION_STATUS.OPEN,
    enum: [CONVERSATION_STATUS.OPEN, CONVERSATION_STATUS.CLOSED, CONVERSATION_STATUS.REOPENED]
  })
  status?: CONVERSATION_STATUS;

  @Prop({ type: [{ type: Types.ObjectId, ref: Tag.name }]})
  tags?: Tag[] | Types.ObjectId[];

  @Prop({ required: true })
  createdBy: string;

  @Prop({ default: new Date() })
  createdAt?: Date;

  @Prop()
  updatedBy?: string;

  @Prop()
  updatedAt?: Date;
}

export const ConversationSchema = SchemaFactory.createForClass(Conversation);

```
tag.schema.ts
```
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

export type TagDocument = Tag & Document;

@Schema()
export class Tag {
  @Prop({ required: true })
  value: string;

  @Prop({ required: true })
  createdBy: string;

  @Prop({ default: new Date() })
  createdAt?: Date;
}

export const TagSchema = SchemaFactory.createForClass(Tag);


```
error:

```
stdout: [Nest] 152   - 11/30/2020, 1:26:46 PM   [RpcExceptionsHandler] Schema hasn't been registered for model "Tag".
Use mongoose.model(name, schema) +7158ms

stdout: MissingSchemaError: Schema hasn't been registered for model "Tag".
Use mongoose.model(name, schema)
    at NativeConnection.Connection.model (/app/node_modules/mongoose/lib/connection.js:1195:11)
    at getModelsMapForPopulate (/app/node_modules/mongoose/lib/helpers/populate/getModelsMapForPopulate.js:285:59)
    at populate (/app/node_modules/mongoose/lib/model.js:4321:21)
    at _populate (/app/node_modules/mongoose/lib/model.js:4291:5)
    at /app/node_modules/mongoose/lib/model.js:4267:5
    at promiseOrCallback (/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:9:12)
    at Function.Model.populate (/app/node_modules/mongoose/lib/model.js:4265:10)
    at cb (/app/node_modules/mongoose/lib/query.js:1946:17)
    at /app/node_modules/mongodb/lib/utils.js:674:5
    at handleCallback (/app/node_modules/mongodb/lib/utils.js:102:55)
    at /app/node_modules/mongodb/lib/cursor.js:838:66
    at /app/node_modules/mongodb/lib/utils.js:674:5
    at /app/node_modules/mongodb/lib/cursor.js:923:9
    at Cursor._endSession (/app/node_modules/mongodb/lib/core/cursor.js:394:7)
    at /app/node_modules/mongodb/lib/cursor.js:921:12
    at maybePromise (/app/node_modules/mongodb/lib/utils.js:662:3)
```
