### ISSUE TITLE
TypeError: domain.enter is not a function

### ISSUE THREAD

**Issue by SDAdham** [nestjs/nest#5985]
## Bug Report
I am experiencing a bug for > 4 days and I can't get around it.

## Current behavior

Any controller returns result, I'd see in the console the following stacktrace with no further details:
```
domain.js:547
  domain.enter();
         ^

TypeError: domain.enter is not a function
    at IncomingMessage.EventEmitter.emit (domain.js:547:10)
    at resume_ (_stream_readable.js:972:10)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
I can't find the root cause or whose reporting this stacktrace. but 2 things I noticed:

* Winston is not seeing that error and it's not reporting it, because the error is not reported within such line`[NestWinston] Info      12/20/2020, 8:36:04 PM log info`, it just simply crash with the error written with no nestjs or anything in it.
* API is no longer working after this happens.

I am just starting the application normally using `nest start -w`

`main.ts` doesnt' have anything interesting than what is mentioned in the documentation, this error started happening after migrating from `typeorm` to mikro-orm`, but `mikro-orm` team confirmed it's not related to them see https://github.com/mikro-orm/mikro-orm/issues/1220 . 🤷‍♂️

I am using `nestjs mysql session`, please see my `package.json`  dependencies below for details of what packages i'm using.

What is leading to it, no idea. The stack trace is very generic. and click on file `domain.js:547:10` is not working as if the file doesn't exist.

I turned on silly debugging but again no details on what's happening to lead to this.
I checked https://docs.nestjs.com/faq/request-lifecycle#summary where I can understand at which point this is happening:
```
Incoming request
Globally bound middleware
Module bound middleware << Used
Global guards
Controller guards
Route guards
Global interceptors (pre-controller)
Controller interceptors (pre-controller)
Route interceptors (pre-controller)
Global pipes
Controller pipes
Route pipes
Route parameter pipes
Controller (method handler) << used (returns but no response can be observed from the browser - the error happens after the return)
Service (if exists)
Route interceptor (post-request)
Controller interceptor (post-request)
Global interceptor (post-request)
Exception filters (route, then controller, then global)
Server response
```
## Input Code

No specific code that reproduces it and I don't know where.

```ts
const your = (code) => here;
```

## Expected behavior
The controller should be able to return, I can confirm that the controller must be returning something but something happens wrong in-between the controller and the response.

```
controller {
  someMethod() {
     .... some code
     console.log('return is going to happen'); // this is how i confirmed
     return something;
  }
}
```

## Possible Solution

I need help in finding a way to know why is this error happening?

## Environment

Here is project dependencies, i tried both node versions 12 and 14:
```
 "dependencies": {
    "@angular/animations": "~10.1.4",
    "@angular/cdk": "^10.2.3",
    "@angular/common": "~10.1.4",
    "@angular/compiler": "~10.1.4",
    "@angular/core": "~10.1.4",
    "@angular/forms": "~10.1.4",
    "@angular/localize": "^10.0.4",
    "@angular/material": "^10.2.3",
    "@angular/platform-browser": "~10.1.4",
    "@angular/platform-browser-dynamic": "~10.1.4",
    "@angular/router": "~10.1.4",
    "@fortawesome/angular-fontawesome": "^0.7.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.30",
    "@fortawesome/free-brands-svg-icons": "^5.14.0",
    "@fortawesome/free-regular-svg-icons": "^5.14.0",
    "@fortawesome/free-solid-svg-icons": "^5.14.0",
    "@mikro-orm/core": "^4.3.4",
    "@mikro-orm/mariadb": "^4.3.4",
    "@mikro-orm/mysql": "^4.3.4",
    "@mikro-orm/nestjs": "^4.2.0",
    "@mikro-orm/reflection": "^4.3.4",
    "@mikro-orm/sql-highlighter": "^1.0.1",
    "@nestjs/common": "^7.5.1",
    "@nestjs/core": "^7.5.1",
    "@nestjs/passport": "^7.1.0",
    "@nestjs/platform-express": "^7.5.1",
    "@nestjs/schedule": "^0.4.1",
    "@nestjs/swagger": "^4.6.1",
    "@ng-bootstrap/ng-bootstrap": "^7.0.0",
    "@tinymce/tinymce-angular": "^4.1.0",
    "angular-calendar": "^0.28.16",
    "angular-google-charts": "^1.1.4",
    "basic-auth": "^2.0.1",
    "bootstrap": "^4.5.0",
    "class-transformer": "^0.3.1",
    "class-validator": "^0.12.2",
    "clipboard": "^2.0.6",
    "cookie-parser": "^1.4.5",
    "core-js": "^3.6.5",
    "credit-card-type": "^9.1.0",
    "cryptojs": "^2.5.3",
    "date-fns": "^2.15.0",
    "express": "^4.17.1",
    "express-list-routes": "^0.1.4",
    "express-mysql-session": "^2.1.4",
    "express-session": "^1.17.1",
    "font-awesome": "^4.7.0",
    "helmet": "^4.1.1",
    "imap": "^0.8.19",
    "jquery": "^3.5.1",
    "locutus": "^2.0.14",
    "mermaid": "^8.6.0",
    "mikro-orm": "^4.3.4",
    "monaco-editor": "^0.20.0",
    "mysql": "^2.18.1",
    "nest-winston": "^1.4.0",
    "nestjs-mikro-orm": "^1.0.3",
    "nestjs-session": "^1.0.1",
    "ng-pick-datetime": "^7.0.0",
    "ngx-avatar": "^4.0.0",
    "ngx-bootstrap": "^5.6.1",
    "ngx-clipboard": "^13.0.1",
    "ngx-cookie-service": "^3.0.4",
    "ngx-monaco-editor": "^9.0.0",
    "node-cryptojs-aes": "^0.4.0",
    "passport": "^0.4.1",
    "passport-local": "^1.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "~6.6.0",
    "swagger-ui-express": "^4.1.4",
    "tslib": "^2.0.0",
    "winston": "^3.3.3",
    "xlsx": "^0.16.8",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1001.4",
    "@angular/cli": "~10.1.4",
    "@angular/compiler-cli": "~10.1.4",
    "@angular/language-service": "^10.0.4",
    "@compodoc/compodoc": "^1.1.11",
    "@nestjs/cli": "^7.5.1",
    "@nestjs/schematics": "^7.1.3",
    "@nestjs/testing": "^7.5.1",
    "@types/clipboard": "^2.0.1",
    "@types/cryptojs": "^3.1.29",
    "@types/express": "^4.17.3",
    "@types/express-session": "^1.17.3",
    "@types/imap": "^0.8.31",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/jest": "26.0.10",
    "@types/jquery": "^3.5.4",
    "@types/jqueryui": "^1.12.13",
    "@types/node": "12.12.41",
    "@types/passport-local": "^1.0.33",
    "@types/supertest": "^2.0.8",
    "@types/webpack-env": "^1.15.3",
    "@typescript-eslint/eslint-plugin": "3.9.1",
    "@typescript-eslint/parser": "3.9.1",
    "codelyzer": "^6.0.0",
    "eslint": "7.7.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-import": "^2.20.1",
    "eslint-plugin-prettier": "^3.1.3",
    "husky": "^4.2.5",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "jest": "26.4.2",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "npm-run-all": "^4.1.5",
    "prettier": "^1.19.1",
    "pretty-quick": "^2.0.1",
    "protractor": "~7.0.0",
    "supertest": "^4.0.2",
    "ts-jest": "26.2.0",
    "ts-loader": "^6.2.1",
    "ts-node": "9.0.0",
    "tsconfig-paths": "^3.9.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2",
    "wait-on": "^5.2.0",
    "webpack-env": "^0.8.0"
  },
```

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository.

**Comment by kamilmysliwiec** [comment]
Likewise, there's no such code in NestJS so this isn't caused by the framework. 

Please, use [StackOverflow](https://stackoverflow.com/questions/tagged/nestjs) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by SDAdham** [comment]
Hello Kamilmysliwiec, I have already asked the question on stackoverflow here https://stackoverflow.com/questions/65367533/typeerror-domain-enter-is-not-a-function

Please leave this issue open as i am trying to create a minimum version of the issue. At worst case scenario, may i maybe please ask for a zoom meeting if it's ok?

**Comment by jmcdo29** [comment]
I'll take a quick look if you can provide something, but Nest doesn't do anything with `domain.enter()` directly. According to Node's documentation, this is used under the hood by `bind()`, `run()`, and `apply()` methods. Without a reproduction, there isn't much more to say.

**Comment by SDAdham** [comment]
Ok, I'll send a zoom meeting jmcdo29, one moment pls

**Comment by SDAdham** [comment]
please join https://us04web.zoom.us/j/79003811925?pwd=R21wSUYyUUFpSUNLYXBFUU1hLy83Zz09

**Comment by jmcdo29** [comment]
Not a zoom meeting. A minimum reproduction. If you can't boil it down to the simplest possible reproduction of the problem, we won't know where to begin on isolating the problem

**Comment by SDAdham** [comment]
I am really trying my best to get a reproducer, the problem is that it's not a small project and the error is unpredictable, it happens at a lot of areas, but one thing for sure, it happens with a controller return results

**Comment by SDAdham** [comment]
a 15 minutes of your time @jmcdo29 would be  a lot appreciated... I'll try to be very quick and short.

**Comment by jmcdo29** [comment]
> the problem is that it's not a small project and the error is unpredictable

And so you want us to take a look through everything and sift through for what's causing the error (even though it's probably not related to Nest)?

> 15 minutes of your time...

I've told you what I need to work with this. Either you can provide it, and I'll take a look, or you can't and I won't.

**Comment by SDAdham** [comment]
No, what I'm hopping is that you might know how can I debug the area where a controller returns the results, this might help me dig more deeper and find out what is the problem

**Comment by SDAdham** [comment]
I was able to finally capture full stacktrace:
```
Zone.runTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:192)
ZoneTask.invokeTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:503)
ZoneTask.invoke (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:492)
data.args.<computed> (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:1444)
processTicksAndRejections (<node_internals>/internal/process/task_queues.js:84)
TickObject (Unknown Source:1)
init (<node_internals>/internal/inspector_async_hook.js:25)
emitInitNative (<node_internals>/internal/async_hooks.js:195)
emitInitScript (<node_internals>/internal/async_hooks.js:401)
nextTick (<node_internals>/internal/process/task_queues.js:135)
scheduleTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:1445)
ZoneDelegate.scheduleTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:407)
Zone.scheduleTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:231)
Zone.scheduleMicroTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:251)
<anonymous> (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:1451)
proto.<computed> (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:1411)
resume (<node_internals>/_stream_readable.js:976)
Readable.resume (<node_internals>/_stream_readable.js:967)
_dump (<node_internals>/_http_incoming.js:289)
resOnFinish (<node_internals>/_http_server.js:683)
ZoneDelegate.invokeTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:421)
Zone.runTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:188)
ZoneTask.invokeTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:503)
ZoneTask.invoke (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:492)
emit (<node_internals>/events.js:314)
EventEmitter.emit (<node_internals>/domain.js:483)
onFinish (<node_internals>/_http_outgoing.js:735)
afterWrite (<node_internals>/_stream_writable.js:490)
afterWriteTick (<node_internals>/_stream_writable.js:477)
ZoneDelegate.invokeTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:421)
Zone.runTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:188)
ZoneTask.invokeTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:503)
ZoneTask.invoke (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:492)
data.args.<computed> (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:1444)
processTicksAndRejections (<node_internals>/internal/process/task_queues.js:83)
TickObject (Unknown Source:1)
init (<node_internals>/internal/inspector_async_hook.js:25)
emitInitNative (<node_internals>/internal/async_hooks.js:195)
emitInitScript (<node_internals>/internal/async_hooks.js:401)
nextTick (<node_internals>/internal/process/task_queues.js:135)
scheduleTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:1445)
ZoneDelegate.scheduleTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:407)
Zone.scheduleTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:231)
Zone.scheduleMicroTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:251)
<anonymous> (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:1451)
proto.<computed> (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:1411)
onwrite (<node_internals>/_stream_writable.js:467)
afterWriteDispatched (<node_internals>/internal/stream_base_commons.js:159)
writeGeneric (<node_internals>/internal/stream_base_commons.js:147)
Socket._writeGeneric (<node_internals>/net.js:787)
Socket._write (<node_internals>/net.js:799)
doWrite (<node_internals>/_stream_writable.js:403)
clearBuffer (<node_internals>/_stream_writable.js:542)
Writable.uncork (<node_internals>/_stream_writable.js:338)
end (<node_internals>/_http_outgoing.js:787)
end (<ProjectDir>\node_modules\express-session\index.js:355)
send (<ProjectDir>\node_modules\express\lib\response.js:221)
reply (<ProjectDir>\node_modules\@nestjs\platform-express\adapters\express-adapter.js:22)
apply (<ProjectDir>\node_modules\@nestjs\core\router\router-response-controller.js:13)
<anonymous> (<ProjectDir>\node_modules\@nestjs\core\router\router-execution-context.js:173)
processTicksAndRejections (<node_internals>/internal/process/task_queues.js:97)
async function (Unknown Source:1)
<anonymous> (<ProjectDir>\node_modules\@nestjs\core\router\router-execution-context.js:47)
processTicksAndRejections (<node_internals>/internal/process/task_queues.js:97)
async function (Unknown Source:1)
<anonymous> (<ProjectDir>\node_modules\@nestjs\core\router\router-proxy.js:9)
handle (<ProjectDir>\node_modules\express\lib\router\layer.js:95)
next (<ProjectDir>\node_modules\express\lib\router\route.js:137)
dispatch (<ProjectDir>\node_modules\express\lib\router\route.js:112)
handle (<ProjectDir>\node_modules\express\lib\router\layer.js:95)
<anonymous> (<ProjectDir>\node_modules\express\lib\router\index.js:281)
process_params (<ProjectDir>\node_modules\express\lib\router\index.js:335)
next (<ProjectDir>\node_modules\express\lib\router\index.js:275)
use (c:\apps\api\src\modules\workspace\modules\website-management\middlewares\website-switcher.middleware.ts:47)
processTicksAndRejections (<node_internals>/internal/process/task_queues.js:97)
async function (Unknown Source:1)
<anonymous> (<ProjectDir>\node_modules\@nestjs\core\router\router-proxy.js:9)
handle (<ProjectDir>\node_modules\express\lib\router\layer.js:95)
trim_prefix (<ProjectDir>\node_modules\express\lib\router\index.js:317)
<anonymous> (<ProjectDir>\node_modules\express\lib\router\index.js:284)
param (<ProjectDir>\node_modules\express\lib\router\index.js:354)
param (<ProjectDir>\node_modules\express\lib\router\index.js:365)
process_params (<ProjectDir>\node_modules\express\lib\router\index.js:410)
next (<ProjectDir>\node_modules\express\lib\router\index.js:275)
use (c:\apps\api\src\modules\workspace\modules\security\middlewares\access-control-permissions-verification.middleware.ts:77)
<anonymous> (<ProjectDir>\node_modules\@nestjs\core\router\router-proxy.js:9)
handle (<ProjectDir>\node_modules\express\lib\router\layer.js:95)
trim_prefix (<ProjectDir>\node_modules\express\lib\router\index.js:317)
<anonymous> (<ProjectDir>\node_modules\express\lib\router\index.js:284)
param (<ProjectDir>\node_modules\express\lib\router\index.js:354)
param (<ProjectDir>\node_modules\express\lib\router\index.js:365)
process_params (<ProjectDir>\node_modules\express\lib\router\index.js:410)
next (<ProjectDir>\node_modules\express\lib\router\index.js:275)
use (c:\apps\api\src\modules\workspace\modules\information-technology\middlewares\domain-switcher.middleware.ts:36)
processTicksAndRejections (<node_internals>/internal/process/task_queues.js:97)
async function (Unknown Source:1)
<anonymous> (<ProjectDir>\node_modules\@nestjs\core\router\router-proxy.js:9)
handle (<ProjectDir>\node_modules\express\lib\router\layer.js:95)
trim_prefix (<ProjectDir>\node_modules\express\lib\router\index.js:317)
<anonymous> (<ProjectDir>\node_modules\express\lib\router\index.js:284)
param (<ProjectDir>\node_modules\express\lib\router\index.js:354)
param (<ProjectDir>\node_modules\express\lib\router\index.js:365)
process_params (<ProjectDir>\node_modules\express\lib\router\index.js:410)
next (<ProjectDir>\node_modules\express\lib\router\index.js:275)
use (c:\apps\api\src\modules\workspace\modules\research-and-development\middlewares\data-source-switcher.middleware.ts:80)
processTicksAndRejections (<node_internals>/internal/process/task_queues.js:97)
async function (Unknown Source:1)
<anonymous> (<ProjectDir>\node_modules\@nestjs\core\router\router-proxy.js:9)
handle (<ProjectDir>\node_modules\express\lib\router\layer.js:95)
trim_prefix (<ProjectDir>\node_modules\express\lib\router\index.js:317)
<anonymous> (<ProjectDir>\node_modules\express\lib\router\index.js:284)
param (<ProjectDir>\node_modules\express\lib\router\index.js:354)
param (<ProjectDir>\node_modules\express\lib\router\index.js:365)
process_params (<ProjectDir>\node_modules\express\lib\router\index.js:410)
next (<ProjectDir>\node_modules\express\lib\router\index.js:275)
use (c:\apps\api\src\modules\account\middlewares\user-switcher.middleware.ts:40)
<anonymous> (<ProjectDir>\node_modules\@nestjs\core\router\router-proxy.js:9)
handle (<ProjectDir>\node_modules\express\lib\router\layer.js:95)
trim_prefix (<ProjectDir>\node_modules\express\lib\router\index.js:317)
<anonymous> (<ProjectDir>\node_modules\express\lib\router\index.js:284)
param (<ProjectDir>\node_modules\express\lib\router\index.js:354)
param (<ProjectDir>\node_modules\express\lib\router\index.js:365)
process_params (<ProjectDir>\node_modules\express\lib\router\index.js:410)
next (<ProjectDir>\node_modules\express\lib\router\index.js:275)
Domain.run (<node_internals>/domain.js:371)
create (<ProjectDir>\node_modules\@mikro-orm\core\utils\RequestContext.js:28)
use (<ProjectDir>\node_modules\@mikro-orm\nestjs\mikro-orm.middleware.js:20)
<anonymous> (<ProjectDir>\node_modules\@nestjs\core\router\router-proxy.js:9)
handle (<ProjectDir>\node_modules\express\lib\router\layer.js:95)
trim_prefix (<ProjectDir>\node_modules\express\lib\router\index.js:317)
<anonymous> (<ProjectDir>\node_modules\express\lib\router\index.js:284)
param (<ProjectDir>\node_modules\express\lib\router\index.js:354)
param (<ProjectDir>\node_modules\express\lib\router\index.js:365)
process_params (<ProjectDir>\node_modules\express\lib\router\index.js:410)
next (<ProjectDir>\node_modules\express\lib\router\index.js:275)
session (<ProjectDir>\node_modules\express-session\index.js:182)
use (<ProjectDir>\node_modules\@nestjs\core\middleware\utils.js:43)
<anonymous> (<ProjectDir>\node_modules\@nestjs\core\router\router-proxy.js:9)
handle (<ProjectDir>\node_modules\express\lib\router\layer.js:95)
trim_prefix (<ProjectDir>\node_modules\express\lib\router\index.js:317)
<anonymous> (<ProjectDir>\node_modules\express\lib\router\index.js:284)
param (<ProjectDir>\node_modules\express\lib\router\index.js:354)
param (<ProjectDir>\node_modules\express\lib\router\index.js:365)
process_params (<ProjectDir>\node_modules\express\lib\router\index.js:410)
next (<ProjectDir>\node_modules\express\lib\router\index.js:275)
use (c:\Users\apps\api\src\middlewares\origin-fetcher.middleware.ts:51)
<anonymous> (<ProjectDir>\node_modules\@nestjs\core\router\router-proxy.js:9)
handle (<ProjectDir>\node_modules\express\lib\router\layer.js:95)
trim_prefix (<ProjectDir>\node_modules\express\lib\router\index.js:317)
<anonymous> (<ProjectDir>\node_modules\express\lib\router\index.js:284)
param (<ProjectDir>\node_modules\express\lib\router\index.js:354)
param (<ProjectDir>\node_modules\express\lib\router\index.js:365)
process_params (<ProjectDir>\node_modules\express\lib\router\index.js:410)
next (<ProjectDir>\node_modules\express\lib\router\index.js:275)
<anonymous> (c:\Users\apps\api\src\middlewares\request-context.middleware.ts:28)
ZoneDelegate.invoke (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:386)
Zone.run (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:143)
use (c:\Users\apps\api\src\middlewares\request-context.middleware.ts:26)
<anonymous> (<ProjectDir>\node_modules\@nestjs\core\router\router-proxy.js:9)
handle (<ProjectDir>\node_modules\express\lib\router\layer.js:95)
trim_prefix (<ProjectDir>\node_modules\express\lib\router\index.js:317)
<anonymous> (<ProjectDir>\node_modules\express\lib\router\index.js:284)
param (<ProjectDir>\node_modules\express\lib\router\index.js:354)
param (<ProjectDir>\node_modules\express\lib\router\index.js:365)
process_params (<ProjectDir>\node_modules\express\lib\router\index.js:410)
next (<ProjectDir>\node_modules\express\lib\router\index.js:275)
urlencodedParser (<ProjectDir>\node_modules\body-parser\lib\types\urlencoded.js:91)
handle (<ProjectDir>\node_modules\express\lib\router\layer.js:95)
trim_prefix (<ProjectDir>\node_modules\express\lib\router\index.js:317)
<anonymous> (<ProjectDir>\node_modules\express\lib\router\index.js:284)
process_params (<ProjectDir>\node_modules\express\lib\router\index.js:335)
next (<ProjectDir>\node_modules\express\lib\router\index.js:275)
jsonParser (<ProjectDir>\node_modules\body-parser\lib\types\json.js:110)
handle (<ProjectDir>\node_modules\express\lib\router\layer.js:95)
trim_prefix (<ProjectDir>\node_modules\express\lib\router\index.js:317)
<anonymous> (<ProjectDir>\node_modules\express\lib\router\index.js:284)
process_params (<ProjectDir>\node_modules\express\lib\router\index.js:335)
next (<ProjectDir>\node_modules\express\lib\router\index.js:275)
error (<ProjectDir>\node_modules\serve-static\index.js:121)
ZoneDelegate.invokeTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:421)
Zone.runTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:188)
ZoneTask.invokeTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:503)
ZoneTask.invoke (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:492)
emit (<node_internals>/events.js:314)
EventEmitter.emit (<node_internals>/domain.js:483)
error (<ProjectDir>\node_modules\send\index.js:270)
onStatError (<ProjectDir>\node_modules\send\index.js:421)
next (<ProjectDir>\node_modules\send\index.js:735)
onstat (<ProjectDir>\node_modules\send\index.js:724)
ZoneDelegate.invokeTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:421)
Zone.runTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:188)
ZoneTask.invokeTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:503)
ZoneTask.invoke (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:492)
data.args.<computed> (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:1425)
<anonymous> (<node_internals>/fs.js:168)
callbackTrampoline (<node_internals>/internal/async_hooks.js:126)
FSREQCALLBACK (Unknown Source:1)
init (<node_internals>/internal/inspector_async_hook.js:25)
emitInitNative (<node_internals>/internal/async_hooks.js:195)
stat (<node_internals>/fs.js:989)
scheduleTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:1426)
ZoneDelegate.scheduleTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:407)
Zone.scheduleTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:231)
Zone.scheduleMacroTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:254)
scheduleMacroTaskWithCurrentZone (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:1181)
<anonymous> (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:1432)
proto.<computed> (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:1411)
sendFile (<ProjectDir>\node_modules\send\index.js:721)
pipe (<ProjectDir>\node_modules\send\index.js:595)
serveStatic (<ProjectDir>\node_modules\serve-static\index.js:125)
handle (<ProjectDir>\node_modules\express\lib\router\layer.js:95)
trim_prefix (<ProjectDir>\node_modules\express\lib\router\index.js:317)
<anonymous> (<ProjectDir>\node_modules\express\lib\router\index.js:284)
process_params (<ProjectDir>\node_modules\express\lib\router\index.js:335)
next (<ProjectDir>\node_modules\express\lib\router\index.js:275)
<anonymous> (<ProjectDir>\node_modules\swagger-ui-express\index.js:212)
handle (<ProjectDir>\node_modules\express\lib\router\layer.js:95)
trim_prefix (<ProjectDir>\node_modules\express\lib\router\index.js:317)
<anonymous> (<ProjectDir>\node_modules\express\lib\router\index.js:284)
process_params (<ProjectDir>\node_modules\express\lib\router\index.js:335)
next (<ProjectDir>\node_modules\express\lib\router\index.js:275)
session (<ProjectDir>\node_modules\express-session\index.js:475)
handle (<ProjectDir>\node_modules\express\lib\router\layer.js:95)
trim_prefix (<ProjectDir>\node_modules\express\lib\router\index.js:317)
<anonymous> (<ProjectDir>\node_modules\express\lib\router\index.js:284)
process_params (<ProjectDir>\node_modules\express\lib\router\index.js:335)
next (<ProjectDir>\node_modules\express\lib\router\index.js:275)
expressInit (<ProjectDir>\node_modules\express\lib\middleware\init.js:40)
handle (<ProjectDir>\node_modules\express\lib\router\layer.js:95)
trim_prefix (<ProjectDir>\node_modules\express\lib\router\index.js:317)
<anonymous> (<ProjectDir>\node_modules\express\lib\router\index.js:284)
process_params (<ProjectDir>\node_modules\express\lib\router\index.js:335)
next (<ProjectDir>\node_modules\express\lib\router\index.js:275)
query (<ProjectDir>\node_modules\express\lib\middleware\query.js:45)
handle (<ProjectDir>\node_modules\express\lib\router\layer.js:95)
trim_prefix (<ProjectDir>\node_modules\express\lib\router\index.js:317)
<anonymous> (<ProjectDir>\node_modules\express\lib\router\index.js:284)
process_params (<ProjectDir>\node_modules\express\lib\router\index.js:335)
next (<ProjectDir>\node_modules\express\lib\router\index.js:275)
handle (<ProjectDir>\node_modules\express\lib\router\index.js:174)
handle (<ProjectDir>\node_modules\express\lib\application.js:174)
app (<ProjectDir>\node_modules\express\lib\express.js:39)
ZoneDelegate.invokeTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:421)
Zone.runTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:188)
ZoneTask.invokeTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:503)
ZoneTask.invoke (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:492)
emit (<node_internals>/events.js:314)
EventEmitter.emit (<node_internals>/domain.js:483)
parserOnIncoming (<node_internals>/_http_server.js:779)
parserOnHeadersComplete (<node_internals>/_http_common.js:122)
HTTPINCOMINGMESSAGE (Unknown Source:1)
init (<node_internals>/internal/inspector_async_hook.js:25)
emitInitNative (<node_internals>/internal/async_hooks.js:195)
connectionListenerInternal (<node_internals>/_http_server.js:420)
defaultTriggerAsyncIdScope (<node_internals>/internal/async_hooks.js:364)
connectionListener (<node_internals>/_http_server.js:396)
ZoneDelegate.invokeTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:421)
Zone.runTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:188)
ZoneTask.invokeTask (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:503)
ZoneTask.invoke (<ProjectDir>\node_modules\zone.js\dist\zone-node.js:492)
emit (<node_internals>/events.js:314)
EventEmitter.emit (<node_internals>/domain.js:483)
onconnection (<node_internals>/net.js:1558)
callbackTrampoline (<node_internals>/internal/async_hooks.js:126)
```

**Comment by SDAdham** [comment]
I don't see anything related to my code in the stacktrace above, this only happens during a return of anything in any controller.

**Comment by SDAdham** [comment]
@jmcdo29 : can the stacktrace above help?

**Comment by jmcdo29** [comment]
For the last time, [provide a minimum reproduction](https://jmcdo29.github.io/wft-is--minimum-reproduction). 

From the (abhorrent) stack trace above, every call to nest gets delegated down to Express, as would be expected. The only things that stand out to me are the custom middleware, but the main issue is that `domain.js` is a node internals file, meaning something very low level is causing a problem. 

If any of your middleware are trying to do post request logic, that's not good cause that's not what they are meant for. Other than that, to do **anything** else **we need a minimum reproduction**.

**Comment by SDAdham** [comment]
@jmcdo29 , the only change i do to the request is the following code:
```
res.setHeader('Access-Control-Allow-Origin', req.headers.origin || req.headers.host);
        res.setHeader('Access-Control-Allow-Headers', 'origin, x-requested-with, content-type, enctype, X-Auth-Token');
        res.setHeader('Access-Control-Allow-methods', '*');
        res.setHeader('Access-Control-Allow-Credentials', 'true');
```
Can you please clarify *If any of your middleware are trying to do post request logic* in more details please?

**Comment by SDAdham** [comment]
Your last response resolved my issue @jmcdo29 , i fixed it. Thanks a lot!!!

**Comment by jmcdo29** [comment]
Would you like to document it so that just in case anyone else _somehow_ has the same problem there's an answer?

**Comment by SDAdham** [comment]
Sure, so I reviewed my middlewares and the changes they do, so apparently, I was overriding `req.domain` variable, all i did is adding a prefix to my variables that i was attaching to the `req` to make sure they are isolated from any default variables, and it worked.
