### ISSUE TITLE
[V5] `npm run test`  failed after  new project created by nest-cli

### ISSUE THREAD

**Issue by janckerchen** [nestjs/nest#608]
Setting up a new project  with Nest CLI, nothing changed, `npm test` failed

```
$ nest new hume2
$ cd hume2
$ npm run test

> hume2@1.0.0 test /opt/dev/hume2
> jest

 FAIL  src/app.controller.spec.ts
  AppController
    root
      ✕ should return "Hello World!" (138ms)

  ● AppController › root › should return "Hello World!"

    Nest can't resolve dependencies of the AppController (?). Please verify whether [0] argument is available in the current context.

      at Injector.<anonymous> (../node_modules/@nestjs/core/injector/injector.js:156:23)
          at Generator.next (<anonymous>)
      at fulfilled (../node_modules/@nestjs/core/injector/injector.js:4:58)
          at <anonymous>
      at process._tickCallback (../internal/process/next_tick.js:118:7)

  ● AppController › root › should return "Hello World!"

    TypeError: Cannot read property 'get' of undefined

      at Object.it (app.controller.spec.ts:16:33)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (../internal/process/next_tick.js:118:7)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        3.532s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hume2@1.0.0 test: `jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hume2@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jason/.npm/_logs/2018-04-28T06_10_02_033Z-debug.log
```

**Comment by ruisaraiva19** [comment]
Same issue for me.
Just added AppService and now runs as it should.

<img width="486" alt="screen shot 2018-04-28 at 11 12 10" src="https://user-images.githubusercontent.com/7356098/39395326-43d506b8-4ad5-11e8-931c-2e6358c8080b.png">

**Comment by kamilmysliwiec** [comment]
cc @ThomRick 
The ts starter is fixed already. This issue should be fixed in the next CLI release.

**Comment by ThomRick** [comment]
@kamilmysliwiec I'm on it ;-)
