### ISSUE TITLE
Error "No connection options were found in any orm configuration files" on production.

### ISSUE THREAD

**Issue by kafetora** [nestjs/nest#6140]
I'm trying the migration using nestjs/typeorm on production.

On development (localhost), migration successfly, but production is not.
According to error messages, there are no configration files.

Is `typeOrmModule.forRootAsync` used incorrectly?
Does anyone know what the problem is?

Error message
```
Error during migration run:
Error: No connection options were found in any orm configuration files.
    at ConnectionOptionsReader.<anonymous> (/home/server_path/.npm/_npx/20537/lib/node_modules/typeorm/connection/ConnectionOptionsReader.js:35:35)
    at step (/home/server_path/.npm/_npx/20537/lib/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/home/server_path/.npm/_npx/20537/lib/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/home/server_path/.npm/_npx/20537/lib/node_modules/typeorm/node_modules/tslib/tslib.js:112:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at findNodeScript.then.existing (/home/server_path/.nodebrew/node/v10.16.0/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
```

Versions:
Node 10.16.0
npm 6.9.0

Build commands:
```
"build": "cross-env NODE_ENV=development nest build",
"build:prod": "cross-env NODE_ENV=production nest build",
```

Migartion command:
`npx typeorm migration:run
`

app.module.ts
```
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { TypeOrmModule } from '@nestjs/typeorm';
import { CustomersModule } from './customers/customers.module';
import { ConfigModule } from '@nestjs/config';
import { TypeOrmConfigService } from './type-orm-config.service';

@Module({
  imports: [
    ConfigModule.forRoot({
      isGlobal: true,
      envFilePath: `.env.${process.env.NODE_ENV}`,
    }),
    TypeOrmModule.forRootAsync({
      imports: [ConfigModule],
      useClass: TypeOrmConfigService
    }),
    CustomersModule
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}

```

type-orm-config.service.ts
```
import { TypeOrmOptionsFactory, TypeOrmModuleOptions } from '@nestjs/typeorm';
import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';


@Injectable()
export class TypeOrmConfigService implements TypeOrmOptionsFactory {

  createTypeOrmOptions(): TypeOrmModuleOptions {
    const configService = new ConfigService();
    return {
      type: 'mysql',
      host: configService.get('DATABASE_HOST', 'localhost'),
      port: 3306,
      username: configService.get('DATABASE_USERNAME', 'root'),
      password: configService.get('DATABASE_PASSWORD', 'mysql'),
      database: configService.get('DATABASE_NAME', 'dbname'),
      entities: [configService.get('ENTITIES_DIR', 'mysql')],
      migrations: [configService.get('MIGRATIONS_DIR', 'mysql')],
      cli: {
        entitiesDir: configService.get('CLI_ENTITIES_DIR', 'src/entities'),
        migrationsDir: configService.get('CLI_MIGRATIONS_DIR', 'src/migrations'),
      },
      synchronize: false,
    };
  }
}
```

.env.development
```
DATABASE_NAME=dbname
DATABASE_HOST=localhost
DATABASE_USERNAME=root
DATABASE_PASSWORD=mysql
DATABASE_PORT=3306
MIGRATIONS_DIR=dist/migrations/*.js
ENTITIES_DIR=dist/entities/*.entity.js
CLI_MIGRATIONS_DIR=src/migrations
CLI_ENTITIES_DIR=src/entities
```

.env.production
```
DATABASE_NAME=dbname
DATABASE_HOST=dbhost
DATABASE_USERNAME=dbusername
DATABASE_PASSWORD=dbpassword
DATABASE_PORT=dbport
MIGRATIONS_DIR=/migrations/*.js
ENTITIES_DIR=/entities/*.entity.js
CLI_MIGRATIONS_DIR=migrations
CLI_ENTITIES_DIR=entities
```

**Comment by kamilmysliwiec** [comment]
There are several reasons that may be causing this issue. My guess is that your `src` directory is hardcoded in migration paths:

```json
cli: {
  entitiesDir: configService.get('CLI_ENTITIES_DIR', 'src/entities'),
  migrationsDir: configService.get('CLI_MIGRATIONS_DIR', 'src/migrations'),
},
```

While you need `dist` instead for the production env.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
