### ISSUE TITLE
Cannot read property 'IMPORTS' of undefined

### ISSUE THREAD

**Issue by itamardavidyan** [nestjs/nest#6143]
I updated @nestjs/common from version `^6.8.3` to version `^7.6.5`
And I got that error:
```
[Nest] 55720   - 01/13/2021, 2:32:24 PM   [ExceptionHandler] Cannot read property 'IMPORTS' of undefined +8ms
TypeError: Cannot read property 'IMPORTS' of undefined
    at DependenciesScanner.scanForModules (/home/itamard/Documents/pix-letter-monorepo/node_modules/@nestjs/core/scanner.js:34:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at DependenciesScanner.scan (/home/itamard/Documents/pix-letter-monorepo/node_modules/@nestjs/core/scanner.js:21:9)
    at /home/itamard/Documents/pix-letter-monorepo/node_modules/@nestjs/core/nest-factory.js:80:17
    at Function.asyncRun (/home/itamard/Documents/pix-letter-monorepo/node_modules/@nestjs/core/errors/exceptions-zone.js:17:13)
    at NestFactoryStatic.initialize (/home/itamard/Documents/pix-letter-monorepo/node_modules/@nestjs/core/nest-factory.js:79:13)
    at NestFactoryStatic.create (/home/itamard/Documents/pix-letter-monorepo/node_modules/@nestjs/core/nest-factory.js:30:9)
```

I fixed it locally by replacing every `constants_1.METADATA` to `constants_1.MODULE_METADATA`

Helpful linux script to fix it:
```
sed -i 's/constants_1.METADATA./constants_1.MODULE_METADATA./g' ./node_modules/@nestjs/corescanner.js
```

This bug return every time I run `npm i`

**Comment by Tony133** [comment]
Hi @itamardavidyan, I recommend that you provide a minimal reproduction of the problem in a clonable git repository, so the core team can evaluate your problem.

**Comment by jmcdo29** [comment]
Make sure your `@nestjs/common` and `@nestjs/core` versions are aligned with each other. These packages refer to each other and **must** be on the same version. Like Tony said, and I've told you on the [Discord](https://discord.gg/nestjs) if you can provide us a reproduction, we can dig in further.
