### ISSUE TITLE
Bcrypt not working?

### ISSUE THREAD

**Issue by casulit** [nestjs/nest#6279]
TypeError: Cannot read property 'hash' of undefined
    at model.<anonymous> (C:\Users\chris\Documents\GitHub\vms-api\dist\shared\shared.module.js:33:73)
    at callMiddlewareFunction (C:\Users\chris\Documents\GitHub\vms-api\node_modules\kareem\index.js:483:23)
    at model.next (C:\Users\chris\Documents\GitHub\vms-api\node_modules\kareem\index.js:58:7)
    at _next (C:\Users\chris\Documents\GitHub\vms-api\node_modules\kareem\index.js:107:10)
    at C:\Users\chris\Documents\GitHub\vms-api\node_modules\kareem\index.js:508:38
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by jmcdo29** [comment]
This isn't a problem with nest. Please visit our [Discord] (https://discord.gg/NestJS) for support.

**Comment by casulit** [comment]
> This isn't a problem with nest. Please visit our [Discord](https://discord.gg/NestJS) for support.

I have to import it like this import { hash } from 'bcrypt' in order to work btw thanks!
