### ISSUE TITLE
Error encoding trace: root.child.error.message: string expected

### ISSUE THREAD

**Issue by sepiette** [nestjs/nest#6355]
## Current behavior
I just upgraded our `apollo-server-express` versions from 2.12.0 to 2.19.0 and am suddenly seeing a lot of errors firing in our logs with the following:
```
" Error encoding trace: root.child.error.message: string expected"
"    at /app/node_modules/apollo-server-core/dist/plugin/usageReporting/plugin.js:265:39"
"    at Generator.next (<anonymous>)</anonymous>"
"    at fulfilled (/app/node_modules/apollo-server-core/dist/plugin/usageReporting/plugin.js:5:58)"
Object
```

## Expected behavior
I expect not to have any console errors.

## Possible Solution
 I found the following [thread](https://github.com/nestjs/nest/issues/1832), but can't join the Discord channel to find out more. It may be a similar problem with the `class-validator` library and Nest. The other [issue](https://github.com/nestjs/nest/issues/1832) I found related to this error seems to have been resolved in Nest version 6.0.4 and we are on 6.7.2.

## Environment
Nest version: 6.7.2

**Comment by jmcdo29** [comment]
This doesn't immediately assist to be related to nest. Can you provide a [minimum reproduction] (https://jmcdo29.github.io/wtf-is-a-minimum-reproduction/)?
