### ISSUE TITLE
SyntaxError: Unexpected token 'export' with node v13.6.0

### ISSUE THREAD

**Issue by rchod** [nestjs/nest#6465]
```
> nest start

/home/nest-todo/node_modules/uuid/dist/esm-browser/index.js:1
export { default as v1 } from './v1.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1060:16)
    at Module._compile (internal/modules/cjs/loader.js:1108:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/nest-todo/node_modules/@nestjs/common/decorators/core/injectable.decorator.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
```

I had to switch to node v14.2.0 to fix this issue

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction](https://jmcdo29.github.io/wtf-is-a-minimum-reproduction/)

**Comment by rchod** [comment]
Yes, I switched you v14 I didn't know [uuid doesn't support node v13 ](https://github.com/uuidjs/uuid/issues/466#issuecomment-641129599).

One reading the NestJs docs:

> Prerequisites#
> Please make sure that Node.js (>= 10.13.0) is installed on your operating system.

might think that all versions of node >= 10.13.0 are supported.

**Comment by jmcdo29** [comment]
We can make an update to the docs that says > 10.13.0 **and** LTS (so 10, 12, 14)

**Comment by rchod** [comment]
Yes, that would more clear, thanks.

**Comment by rubiin** [comment]
> >

That would be a nice addition to docs and might prevent future issues of this sort

**Comment by jmcdo29** [comment]
Someone want to make a PR for that?

**Comment by rchod** [comment]
I made this one https://github.com/nestjs/docs.nestjs.com/pull/1794 please tell me If my phrasing needs improvement

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/docs.nestjs.com/pull/1794
