### ISSUE TITLE
nest new error: Collection "@nestjs/schematics" cannot be resolved.

### ISSUE THREAD

**Issue by hehehai** [nestjs/nest#6550]
## Bug Report
use nest cli inti new project error (Chinese network)

## Input Code
cli input: `nest new server`

## Expected behavior
```
  We will scaffold your app in a few seconds..

Error: Collection "@nestjs/schematics" cannot be resolved.
    at NodeModulesEngineHost.resolve (/Users/guanwei/.config/yarn/global/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:75:19)
    at NodeModulesEngineHost._resolveCollectionPath (/Users/guanwei/.config/yarn/global/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:80:37)
    at NodeModulesEngineHost.createCollectionDescription (/Users/guanwei/.config/yarn/global/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:110:27)
    at SchematicEngine._createCollectionDescription (/Users/guanwei/.config/yarn/global/node_modules/@angular-devkit/schematics/src/engine/engine.js:148:40)
    at SchematicEngine.createCollection (/Users/guanwei/.config/yarn/global/node_modules/@angular-devkit/schematics/src/engine/engine.js:141:43)
    at NodeWorkflow.execute (/Users/guanwei/.config/yarn/global/node_modules/@angular-devkit/schematics/src/workflow/base.js:101:41)
    at main (/Users/guanwei/.config/yarn/global/node_modules/@angular-devkit/schematics-cli/bin/schematics.js:229:24)
    at Object.<anonymous> (/Users/guanwei/.config/yarn/global/node_modules/@angular-devkit/schematics-cli/bin/schematics.js:336:5)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)

Failed to execute command: node @nestjs/schematics:application --name=server --directory=undefined --no-dry-run --no-skip-git --package-manager=undefined --language="ts" --collection="@nestjs/schematics"
```

## Environment

<pre><code>
os: mac(big sur)
node version: v15.10.0
nest cli version: v7.5.6

**Comment by chenc041** [comment]
you should try install @nestjs/schematics  global

**Comment by hehehai** [comment]
> you should try install @nestjs/schematics global

@chenc041 Thanks! that's working

**Comment by chenc041** [comment]
> > you should try install @nestjs/schematics global
> 
> @chenc041 Thanks! that's working

😊
