### ISSUE TITLE
CSURF implementation

### ISSUE THREAD

**Issue by LadIQe** [nestjs/nest#6552]
Hello,

Im trying to implement csurf protection, but without any success. Previously I implemented it to test server, which works great, but this server was simple express server, not based on NestJS framework.

So my code in main.ts is like this:

```
import { AppModule } from './app.module'
import { NestFactory } from '@nestjs/core'
import cookieParser from 'cookie-parser'
import csurf from 'csurf'

async function bootstrap() {
  const app = await NestFactory.create(AppModule)

  app.use(cookieParser())
  app.use(csurf({ cookie: { sameSite: true } }))

  app.use((req: any, res: any, next: any) => {
    const token = req.csrfToken()
    res.cookie('XSRF-TOKEN', token)
    res.locals.csrfToken = token

    next()
  })

  const port = process.env.PORT_NODE_BACKEND || 4000

  await app.listen(port)
}

bootstrap()

```

As you can see, there is simple `app.use` where Im sending new CSRF token on every request. But my GraphQL playground is not working and this is the error

```
[Nest] 159   - 03/02/2021, 3:11:50 PM   [ExceptionsHandler] invalid csrf token +4598ms
ForbiddenError: invalid csrf token
    at csrf (/usr/src/app/node_modules/csurf/index.js:112:19)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at cookieParser (/usr/src/app/node_modules/cookie-parser/index.js:71:5)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
```

Im new to NestJS, so forgive me if there is something wrong

Thank you

**Comment by Tony133** [comment]
Hi @LadIQe, if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

**Comment by mozgbrasil** [comment]
Good morning my friends

I'm using as

   app.use(csurf());

but the error is returned

	[Nest] 24365  - 09/21/2021, 10:23:32 PM   ERROR [ExceptionsHandler] misconfigured csrf
	Error: misconfigured csrf
	    at csrf (/workspace/nestjs-labs/node_modules/csurf/index.js:71:19)
	    at Layer.handle [as handle_request] (/workspace/nestjs-labs/node_modules/express/lib/router/layer.js:95:5)
	    at trim_prefix (/workspace/nestjs-labs/node_modules/express/lib/router/index.js:317:13)
	    at /workspace/nestjs-labs/node_modules/express/lib/router/index.js:284:7
	    at Function.process_params (/workspace/nestjs-labs/node_modules/express/lib/router/index.js:335:12)
	    at next (/workspace/nestjs-labs/node_modules/express/lib/router/index.js:275:10)
	    at cors (/workspace/nestjs-labs/node_modules/cors/lib/index.js:188:7)
	    at /workspace/nestjs-labs/node_modules/cors/lib/index.js:224:17
	    at originCallback (/workspace/nestjs-labs/node_modules/cors/lib/index.js:214:15)
	    at /workspace/nestjs-labs/node_modules/cors/lib/index.js:219:13

Thank you in advance if you can help

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

**Comment by rintran720** [comment]
> 

You have to install cookie-parser and session before
`
  app.use(cookieParser());
  app.use(
    session({
      secret: 'secret key',
      resave: false,
      saveUninitialized: true,
      cookie: {
        secure: false,
        httpOnly: true,
        maxAge: 5 * 60 * 1000,
      },
    }),
  );
  app.use(csrf());
`

**Comment by Tony133** [comment]
solution update:

```
import { AppModule } from './app.module';
import { NestFactory } from '@nestjs/core';
import * as cookieParser from 'cookie-parser';
import * as csurf from 'csurf';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  app.use(cookieParser());
  app.use(csurf({ cookie: { sameSite: true } }));

  app.use((req: any, res: any, next: any) => {
    const token = req.csrfToken();
    res.cookie('XSRF-TOKEN', token);
    res.locals.csrfToken = token;

    next();
  });

  await app.listen(3000);
}

bootstrap();
```

<img width="1610" alt="screenshot" src="https://user-images.githubusercontent.com/11542387/177377090-ec814a47-f05a-40e9-9c91-a8d47e1cf049.png">
