### ISSUE TITLE
Schema Directives don't work with gql-tools 5, 6 or 7 installed according to documentation

### ISSUE THREAD

**Issue by goofiw** [nestjs/nest#6577]
## Current behavior
Including a schema directive in the `GraphQLModule.forRoot` factory causes an error on startup when gql-tools 5+ is installed (4 seems to work)

## Input Code

```ts
  return GraphQLModule.forRoot({
    autoSchemaFile: join(process.cwd(), '__generated__/schema.gql'), // use this to compare current vs next in git for breaking changes
    sortSchema: true,
    schemaDirectives: {
      constraints: ConstraintDirective,
    },
  });
```

## Expected behavior
App to run 👯 using the docs here: https://docs.nestjs.com/graphql/directives

## Possible Solution
install graphql-tools@4 at project root

## Environment

<pre><code> Nest Versions
```
    "@nestjs/common": "^7.0.0",
    "@nestjs/config": "^0.6.1",
    "@nestjs/core": "^7.0.0",
    "@nestjs/graphql": "^7.9.11",
    "@nestjs/passport": "^7.1.5",
    "@nestjs/platform-express": "^7.0.0"
 ```
 
For Tooling issues:
- Node version:v14.15.1
- Platform:  Mac

Others:
Heres the start output:
```
yarn nx serve server-app-api                                                                  20s 13:23:30
yarn run v1.22.10
warning ../package.json: No license field
$ nx serve server-app-api

> nx run server-app-api:serve 
Starting type checking service...
Using 10 workers with 2048MB memory limit
Type checking in progress...
Hash: d9a21bed26a7a6df7351
Built at: 03/05/2021 1:24:06 PM
Entrypoint main = main.js main.js.map
chunk {main} main.js, main.js.map (main) 55.6 KiB [entry] [rendered]
Debugger listening on ws://localhost:58752/80acc659-94d3-4b85-b52d-4c32b72dcb7c
Debugger listening on ws://localhost:58753/80acc659-94d3-4b85-b52d-4c32b72dcb7c
For help, see: https://nodejs.org/en/docs/inspector

/Users/will/strive-projects/strive-performance/dist/apps/server/app-api/webpack:/node_modules/apollo-server/dist/exports.js:17
Object.defineProperty(exports, "GraphQLUpload", { enumerable: true, get: function () { return apollo_server_core_1.GraphQLUpload; } });
^
TypeError: Cannot redefine property: GraphQLUpload
    at Function.defineProperty (<anonymous>)
    at Object.../node_modules/apollo-server/dist/exports.js (/Users/will/strive-projects/strive-performance/dist/apps/server/app-api/webpack:/node_modules/apollo-server/dist/exports.js:17:1)
    at __webpack_require__ (/Users/will/strive-projects/strive-performance/dist/apps/server/app-api/webpack:/webpack/bootstrap:19:1)
    at Object.../node_modules/apollo-server/dist/index.js (/Users/will/strive-projects/strive-performance/dist/apps/server/app-api/webpack:/node_modules/apollo-server/dist/index.js:30:14)
    at __webpack_require__ (/Users/will/strive-projects/strive-performance/dist/apps/server/app-api/webpack:/webpack/bootstrap:19:1)
    at Module../libs/server/gql-server/src/lib/directives/constraint.ts (/Users/will/strive-projects/strive-performance/dist/apps/server/app-api/main.js:1694:71)
    at __webpack_require__ (/Users/will/strive-projects/strive-performance/dist/apps/server/app-api/webpack:/webpack/bootstrap:19:1)
    at Module../libs/server/gql-server/src/lib/directives/index.ts (/Users/will/strive-projects/strive-performance/dist/apps/server/app-api/webpack:/libs/server/gql-server/src/lib/directives/index.ts:1:1)
    at __webpack_require__ (/Users/will/strive-projects/strive-performance/dist/apps/server/app-api/webpack:/webpack/bootstrap:19:1)
    at Module../libs/server/gql-server/src/lib/gql-module.factory.ts (/Users/will/strive-projects/strive-performance/dist/apps/server/app-api/main.js:1787:69)
No type errors found
Version: typescript 4.0.5
```
</code></pre>

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduciton](http://minimum-reproduction.wtf)

**Comment by goofiw** [comment]
@jmcdo29 following the docs will result in the bug with gql-tools 5+ installed at project root.

**Comment by goofiw** [comment]
Got it sorted.  The issue was I mispelled constraint in my codefirst schema.  It seems the directive must be used in order to be included.
