### ISSUE TITLE
TypeError: stripe_1.default is not a constructor

### ISSUE THREAD

**Issue by Araknos** [nestjs/nest#6583]
Hello,

After migrating from Nestjs v6 to v7 Stripe is no more working I got the following error:

`TypeError: stripe_1.default is not a constructor`

I tried with nestjs-stripe v0.2.1 & @golevelup/nestjs-stripe v0.1.0 and still got the same error.

Here is an example of full log:

```
TypeError: stripe_1.default is not a constructor
    at InstanceWrapper.useFactory [as metatype] (E:\workspace\Games\backend\master\node_modules\@golevelup\nestjs-stripe\lib\stripe.module.js:55:24)
    at Injector.instantiateClass (E:\workspace\Games\backend\master\node_modules\@nestjs\core\injector\injector.js:289:55)
    at callback (E:\workspace\Games\backend\master\node_modules\@nestjs\core\injector\injector.js:42:41)
    at async Injector.resolveConstructorParams (E:\workspace\Games\backend\master\node_modules\@nestjs\core\injector\injector.js:114:24)
    at async Injector.loadInstance (E:\workspace\Games\backend\master\node_modules\@nestjs\core\injector\injector.js:46:9)
    at async Injector.loadProvider (E:\workspace\Games\backend\master\node_modules\@nestjs\core\injector\injector.js:68:9)
    at async Promise.all (index 5)
    at async InstanceLoader.createInstancesOfProviders (E:\workspace\Games\backend\master\node_modules\@nestjs\core\injector\instance-loader.js:43:9)
    at async E:\workspace\Games\backend\master\node_modules\@nestjs\core\injector\instance-loader.js:28:13
    at async Promise.all (index 21)
    at async InstanceLoader.createInstances (E:\workspace\Games\backend\master\node_modules\@nestjs\core\injector\instance-loader.js:27:9)
    at async InstanceLoader.createInstancesOfDependencies (E:\workspace\Games\backend\master\node_modules\@nestjs\core\injector\instance-loader.js:17:9)
    at async E:\workspace\Games\backend\master\node_modules\@nestjs\core\nest-factory.js:90:17
    at async Function.asyncRun (E:\workspace\Games\backend\master\node_modules\@nestjs\core\errors\exceptions-zone.js:18:13)
    at async NestFactoryStatic.initialize (E:\workspace\Games\backend\master\node_modules\@nestjs\core\nest-factory.js:88:13)
    at async NestFactoryStatic.create (E:\workspace\Games\backend\master\node_modules\@nestjs\core\nest-factory.js:34:9)
```

Any idea ?

**Comment by jmcdo29** [comment]
Looks like the packages are using a default import which probably shouldn't be the case. I'd suggest reporting this to the appropriate libraries, as this doesn't seem directly related to Nest. If you think it is, please provide a minimum reproduction.
