### ISSUE TITLE
Jest RANDOMBYTESREQUEST

### ISSUE THREAD

**Issue by guiaramos** [nestjs/nest#6838]
## Current behavior
Jest not exiting

```bash
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  RANDOMBYTESREQUEST

      3 | import { UserAuth } from 'src/auth/dto/user.jwt';
      4 | 
    > 5 | export const CurrentUser = createParamDecorator(
        |                            ^
      6 |   (data: unknown, context: ExecutionContext): UserAuth => {
      7 |     const ctx = GqlExecutionContext.create(context);
      8 |     return ctx.getContext().req.user;

      at rng (node_modules/uuid/dist/rng.js:18:21)
      at Object.v4 (node_modules/uuid/dist/v4.js:17:63)
      at Object.createParamDecorator (node_modules/@nestjs/common/decorators/http/create-route-param-metadata.decorator.js:14:30)
      at Object.<anonymous> (src/common/guards/current-user.guard.ts:5:28)
```

## Input Code

```ts
import { createParamDecorator, ExecutionContext } from '@nestjs/common';
import { GqlExecutionContext } from '@nestjs/graphql';
import { UserAuth } from 'src/auth/dto/user.jwt';

export const CurrentUser = createParamDecorator(
  (data: unknown, context: ExecutionContext): UserAuth => {
    const ctx = GqlExecutionContext.create(context);
    return ctx.getContext().req.user;
  }
);
```

```ts
describe('AuthService', () => {
  let service: AuthService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      imports: [
        rootMongooseTestModule(),
        PassportModule.register({ defaultStrategy: 'jwt' }),
        CacheModule.register(),
        TwilioModule.forRoot({
          accountSid: process.env.ACCOUNT_SID,
          authToken: process.env.AUTH_TOKEN,
        }),
        UserModule,
      ],
      providers: [AuthService, AuthResolver, AuthConfig, CookieService, JwtStrategy],
      exports: [AuthService],
      controllers: [AuthController],
    }).compile();

    service = module.get<AuthService>(AuthService);
  });

  it('should be defined', () => {
    expect(service).toBeDefined();
  });

  afterAll(async (done) => {
    await closeInMongoDConnection();
    done();
  });
});
```

## Expected behavior

jest should exit  without open handlers

## Possible Solution

the error is on uuid used on createParamDecorator
https://github.com/uuidjs/uuid/issues/566

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: v15.6.0
- Platform:   Mac

Others:

</code>
</pre>
https://stackoverflow.com/questions/66958699/jest-open-handle-randombytesrequest-on-nestjs-graphql

**Comment by Tony133** [comment]
Hi @guiaramos,
 
If you think this is an issue with Nest, it's a good idea to provide minimal replay when submitting a bug report so the nest core team can evaluate your issue.

Otherwise use the [Discord](https://discord.com/invite/G7Qnnhy) channel for support and support requests.

Nest's core team uses GitHub to track bug reports, feature requests, and regressions

**Comment by guiaramos** [comment]
Hi @Tony133, 

Sorry for that, I will ask on discord and preparea repo if not fixed and reopen the issue

**Comment by guiaramos** [comment]
after contacting on discord the solution was:
```
jmcdo29 — Today at 10:34 PM
@GuiRamos 
1) Your unit tests are doing too much. They aren't unit tests, but integration tests. Just an FYI
2) change your afterAll to afterEach to fix your issue
```
