### ISSUE TITLE
Dynamic Global Module provider is undefined on inject it on root module to open a connection with neo4j database

### ISSUE THREAD

**Issue by 4lessandrodev** [nestjs/nest#6905]
## Current behavior
The provider is identified as undefined 

```shell
TypeError: Cannot read property 'provide' of undefined
    at Module.isCustomProvider (/home/alessandro/Workspace/Projects/teste/node_modules/@nestjs/core/injector/module.js:154:47)
    at Module.addExportedProvider (/home/alessandro/Workspace/Projects/teste/node_modules/@nestjs/core/injector/module.js:240:18)
    at NestContainer.addExportedProvider (/home/alessandro/Workspace/Projects/teste/node_modules/@nestjs/core/injector/container.js:122:19)
    at DependenciesScanner.insertExportedProvider (/home/alessandro/Workspace/Projects/teste/node_modules/@nestjs/core/scanner.js:213:24)
    at /home/alessandro/Workspace/Projects/teste/node_modules/@nestjs/core/scanner.js:121:50
    at Array.forEach (<anonymous>)
    at DependenciesScanner.reflectExports (/home/alessandro/Workspace/Projects/teste/node_modules/@nestjs/core/scanner.js:121:17)
    at DependenciesScanner.scanModulesForDependencies (/home/alessandro/Workspace/Projects/teste/node_modules/@nestjs/core/scanner.js:73:18)
    at async DependenciesScanner.scan (/home/alessandro/Workspace/Projects/teste/node_modules/@nestjs/core/scanner.js:26:9)
    at async /home/alessandro/Workspace/Projects/teste/node_modules/@nestjs/core/nest-factory.js:89:17
```

## Input Code
[Github repository link](https://github.com/4lessandrodev/teste/tree/394de6b85766b6d9cec12f40ff93042eb1381973)

```ts
@Global()
@Module({})
export class NeodeModule {
  static forRoot(directory?: string): DynamicModule {
    return {
      module: NeodeModule,
      global: true,
      providers: [
        {
          provide: 'DIRECTORY',
          useValue: directory,
        },
        {
          provide: Neode,
          useFactory: async () => {
            let connection: Neode;
            if (directory) {
              connection = await Neode.fromEnv().withDirectory(directory);
              await connection.schema.install();
            } else {
              connection = await Neode.fromEnv();
            }
            return connection;
          },
          inject: ['DIRECTORY'],
        },
      ],
      exports: [Neode],
    };
  }

  static forFeature(schema: SchemaObject): DynamicModule {
    return {
      module: NeodeModule,
      global: false,
      providers: [
        {
          provide: 'SCHEMA',
          useValue: schema,
        },
        {
          provide: Neode,
          useFactory: async () => {
            const connection = await Neode.fromEnv().with({ schema });
            await connection.schema.install();
            return connection;
          },
          inject: ['SCHEMA'],
        },
      ],
      exports: [Neode],
    };
  }
}
```

## Expected behavior
Global Dynamic Module generates (open) a database connection and return it to root module 

## Environment
```shell
Nest version: 7.6.13
 
For Tooling issues:
- Node version:  14.15.4
- Platform:  Linux 
```

Others:
Trying to open a connection with Neo4J graph database by Neode ORM 

References:
[Neode Npm](https://www.npmjs.com/package/neode)
[Neo4j Driver Npm](https://www.npmjs.com/package/neo4j-driver)

**Comment by jmcdo29** [comment]
Overall, looks like an issue with the Types that `Neode` provides. The default import comes in as `undefined` so `provide: undefined` fails and things go sideways. Using `import * as Neode ...` I was able to get the project to get to the next error which comes from Neode specifically. This doesn't appear to be a problem with Nest, though we might be able to make that error more clear. Debugging that was a bit of fun.

**Comment by 4lessandrodev** [comment]
All running well. Thank you very much @jmcdo29 

```ts
import * as Neode
```
