### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: stream.on is not a function at ServerNats.handleError

### ISSUE THREAD

**Issue by num8er** [nestjs/nest#6927]
## Bug Report
Very basic (did by [official manual](https://docs.nestjs.com/microservices/nats)) microservice which fails to start
```
UnhandledPromiseRejectionWarning: TypeError: stream.on is not a function at ServerNats.handleError
```

## Current behavior
```
num8er@Anars-MacBook-Pro test % yarn start:dev
yarn run v1.22.4
$ nest start --watch
[5:31:06 PM] Starting compilation in watch mode...

[5:31:08 PM] Found 0 errors. Watching for file changes.

[Nest] 30438   - 04/19/2021, 5:31:08 PM   [NestFactory] Starting Nest application...
[Nest] 30438   - 04/19/2021, 5:31:08 PM   [InstanceLoader] AppModule dependencies initialized +26ms
[Nest] 30438   - 04/19/2021, 5:31:08 PM   [NestMicroservice] Nest microservice successfully started +24ms
(node:30438) UnhandledPromiseRejectionWarning: TypeError: stream.on is not a function
    at ServerNats.handleError (/Users/num8er/Work/Trembit/test/node_modules/@nestjs/microservices/server/server-nats.js:85:16)
    at ServerNats.listen (/Users/num8er/Work/Trembit/test/node_modules/@nestjs/microservices/server/server-nats.js:22:14)
    at /Users/num8er/Work/Trembit/test/node_modules/@nestjs/microservices/nest-microservice.js:86:51
    at new Promise (<anonymous>)
    at NestMicroservice.listenAsync (/Users/num8er/Work/Trembit/test/node_modules/@nestjs/microservices/nest-microservice.js:86:16)
    at async bootstrap (/Users/num8er/Work/Trembit/test/dist/main.js:13:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:30438) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:30438) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Input Code

```ts
import { NestFactory } from '@nestjs/core';
import { MicroserviceOptions, Transport } from '@nestjs/microservices';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.createMicroservice<MicroserviceOptions>(
    AppModule,
    {
      transport: Transport.NATS,
      options: {
        url: 'nats://localhost:4222',
      },
    },
  );
  await app.listenAsync();
}
bootstrap();
```

## Environment

<pre><code>
Nest version: 7.6.15

 
For Tooling issues:
- Node version: v14.15.3
- Platform:  Mac

</code></pre>

**Comment by kamilmysliwiec** [comment]
NATS v2 isn't supported in NestJS v7 (it will be supported in the upcoming major release, v8). For now, you have to use NATS v1, as shown in the docs https://docs.nestjs.com/microservices/nats#installation
