### ISSUE TITLE
websocket error: can't bind Socket to client

### ISSUE THREAD

**Issue by j92z** [nestjs/nest#6998]
## Current behavior

when connect server,  handleConnection() client.id is undefined.
```
[Nest] 21204   - 2021-04-28 10:27:40 ├F10: PM┤   [ClassroomChatGateway] Client connected: undefined
```
when emit event, handleMessage() 'joinRoom' client.to is not a function
```
[Nest] 21204   - 2021-04-28 10:32:49 ├F10: PM┤   [WsExceptionsHandler] client.to is not a function +309241ms
TypeError: client.to is not a function
    at ClassroomChatGateway.handleMessage (C:\code_file\dyoung.server\dist\classroom\classroom-chat.gateway.js:23:16)
    at C:\code_file\dyoung.server\node_modules\@nestjs\websockets\context\ws-context-creator.js:43:33
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ClassroomChatGateway.<anonymous> (C:\code_file\dyoung.server\node_modules\@nestjs\websockets\context\ws-proxy.js:12:32)
    at async WebSocketsController.pickResult (C:\code_file\dyoung.server\node_modules\@nestjs\websockets\web-sockets-controller.js:86:24)
```
## Input Code

```ts
// gateway.ts
import {
    WebSocketGateway,
    OnGatewayInit,
    WebSocketServer,
    OnGatewayConnection,
    OnGatewayDisconnect,
    ConnectedSocket,
    MessageBody,
    SubscribeMessage,
} from '@nestjs/websockets';
import { Logger } from '@nestjs/common';
import { Socket, Server } from 'socket.io';

@WebSocketGateway()
export class ClassroomChatGateway implements OnGatewayInit, OnGatewayConnection, OnGatewayDisconnect {

    @WebSocketServer() server: Server;
    private logger: Logger = new Logger('ClassroomChatGateway');

    @SubscribeMessage('joinRoom')
    handleMessage( @MessageBody() data: any,
    @ConnectedSocket() client: Socket,): void {
        client.to("111")
        this.server.emit('joinRoom', data);
    }

    afterInit(server: Server) {
        this.logger.log('Init');
    }

    handleDisconnect(client: Socket) {
        this.logger.log(`Client disconnected: ${client.id}`);
    }

    handleConnection(client: Socket, ...args: any[]) {
        this.logger.log(`Client connected: ${client.id}`);
    }
}
```
```ts
// main.ts
import { NestFactory } from '@nestjs/core';
import { WsAdapter } from '@nestjs/platform-ws';
import { AppModule } from './app.module';
async function bootstrap() {
    const app = await NestFactory.create(AppModule);
    app.useWebSocketAdapter(new WsAdapter(app));
    await app.listen(process.env.SERVER_PORT || 3000);
}
bootstrap();
```
## Expected behavior

I wonder what caused socket object empty
## Environment

<pre><code>
Nest version: 7.6.15

 
For Tooling issues:
- Node version: 12.18.1  
- Platform: Windows 10 

Others:

</code></pre>

**Comment by jmcdo29** [comment]
More than likely, this is caused by incompatible versions of socket.io. can you please provide a [minimum reproduction](https://jmcdo29.github.io/wtf-is-a-minimum-reproduction/)?

**Comment by j92z** [comment]
@jmcdo29 i get it. use incompatible versions of socket.io.

**Comment by chaddaess** [comment]
I have the exact same error and i don't understand what you mean by "ncompatible versions of socket.io." can you please elaborate?

**Comment by Highnesslin** [comment]
How to solve it???

**Comment by shawnnolanjr** [comment]
why is this closed? This is still an issue, and if it's not, could someone please show me a working example? Because all examples work fine until you have to integrate _rooms_ or get a client/socket id...
