### ISSUE TITLE
BUG - possible unhandled exception bug - using rabbitmq microservice

### ISSUE THREAD

**Issue by amiroooo** [nestjs/nest#7071]
enabling rabbitmq to communicate for a microservice can result in an unhandled exception.

reproduction:
simply send any non json message to a rabbitmq queue that is supposed to work with nestJS microservice controller.

the bug is caused in the following line:
https://github.com/nestjs/nest/blob/1a554694ce54a35ee8c1095f12dbd1268124c52d/packages/microservices/server/server-rmq.ts#L122
which will cause the message received show an exception and so the message remain in consuming mode, so we cant assign ack=true to it in order for it to be removed from queue.

`(node:18) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token c in JSON at position 0
    at JSON.parse (<anonymous>)
    at ServerRMQ.handleMessage (/app/dist/node_modules/@nestjs/microservices/server/server-rmq.js:75:33)
    at channel.consume.noAck.noAck (/app/dist/node_modules/@nestjs/microservices/server/server-rmq.js:65:51)
    at ConfirmChannel.BaseChannel.dispatchMessage (/app/dist/node_modules/amqplib/lib/channel.js:484:12)
    at ConfirmChannel.BaseChannel.handleDelivery (/app/dist/node_modules/amqplib/lib/channel.js:493:15)
    at ConfirmChannel.emit (events.js:315:20)
    at ConfirmChannel.EventEmitter.emit (domain.js:485:12)
    at /app/dist/node_modules/amqplib/lib/channel.js:279:10
    at ConfirmChannel.content (/app/dist/node_modules/amqplib/lib/channel.js:332:9)
    at ConfirmChannel.C.acceptMessageFrame (/app/dist/node_modules/amqplib/lib/channel.js:247:31)
    at ConfirmChannel.C.accept (/app/dist/node_modules/amqplib/lib/channel.js:400:17)
    at Connection.mainAccept [as accept] (/app/dist/node_modules/amqplib/lib/connection.js:64:33)
    at Socket.go (/app/dist/node_modules/amqplib/lib/connection.js:478:48)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:485:12)
    at emitReadable_ (_stream_readable.js:558:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

if supporting strings through rmq will not be allowed, at least give us the option to configure the channel to ack content, so those messages wont be held in progress status indefinitely.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
