### ISSUE TITLE
Issue with testing Microservice via REDIS bus.

### ISSUE THREAD

**Issue by bsreeram08** [nestjs/nest#7208]
I have been trying to test my Microservice which uses REDIS as my Transport Layer but, the connection always tries to connect via TCP.

And the error thrown is, **'Internal server error'**

    console.error
      Error: Error: connect ECONNREFUSED 127.0.0.1:80
          at Object.dispatchError (/Users/sreerambalamurugan/Documents/Surfboard/Projects/surfboard-surfpay/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:62:19)
          at Request.<anonymous> (/Users/sreerambalamurugan/Documents/Surfboard/Projects/surfboard-surfpay/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:654:18)
          at Request.emit (events.js:326:22)
          at Request.onRequestError (/Users/sreerambalamurugan/Documents/Surfboard/Projects/surfboard-surfpay/node_modules/request/request.js:877:8)
          at ClientRequest.emit (events.js:314:20)
          at Socket.socketErrorListener (_http_client.js:428:9)
          at Socket.emit (events.js:314:20)
          at emitErrorNT (internal/streams/destroy.js:92:8)
          at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
          at processTicksAndRejections (internal/process/task_queues.js:84:21) undefined

My Client is:
 ```
ClientRedis {
        routingMap: Map {},
        options: { url: 'redis://127.0.0.1:6379' },
        logger: Logger { context: 'ClientProxy', isTimestampEnabled: false },
        subscriptionsCount: Map {},
        isExplicitlyTerminated: false,
        url: 'redis://127.0.0.1:6379',
        serializer: IdentitySerializer {},
        deserializer: IncomingResponseDeserializer {},
        pubClient: RedisClient {
          _events: [Object: null prototype] {
            newListener: [Function],
            error: [Function]
          },
          _eventsCount: 2,
          _maxListeners: undefined,
          address: '127.0.0.1:6379',
          connection_options: { port: 6379, host: '127.0.0.1', family: 4 },
          connection_id: 2,
          connected: true,
          ready: false,
          should_buffer: false,
          command_queue: Denque { _head: 0, _tail: 1, _capacityMask: 3, _list: [Array] },
          offline_queue: Denque { _head: 0, _tail: 0, _capacityMask: 3, _list: [Array] },
          pipeline_queue: Denque { _head: 0, _tail: 0, _capacityMask: 3, _list: [Array] },
          connect_timeout: 3600000,
          enable_offline_queue: true,
          retry_timer: null,
          retry_totaltime: 0,
          retry_delay: 200,
          retry_backoff: 1.7,
          attempts: 1,
          pub_sub_mode: 0,
          subscription_set: {},
          monitoring: false,
          message_buffers: false,
          closing: false,
          server_info: {},
          auth_pass: undefined,
          selected_db: undefined,
          fire_strings: true,
          pipeline: false,
          sub_commands_left: 0,
          times_connected: 1,
          buffers: false,
          options: {
            port: '6379',
            host: '127.0.0.1',
            url: 'redis://127.0.0.1:6379',
            retry_strategy: [Function: retry_strategy],
            socket_keepalive: true,
            socket_initial_delay: 0,
            return_buffers: false,
            detect_buffers: false
          },
          reply: 'ON',
          reply_parser: JavascriptRedisParser {
            optionReturnBuffers: false,
            optionStringNumbers: false,
            returnError: [Function: returnError],
            returnFatalError: [Function: returnFatalError],
            returnReply: [Function: returnReply],
            offset: 0,
            buffer: null,
            bigStrSize: 0,
            totalChunkSize: 0,
            bufferCache: [],
            arrayCache: [],
            arrayPos: []
          },
          stream: Socket {
            connecting: false,
            _hadError: false,
            _parent: null,
            _host: null,
            _readableState: [ReadableState],
            readable: true,
            _events: [Object: null prototype],
            _eventsCount: 5,
            _maxListeners: undefined,
            _writableState: [WritableState],
            writable: true,
            allowHalfOpen: false,
            _sockname: null,
            _pendingData: null,
            _pendingEncoding: '',
            server: null,
            _server: null,
            timeout: 0,
            [Symbol(asyncId)]: 223,
            [Symbol(kHandle)]: [TCP],
            [Symbol(kSetNoDelay)]: true,
            [Symbol(lastWriteQueueSize)]: 0,
            [Symbol(timeout)]: null,
            [Symbol(kBuffer)]: null,
            [Symbol(kBufferCb)]: null,
            [Symbol(kBufferGen)]: null,
            [Symbol(kCapture)]: false,
            [Symbol(kBytesRead)]: 0,
            [Symbol(kBytesWritten)]: 0
          },
          emitted_end: false,
          [Symbol(kCapture)]: false
        },
        subClient: RedisClient {
          _events: [Object: null prototype] {
            newListener: [Function],
            error: [Function],
            message: [Function]
          },
          _eventsCount: 3,
          _maxListeners: undefined,
          address: '127.0.0.1:6379',
          connection_options: { port: 6379, host: '127.0.0.1', family: 4 },
          connection_id: 3,
          connected: true,
          ready: false,
          should_buffer: false,
          command_queue: Denque { _head: 0, _tail: 1, _capacityMask: 3, _list: [Array] },
          offline_queue: Denque { _head: 0, _tail: 0, _capacityMask: 3, _list: [Array] },
          pipeline_queue: Denque { _head: 0, _tail: 0, _capacityMask: 3, _list: [Array] },
          connect_timeout: 3600000,
          enable_offline_queue: true,
          retry_timer: null,
          retry_totaltime: 0,
          retry_delay: 200,
          retry_backoff: 1.7,
          attempts: 1,
          pub_sub_mode: 0,
          subscription_set: {},
          monitoring: false,
          message_buffers: false,
          closing: false,
          server_info: {},
          auth_pass: undefined,
          selected_db: undefined,
          fire_strings: true,
          pipeline: false,
          sub_commands_left: 0,
          times_connected: 1,
          buffers: false,
          options: {
            port: '6379',
            host: '127.0.0.1',
            url: 'redis://127.0.0.1:6379',
            retry_strategy: [Function: retry_strategy],
            socket_keepalive: true,
            socket_initial_delay: 0,
            return_buffers: false,
            detect_buffers: false
          },
          reply: 'ON',
          reply_parser: JavascriptRedisParser {
            optionReturnBuffers: false,
            optionStringNumbers: false,
            returnError: [Function: returnError],
            returnFatalError: [Function: returnFatalError],
            returnReply: [Function: returnReply],
            offset: 0,
            buffer: null,
            bigStrSize: 0,
            totalChunkSize: 0,
            bufferCache: [],
            arrayCache: [],
            arrayPos: []
          },
          stream: Socket {
            connecting: false,
            _hadError: false,
            _parent: null,
            _host: null,
            _readableState: [ReadableState],
            readable: true,
            _events: [Object: null prototype],
            _eventsCount: 5,
            _maxListeners: undefined,
            _writableState: [WritableState],
            writable: true,
            allowHalfOpen: false,
            _sockname: null,
            _pendingData: null,
            _pendingEncoding: '',
            server: null,
            _server: null,
            timeout: 0,
            [Symbol(asyncId)]: 226,
            [Symbol(kHandle)]: [TCP],
            [Symbol(kSetNoDelay)]: true,
            [Symbol(lastWriteQueueSize)]: 0,
            [Symbol(timeout)]: null,
            [Symbol(kBuffer)]: null,
            [Symbol(kBufferCb)]: null,
            [Symbol(kBufferGen)]: null,
            [Symbol(kCapture)]: false,
            [Symbol(kBytesRead)]: 0,
            [Symbol(kBytesWritten)]: 0
          },
          emitted_end: false,
          [Symbol(kCapture)]: false
        },
        connection: Promise { [ undefined, undefined ] }
      }

```
My Code:
```
describe('Mpp services for Merchant', () => {
    let app: INestApplication;
    let mS: myService;
    let aC: AppController;
    let client: ClientProxy;
    beforeAll(async () => {
        const module = await Test.createTestingModule({
            imports: [HttpModule,
                ClientsModule.register([{
                    name: 'REDIS_SERVICE', transport: Transport.REDIS, options: {
                        url: 'redis://127.0.0.1:6379'
                    }
                }]),
                TypeOrmModule.forRoot(environment.typeOrmConfig),
                TypeOrmModule.forFeature([...entities]),],
            controllers: [AppController],
            providers: [MyService, ...repositories],
        }).compile();
        mS = module.get<MyService>(MyService);
        aC = module.get<AppController>(AppController);
        app = module.createNestApplication();
        app.connectMicroservice({
            transport: Transport.REDIS
        })

        await app.startAllMicroservicesAsync();
        await app.init()
        client = app.get('REDIS_SERVICE');
        await client.connect();
    });
    afterAll(async () => {
        await app.close();
    });
    describe('Validate My Services.', () => {
        it('Test Request with request ID.', async () => {
            const requestId = 'TEST_REQUEST_ID';
            console.log(aC);
            try {
        console.log(client);
                const res = await client.send('MESSAGE_PATTERN', { requestId }).toPromise();
            }
            catch(e){
                console.log(e);
            }

            expect(1).toBe(1);
        }, 10000);
    });
});

```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
