### ISSUE TITLE
Crash  app when check token on handleConnection , cannot try catch error

### ISSUE THREAD

**Issue by BuiTanLan** [nestjs/nest#7212]
## Current behavior
Crash app  when when I pass a fake token to handleConnection()
C:\Users\TMT\source\repos\socket_app\tmt.tdeskapp\node_modules\rxjs\internal\util\hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^

Error
    at MessageGateway.handleConnection (C:\Users\TMT\source\repos\socket_app\tmt.tdeskapp\dist\message\message.gateway.js:59:19)
    at SafeSubscriber._next (C:\Users\TMT\source\repos\socket_app\tmt.tdeskapp\node_modules\@nestjs\websockets\web-sockets-controller.js:67:47)
    at SafeSubscriber.__tryOrUnsub (C:\Users\TMT\source\repos\socket_app\tmt.tdeskapp\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (C:\Users\TMT\source\repos\socket_app\tmt.tdeskapp\node_modules\rxjs\internal\Subscriber.js:143:22)
    at Subscriber._next (C:\Users\TMT\source\repos\socket_app\tmt.tdeskapp\node_modules\rxjs\internal\Subscriber.js:89:26)
    at Subscriber.next (C:\Users\TMT\source\repos\socket_app\tmt.tdeskapp\node_modules\rxjs\internal\Subscriber.js:66:18)                                    9:30)
    at DistinctUntilChangedSubscriber._next (C:\Users\TMT\source\repos\socket_app\tmt.tdeskapp\node_modules\rxjs\internal\operators\distinctUntilChanged.js:69:30)
    at DistinctUntilChangedSubscriber.Subscriber.next (C:\Users\TMT\source\repos\socket_app\tmt.tdeskapp\node_modules\rxjs\internal\Subscriber.js:66:18)     
    at Subject.next (C:\Users\TMT\source\repos\socket_app\tmt.tdeskapp\node_modules\rxjs\internal\Subject.js:60:25)
    at Namespace.<anonymous> (C:\Users\TMT\source\repos\socket_app\tmt.tdeskapp\node_modules\@nestjs\websockets\web-sockets-controller.js:51:24)
## Input Code
``` javascript
  parseJwt (token) {
    var base64Url = token.split('.')[1]; // undefind error hear
    var base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/');
    var jsonPayload = decodeURIComponent(atob(base64).split('').map(c => 
      '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2)
    ).join(''));
    return JSON.parse(jsonPayload);
  }
```
``` javascript
 handleConnection(client: Socket, ...args: any[]) {
    let decodedToken: any
    // const token = client.handshake.query.token;
   // this is a type of error 
    const token = 'hsgsggsgs'
    try {
      decodedToken = this.parseJwt(token);
}
  catch(err)
  {
           throw new Error();
  }
}
```
## Expected behavior
Log  the error and continue handle next request
## Environment

Nest version: 7.5.6
 
For Tooling issues:
- Node version: 14.5.4
- Platform:  Win 10

>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
