### ISSUE TITLE
[HMR] Update failed Problem

### ISSUE THREAD

**Issue by LKHcoding** [nestjs/nest#7260]
## Bug Report

I'm following the official document.
but sometimes my code updates does not reflect by hmr.
with this error:

```ts
[HMR] Update failed: SyntaxError: D:\blahblah\blahblah\dist\main.3c23bdbe3e77eb518d90.hot-update.json: Unexpected end of JSON input
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1106:22)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at D:\blahblah\blahblahblah\dist\main.js:2914:21
```

plz someone help me how to fix it.

thanks

## Input Code

```ts
"scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev-backup": "nest start --watch",
    "start:dev": "nest build --webpack --webpackPath webpack-hmr.config.js --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^7.6.15",
    "@nestjs/config": "^0.6.3",
    "@nestjs/core": "^7.6.15",
    "@nestjs/jwt": "^7.2.0",
    "@nestjs/passport": "^7.1.5",
    "@nestjs/platform-express": "^7.6.15",
    "@nestjs/swagger": "^4.8.0",
    "@nestjs/typeorm": "^7.1.5",
    "axios": "^0.21.1",
    "bcrypt": "^5.0.1",
    "class-transformer": "^0.4.0",
    "class-validator": "^0.13.1",
    "cookie-parser": "^1.4.5",
    "express-session": "^1.17.1",
    "mysql2": "^2.2.5",
    "passport": "^0.4.1",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^6.6.6",
    "swagger-ui-express": "^4.1.6",
    "typeorm": "^0.2.32"
  },
  "devDependencies": {
    "@nestjs/cli": "^7.6.0",
    "@nestjs/schematics": "^7.3.0",
    "@nestjs/testing": "^7.6.15",
    "@types/bcrypt": "^5.0.0",
    "@types/cookie-parser": "^1.4.2",
    "@types/express": "^4.17.11",
    "@types/jest": "^26.0.22",
    "@types/node": "^14.14.36",
    "@types/passport-jwt": "^3.0.5",
    "@types/passport-local": "^1.0.33",
    "@types/supertest": "^2.0.10",
    "@typescript-eslint/eslint-plugin": "^4.19.0",
    "@typescript-eslint/parser": "^4.19.0",
    "eslint": "^7.22.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-prettier": "^3.3.1",
    "jest": "^26.6.3",
    "prettier": "^2.2.1",
    "run-script-webpack-plugin": "0.0.11",
    "supertest": "^6.1.3",
    "ts-jest": "^26.5.4",
    "ts-loader": "^8.0.18",
    "ts-node": "^9.1.1",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^4.2.3",
    "webpack": "^5.37.0",
    "webpack-node-externals": "^3.0.0"
  },
```

## Expected behavior

`npm run start:dev`

and

```ts
@Get('all')
  findAll(@Query() query) {
    return this.userService.findAll();
  }

  // Modified as below...

@Get('all')
  async findAll(@Query() query) {
    return await this.userService.findAll();
  }

// if i save -> error [HMR] Update failed: SyntaxError:

```

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: v14.15.4  
- Platform:  

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) for Support and provide a [minimum reproduction](http://minimum-reproduction.wtf) to gain better assistance. We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
