### ISSUE TITLE
Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by LitHaxor** [nestjs/nest#7514]
## Current behavior
URL : http://127.0.0.1:3000/

When I use Fasitfy adapter it always throws  a error in response.
For the express one working fine.

{
"statusCode": 500,
"error": "Internal Server Error",
"message": "Right-hand side of 'instanceof' is not an object"
}

## Input Code

```ts
import { NestFactory } from '@nestjs/core';
import {
  FastifyAdapter,
  NestFastifyApplication,
} from '@nestjs/platform-fastify';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter(),
  );
  await app.listen(3000);
}
bootstrap();
```

## Expected behavior

Nest factory should return Hello world when I hit http://127.0.0.1:3000/
## Environment

<pre><code>
Nest version: 7.6.15

 
For Tooling issues:
- Node version:   16.0.0
- Platform:  windows

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by LitHaxor** [comment]
Bear minimum,
It's a boilerplate repository!
nest new .

**Comment by jmcdo29** [comment]
This works perfectly fine for me on the newest versions, using `nest new` to create and the following system info
```
[System Information]
OS Version     : Linux 5.11
NodeJS Version : v14.16.0
NPM Version    : 6.14.11

[Nest CLI]
Nest CLI Version : 8.0.2

[Nest Platform Information]
platform-express version : 8.0.0
platform-fastify version : 8.0.1
common version           : 8.0.0
core version             : 8.0.0
```
If you can provide a minimum reproduction, I'll take a look, but at the moment, everything is working as expected.

**Comment by loicnestler** [comment]
Same error for me.
When using `@nest/fastify-adapter` every request returns a 500 with the error message described above.

<img width="480" alt="Screenshot 2021-07-16 at 10 04 30" src="https://user-images.githubusercontent.com/48695625/125914223-a05a6cf0-59df-45b1-9e2b-335fe232080a.png">

_main.ts_:
```typescript
async function bootstrap() {
   const app = await NestFactory.create<NestFastifyApplication>(
      AppModule,
      new FastifyAdapter({
         logger: true,
      }),
   )
   // app.useGlobalPipes(new ValidationPipe())
   // app.useGlobalInterceptors(new ApiInterceptor())
   await app.listen(3000, '0.0.0.0')
}
bootstrap()
```

_app.module.ts_:
```typescript
@Module({
   imports: [],
   controllers: [AppController],
   providers: [AppService],
})
export class AppModule {}
```

_app.service.ts_:
```typescript
import { Injectable } from '@nestjs/common'

@Injectable()
export class AppService {
   getHello(): string {
      return 'Hello World!'
   }
}
```

_app.controller.ts_:
```typescript
import { Controller, Get } from '@nestjs/common'
import { AppService } from './app.service'

@Controller()
export class AppController {
   constructor(private readonly appService: AppService) {}

   @Get()
   getHello(): string {
      return this.appService.getHello()
   }
}
```


Detailed error message when using Fastify's `logger` option:
```json
{"level":50,"time":1626421134264,"pid":73789,"hostname":"xxx","reqId":"req-1","req":{"method":"GET","url":"/","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":59780},"res":{"statusCode":500},"err":{"type":"TypeError","message":"Right-hand side of 'instanceof' is not an object","stack":"TypeError: Right-hand side of 'instanceof' is not an object\n    at FastifyAdapter.reply (/Users/loic/Documents/xxx/apps/yyy/node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.js:46:18)\n    at ExceptionsHandler.handleUnknownError (/Users/loic/Documents/xxx/apps/yyy/node_modules/@nestjs/core/exceptions/base-exception-filter.js:33:24)\n    at ExceptionsHandler.catch (/Users/loic/Documents/xxx/apps/yyy/node_modules/@nestjs/core/exceptions/base-exception-filter.js:17:25)\n    at ExceptionsHandler.next (/Users/loic/Documents/xxx/apps/yyy/node_modules/@nestjs/core/exceptions/exceptions-handler.js:16:20)\n    at Object.<anonymous> (/Users/loic/Documents/xxx/apps/yyy/node_modules/@nestjs/core/router/router-proxy.js:13:35)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"},"msg":"Right-hand side of 'instanceof' is not an object"}
{"level":30,"time":1626421134268,"pid":73789,"hostname":"xxx","reqId":"req-1","res":{"statusCode":500},"responseTime":123.23202300071716,"msg":"request completed"}
```

**Comment by kamilmysliwiec** [comment]
`@nestjs/core` and `@nestjs/common` should be at the same version as the `@nestjs/platform-fastify`.

If you're still running into this issue, please create a separate GH issue and provide a minimum reproduction repository.
