### ISSUE TITLE
Http Module Injection in Auth Guard not working in version 8

### ISSUE THREAD

**Issue by abhideepm** [nestjs/nest#7538]
I'm getting the following error when I try to inject HttpService into the AuthGuard.

```[4:57:11 PM] Starting compilation in watch mode...

[4:57:18 PM] Found 0 errors. Watching for file changes.

[Nest] 51467  - 07/12/2021, 4:57:19 PM     LOG [NestFactory] Starting Nest application...
[Nest] 51467  - 07/12/2021, 4:57:19 PM     LOG [InstanceLoader] FirestoreModule dependencies initialized +38ms
[Nest] 51467  - 07/12/2021, 4:57:19 PM     LOG [InstanceLoader] SequelizeModule dependencies initialized +0ms
[Nest] 51467  - 07/12/2021, 4:57:19 PM     LOG [InstanceLoader] SequelizeModule dependencies initialized +0ms
[Nest] 51467  - 07/12/2021, 4:57:19 PM     LOG [InstanceLoader] HttpModule dependencies initialized +1ms
[Nest] 51467  - 07/12/2021, 4:57:19 PM     LOG [InstanceLoader] JwtModule dependencies initialized +0ms
[Nest] 51467  - 07/12/2021, 4:57:19 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +1ms
[Nest] 51467  - 07/12/2021, 4:57:19 PM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the AuthGuard (?, JwtService). Please make sure that the argument HttpService at index [0] is available in the AppModule context.

Potential solutions:
- If HttpService is a provider, is it part of the current AppModule?
- If HttpService is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing HttpService */ ]
  })

Error: Nest can't resolve dependencies of the AuthGuard (?, JwtService). Please make sure that the argument HttpService at index [0] is available in the AppModule context.

Potential solutions:
- If HttpService is a provider, is it part of the current AppModule?
- If HttpService is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing HttpService */ ]
  })

    at Injector.lookupComponentInParentModules (/project/common/temp/node_modules/.pnpm/@nestjs+core@8.0.2_bdc7d2ccb696b9487f714c3cb0124821/node_modules/@nestjs/core/injector/injector.js:189:19)
    at Injector.resolveComponentInstance (/project/common/temp/node_modules/.pnpm/@nestjs+core@8.0.2_bdc7d2ccb696b9487f714c3cb0124821/node_modules/@nestjs/core/injector/injector.js:145:33)
    at resolveParam (/project/common/temp/node_modules/.pnpm/@nestjs+core@8.0.2_bdc7d2ccb696b9487f714c3cb0124821/node_modules/@nestjs/core/injector/injector.js:99:38)
    at async Promise.all (index 0)
    at Injector.resolveConstructorParams (/project/common/temp/node_modules/.pnpm/@nestjs+core@8.0.2_bdc7d2ccb696b9487f714c3cb0124821/node_modules/@nestjs/core/injector/injector.js:114:27)
    at Injector.loadInstance (/project/common/temp/node_modules/.pnpm/@nestjs+core@8.0.2_bdc7d2ccb696b9487f714c3cb0124821/node_modules/@nestjs/core/injector/injector.js:47:9)
    at Injector.loadProvider (/project/common/temp/node_modules/.pnpm/@nestjs+core@8.0.2_bdc7d2ccb696b9487f714c3cb0124821/node_modules/@nestjs/core/injector/injector.js:69:9)
    at async Promise.all (index 3)
    at InstanceLoader.createInstancesOfProviders (/project/common/temp/node_modules/.pnpm/@nestjs+core@8.0.2_bdc7d2ccb696b9487f714c3cb0124821/node_modules/@nestjs/core/injector/instance-loader.js:44:9)
    at /project/common/temp/node_modules/.pnpm/@nestjs+core@8.0.2_bdc7d2ccb696b9487f714c3cb0124821/node_modules/@nestjs/core/injector/instance-loader.js:29:13
```

In the AuthGuard

```ts
@Injectable()
export class AuthGuard implements CanActivate {
  constructor(
    @Inject("HttpService") private readonly httpService: HttpService,
    @Inject("JwtService") private readonly jwtService: JwtService
  ) {}

  canActivate(context: ExecutionContext): Promise<boolean> {
    const request = context.switchToHttp().getRequest();
    return validateToken(request, this.httpService, this.jwtService);
  }
}
```
This error also happens for jwtService if I change the order of dependency injection in the AuthGuard constructor.

Both HttpModule and JwtModule are included in the AppModule imports.

I am importing the AuthGuard in AppModule like this:
```ts
providers: [
    {
      provide: APP_GUARD,
      useClass: AuthGuard
    }
  ]
```

And using it like this:
```ts
export class AppModule implements NestModule {
  configure(consumer: MiddlewareConsumer): void {
    consumer.apply(AppLoggerMiddleware).forRoutes("*");
  }
}
```

## Expected behavior
It should work without any modifications as it was working in Nest version 7.

Nest version: 8.0.2
Tooling:
- Node version: 16.4.2
- Platform:  Mac
- IDE: Webstorm
- Package Manager: Rush with PNPM

**Comment by kamilmysliwiec** [comment]
Your code is invalid. Remove `@Inject("HttpService")`.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
