### ISSUE TITLE
Cannot find module 'rxjs' on @nestjs/common

### ISSUE THREAD

**Issue by rochadsouzaiit** [nestjs/nest#7575]
## Bug Report
When I do `npm install --only=production` rxjs is not installed however  @nestjs/common requires it.

## Current behavior
Not able to build my code for production

## Input Code
```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'rxjs'
Require stack:
- /usr/src/app/node_modules/@nestjs/common/cache/interceptors/cache.interceptor.js
- /usr/src/app/node_modules/@nestjs/common/cache/interceptors/index.js
- /usr/src/app/node_modules/@nestjs/common/cache/index.js
- /usr/src/app/node_modules/@nestjs/common/index.js
- /usr/src/app/dist/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/src/app/node_modules/@nestjs/common/cache/interceptors/cache.interceptor.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/app/node_modules/@nestjs/common/cache/interceptors/cache.interceptor.js',
    '/usr/src/app/node_modules/@nestjs/common/cache/interceptors/index.js',
    '/usr/src/app/node_modules/@nestjs/common/cache/index.js',
    '/usr/src/app/node_modules/@nestjs/common/index.js',
    '/usr/src/app/dist/main.js'
  ]
}
```
## Expected behavior
This dependency to be added.

## Possible Solution
Add this dependency for production to  @nestjs/common

On time solution: `npm i -S rxjs`

**Comment by kamilmysliwiec** [comment]
`rxjs` is a peer dependency of NestJS. 

![image](https://user-images.githubusercontent.com/23244943/125765380-3640e8df-21a6-4f7d-aedd-ff844bfd14ff.png)

https://docs.nestjs.com/#alternatives
