### ISSUE TITLE
A dynamic module can't be exported using module options

### ISSUE THREAD

**Issue by leon19** [nestjs/nest#7576]
## Current behavior
A dynamic module can't be exported using module options and requires the module to be exported using the module key

```
[Nest] 34554  - 15/07/2021 11:57:14     LOG [NestFactory] Starting Nest application...
[Nest] 34554  - 15/07/2021 11:57:14   ERROR [ExceptionHandler] Nest cannot export a provider/module that is not a part of the currently processed module (AppModule). Please verify whether the exported MyDynamicModule is available in this particular context.

Possible Solutions:
- Is MyDynamicModule part of the relevant providers/imports within AppModule?

Error: Nest cannot export a provider/module that is not a part of the currently processed module (AppModule). Please verify whether the exported MyDynamicModule is available in this particular context.

Possible Solutions:
- Is MyDynamicModule part of the relevant providers/imports within AppModule?

    at Module.validateExportedProvider (/home/user/project/node_modules/@nestjs/core/injector/module.js:286:19)
    at addExportedUnit (/home/user/project/node_modules/@nestjs/core/injector/module.js:254:67)
    at Module.addExportedProvider (/home/user/project/node_modules/@nestjs/core/injector/module.js:263:20)
    at NestContainer.addExportedProvider (/home/user/project/node_modules/@nestjs/core/injector/container.js:127:19)
    at DependenciesScanner.insertExportedProvider (/home/user/project/node_modules/@nestjs/core/scanner.js:221:24)
    at /home/user/project/node_modules/@nestjs/core/scanner.js:126:50
    at Array.forEach (<anonymous>)
    at DependenciesScanner.reflectExports (/home/user/project/node_modules/@nestjs/core/scanner.js:126:17)
    at DependenciesScanner.scanModulesForDependencies (/home/user/project/node_modules/@nestjs/core/scanner.js:79:18)
    at DependenciesScanner.scan (/home/user/project/node_modules/@nestjs/core/scanner.js:27:9)
```

## Input Code

```ts
import { DynamicModule, Module } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';

class MyDynamicModule {
  static forRoot(): DynamicModule {
    return {
      module: MyDynamicModule
    };
  }
}

const myDynamicModule = MyDynamicModule.forRoot();

@Module({ imports: [myDynamicModule], exports: [myDynamicModule] }) // It works if I export myDynamicModule.module or MyDynamicModule
class AppModule {}

NestFactory.create(AppModule);
```

## Expected behavior
I expect the module to be exported using module options or the module class indistinctly like the previous version

## Environment

<pre><code>
Nest version: 8.0.2

 
For Tooling issues:
- Node version: v14.16.1  
- Platform:  Linux (Ubuntu 20.04)

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Fixed in 8.0.3. Thanks for reporting
