### ISSUE TITLE
MongoDb with TypeORM doesn't work

### ISSUE THREAD

**Issue by knopkem** [nestjs/nest#7798]
## Current behavior
Running the example mongo-typeorm (docker, local mongodb) throws exception when accessing data:

<pre><code>
[Nest] 9771  - 08/09/2021, 8:15:09 AM   ERROR [ExceptionsHandler] Cannot read property 'prototype' of undefined
TypeError: Cannot read property 'prototype' of undefined
    at FindCursor.cursor.toArray (/home/anon/projects/mongo-typeorm-sample/src/entity-manager/MongoEntityManager.ts:707:37)
    at MongoEntityManager.<anonymous> (/home/anon/projects/mongo-typeorm-sample/src/entity-manager/MongoEntityManager.ts:97:23)
    at step (/home/anon/projects/mongo-typeorm-sample/node_modules/tslib/tslib.js:143:27)
    at Object.next (/home/anon/projects/mongo-typeorm-sample/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/home/anon/projects/mongo-typeorm-sample/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
</code></pre>

## Expected behavior
* in case of of an empty mongodb opening the browser http://localhost/photo should return an empty array
* in case of using the docker image, it should return an array of photo entities
* no error should be shown in nest.js

## Environment

<pre><code>
"@nestjs/common": "8.0.5",
"@nestjs/core": "8.0.5",
"@nestjs/platform-express": "8.0.5",
"@nestjs/typeorm": "8.0.2",
"mongodb": "4.1.0",
"reflect-metadata": "0.1.13",
"rimraf": "3.0.2",
"rxjs": "7.3.0",
"typeorm": "0.2.36"
 
For Tooling issues:
- Node version: 14.17.4
- Platform:  Linux 

Others:
* tried using docker-compose
* tried with local mongodb installed (same error)

**Comment by jmcdo29** [comment]
TypeORM doesn't support Mongo v4. This is a problem with TypeORM not Nest. Please report it to the appropriate repo.
