### ISSUE TITLE
Cannot change file config from ormconfig.js to ormconfig.ts

### ISSUE THREAD

**Issue by tuanna2704** [nestjs/nest#7850]
## Bug Report
I am using @nestjs/typeorm for my application and I put my config in ormconfig.js. Its work normally. Here is content of file ormconfig.js:
```
const {
  DB_TYPE,
  DB_HOST,
  DB_USERNAME,
  DB_PASSWORD,
  DB_PORT,
  DB_DATABASE,
} = process.env;

export default {
  type: DB_TYPE,
  host: DB_HOST,
  port: DB_PORT,
  username: DB_USERNAME,
  password: DB_PASSWORD,
  database: DB_DATABASE,
  migrations: [__dirname + '/src/migrations/*{.ts,.js}'],
  cli: {
    migrationsDir: 'src/migrations',
  },
};
```
But when I change file name from from ormconfig.js to ormconfig.ts. I got the error.
## Current behavior

After change file name, I got this error when run `yarn start:dev`
```
[11:47:37 PM] Found 0 errors. Watching for file changes.

internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '../../protobuf/issue_pb'
Require stack:
- microservice-base-template/dist/src/shared/services/status.details.serialization.js
- microservice-base-template/dist/src/shared/services/common.utils.js
- microservice-base-template/dist/src/app.controller.js
- microservice-base-template/dist/src/app.module.js
- microservice-base-template/dist/src/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/tuannna2704/cerebral/microservice-base-template/dist/src/shared/services/status.details.serialization.js:5:20)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'microservice-base-template/dist/src/shared/services/status.details.serialization.js',
    'microservice-base-template/dist/src/shared/services/common.utils.js',
    'microservice-base-template/dist/src/app.controller.js',
    'microservice-base-template/dist/src/app.module.js',
    'microservice-base-template/dist/src/main.js'
  ]
}
```
## Expected behavior
I expect that after change filename from ormconfig.js to ormconfig.ts

## Environment

<pre><code>
Nest version: 8.0.2

 
For Tooling issues:
- Node version:  v14.17.4  
- Platform:  Mac

Others:

</code></pre>

**Comment by jmcdo29** [comment]
This isn't a problem with NestJS, but rather how Typescript works. When you have `ts` files outside of your rootDir that Typescript believes it should read and compile, it will try to keep the directory structure when it moves the transpiled code to `dist`, so instead of having
```
dist
  feature1
  feature2
  main.js
src
  feature1
  feature2
  main.ts
ormconfig.js
```

You end up getting
```
dist
  src
    feature1
    feature2
    main.js
  ormconfig.js
src
  feature1
  feature2
  main.ts
ormconfig.ts
```

This means that if you're using `__dirname` to get back to your workspace root, you're now one more level away than you used to be. You can use `process.cwd()` to get the root directory where the `node` command was ran from, or you continue to use a `js` file instead of `ts`.
