### ISSUE TITLE
Undefined method when using IntersectionType

### ISSUE THREAD

**Issue by averri** [nestjs/nest#7856]
## Current behavior
I'm using the `IntersectionType` to derive a class from two other classes. 

## Input Code

Derived class: 

```ts
import {Validate} from 'class-validator';
import {Type} from 'class-transformer';
import {ApiProperty, IntersectionType} from "@nestjs/swagger";
import {IsUsernameAvailable} from "src/validations/decorators/username.validator";
import {IsEmailAvailable, IsEmailValid} from "src/validations/decorators/email.validator";
import {ExistingTimeZone} from 'src/validations/decorators/time-zone.validator';
import {ExistingLocale} from 'src/validations/decorators/locale.validator';
import {ClearPasswordDto} from "src/base/clear-password.dto";
import {User} from "src/users/entities/user.entity";
import {
  IsNotEmpty, IsDate, Length,
  MaxLength, IsBoolean, IsPastDate
} from 'src/validations/decorators/class-validator'
import {CaptchaV2Dto} from "../../base/captcha.dto";


export class CreateSignUpDto extends IntersectionType(ClearPasswordDto, CaptchaV2Dto) {

  @ApiProperty()
  @IsNotEmpty()
  @Length(3, 20)
  @Validate(IsUsernameAvailable)
  username: string;

  @MaxLength(100)
  @Validate(IsEmailValid)
  @Validate(IsEmailAvailable)
  email: string;

  @IsDate()
  @Type(() => Date)
  @IsPastDate()
  birthDate: Date;

  @IsBoolean()
  @IsNotEmpty()
  acceptTerms: boolean;

  @IsNotEmpty()
  @Validate(ExistingLocale)
  locale: string;

  @IsNotEmpty()
  @Validate(ExistingTimeZone)
  timeZone: string;

  static new(dto: CreateSignUpDto) {
    return Object.assign(new CreateSignUpDto(), dto);
  }

  /**
   * Creates a new user from the sign-up data.
   */
  async newUser(): Promise<User> {
    const now = new Date();
    return new User(this.username, this.email, this.birthDate,
      await this.getPassword(), this.locale, this.timeZone, now, now);
      //          ^^^^^^^^^ This method is not found when running the code.
  }
}

```

Base class 1:

```ts
import {IsNotEmpty, Length} from "src/validations/decorators/class-validator";
import {hashSafe} from "../utils/token-utils";

export class ClearPasswordDto {

  @IsNotEmpty()
  @Length(6, 200)
  clearPassword: string;

  /**
   * Hashes the clear password and return the result.
   */
  async getPassword() {
    return hashSafe(this.clearPassword);
  }

}
```

Base class 2:

```ts
import {IsNotEmpty, MaxLength} from "../validations/decorators/class-validator";
import {Validate} from "class-validator";
import {IsCaptchaV2Valid} from "../validations/decorators/captcha.validator";


export class CaptchaV2Dto {

  @IsNotEmpty()
  @MaxLength(500)
  @Validate(IsCaptchaV2Valid)
  captchaResponse: string;
}
```

## Expected behavior
The composed class `CreateSignUpDto` should contain all the methods and properties from both `ClearPasswordDto` and `CaptchaV2Dto`. When running the application, I get the following error:

```
0|api  | **TypeError: this.getPassword is not a function**
0|api  |     at CreateSignUpDto.newUser (/home/alex/dev/src/other/mentoring-journey-api/src/sign-up/dto/create-sign-up.dto.ts:57:18)
0|api  |     at Object.createUser (/home/alex/dev/src/other/mentoring-journey-api/src/sign-up/sign-up.service.ts:68:59)
0|api  |     at FlowsService.run (/home/alex/dev/src/other/mentoring-journey-api/src/flows/flows.service.ts:132:29)
0|api  |     at FlowsService.runUserTask (/home/alex/dev/src/other/mentoring-journey-api/src/flows/flows.service.ts:112:17)
0|api  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

... indicating that the method `getPassword` was not found.

## Possible Solution
In order to make it work, I have created the following solution:

```ts
import {Type} from '@nestjs/common';
import {IntersectionType as Intersection} from "@nestjs/swagger";


function getMethods(obj) {
  return Object.getOwnPropertyNames(obj).filter(item => typeof obj[item] === 'function')
}


function applyMethodsMixin(derived: any, baseClasses: any[]) {
  baseClasses.forEach(base => {
    getMethods(base.prototype).forEach(name => {
      if (name !== 'constructor') {
        derived.prototype[name] = base.prototype[name];
      }
    });
  });
}


export function IntersectionType<A, B>(classARef: Type<A>, classBRef: Type<B>): Type<A & B> {
  const result = Intersection(classARef, classBRef);
  applyMethodsMixin(result, [classARef, classBRef]);
  return result;
}

```

## Environment

<pre><code>
Nest version: 8.0.0

 
For Tooling issues:
- Node version: v14.15.4
- Platform: Linux Ubuntu 18

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
