### ISSUE TITLE
Injector boot exception doesn't provide any information for debugging

### ISSUE THREAD

**Issue by ccontour** [nestjs/nest#7890]
## Current behavior
Recently attempted an update from 8.0.4 -> 8.0.6, and started receiving errors from this exception. 
https://github.com/nestjs/nest/blob/master/packages/core/injector/injector.ts#L108

It appears just after discovery module is loaded, and provides no information on why it is being thrown. 

```
 Error:
    at Injector.loadInstance (..../node_modules/@nestjs/core/injector/injector.js:36:19)
    at Injector.loadProvider (..../node_modules/@nestjs/core/injector/injector.js:69:20)
    at Injector.resolveComponentHost (..../node_modules/@nestjs/core/injector/injector.js:156:24)
    at Injector.resolveComponentInstance (..../node_modules/@nestjs/core/injector/injector.js:150:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at resolveParam (..../node_modules/@nestjs/core/injector/injector.js:103:38)
    at async Promise.all (index 3)
    at Injector.resolveConstructorParams (..../node_modules/@nestjs/core/injector/injector.js:118:27)
    at Injector.loadInstance (..../node_modules/@nestjs/core/injector/injector.js:47:9)
    at Injector.loadProvider (..../node_modules/@nestjs/core/injector/injector.js:69:9)
    at Injector.lookupComponentInImports (..../node_modules/@nestjs/core/injector/injector.js:225:17)
    at Injector.lookupComponentInParentModules (..../node_modules/@nestjs/core/injector/injector.js:191:33)
    at Injector.resolveComponentInstance (..../node_modules/@nestjs/core/injector/injector.js:149:33)
    at resolveParam (..../node_modules/@nestjs/core/injector/injector.js:103:38)
    at async Promise.all (index 0)
    at Injector.resolveConstructorParams (..../node_modules/@nestjs/core/injector/injector.js:118:27)
```

## Expected behavior
Exceptions being thrown during boot time should provide some explanation as to why they are being thrown

## Possible Solution
Add additional context to the message. Any additional secondary information around what that error is that might be of use before I jump in and attempt to find my breaking module would be appreciated.

**Comment by jmcdo29** [comment]
Can you please provide a [minimum reproduction repository](http://minimum-reproduction.wtf) that triggers this error specifically?

**Comment by ccontour** [comment]
I'd be happy to after I find out which module is causing it. Is there any guidance that you can provide to help me isolate which module it might be? I am not sure what that error message is trying to communicate

**Comment by jmcdo29** [comment]
Strange that it's really just a stack trace. It seems like this error may have not been meant to be thrown as there's explicitly no default error message. Anything you can provide that triggered this would be helpful in figuring out what happened

**Comment by micalevisk** [comment]
@ccontour are you using injection scopes?

**Comment by ccontour** [comment]
@micalevisk Yes, I have a few that are set up as TRANSIENT. Thanks for the push in that direction, it seems that was the key to finding the breaking service.

The service I am using as my logger is set up as TRANSIENT, and is attempting to inject INQUIRER in order to gain additional context information for log messages. It's getting pulled in all over the place, so that's probably why things bombed so early in startup for for me.

Pulling the scope gets me past the boot error, but breaks the INQUIRER injection

**Comment by ccontour** [comment]
Got the issue resolved in my repo, but the breaking file doesn't seem to be unique. I'm at a bit of a loss unfortunately for replicating it in a minimal way. 

It'd be nice to get a message or some comments around that error to provide a hint that there is probably an issue related scopes if that exception gets thrown. I'm otherwise fine closing this issue

**Comment by kamilmysliwiec** [comment]
@ccontour there's no additional context to this error because you should never really face it in the real-world application. If you figure to somehow track this issue down/create a mini repository that recreates this error, that would be very helpful!
