### ISSUE TITLE
Runtime error after upgrading from 7.6.17 to 8.0.6

### ISSUE THREAD

**Issue by horrendo** [nestjs/nest#7901]
## Describe the regression

An application that was working fine in 7.6.17 fails to start after upgrading to 8.0.6. I now see this on starting the app:

```
Error: Nest can't resolve dependencies of the FxRateService (FxRateRepository, ?, config.APP_SPHERE_MAX_FAILURE_DAYS, CacheService). Please make sure that the argument SphereStubClient at index [1] is available in the FxRateModule context.

Potential solutions:
- If SphereStubClient is a provider, is it part of the current FxRateModule?
- If SphereStubClient is exported from a separate @Module, is that module imported within FxRateModule?
  @Module({
    imports: [ /* the Module containing SphereStubClient */ ]
  })

    at Injector.lookupComponentInParentModules (/Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/injector.js:193:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Injector.resolveComponentInstance (/Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/injector.js:149:33)
    at resolveParam (/Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/injector.js:103:38)
    at async Promise.all (index 1)
    at Injector.resolveConstructorParams (/Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/injector.js:118:27)
    at Injector.loadInstance (/Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/injector.js:47:9)
    at Injector.loadProvider (/Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/injector.js:69:9)
    at async Promise.all (index 3)
    at InstanceLoader.createInstancesOfProviders (/Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/instance-loader.js:44:9)
```

## Input Code

The constructor of `FxRateService`:

```ts
    public constructor(
        private readonly fxRateRepo: FxRateRepository,
        @InjectSphereClient() private readonly sphereClient: SphereClientInterface,
        @Inject('config.APP_SPHERE_MAX_FAILURE_DAYS') private readonly sphereMaxFailureDays: number,
        private readonly cacheService: CacheService
    ) {}
```
The definition of `InjectSphereClient`:

```ts
import { Inject } from '@nestjs/common';
import * as convict from 'convict';
import { convictSchema } from '@/infrastructure/config/ConvictSchema';
import { Stage } from '@/infrastructure/Stage';

const convictConfig = convict(convictSchema);

export const InjectSphereClient = (): any => {
    if (convictConfig.get('STAGE') === Stage.LOCAL) {
        return Inject('SphereStubClient');
    } else {
        return Inject('SphereClient');
    }
};
```
The module including `FxRateService`:

```ts
import { Module } from '@nestjs/common';
import { FxRateService } from '@/business/fx/FxRateService';
import { SphereClient } from '@/business/fx/SphereClient';
import { SphereStubClient } from '@/business/fx/SphereStubClient';
import { CacheModule } from '@/business/cache/CacheModule';

@Module({
    imports: [CacheModule],
    providers: [FxRateService, SphereClient, SphereStubClient],
    controllers: [],
    exports: [FxRateService, SphereClient, SphereStubClient]
})
export class FxRateModule {}
```

## Expected behavior/code

I expected the app to start just like it used to.

## Environment
<pre><code>
Nest version: 7.6.17 -> 8.0.6

For Tooling issues:
- Node version: v14.17.3  
- Platform: Mac  

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Nest v8 uses a class reference instead of the class name for the injection token. As using the class babe was never documented, this change was not documented in the migration guide, but the PR and other issues can be found about this. It's not an issue, your code needs to be updated to use class references as well instead of the name.

**Comment by horrendo** [comment]
Thank you @jmcdo29. With your comment I was able to resolve my issue.
