### ISSUE TITLE
Nest failing to deploy - TypeError cannot read property of '_events' of undefined

### ISSUE THREAD

**Issue by twigs67** [nestjs/nest#7989]
Hello,

Apologies if this isn't the correct place for this, but I'm completely lost as to why I'm getting this error.  `events=target._events` does not exist anywhere in my codebase, so i'm guessing it is due to a node_module, but I can't find the culprit.

What's worse is I can't reproduce this locally, it just fails when deploying to our dev environment. 

```
2021-08-29T14:26:05.489-04:00	Running Node Cluster

2021-08-29T14:26:05.489-04:00	Master server started on 1

2021-08-29T14:26:05.529-04:00	events.js:350

2021-08-29T14:26:05.530-04:00	events = target._events;

2021-08-29T14:26:05.530-04:00	^

2021-08-29T14:26:05.530-04:00	TypeError: Cannot read property '_events' of undefined

2021-08-29T14:26:05.530-04:00	at _addListener (events.js:350:19)

2021-08-29T14:26:05.530-04:00	at addListener (events.js:406:10)

2021-08-29T14:26:05.530-04:00	at Function.clusterize (/usr/src/app/dist/src/core/node-cluster.js:40:30)

2021-08-29T14:26:05.530-04:00	at Object.<anonymous> (/usr/src/app/dist/src/main.js:121:38)

2021-08-29T14:26:05.530-04:00	at Module._compile (internal/modules/cjs/loader.js:1200:30)

2021-08-29T14:26:05.530-04:00	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)

2021-08-29T14:26:05.530-04:00	at Module.load (internal/modules/cjs/loader.js:1049:32)

2021-08-29T14:26:05.530-04:00	at Function.Module._load (internal/modules/cjs/loader.js:937:14)

2021-08-29T14:26:05.530-04:00	at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)

2021-08-29T14:26:05.530-04:00	at internal/main/run_main_module.js:17:47
```

package.json
```
"@nestjs-modules/mailer": "^1.5.1",
    "@nestjs/axios": "^0.0.1",
    "@nestjs/common": "^7.5.1",
    "@nestjs/config": "0.5.0",
    "@nestjs/core": "^7.5.1",
    "@nestjs/jwt": "^7.0.0",
    "@nestjs/mongoose": "^7.1.1",
    "@nestjs/passport": "^7.1.5",
    "@nestjs/platform-express": "^7.5.1",
    "@nestjs/platform-socket.io": "7.6.13",
    "@nestjs/platform-ws": "^7.6.13",
    "@nestjs/serve-static": "^2.1.3",
    "@nestjs/swagger": "^4.7.0",
    "@nestjs/typeorm": "^7.1.5",
    "@nestjs/websockets": "^7.6.11",
    "@types/crypto-js": "^4.0.1",
    "axios": "^0.21.1",
    "bcrypt": "^5.0.0",
    "cache-manager": "^3.4.0",
    "cache-manager-redis-store": "^2.0.0",
    "class-transformer": "^0.3.1",
    "class-validator": "^0.12.2",
    "crypto-js": "^4.0.0",
    "dotenv": "^8.2.0",
    "handlebars": "^4.7.6",
    "jwk-to-pem": "^2.0.3",
    "moment": "^2.29.1",
    "mongoose": "^5.10.13",
    "mysql": "^2.18.1",
    "nanoid": "^3.1.9",
    "nest-winston": "^1.4.0",
    "nestjs-rate-limiter": "^2.7.0",
    "nestjs-stripe": "^0.4.0",
    "nestjs-twilio": "^1.0.2",
    "nodemailer": "^6.4.17",
    "passport": "^0.4.1",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "pg": "^8.5.1",
    "ramda": "^0.27.1",
    "redis": "^3.0.2",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.3.0",
    "socket.io-redis": "5.4.0",
    "stripe": "^8.132.0",
    "swagger-ui-express": "^4.1.4",
    "twilio": "^3.54.0",
    "typeorm": "^0.2.30",
    "typeorm-transactional-cls-hooked": "^0.1.20",
    "winston": "^3.3.3",
    "winston-daily-rotate-file": "^4.5.0"
```

Any help would be greatly appreciated.

**Comment by kamilmysliwiec** [comment]
This is unrelated to the framework. Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
