### ISSUE TITLE
DI in tests failing after v8 upgrade

### ISSUE THREAD

**Issue by davidgoli** [nestjs/nest#8079]
## Bug Report

The code in the linked repository worked fine in Nest 7.6.18, but the tests fail after upgrading to 8. 

## Current behavior

Tests fail:

```
 FAIL  src/app.controller.spec.ts
  ● AppController › root › should return "Hello World!"

    Nest can't resolve dependencies of the ServeAppInterceptor (?). Please make sure that the argument ConfigService at index [0] is available in the RootTestModule context.

    Potential solutions:
    - If ConfigService is a provider, is it part of the current RootTestModule?
    - If ConfigService is exported from a separate @Module, is that module imported within RootTestModule?
      @Module({
        imports: [ /* the Module containing ConfigService */ ]
      })

      at Injector.lookupComponentInParentModules (../node_modules/@nestjs/core/injector/injector.js:193:19)
      at Injector.resolveComponentInstance (../node_modules/@nestjs/core/injector/injector.js:149:33)
      at resolveParam (../node_modules/@nestjs/core/injector/injector.js:103:38)
          at async Promise.all (index 0)
      at Injector.resolveConstructorParams (../node_modules/@nestjs/core/injector/injector.js:118:27)
      at Injector.loadInstance (../node_modules/@nestjs/core/injector/injector.js:47:9)
      at Injector.loadInjectable (../node_modules/@nestjs/core/injector/injector.js:65:9)
          at async Promise.all (index 0)
      at InstanceLoader.createInstancesOfInjectables (../node_modules/@nestjs/core/injector/instance-loader.js:62:9)
```

## Input Code

https://github.com/davidgoli/nest-testing

This code 

## Expected behavior

Tests should pass.

## Possible Solution

The basic issue appears to be caused by a mocked service (`ConfigService`). It is a dependency of the ServeAppInterceptor, which is applied to the AppController. The mocked provider (associated with the ConfigService) is somehow not found when it is being looked up for injection into the ServeAppInterceptor.

However, dependency injection *does* work if it's a direct dependency of the controller; see `WorkingController` for an example.

## Environment

<pre><code>
Nest version: 8.0.0

 
Others:

</code></pre>

**Comment by micalevisk** [comment]
This is not a bug but rather a breaking change.

in v8, this:

```js
          provide: 'ConfigService',
          useValue: new MockConfigService(),
```

becomes this:

```js
          provide: ConfigService,
          useValue: new MockConfigService(),
```

![image](https://user-images.githubusercontent.com/13461315/133181334-9d363258-c977-45d2-be2f-9e3182919546.png)

https://github.com/nestjs/nest/releases/tag/v8.0.0

**Comment by davidgoli** [comment]
Ah, that makes sense. Thank you!
