### ISSUE TITLE
Can't get name of Schema class 

### ISSUE THREAD

**Issue by thehaung** [nestjs/nest#8088]
/home/admin217/Documents/IUH/New Technology/Source Code/be-3hq-chat/dist/user/schemas/user.schema.js:49
    (0, mongoose_1.Prop)({ ref: file_schema_1.File.name, type: [mongoose_2.SchemaTypes.ObjectId], default: [] }),
                                                   ^

TypeError: Cannot read property 'name' of undefined
    at Object.<anonymous> (/home/admin217/Documents/IUH/New Technology/Source Code/be-3hq-chat/dist/user/schemas/user.schema.js:49:52)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/admin217/Documents/IUH/New Technology/Source Code/be-3hq-chat/dist/file/schemas/file.schema.js:14:23)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/admin217/Documents/IUH/New Technology/Source Code/be-3hq-chat/dist/file/file.service.js:22:23)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

**Comment by Tony133** [comment]
Hi @thehaung,  for this type of question I recommend that you use the support channel [discord](https://discord.com/invite/G7Qnnhy).

The NestJS Core Team uses GitHub to track bug reports, feature requests, and regressions.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
