### ISSUE TITLE
Unable to inject a chosen custom repository in a module

### ISSUE THREAD

**Issue by amehmeto** [nestjs/nest#8089]
## Current behavior
I am attempting to apply SOLID principles, and therefore decoupling my service from TypeOrm.
The benefit is that I could use an `InMemoryRepository` for test purposes, and `TypeOrmRepository` for the real production code.

At the moment, I can't inject my custom TypeOrm repository as any random provider. I suspect a specific behavior for handling `@InjectRepository()` and `TypeOrm` to interfere here.
Yet, I can inject my In Memory repositories in my unit test without any problem.

```
[Nest] 12311   - 18/09/2021 à 06:22:43   [ExceptionHandler] Cannot read property 'save' of undefined
TypeError: Cannot read property 'save' of undefined
    at TypeOrmWorkoutRepository.Object.<anonymous>.Repository.save (/Users/arthurmehmetoglu/Development/CorpoSano/back/src/repository/Repository.ts:150:29)
    at WorkoutService.create (/Users/arthurmehmetoglu/Development/CorpoSano/back/src/workout/workout.service.ts:30:35)
    at WorkoutResolver.create (/Users/arthurmehmetoglu/Development/CorpoSano/back/src/workout/workout.resolver.ts:22:32)
    at /Users/arthurmehmetoglu/Development/CorpoSano/back/node_modules/@nestjs/core/helpers/external-context-creator.js:69:33
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at target (/Users/arthurmehmetoglu/Development/CorpoSano/back/node_modules/@nestjs/core/helpers/external-context-creator.js:76:28)
    at /Users/arthurmehmetoglu/Development/CorpoSano/back/node_modules/@nestjs/core/helpers/external-proxy.js:9:24
[Nest] 12311   - 18/09/2021 à 06:22:43   [ExceptionHandler] Cannot read property 'findOne' of undefined +45ms
TypeError: Cannot read property 'findOne' of undefined
    at TypeOrmWorkoutRepository.Object.<anonymous>.Repository.findOne (/Users/arthurmehmetoglu/Development/CorpoSano/back/src/repository/Repository.ts:370:29)
    at TypeOrmWorkoutRepository.findById (/Users/arthurmehmetoglu/Development/CorpoSano/back/src/workout/repositories/typeorm-workout.repository.ts:12:17)
    at WorkoutService.fillWorkoutWithExercises (/Users/arthurmehmetoglu/Development/CorpoSano/back/src/workout/workout.service.ts:38:50)
    at WorkoutResolver.fillWorkoutWithExercises (/Users/arthurmehmetoglu/Development/CorpoSano/back/src/workout/workout.resolver.ts:32:32)
    at /Users/arthurmehmetoglu/Development/CorpoSano/back/node_modules/@nestjs/core/helpers/external-context-creator.js:69:33
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at target (/Users/arthurmehmetoglu/Development/CorpoSano/back/node_modules/@nestjs/core/helpers/external-context-creator.js:76:28)
    at /Users/arthurmehmetoglu/Development/CorpoSano/back/node_modules/@nestjs/core/helpers/external-proxy.js:9:24
```

More details with the code input below.

## Input Code

`workout.module.ts`
```ts
import ...

@Module({
  imports: [TypeOrmModule.forFeature([Workout])],
  providers: [
    {
      provide: EXERCISE_REPOSITORY,
      useClass: TypeOrmExerciseRepository,
    },
    {
      provide: WORKOUT_REPOSITORY,
      useClass: TypeOrmWorkoutRepository,
    },
    WorkoutResolver,
    WorkoutService,
  ],
})
export class WorkoutModule {}
```

`workout.service.ts`
```ts
...

@Injectable()
export class WorkoutService {
  constructor(
    @Inject(WORKOUT_REPOSITORY)
    private readonly workoutRepository: WorkoutRepository,
    @Inject(EXERCISE_REPOSITORY)
    private readonly exerciseRepository: ExerciseRepository,
  ) {}
  
...
```

`workout.service.spec.ts`
```ts
...

describe('Workout Service', () => {
  let workoutService: WorkoutService
  let workoutRepository: WorkoutRepository
  let exerciseRepository: ExerciseRepository

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        {
          provide: WORKOUT_REPOSITORY,
          useClass: InMemoryWorkoutRepository,
        },
        {
          provide: EXERCISE_REPOSITORY,
          useClass: InMemoryExerciseRepository,
        },
        WorkoutService,
      ],
    }).compile()

    workoutService = module.get<WorkoutService>(WorkoutService)
    workoutRepository = module.get<WorkoutRepository>(WORKOUT_REPOSITORY)
    exerciseRepository = module.get<ExerciseRepository>(EXERCISE_REPOSITORY)
  })

  it('should be defined', () => {
    expect(workoutService).toBeDefined()
  })
  
  ...
```

`workout-repository.interface.ts`
```ts
import { Workout } from '../entities/workout.entity'
import { Exercise } from '../../exercise/entities/exercise.entity'

export const WORKOUT_REPOSITORY = 'WorkoutRepository'

export interface WorkoutRepository {
  findById(id: string): Promise<Workout>
}

```

`in-memory-exercise.repository.ts`
```ts
export class InMemoryWorkoutRepository implements WorkoutRepository {
  findById(id: string): Promise<Workout> {
    return Promise.resolve(undefined)
  }
}
```

`typeorm-workout.repository.ts`
```ts
@EntityRepository(Workout)
export class TypeOrmWorkoutRepository
  extends Repository<Workout>
  implements WorkoutRepository
{
  async findById(workoutId: string): Promise<Workout> {
    return this.findOne(workoutId)
  }
}
```

## Environment

Nest version: 7.6.0
 
For Tooling issues:
- Node version: v14.16.1
- Platform:  Mac

Others:
For more details on what I'm trying to achieve, my work has been inspired by these articles : 
* https://jasonwhite.xyz/posts/2020/10/20/nestjs-dependency-injection-decoupling-services-with-interfaces
* https://khalilstemmler.com/articles/solid-principles/solid-typescript/#DIP

PS: I tried to streamline the code to what's necessary to understand.

**Comment by Tony133** [comment]
Hi @amehmeto,  I advise you to leave a minimal reproduction of a clonable git repository so that the core team of NestJS can evaluate the problem you have reported.

**Comment by micalevisk** [comment]
@amehmeto You don't need these `@Inject(WORKOUT_REPOSITORY)` since you're using a custom repository. Just use `TypeOrmWorkoutRepository` as the token provider. Thus, remove the manual bind in your `workout.module.ts` for `WORKOUT_REPOSITORY`

Then in your spec file:

```js
        {
          provide: getRepositoryToken(Workout),
          useClass: InMemoryWorkoutRepository,
        },
```

Just follow the docs: https://docs.nestjs.com/techniques/database#custom-repository and you'll be fine :) (this is how I've done so far)

**Comment by jmcdo29** [comment]
@amehmeto @micalevisk is correct, there's no need to go through creating a new provider token. If it _really is_ what you want to do, you can do the following in your `WorkoutModule`

```ts
@Module({
  imports: [
    TypeOrmModule.forFeature([
      TypeOrmExerciseRepository,
      TypeOrmWorkoutRepository,
    ]),
  ],
  providers: [
    {
      provide: EXERCISE_REPOSITORY,
      useExisting: getRepositoryToken(TypeOrmExerciseRepository),
    },
    {
      provide: WORKOUT_REPOSITORY,
      useExisting: getRepositoryToken(TypeOrmWorkoutRepository),
    },
    WorkoutResolver,
    WorkoutService,
  ],
})
export class WorkoutModule {}
```

This will

A) register your custom repositories with TypeORM, so that it ends up using the right base repository class
B) Set up the new injection tokens (`EXERCISE_REPOSITORY` and `WORKOUT_REPOSITORY`) and point Nest to the existing injection tokens for the default injection tokens for the custom repositories. 

---

Next time, please provide a [minimum reproduction](http://minimum-reproduction.wtf) with a docker-ccompose so that it's easier for us to diagnose and text, and use our [Discord](https://discord.gg/nestjs) for support before opening an issue, as this is just a configuration issue.
