### ISSUE TITLE
Header Versioning with same path is not working

### ISSUE THREAD

**Issue by cyan-kinesin** [nestjs/nest#8098]
## Current behavior

Header Versioning with same path is not working

## Input Code

```ts
# health-check.controller.ts

@Controller()
export class HealthCheckController {

    @Version('2')
    @Get('/health')
    healthCheck(): string {
        return 'ok';
    }

    @Version('1')
    @Get('/health')
    healthCheckV1(): string {
        return 'ok v1';
    }
}

```

```ts
// app.module.ts
... (omit)
    controllers: [
        HealthCheckController
    ],
... (omit)

// main.ts
    app.enableVersioning({
        type: VersioningType.HEADER,
        header: 'Version'
    });

```

## Expected behavior

on bash

`curl localhost:3000/health -H 'Version: 1'`
or 
`curl localhost:3000/health -H 'Version: 2'`
->  'ok'

both api is not working.

## Environment

<pre><code>
Nest version: 8.0.6
 
For Tooling issues:
- Node version: XX  
v14.12.0

- Platform:  
Mac OS X 10.13.6

Others:

npm 

</code></pre>

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by cyan-kinesin** [comment]
@jmcdo29 here is [repo](https://github.com/cyan-kinesin/nestjs-kinesin-bugs)

I found this issue is happened when I use fastify-adapter

**Comment by jmcdo29** [comment]
Yep, I was able to get this error with using Fastify:

```
AssertionError [ERR_ASSERTION]: Method 'GET' already declared for route '/health' with constraints '{}'
    at Router._insert (~/nestjs-kinesin-bugs/node_modules/.pnpm/find-my-way@4.3.3/node_modules/find-my-way/index.js:285:7)
    at Router._on (~/nestjs-kinesin-bugs/node_modules/.pnpm/find-my-way@4.3.3/node_modules/find-my-way/index.js:213:8)
    at Router.on (~/nestjs-kinesin-bugs/node_modules/.pnpm/find-my-way@4.3.3/node_modules/find-my-way/index.js:82:8)
    at Object.afterRouteAdded (~/nestjs-kinesin-bugs/node_modules/.pnpm/fastify@3.20.1/node_modules/fastify/lib/route.js:253:16)
    at ~/nestjs-kinesin-bugs/node_modules/.pnpm/fastify@3.20.1/node_modules/fastify/lib/route.js:180:25
    at Object._encapsulateThreeParam (~/nestjs-kinesin-bugs/node_modules/.pnpm/avvio@7.2.2/node_modules/avvio/boot.js:551:7)
    at Boot.timeoutCall (~/nestjs-kinesin-bugs/node_modules/.pnpm/avvio@7.2.2/node_modules/avvio/boot.js:447:5)
    at Boot.callWithCbOrNextTick (~/nestjs-kinesin-bugs/node_modules/.pnpm/avvio@7.2.2/node_modules/avvio/boot.js:428:19)
    at Boot._after (~/nestjs-kinesin-bugs/node_modules/.pnpm/avvio@7.2.2/node_modules/avvio/boot.js:273:26)
    at Plugin.exec (~/nestjs-kinesin-bugs/node_modules/.pnpm/avvio@7.2.2/node_modules/avvio/plugin.js:132:19) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

Thanks for the reproduction. I'll have to look into how we set up this versioning for Express and see if it's something we can make work for Fastify.

**Comment by cyan-kinesin** [comment]
Thank you ! I'll wait for working.

**Comment by micalevisk** [comment]
@jmcdo29 this was reported here #7852

**Comment by jmcdo29** [comment]
Thanks @micalevisk! I missed this conversation. @cyan-kinesin looks like there's a PR in the works already
