### ISSUE TITLE
FST_ERR_DEC_ALREADY_PRESENT error with CORS enabled

### ISSUE THREAD

**Issue by yannterzi** [nestjs/nest#8280]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

8.0.6 -> 8.0.11

### Describe the regression

Hi,
I'm using Fastify Adapter with @nestjs/graphql:9.0.6, and I'm trying to upgrade plateform-fastify 8.0.6 -> 8.0.11.
After the upgrade, I got this error:

`node_modules/fastify/lib/decorate.js:40
    throw new FST_ERR_DEC_ALREADY_PRESENT(name)
          ^
FastifyError: The decorator 'corsPreflightEnabled' has already been added!
    at decorateConstructor (/Users/yannterzibachian/Documents/projects/piency-backend/node_modules/fastify/lib/decorate.js:40:11)
    at Object.decorateRequest (/Users/yannterzibachian/Documents/projects/piency-backend/node_modules/fastify/lib/decorate.js:118:3)
    at fastifyCors (/Users/yannterzibachian/Documents/projects/piency-backend/node_modules/fastify-cors/index.js:20:11)
    at Plugin.exec (/Users/yannterzibachian/Documents/projects/piency-backend/node_modules/avvio/plugin.js:132:19)
    at Boot.loadPlugin (/Users/yannterzibachian/Documents/projects/piency-backend/node_modules/avvio/plugin.js:267:10)
    at Task.release (/Users/yannterzibachian/Documents/projects/piency-backend/node_modules/fastq/queue.js:149:16)
    at worked (/Users/yannterzibachian/Documents/projects/piency-backend/node_modules/fastq/queue.js:201:10)
    at /Users/yannterzibachian/Documents/projects/piency-backend/node_modules/avvio/plugin.js:270:7
    at done (/Users/yannterzibachian/Documents/projects/piency-backend/node_modules/avvio/plugin.js:202:5)
    at check (/Users/yannterzibachian/Documents/projects/piency-backend/node_modules/avvio/plugin.js:226:9)`

if I remove my cors configuration `app.enableCors({
    origin: configService.get('cors.origin'),
    credentials: true,
  });`

it works, but no more CORS.

For information, I'm using the GrpahQL module with the latest version 8.0.11. The cors is not enabled in the GraphQL module.

### Input code

package.json

```ts
{
  "name": "piency",
  "version": "0.0.4",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "build:dev": "nest build --watch --webpack --webpackPath webpack-hmr.config.js",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^8.0.11",
    "@nestjs/config": "^1.0.2",
    "@nestjs/core": "^8.0.11",
    "@nestjs/graphql": "^9.0.6",
    "@nestjs/jwt": "^8.0.0",
    "@nestjs/mongoose": "^9.0.0",
    "@nestjs/passport": "^8.0.1",
    "@nestjs/platform-fastify": "^8.0.6",
    "@nestjs/schedule": "^1.0.1",
    "@nestjs/terminus": "^8.0.1",
    "apollo-server-fastify": "^3.3.0",
    "axios": "^0.22.0",
    "bcrypt": "^5.0.1",
    "cache-manager": "^3.4.4",
    "cache-manager-redis-store": "^2.0.0",
    "class-validator": "^0.13.1",
    "fastify": "^3.21.0",
    "fastify-cookie": "^5.3.1",
    "fastify-multipart": "^4.0.7",
    "graphql": "^15.6.1",
    "graphql-redis-subscriptions": "^2.4.0",
    "graphql-ws": "^5.5.0",
    "ioredis": "^4.27.10",
    "js-yaml": "^4.1.0",
    "minio": "^7.0.19",
    "mongoose": "^6.0.10",
    "ms": "^2.1.3",
    "passport": "^0.4.1",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "pump": "^3.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.3.0",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.1.2",
    "@nestjs/schematics": "^8.0.3",
    "@nestjs/testing": "^8.0.11",
    "@types/bcrypt": "^5.0.0",
    "@types/busboy": "^0.2.4",
    "@types/cache-manager": "^3.4.2",
    "@types/connect-redis": "0.0.17",
    "@types/cron": "^1.7.3",
    "@types/ioredis": "^4.27.6",
    "@types/jest": "^27.0.2",
    "@types/js-yaml": "^4.0.3",
    "@types/minio": "^7.0.10",
    "@types/node": "^16.9.1",
    "@types/passport-jwt": "^3.0.6",
    "@types/passport-local": "^1.0.34",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^4.33.0",
    "@typescript-eslint/parser": "^4.33.0",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "^27.2.5",
    "prettier": "^2.4.1",
    "start-server-webpack-plugin": "^2.2.5",
    "supertest": "^6.1.6",
    "ts-jest": "^27.0.5",
    "ts-loader": "^9.2.6",
    "ts-node": "^10.2.1",
    "tsconfig-paths": "^3.11.0",
    "typescript": "^4.4.2",
    "webpack-node-externals": "^3.0.0"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  },
  "volta": {
    "node": "16.4.2"
  }
}

```

main.ts

```ts
import * as mongoose from 'mongoose';

import {
  FastifyAdapter,
  NestFastifyApplication,
} from '@nestjs/platform-fastify';

import { AppModule } from './app.module';
import { ConfigService } from '@nestjs/config';
import { NestFactory } from '@nestjs/core';
import fastifyCookie from 'fastify-cookie';
import multipart from 'fastify-multipart';

// somewhere in your code
mongoose.set('debug', true);

declare const module: any;

async function bootstrap() {
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter({logger: true}),
  );

  const configService = app.get(ConfigService);

  app.enableCors({
    origin: configService.get('cors.origin'),
    credentials: true,
  });

  app.register(multipart);

  app.register(fastifyCookie, {
    secret: configService.get('jwt.cookie.secret'),
  });

  app.setGlobalPrefix(configService.get('api.prefix'));

  await app.listen(3001, '0.0.0.0');
  console.log(`🚀 Server ready at ${await app.getUrl()}`);
  if (module.hot) {
    module.hot.accept();
    module.hot.dispose(() => app.close());
  }
}
bootstrap();

```

### Expected behavior

Using CORS with latest packages

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by yannterzi** [comment]
Minimum repository provided: https://github.com/yannterzi/nest-cors-issue

**Comment by tkow** [comment]
@TriPSs 
Thank you, you save my time and it works for me. For this  I add fastify-cors in my project package.json as same version used.

@lampsbr 
Set {cors: false} at GraphQLModule.forRoot and set origin config  at app.enableCors. GraphQL protocol is intrinsically same as REST, it just request  /graphql with body including query parameter of gql by POST, thus it should work only app.enableCors. I tested removing  `authorization` in allowedHeaders then it denied access gql resource though it is accessible if it exists. [Current document](https://docs.nestjs.com/security/cors#getting-started) says that both configurations needed but, now this behavior may be broken and no longer need cors configuration in `@nestjs/graphql` against current latest version of `apollo-server-fastify`` and `@nestjs/platform-fastify`.
