### ISSUE TITLE
`NEST_DEBUG` throws `TypeError: Cannot convert a Symbol value to a string` when using symbols as providers token

### ISSUE THREAD

**Issue by micalevisk** [nestjs/nest#8560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Using `NEST_DEBUG=true` doesn't works as expected when using `Symbol` as a provider token because `dependentName` (below) will be an symbol and thus `clc.yellow` will throw as it expects strings

Note that I tested this with v8 but using [`@nestjs-modules/ioredis`](https://github.com/nest-modules/ioredis/blob/72372842b35a2694d2c6987d4024f762690fe7a1/package.json?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L27) which was developed to v6 and v7, and I don't know if it can be used with v8

https://github.com/nestjs/nest/blob/95834b302ff77c06d4832dc9a849522ec11a5e64/packages/core/injector/injector.ts#L799-L805

```
[Nest] 179331  - 11/10/2021, 8:38:13 PM     LOG [NestFactory] Starting Nest application...
[Nest] 179331  - 11/10/2021, 8:38:13 PM     LOG [InjectorLogger] Resolving dependency Reflector in the Reflector provider (alias)
[Nest] 179331  - 11/10/2021, 8:38:13 PM     LOG [InjectorLogger] Looking for Reflector in InternalCoreModule
[Nest] 179331  - 11/10/2021, 8:38:13 PM     LOG [InjectorLogger] Found Reflector in InternalCoreModule
[Nest] 179331  - 11/10/2021, 8:38:13 PM     LOG [InjectorLogger] Resolving dependency HttpAdapterHost in the HttpAdapterHost provider (alias)
[Nest] 179331  - 11/10/2021, 8:38:13 PM     LOG [InjectorLogger] Looking for HttpAdapterHost in InternalCoreModule
[Nest] 179331  - 11/10/2021, 8:38:13 PM     LOG [InjectorLogger] Found HttpAdapterHost in InternalCoreModule
[Nest] 179331  - 11/10/2021, 8:38:13 PM     LOG [InjectorLogger] Resolving dependency BAR_IORedisModuleOptionsToken in the BAR_IORedisModuleConnectionToken provider 
[Nest] 179331  - 11/10/2021, 8:38:13 PM     LOG [InjectorLogger] Looking for BAR_IORedisModuleOptionsToken in RedisCoreModule
[Nest] 179331  - 11/10/2021, 8:38:13 PM     LOG [InjectorLogger] Found BAR_IORedisModuleOptionsToken in RedisCoreModule
[Nest] 179331  - 11/10/2021, 8:38:13 PM   ERROR [ExceptionHandler] Cannot convert a Symbol value to a string
TypeError: Cannot convert a Symbol value to a string
    at XXXXXX/node_modules/@nestjs/common/utils/cli-colors.util.js:8:49
    at Object.yellow (XXXXXX/node_modules/@nestjs/common/utils/cli-colors.util.js:5:66)
    at Injector.printResolvingDependenciesLog (XXXXXX/node_modules/@nestjs/core/injector/injector.js:375:166)
    at Injector.resolveComponentInstance (XXXXXX/node_modules/@nestjs/core/injector/injector.js:153:14)
    at Injector.resolveSingleParam (XXXXXX/node_modules/@nestjs/core/injector/injector.js:143:21)
    at resolveParam (XXXXXX/node_modules/@nestjs/core/injector/injector.js:108:49)
    at Array.map (<anonymous>)
    at Injector.resolveConstructorParams (XXXXXX/node_modules/@nestjs/core/injector/injector.js:123:58)
    at Injector.loadInstance (XXXXXX/node_modules/@nestjs/core/injector/injector.js:52:20)
    at Injector.loadProvider (XXXXXX/node_modules/@nestjs/core/injector/injector.js:74:20)
```

Read the [`src/app.module.ts`](https://gitlab.com/micalevisk/nestjs-v8-debug-issue/-/blob/main/src/app.module.ts) to understand this issue better

### Minimum reproduction code

https://gitlab.com/micalevisk/nestjs-v8-debug-issue (you don't need Redis to face this issue btw)

### Steps to reproduce

follow the `README.md`

### Expected behavior

prints provider's token properly. I guess `dependentName.toString()` is enough.

```
[Nest] 179274  - 11/10/2021, 8:37:44 PM     LOG [NestFactory] Starting Nest application...
[Nest] 179274  - 11/10/2021, 8:37:44 PM     LOG [InjectorLogger] Resolving dependency Reflector in the Reflector provider (alias)
[Nest] 179274  - 11/10/2021, 8:37:44 PM     LOG [InjectorLogger] Looking for Reflector in InternalCoreModule
[Nest] 179274  - 11/10/2021, 8:37:44 PM     LOG [InjectorLogger] Found Reflector in InternalCoreModule
[Nest] 179274  - 11/10/2021, 8:37:44 PM     LOG [InjectorLogger] Resolving dependency HttpAdapterHost in the HttpAdapterHost provider (alias)
[Nest] 179274  - 11/10/2021, 8:37:44 PM     LOG [InjectorLogger] Looking for HttpAdapterHost in InternalCoreModule
[Nest] 179274  - 11/10/2021, 8:37:44 PM     LOG [InjectorLogger] Found HttpAdapterHost in InternalCoreModule
[Nest] 179274  - 11/10/2021, 8:37:44 PM     LOG [InjectorLogger] Resolving dependency BAR_IORedisModuleConnectionToken in the Symbol(foo) provider 
[Nest] 179274  - 11/10/2021, 8:37:44 PM     LOG [InjectorLogger] Looking for BAR_IORedisModuleConnectionToken in module
[Nest] 179274  - 11/10/2021, 8:37:44 PM     LOG [InjectorLogger] Looking for BAR_IORedisModuleConnectionToken in RedisModule
[Nest] 179274  - 11/10/2021, 8:37:44 PM     LOG [InjectorLogger] Looking for BAR_IORedisModuleConnectionToken in RedisCoreModule
[Nest] 179274  - 11/10/2021, 8:37:44 PM     LOG [InjectorLogger] Found BAR_IORedisModuleConnectionToken in RedisCoreModule
[Nest] 179274  - 11/10/2021, 8:37:44 PM     LOG [InjectorLogger] Resolving dependency BAR_IORedisModuleOptionsToken in the BAR_IORedisModuleConnectionToken provider 
[Nest] 179274  - 11/10/2021, 8:37:44 PM     LOG [InjectorLogger] Looking for BAR_IORedisModuleOptionsToken in RedisCoreModule
[Nest] 179274  - 11/10/2021, 8:37:44 PM     LOG [InjectorLogger] Found BAR_IORedisModuleOptionsToken in RedisCoreModule
[Nest] 179274  - 11/10/2021, 8:37:44 PM     LOG [InstanceLoader] AppModule dependencies initialized +14ms
[Nest] 179274  - 11/10/2021, 8:37:44 PM     LOG [InstanceLoader] RedisModule dependencies initialized +0ms
[Nest] 179274  - 11/10/2021, 8:37:44 PM     LOG [InstanceLoader] RedisCoreModule dependencies initialized +1ms
[Nest] 179274  - 11/10/2021, 8:37:44 PM     LOG [InstanceLoader] module dependencies initialized +1ms
[Nest] 179274  - 11/10/2021, 8:37:45 PM     LOG [NestApplication] Nest application successfully started +11ms
```

![image](https://user-images.githubusercontent.com/13461315/141216264-7187899c-cdb4-4869-a617-c687edcfa561.png)

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.0

### Packages versions

`@nestjs/core` 8.2.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [x] Linux

**Comment by jmcdo29** [comment]
Good find. Would you like to make a PR for this?

**Comment by micalevisk** [comment]
sure :)

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/8561
