### ISSUE TITLE
Closing multiple Sequelize instances causing nest to crash

### ISSUE THREAD

**Issue by ppamorim** [nestjs/nest#8939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Our application has access to multiple databases. Given the example:

```typescript
@Module({
  imports: [
    ConfigModule.forRoot({
      isGlobal: true,
      cache: true,
      validate,
      load: [configuration]
    }),
    SequelizeModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: (config: ConfigService) => config.get('db1'),
      inject: [ConfigService]
    }),
    SequelizeModule.forRootAsync({
      name: 'db2',
      imports: [ConfigModule],
      useFactory: (config: ConfigService) => config.get('db2'),
      inject: [ConfigService],
    }),
  controllers: [...],
  providers: [...]
})
```

We start the application by running this bootstrap:

```typescript
async function bootstrap() {

  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter(...)
  );

  useContainer(app.select(AppModule), { fallbackOnErrors: true });

  app.useGlobalPipes(
    new ValidationPipe({
      exceptionFactory: (errors) => new ValidationException(errors),
      transform: true,
      whitelist: true,
      validationError: {
        target: false,
        value: false
      }
    })
  );

  app.setGlobalPrefix('v1');

  app.useWebSocketAdapter(new RedisIoAdapter(app));

  app.enableCors({ origin: '*' });

  /**
   * When SIGTERM, run functions before shutting down
   */
  app.enableShutdownHooks();

  if (process.env.SETUP) {
    const service = app.get(FooService);
    await service.setup();
    await app.close();
    return;
  }

  await app.listen(3000, '0.0.0.0');
}

bootstrap().then();
```

### Minimum reproduction code

See above

### Steps to reproduce

When calling `SETUP=true nest start`

The function `await app.close();` from `bootstrap()` causes this error:

```
Error: Nest could not find Sequelize element (this provider does not exist in the current context)
    at InstanceLinksHost.get (/Users/me/Repository/project_nest/node_modules/@nestjs/core/injector/instance-links-host.js:21:19)
    at Object.find (/Users/me/Repository/project_nest/node_modules/@nestjs/core/injector/module-ref.js:38:55)
    at Object.get (/Users/me/Repository/project_nest/node_modules/@nestjs/core/injector/module.js:345:28)
    at SequelizeCoreModule.<anonymous> (/Users/me/Repository/project_nest/node_modules/@nestjs/sequelize/dist/sequelize-core.module.js:81:47)
    at Generator.next (<anonymous>)
    at /Users/me/Repository/project_nest/node_modules/@nestjs/sequelize/dist/sequelize-core.module.js:20:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/me/Repository/project_nest/node_modules/@nestjs/sequelize/dist/sequelize-core.module.js:16:12)
    at SequelizeCoreModule.onApplicationShutdown (/Users/me/Repository/project_nest/node_modules/@nestjs/sequelize/dist/sequelize-core.module.js:80:16)
    at Object.callAppShutdownHook (/Users/me/Repository/project_nest/node_modules/@nestjs/core/hooks/on-app-shutdown.hook.js:51:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at NestApplication.callShutdownHook (/Users/me/Repository/project_nest/node_modules/@nestjs/core/nest-application-context.js:199:13)
    at NestApplication.close (/Users/me/Repository/project_nest/node_modules/@nestjs/core/nest-application-context.js:83:9)
    at bootstrap (/Users/me/Repository/project_nest/src/main.ts:143:5)
```

### Expected behavior

We suspect that a global sequelize instance is getting closed and the additional database instance cannot access it.

We tried to log the process by doing:

```typescript
export class AppModule implements OnModuleDestroy {

  constructor(
    @InjectConnection() private sequelize: Sequelize,
    @InjectConnection('db2') private db2: Sequelize) {
  }

  async onModuleDestroy() {
    console.log('onModuleDestroy called'); // Called
    try {
      await this.sequelize.close();
      await this.db2.close();
    } catch (e) {
      console.log(e);
    }
  }

  async onApplicationShutdown() {
    console.log('onApplicationShutdown called'); // Never called
  }

}
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [X] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [X] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

nestjs/sequelize

### NestJS version

8.0.8

### Packages versions

```json
"@nestjs-modules/mailer": "^1.6.0",
"@nestjs/axios": "0.0.2",
"@nestjs/bull": "^0.4.1",
"@nestjs/common": "^8.0.8",
"@nestjs/config": "^1.0.1",
"@nestjs/core": "^8.0.8",
"@nestjs/jwt": "^8.0.0",
"@nestjs/passport": "^8.0.1",
"@nestjs/platform-fastify": "^8.0.8",
"@nestjs/platform-socket.io": "^8.0.8",
"@nestjs/sequelize": "^8.0.0",
"@nestjs/swagger": "5.0.9",
"@nestjs/terminus": "^8.0.1",
"@nestjs/throttler": "^2.0.0",
"@nestjs/websockets": "^8.0.8",
```

### Node.js version

17.3.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
