### ISSUE TITLE
Integrating socket.io with uws 

### ISSUE THREAD

**Issue by jatin510** [nestjs/nest#9077]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```
/node_modules/@nestjs/platform-socket.io/node_modules/socket.io/dist/uws.js:85
        websocket.subscribe(namespaceName);
                  ^

TypeError: websocket.subscribe is not a function
    at subscribe (/node_modules/@nestjs/platform-socket.io/node_modules/socket.io/dist/uws.js:85:19)
    at Socket.<anonymous> (/node_modules/@nestjs/platform-socket.io/node_modules/socket.io/dist/uws.js:28:17)
    at Socket.emit (node:events:402:35)
    at Socket.emit (node:domain:475:12)
    at WebSocket.onPacket (/node_modules/engine.io/build/socket.js:212:22)
    at WebSocket.emit (node:events:390:28)
    at WebSocket.emit (node:domain:475:12)
    at WebSocket.onPacket (/node_modules/engine.io/build/transport.js:92:14)
    at WebSocket.onData (/node_modules/engine.io/build/transport.js:101:14)
    at WebSocket.<anonymous> (/node_modules/engine.io/build/transports/websocket.js:20:19)

```

### Minimum reproduction code

https://codesandbox.io/s/withered-glade-ht7bt

### Expected behavior

The message should be sent via the socket.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

"socket.io": "^4.4.1"

### NestJS version

8.2.3

### Packages versions

```json

    "@inway/meteor-random": "^1.1.3",
    "@nestjs/common": "^8.2.3",
    "@nestjs/config": "^1.1.5",
    "@nestjs/core": "^8.2.3",
    "@nestjs/jwt": "^8.0.0",
    "@nestjs/mongoose": "^9.0.2",
    "@nestjs/passport": "^8.0.1",
    "@nestjs/platform-express": "^8.2.3",
    "@nestjs/platform-socket.io": "^8.2.3",
    "@nestjs/websockets": "^8.2.3",
    "@socket.io/admin-ui": "^0.2.0",
    "@types/passport-jwt": "^3.0.6",
    "@types/passport-local": "^1.0.34",
    "add": "^2.0.6",
    "aws-sdk": "^2.1018.0",
    "bcrypt": "^5.0.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.1",
    "date-fns": "^2.25.0",
    "emojione": "^4.5.0",
    "file-type": "^17.0.0",
    "firebase-admin": "^10.0.0",
    "handlebars": "^4.7.7",
    "into-stream": "^7.0.0",
    "lodash": "^4.17.21",
    "moment": "^2.29.1",
    "mongoose": "^6.1.4",
    "nodemailer": "^6.7.0",
    "passport": "0.4.1",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.4.0",
    "socket.io": "^4.4.1",
    "triple-beam": "^1.3.0",
    "uWebSockets.js": "uNetworking/uWebSockets.js#v20.4.0",
    "uuid": "^8.3.2",
    "winston": "^3.3.3",
    "yarn": "^1.22.15"

```

### Node.js version

v16.13.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
