### ISSUE TITLE
TypeScript path aliases are not supported for .tsx files

### ISSUE THREAD

**Issue by pkerschbaum** [nestjs/nest#9266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

NestJS does support tsconfig.json path aliases for `.ts` files automatically, but it fails for `.tsx` files.

The reproduction project has the following changes applied to the StackBlitz template:
* tsconfig.json
  * configured a path alias
  * `"jsx"` set to `"preserve"`.
* created a example file `src/example/ExampleComponent.tsx` which exports a constant `ExampleComponent`
* `main.ts`
  * importing `ExampleComponent`
  * logging `ExampleComponent` (just to make sure the import is not eliminated)
  * also changed the import for `AppModule` to a path alias - that import works.

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-p48ucb?file=src%2Fmain.ts

### Steps to reproduce

Just run `nest start` in the reproduction StackBlitz project.

The following error is thrown:

```
Error: Cannot find module '~/example/ExampleComponent'
Require stack:
- /home/projects/nestjs-typescript-starter-p48ucb/dist/main.js
    at Function.Module._resolveFilename (https://nestjs-typescript-starter-p48ucb.w.staticblitz.com/blitz.a8f9013f6760f2c4e84edef607d361d3a32b8049.js:6:194030)
    at Function.Module._load (https://nestjs-typescript-starter-p48ucb.w.staticblitz.com/blitz.a8f9013f6760f2c4e84edef607d361d3a32b8049.js:6:191604)
    at Module.require (https://nestjs-typescript-starter-p48ucb.w.staticblitz.com/blitz.a8f9013f6760f2c4e84edef607d361d3a32b8049.js:6:194806)
    at i (https://nestjs-typescript-starter-p48ucb.w.staticblitz.com/blitz.a8f9013f6760f2c4e84edef607d361d3a32b8049.js:6:349630)
    at _0x4e304d (https://nestjs-typescript-starter-p48ucb.w.staticblitz.com/blitz.a8f9013f6760f2c4e84edef607d361d3a32b8049.js:15:99674)
    at Object.eval (/home/projects/nestjs-typescript-starter-p48ucb/src/main.ts:3:1)
    at Object.function (https://nestjs-typescript-starter-p48ucb.w.staticblitz.com/blitz.a8f9013f6760f2c4e84edef607d361d3a32b8049.js:15:100056)
    at Module._compile (https://nestjs-typescript-starter-p48ucb.w.staticblitz.com/blitz.a8f9013f6760f2c4e84edef607d361d3a32b8049.js:6:196043)
    at Object.Module._extensions..js (https://nestjs-typescript-starter-p48ucb.w.staticblitz.com/blitz.a8f9013f6760f2c4e84edef607d361d3a32b8049.js:6:196398)
    at Module.load (https://nestjs-typescript-starter-p48ucb.w.staticblitz.com/blitz.a8f9013f6760f2c4e84edef607d361d3a32b8049.js:6:194488)
```

### Expected behavior

No error.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.3.1

### Packages versions

8.3.1

### Node.js version

14.19.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Why are you importing a `tsx` file in a node/server project? Is there something I'm missing here?

**Comment by pkerschbaum** [comment]
The NestJS server I am working on must send emails in some use cases.  
I am using React to generate the HTML for those emails (i.e. I use `react-dom/server` to transform the React templates to HTML).
