### ISSUE TITLE
The GraphQL federation sample doesn't work with most recent dependencies

### ISSUE THREAD

**Issue by stringbeans** [nestjs/nest#9472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi there!

The sample implementation of GraphQL federation using NestJS doesn't seem to work with up-to-date dependencies. I used https://github.com/nestjs/nest/tree/master/sample/31-graphql-federation-code-first as a starting point and can confirm it worked. However, I noticed some of the deps were out of date and went ahead to update them and resolve the peer dependency issues. (I also tried recreating the sample manually with a fresh nestjs install and it failed due to more up-to-date deps with a new nest project)

So the problem is that with the latest deps of:
```
@apollo/federation
@apollo/gateway
@apollo/subgraph
@nestjs/apollo
@nestjs/graphql
graphql
graphql-tools
```

... the start up of the gateway fails with the following error:

```
/home/john/Development/nestjs-federation-sample/sample/31-graphql-federation-code-first/gateway/node_modules/@apollo/gateway/src/supergraphManagers/IntrospectAndCompose/index.ts:121
      throw Error(
            ^
Error: A valid schema couldn't be composed. The following composition errors were found:
	[users] User -> A @key directive specifies the `id` field which has no matching @external field.
	Unknown type "User".
	[users] Query -> `Query` is an extension type, but `Query` is not defined in any service
	Unknown type "User".
	[posts] Query -> `Query` is an extension type, but `Query` is not defined in any service
	Unknown type "Post".
	Unknown type "Post".
	[users] User -> `User` is an extension type, but `User` is not defined in any service
	[posts] User -> `User` is an extension type, but `User` is not defined in any service
	Unknown type "Post".
	Query root type must be provided.
    at IntrospectAndCompose.createSupergraphFromSubgraphList (/home/john/Development/nestjs-federation-sample/sample/31-graphql-federation-code-first/gateway/node_modules/@apollo/gateway/src/supergraphManagers/IntrospectAndCompose/index.ts:121:13)
    at IntrospectAndCompose.updateSupergraphSdl (/home/john/Development/nestjs-federation-sample/sample/31-graphql-federation-code-first/gateway/node_modules/@apollo/gateway/src/supergraphManagers/IntrospectAndCompose/index.ts:109:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at IntrospectAndCompose.initialize (/home/john/Development/nestjs-federation-sample/sample/31-graphql-federation-code-first/gateway/node_modules/@apollo/gateway/src/supergraphManagers/IntrospectAndCompose/index.ts:65:30)
    at ApolloGateway.initializeSupergraphManager (/home/john/Development/nestjs-federation-sample/sample/31-graphql-federation-code-first/gateway/node_modules/@apollo/gateway/src/index.ts:462:22)
    at ApolloGateway.load (/home/john/Development/nestjs-federation-sample/sample/31-graphql-federation-code-first/gateway/node_modules/@apollo/gateway/src/index.ts:357:7)
    at SchemaManager.start (/home/john/Development/nestjs-federation-sample/sample/31-graphql-federation-code-first/gateway/node_modules/apollo-server-core/src/utils/schemaManager.ts:111:22)
    at ApolloServer._start (/home/john/Development/nestjs-federation-sample/sample/31-graphql-federation-code-first/gateway/node_modules/apollo-server-core/src/ApolloServer.ts:360:24)
    at ApolloServer.start (/home/john/Development/nestjs-federation-sample/sample/31-graphql-federation-code-first/gateway/node_modules/apollo-server-core/src/ApolloServer.ts:341:12)
    at ApolloGatewayDriver.registerExpress (/home/john/Development/nestjs-federation-sample/sample/31-graphql-federation-code-first/gateway/node_modules/@nestjs/apollo/dist/drivers/apollo-base.driver.js:78:9)
```

I have a repo to help reproduce: https://github.com/stringbeans/nest-federation-example

### Minimum reproduction code

https://github.com/stringbeans/nest-federation-example

### Steps to reproduce

1. start the "users" app
2. start the "posts" app
3. start the "gateway" app

### Expected behavior

The gateway should start without error using the more recent versions of dependencies from both apollo and nestjs. Or another way to put it: The graphql federation using the code-first example should work on a fresh install of nestjs and apollo/federation dependencies.

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.3

### Packages versions

(see https://github.com/stringbeans/nest-federation-example as it is 3 separate apps)

### Node.js version

v16.13.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/graphql/issues/2141
