### ISSUE TITLE
Exceptions thrown from Kafka microservice are not sent

### ISSUE THREAD

**Issue by svyatogor** [nestjs/nest#9679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you throw an exception from Kafka based micro service message handler it seems that it is supposed to be places in `kafka_nest-err` message header by `assignErrorHeader`. However `BaseRpcExceptionFilter` returns an object that cannot be fed into `Buffer.from` so we get an error and the exception is never delivered.

https://github.com/nestjs/nest/blob/2e3727b78681ea2ca8fcd417c966a9b705bb8431/packages/microservices/server/server-kafka.ts#L231

```
Error: Ouch!
    at ServerController.getHello (/Users/sergeykuleshov/Projects/nest-ms-kafka-ex/dist/apps/server/main.js:76:15)
    at /Users/sergeykuleshov/Projects/nest-ms-kafka-ex/node_modules/@nestjs/microservices/context/rpc-context-creator.js:44:33
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /Users/sergeykuleshov/Projects/nest-ms-kafka-ex/node_modules/@nestjs/microservices/context/rpc-proxy.js:11:32
    at ServerKafka.handleMessage (/Users/sergeykuleshov/Projects/nest-ms-kafka-ex/node_modules/@nestjs/microservices/server/server-kafka.js:112:54)
    at Runner.processEachMessage (/Users/sergeykuleshov/Projects/nest-ms-kafka-ex/node_modules/kafkajs/src/consumer/runner.js:191:9)
    at onBatch (/Users/sergeykuleshov/Projects/nest-ms-kafka-ex/node_modules/kafkajs/src/consumer/runner.js:393:9)
    at /Users/sergeykuleshov/Projects/nest-ms-kafka-ex/node_modules/kafkajs/src/consumer/runner.js:409:9
    at /Users/sergeykuleshov/Projects/nest-ms-kafka-ex/node_modules/kafkajs/src/consumer/worker.js:29:9
TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
    at new NodeError (node:internal/errors:371:5)
    at Function.from (node:buffer:322:9)
    at ServerKafka.assignErrorHeader (/Users/sergeykuleshov/Projects/nest-ms-kafka-ex/node_modules/@nestjs/microservices/server/server-kafka.js:137:73)
    at ServerKafka.sendMessage (/Users/sergeykuleshov/Projects/nest-ms-kafka-ex/node_modules/@nestjs/microservices/server/server-kafka.js:119:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /Users/sergeykuleshov/Projects/nest-ms-kafka-ex/node_modules/@nestjs/microservices/server/server.js:47:25
```

### Minimum reproduction code

https://github.com/svyatogor/nest-ms-kafka-ex

### Steps to reproduce

1. nest start server
2. nest start client
3. visi http://localhost:3000 to trigger the micro service call

### Expected behavior

The message should be serialised before being set onto the header.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.4.5

### Packages versions

```json
 "@nestjs/common": "^8.0.0",
"@nestjs/core": "^8.0.0",
"@nestjs/microservices": "^8.4.5",
"@nestjs/platform-express": "^8.0.0",
"kafkajs": "^2.0.1",
"reflect-metadata": "^0.1.13",
"rimraf": "^3.0.2",
"rxjs": "^7.2.0"
```

### Node.js version

16.14

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
This has been fixed in this PR https://github.com/nestjs/nest/pull/9586 and will be published as part of v9.0.0
