### ISSUE TITLE
nest g co xxx Cannot create controller

### ISSUE THREAD

**Issue by ChenLiuPng** [nestjs/nest#9826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Use the latest nestjs version @nestjs/cli@8.2.7

Delete in project node_moudles

command `nest g co xxx`

```js
node_modules\@nestjs\cli\node_modules\@angular-devkit\schematics-cli\bin\schematics.js:338
            throw new Error(`Unknown argument ${key}. Did you mean ${(0, yargs_parser_1.decamelize)(key)}?`);
                  ^

Error: Unknown argument skipImport. Did you mean skip-import?
    at parseArgs (C:\nvm\v16.15.0\node_modules\@nestjs\cli\node_modules\@angular-devkit\schematics-cli\bin\schematics.js:338:19)
    at main (C:\nvm\v16.15.0\node_modules\@nestjs\cli\node_modules\@angular-devkit\schematics-cli\bin\schematics.js:122:49)
    at Object.<anonymous> (C:\nvm\v16.15.0\node_modules\@nestjs\cli\node_modules\@angular-devkit\schematics-cli\bin\schematics.js:367:5)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

Failed to execute command: node @nestjs/schematics:controller --name=abceg --no-dry-run --no-skipImport --language="ts" --sourceRoot="src" --spec
```

### Minimum reproduction code

The following operations can be repeated

### Steps to reproduce

1. `npm i -g @nestjs/cli`
2. `nest new project-name`
3. `nest g co xxx`

### Expected behavior

Ability to create controller

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

@angular-devkit\schematics-cli

### NestJS version

8.2.7

### Packages versions

```json
{
  "name": "projectdemo",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "27.0.2",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "^27.2.5",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}


```

### Node.js version

16.15.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

I found that it may be because the @angular-devkit\schemas-cli version is 14.0.2. If 13.1.2 is used, this error will not occur

**Comment by micalevisk** [comment]
duplicate https://github.com/nestjs/nest-cli/issues/1693

**Comment by abubakar2000** [comment]
For me `sudo npm i -g @nestjs/cli` worked. Some libraries might be just broken.

**Comment by abubakar2000** [comment]
> For me `sudo npm i -g @nestjs/cli` worked. Some libraries might be just broken.

And this was done over mac/linux
