### ISSUE TITLE
SwaggerModule.setup call fails with error in Nest 9 with Fastify adapter and ignoreTrailingSlash set to true

### ISSUE THREAD

**Issue by piosystems** [nestjs/nest#9913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Set up a project with nest 9 and change the adapter from the default _express_ to _fastify_. When the _ignoreTrailingSlash_ option for _fastify_ adapter is set to _true_, SwaggerModule.setup call will fail with an error message like that shown below. SwaggerModule.setup call works only when the _ignoreTrailingSlash_ is set to the default false.

**Sample error message:**
/Users/myHome/test-nest-9-fastify-swagger/node_modules/find-my-way/index.js:283
      throw new Error(`Method '${method}' already declared for route '${path}' with constraints '${JSON.stringify(constraints)}'`)
            ^
Error: Method 'GET' already declared for route '/api' with constraints '{}'
    at Router._on (/Users/myHome/test-nest-9-fastify-swagger/node_modules/find-my-way/index.js:283:13)
    at Router.on (/Users/myHome/test-nest-9-fastify-swagger/node_modules/find-my-way/index.js:136:10)
    at Object.addNewRoute (/Users/myHome/test-nest-9-fastify-swagger/node_modules/fastify/lib/route.js:262:16)
    at Object.route (/Users/myHome/test-nest-9-fastify-swagger/node_modules/fastify/lib/route.js:196:19)
    at Object.prepareRoute (/Users/myHome/test-nest-9-fastify-swagger/node_modules/fastify/lib/route.js:143:18)
    at Object._get [as get] (/Users/myHome/test-nest-9-fastify-swagger/node_modules/fastify/fastify.js:244:34)
    at FastifyAdapter.injectConstraintsIfVersioned (/Users/myHome/test-nest-9-fastify-swagger/node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.js:312:46)
    at FastifyAdapter.get (/Users/myHome/test-nest-9-fastify-swagger/node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.js:106:21)
    at Function.serveDocuments (/Users/myHome/test-nest-9-fastify-swagger/node_modules/@nestjs/swagger/dist/swagger-module.js:39:21)
    at Function.setup (/Users/myHome/test-nest-9-fastify-swagger/node_modules/@nestjs/swagger/dist/swagger-module.js:62:23)

### Minimum reproduction code

https://github.com/piosystems/test-nest-9-fastify-swagger

### Steps to reproduce

1. _npm i -g @nestjs/cli_
2. _nest new project-name_
3. Open project in VSCode
4. _npm i --save @nestjs/platform-fastify @fastify/static @nestjs/swagger_
5. Change the adapter in _main.ts_ to fastifyAdapter and set the _ignoreTrailingSlash_ option to _true_, as shown in the code [https://github.com/piosystems/test-nest-9-fastify-swagger/blob/main/src/main.ts](https://github.com/piosystems/test-nest-9-fastify-swagger/blob/main/src/main.ts)
6. _npm run start:dev_ and you will get the error message.
7. Comment out the _ignoreTrailingSlash_ option or set it to false, and Swagger will startup normally.

### Expected behavior

Swagger should startup normally even when ignoreTrailingSlash option is set to true for fastify adapter.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/swagger

### NestJS version

9.0.2

### Packages versions

{
  "name": "test-nest-9-fastify-swagger",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@fastify/static": "^6.4.0",
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/platform-fastify": "^9.0.2",
    "@nestjs/swagger": "^6.0.1",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "28.1.4",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.1.2",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.5",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.0.0",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

### Node.js version

16.14.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
@flamewow want to take a look? 🙌

**Comment by flamewow** [comment]
> @flamewow want to take a look? 🙌

sure, I'm on it

**Comment by kamilmysliwiec** [comment]
Fixed in 6.0.2
